android_p/google_diff/cel_apl/packages/apps/Bluetooth/0003-Fix-BT-paired-icon-is-not-displayed-on-the-New-User-.patch
When switch to new user, systemUI is owner process, unable to
get the bluetooth connectition device update information throung broadcast.
so, send the connection information to all user like intent ACTION_CONNECTION_STATE_CHANGED.
Tracked-On:OAM-67838
Signed-off-by: Yue, VincentX <vincentx.yue@intel.com>
=> Fix BT paired icon is not displayed on the New User's status bar

android_p/google_diff/cel_apl/frameworks/base/0011-Add-DISALLOW_ADD_USER-restriction-for-default-user-a.patch
The default user and guest user is missing DISALLOW_ADD_USER restriction,
lead to canCurrentProcessAddUsers() always return true. So add DISALLOW_ADD_USER
restriction for default user and guest user.
Tracked-On: OAM-67841
=> Add DISALLOW_ADD_USER restriction for default user and guest user

android_p/google_diff/cel_apl/frameworks/base/0012-Fix-issue-that-the-position-of-QuickSetting-is-impro.patch
NotificationPanelView uses the width of notification stack Scroller to
estimate if notification stack Scroller and QuickSetting to be applied
the offset. That may cause the position of QuickSetting is improper if
the width of notification stack Scroller is smaller than the width of
QuickSetting.
The solution is that comparing the width of notification stack Scroller
with the width of QuickSetting and using the larger one to estimate if
notification stack Scroller and QuickSetting to be applied the offset.
Test:
1. Click on the top right of Status Bar.
2. Show notifications
Tracked-On: OAM-67772
=> Fix issue that the position of QuickSetting is improper on DUT (IVI)

android_p/google_diff/cel_apl/packages/services/Car/0003-Keep-statusBar-window-height-same-with-SystemUI-stat.patch
status_bar_height is use for set systemUI statusBar view height.
status_bar_height_landscape and status_bar_height_portrait are use for
setting statusBar window height.
Test: Observer the statusBar height at a 1080P display
Tracked-On: OAM-67784
=> Keep statusBar window height same with SystemUI statusBar height

android_p/google_diff/cel_apl/packages/apps/Car/Media/0001-Fix-duration-time-incorrect-by-new-format.patch
Duration time is not date format, using h:mm:ss to format it.
Tracked-On: OAM-68261
=> Fix duration time incorrect by new format.

android_p/google_diff/cel_apl/system/gatekeeper/0001-fix-input-wrong-wait-time-after-input-wrong-key.patch
Wrong wait time after input wrong key over 5 times.
The patch is to fix the wrong wait time after input
wrong key.
Test: Boot to android GUI
Tracked-On: OAM-68280
Signed-off-by: yingbinx <yingbinx.zeng@intel.com>
=> Fix input wrong wait time after input wrong key

android_p/google_diff/cel_apl/frameworks/av/0003-Fix-the-flicker-on-single-touch.patch, android_p/google_diff/cel_apl/packages/apps/Gallery2/0003-Fix-the-audio-and-video-flicker-problem-when-seeking.patch
1. Fix the audio and video flicker problem when seeking.
2. Filter out the dupliate call to seekTo with the same
seek time when seeking with a "touch and leave" manner.
Tracked-On: OAM-68571
=> Fix the audio and video flicker problem when seeking.

android_p/google_diff/cel_apl/packages/apps/Car/LocalMediaPlayer/0002-Fix-the-audio-rack-is-not-removed-from-notification-.patch
When paused, to remove the notification should be allowed.
Tracked-On: OAM-68130
=> Fix the audio rack is not removed from notification after pause music.

android_p/google_diff/cel_apl/trusty/external/lk/0001-x64-64-enabling-patch-for-google-diff.patch, android_p/google_diff/celadon/trusty/external/lk/0001-x64-64-enabling-patch-for-google-diff.patch
Update memory unmap entry mechanism, set entry value to
zero instread of clear Present bit.
Test: Boot to android GUI
Tracked-On: None
Signed-off-by: Zhong,Fangjian <fangjian.zhong@intel.com>
Signed-off-by: Zhang, Qi <qi1.zhang@intel.com>
=> trusty: Add fix for L1TF and refine clang build

android_p/google_diff/cel_apl/packages/apps/Calendar/0001-Calendar-supports-a-larger-screen-aspect-ratio.patch, android_p/google_diff/cel_apl/packages/apps/Email/0001-Email-supports-a-larger-screen-aspect-ratio.patch
The maximum aspect ratio defaults to 1.86 (roughly 16:9) and
application will not take advantage of the extra screen space.
using android.max_aspect element in the app's <application> element to
increase maximum supported aspect ratio.
Tracked-On: OAM-68598
=> supports a larger screen aspect ratio for Email and Calendar

android_p/google_diff/cel_apl/packages/apps/Car/Settings/0001-Fix-can-t-drag-in-car-setting-sound.patch
The adapter notifyDataSetChanged will relayout UI.
But the SoundSettingsFragment called notifyDataSetChanged while receiving
a volume size change. Lead to the AbsSeekBar get MotionEvent.ACTION_CANCEL.
Test:
1. Go to car settings->sound
2. Adjust a item by dragging
3. Expected volume adjustment should happen when dragging
Tracked-On: OAM-67867
=> Fix can't drag in car setting sound

android_p/google_diff/cel_apl/packages/apps/HTMLViewer/0001-HTMLViewer-supports-a-larger-screen-aspect-ratio.patch
The maximum aspect ratio defaults to 1.86 (roughly 16:9) and
application will not take advantage of the extra screen space.
using android.max_aspect element in the app's <application> element to
increase maximum supported aspect ratio.
Tracked-On: OAM-67747
=> [HTMLViewer] supports a larger screen aspect ratio

android_p/google_diff/cel_apl/device/intel/project-celadon/0004-f2fs-filesystem-support-enabled.patch, android_p/google_diff/celadon/device/intel/project-celadon/0001-f2fs-filesystem-support-enabled.patch
f2fs filesystem support is enabled for using in adoptable storage
as per google AOSP CDD adoptable storage shall use both ext4 and f2fs. so enabling f2fs
Jira: None
Test: mount cmd
1. create a storage volume with mkfs.f2fs utility
2. mount -t f2fs <dev entry> <mount point>
3. check mount cmd output and check for mount type as f2fs
Tracked-On: None
=> [CELADON] f2fs filesystem support enabled

android_p/google_diff/cel_apl/frameworks/av/0004-Adjust-sendObject-parameter-s-data-type.patch
Now the MtpDevice#sendObject is using int to define object size,
if the object size is bigger than 2GB, the size will be type cast to
a negative number in MtpDevice#sendObject. And it will cause a endless
loop in MtpDataPacket#write until DUT auto reboot.
Due to the JNI api android_mtp_MtpDevice_send_object is using uint32_t
to define object size, so adjust the native api MtpDevice#sendObject
size parameter's data type to uint32_t.
Tracked-On: OAM-68165
=> Adjust sendObject parameter's data type.

android_p/google_diff/cel_apl/frameworks/base/0013-Fix-navigation-bar-not-scaling-up-down-when-the-disp.patch
Restart the navigation bar when the density or font scale changed
Test:
1. goto Settings->Display->Advanced->Display size->Largest
2. check whether scaling up for the facet buttons of navigation bar
Tracked-On: OAM-67836
=> Fix navigation bar not scaling up/down when the display size changed.

android_p/google_diff/cel_apl/frameworks/base/0014-Fix-the-TimePickerClock-display-is-incomplete.patch
The AOSP widget TimePickerClock include the alert_dialog_button_bar_material.
The alert_dialog_button_bar_material is overlaid by the automotive UI. Due to
the automotive UI don't make the car TimePickerClock, hence, remove the
alert_dialog_button_bar_material automotive changes from the TimePickerClock.
Tracked-On: OAM-67760
=> Fix the TimePickerClock display is incomplete

android_p/google_diff/cel_apl/packages/apps/DocumentsUI/0001-DocumentUI-Fix-file-cannot-be-accessed-using-mouse-r.patch
DocumentUI don't implement onDocumentPicked() in FilesActivity.java yet.
The solution is that sending ACTION_VIEW intent to system and system
start the right application to open the file.
Tracked-On: OAM-68477
=> [DocumentUI]Fix file cannot be accessed using mouse right click 'Open'.

android_p/google_diff/cel_apl/frameworks/base/0015-Fix-unable-to-input-PIN-password-with-the-physical-k.patch, android_p/google_diff/celadon/frameworks/base/0009-Fix-unable-to-input-PIN-password-with-the-physical-k.patch
If inputting a wrong password, the Pin's input editText view will be
disabled by the verifyPassword function. Then the viewGroup will clear
the editText view's focus and find another focus view(ScrimView), it
leads to being unable to input pin password again.
Test:
1. Set a PIN from Settings->security & location->screen lock->PIN
2. Lock the device by pressing the ignition button
3. Enter a wrong PIN from a physical keyboard
4. For the next attempt, the physical keyboard cannot be used
Tracked-On: OAM-69586
=> Fix unable to input PIN password with the physical keyboard

android_p/google_diff/cel_apl/frameworks/base/0015-Enable-Add-button-after-cancel-by-clicking-outside-o.patch
If not to enable the Add button after the dialog cancel by clicking
outside of the dialog, the user is not able to click the Add button
anymore. setOnCancelListener to fix this bug.
Tracked-On: OAM-69585
=> Enable Add button after cancel by clicking outside of dialog.

android_p/google_diff/cel_apl/packages/services/Car/0005-Fix-the-status-bar-icons-disappear.patch
The status bar icons disappear due to the statusBar is overlaid by a
Head-Up Notification's ticker text. Reference to the phone status bar
layout, Head-up notifications only use the 1/2 of the statusBar width
to display the notification ticker text.
Test:
1. Turn on WIFI
2. Show a Head_Up notification
Tracked-On: OAM-69584
=> Fix the status bar icons disappear.

android_p/google_diff/cel_apl/packages/apps/Car/Settings/0002-Correct-the-seekbar-value-by-min-volume-of-the-strea.patch
For some streams (e.g.Alarm), the min volume is not zero.
Needs to correct the value of seekbar by min volume.
Tracked-On: OAM-68651
=> Correct the seekbar value by min volume of the stream.

android_p/google_diff/cel_apl/packages/apps/Bluetooth/0004-Fix-for-Audio-resumed-once-message-is-received.patch
Issue: When message readout is done, paused audio resumes
automatically.
Reason: When audio Focus changes, pausing of the audio is done
on the basis of mStreamAvailable variable. This variable was
not handled properly. It is made true at SRC_STR_START command.
When message is received, to start readout, again SRC_STR_START
is received which again makes mStreamavailable true and the
previous state of mStreamAvailable was lost. Due to which on
recepetion of AudioFocus Loss Transient, always a pause commmand
was sent and audio resumes when message readout happens.
Fix: Changed handling of mStreamAvailable from SRC_STR_START to
SRC_PLAY and SNK_PLAY.
Tracked-On: OAM-68209
Signed-off-by: Gaganpreet kaur <gaganpreetx.kaur@intel.com>
=> Fix for Audio resumed once message is received

android_p/google_diff/cel_apl/system/bt/0005-A-work-around-fix-for-incorrect-controller-response.patch
Reason: The controller did not send correct response
for read remote extended features for "page 1" request.
Since lmp extended features ssp was not true, the sm4
was not enabled. Therefore host did not initiate
authentication request. When L2CAP AVDTP connection
was established, the controller returned disconnect
complete with authentication failed reason.
Fix: Provided a retry of read remote extended features
request from host, when response for 'page 1' was
incorrect. This enabled authentication from host and
hence L2CAP AVDTP connection was successful.
Revert the changes, once contoller fix is available
Tracked-On: OAM-69566
Signed-off-by: anitha3x <anithax.h.chandrasekar@intel.com>
=> A work around fix for incorrect controller response.

android_p/google_diff/cel_apl/frameworks/av/services/0001-CELADON-Set-available-device-as-prmary-hardware-devi.patch
set the available device as hardware primary when the on-board
sound card is not present. This is to fix the USB recording issue
on commercial NUC.
Tracked-On:OAM-70176
=> [CELADON]Set available device as prmary hardware device

android_p/google_diff/cel_apl/frameworks/av/0001-Fix-an-issue-that-video-can-not-be-resumed-after-bei.patch, android_p/google_diff/celadon/frameworks/av/0001-Fix-an-issue-that-video-can-not-be-resumed-after-bei.patch
Some video clips contain unsupported audio tracks and when the clip is paused and resumed,
the audio track would trigger a flush and make the MediaClock's anchor being cleared.
Tracked-On: OAM-71147
Signed-off-by: tianmi.chen <tianmi.chen@intel.com>
=> [Celadon] Fix an issue that video can not be resumed after being paused

android_p/google_diff/cel_apl/packages/apps/Bluetooth/0005-Fix-for-request-audio-focus-when-play-audio-by-A2DP.patch
Reason: During DUT BT ON/OFF or Reboot, the ongoing audio
stream was paused.
Fix: Removed the audio pause and requested for audio focus
Tracked-On: OAM-70162
Signed-off-by: huguobiX <guobingx.hu@intel.com>
Signed-off-by: anitha3x <anithax.h.chandrasekar@intel.com>
=> Fix for request audio focus when play audio by A2DP.

android_p/google_diff/cel_apl/frameworks/base/0016-Add-default-values-for-system-locales.patch
Now when first time log in, the system user's system locales is not
stored in settings_system database. So the value will be written by
the new user's change language action. And after switch back to system
user, the system locales value will remain the same as new user.
So the solution is add default values for system locales when system
user first time log in, and the default values is coming from device
configuration.
Tracked-On: OAM-70885
Signed-off-by: robinz1x <robinx.zhang@intel.com>
=> Add default values for system locales

android_p/google_diff/cel_apl/frameworks/av/0005-AudioPolicyManager-Avoid-invalid-volume-setting-in-A.patch
Do skip volume setting when invalid device id is sent as
argument to checkAndSetVolume().  If this setting is not skipped,
the audio volume index sent to checkAndSetVolume() may not match
with the actual audio device associated with outputDesc sent as
another argument, causing invalid volume set to actual audio device.
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-71124
Signed-off-by: Aravind Siddappaji <aravindx.siddappaji@intel.com>
=> [CEALDON]AudioPolicyManager: Avoid invalid volume setting in APM

android_p/google_diff/cel_apl/frameworks/base/0017-Backport-Prevent-shortcut-info-package-name-spoofing.patch, android_p/google_diff/celadon/frameworks/base/0010-Backport-Prevent-shortcut-info-package-name-spoofing.patch
Test: cts-tradefed run cts -m CtsShortcutManagerTestCases -t android.content.pm.cts.shortcutmanager.ShortcutManagerFakingPublisherTest
Bug: 109824443
Change-Id: I90443973aaef157d357b98b739572866125b2bbc
Merged-In: I78948446a63b428ae750464194558fd44a658493
(cherry picked from commit 9e21579a11219581a0c08ff5dd6ac4dc22e988a4)
=> Backport Prevent shortcut info package name spoofing

android_p/google_diff/cel_apl/packages/services/Car/0007-Add-permission-whitelist-for-Car-apps.patch
Test: run cts -m CtsPermission2TestCases \
-t android.permission2.cts.PrivappPermissionsTest#testPrivappPermissionsEnforcement
Tracked-On: OAM-71342
=> Add permission whitelist for Car apps.

android_p/google_diff/cel_apl/device/intel/project-celadon/0004-CELADON-SELinux-Remove-dedicated-sepolicy-configurat.patch, android_p/google_diff/cel_apl/device/intel/project-celadon/0005-CELADON-Enabling-CONFIG_ANDROID_AUTO_SUSPEND_BEHAVIO.patch, android_p/google_diff/cel_apl/frameworks/base/0017-CELADON-GlobalActions-Handle-sleep-action.patch, android_p/google_diff/cel_apl/frameworks/base/0018-CELADON-Enabling-suspend-on-IVI-after-clicking.patch, android_p/google_diff/cel_apl/packages/services/Car/0006-CELADON-Enabling-display-timeout-on-IVI.patch
the power button menu.
Enabled S3 and modified dedicated sepolicy configurations.
Tracked-on: OAM-56502
=> [CELADON] Enabling suspend on IVI after clicking sleep from

android_p/google_diff/cel_apl/device/intel/project-celadon/0004-MMC-SDHCI-Host-controller-enabling-for-4.19.x-kernel.patch
Tracked-On: OAM-71946
Signed-off-by: shyjumon <shyjumon.n@intel.com>
=> MMC: SDHCI-Host-controller-enabling-for-4.19.x-kernel

android_p/google_diff/cel_apl/frameworks/base/0019-Changing-usb-config-during-suspend-and-resume.patch
Changing the usb config to "none" during S3 and enabling
the usb config to "adb" to resume adb.
Tracked-on: OAM-71949
=> [CELADON] Changing usb config during suspend and resume

android_p/google_diff/cel_apl/packages/apps/Car/libs/0001-Fix-LocalMediaPlayer-freezed-when-change-the-display.patch
After the display size changed, LocalMediaPlayer forced to stop
and restarted. And the media session will be destroyed when the
app stopped. But the related mediacontroller is still alive even
the session is invalid.
Set the mediacontroller as null when the session is destroyed.
Tracked-On: OAM-72299
=> [CELADON] Fix LocalMediaPlayer freezed when change the display size

android_p/google_diff/cel_apl/packages/apps/Bluetooth/0006-Fix-for-failing-CTS-test-BluetoothLeScanTest-testBat.patch
Reason: While running testBatchScan assertion happened for
invalid advertisePacketLen and timestamp .Fix Added condition checks to prevent erroneous array
operations
Tracked-On: OAM-71309
Signed-off-by: anitha3x <anithax.h.chandrasekar@intel.com>
=> Fix for failing CTS test BluetoothLeScanTest#testBatchScan

android_p/google_diff/cel_apl/frameworks/base/0021-CELADON-Resuming-display-after-S3.patch
On platforms like KBL, the display was never resuming
on single power button press. This work-around will fix
issues where single power button press is not detected
during wakeup.
Tracked-on: OAM-72346
=> Resuming display after S3

android_p/google_diff/cel_apl/system/sepolicy/0001-sepolicy-Allow-apps-to-get-info-from-priv_app-by-ash.patch, android_p/google_diff/celadon/system/sepolicy/0001-sepolicy-Allow-apps-to-get-info-from-priv_app-by-ash.patch
This is used to address a CTS testcase failure. This CTS
testcase need to access the content of Contact, some data
from ContactProvider is transfered through ashmem.
Currently ashmem is backed by the tmpfs filesystem, ContactProvider
in android run as a priv_app, so the file context of the ashmem
created by ContactProvider is priv_app_tmpfs. CTS runs as an
untrusted_app, need to be granted the read permission to the
priv_app_tmpfs files.
Tracked-On: OAM-72412
=> sepolicy: Allow apps to get info from priv_app by ashmem

android_p/google_diff/cel_apl/frameworks/base/0022-Fix-Guest-user-option-seen-when-logged-in-as-New-Use.patch, android_p/google_diff/cel_apl/packages/apps/Car/Settings/0003-Fix-Guest-user-option-seen-when-logged-in-as-New-Use.patch
if the foreground user is the device owner, add the guest
user record.
Tracked-On: OAM-70634
=> Fix "Guest" user option seen when logged in as "New User"

android_p/google_diff/cel_apl/packages/services/Car/0008-Fix-testScreenBrightness-failed-in-CtsStatsdHostTest.patch
Case fail due to update a wrong backlight brightness to the Setting database.
Due to the display brightness for the vehicle, need a percent brightness.
but the System screen backlight brightness is a value between 0 and 255, need
to convert the screen backlight brightness to the percent brightness. If the
screen backlight brightness had changed from the vehicle, need to convert the
percent brightness to screen backlight brightness value, So unable to save a
accurate brightness value to the Setting database.
Test:
1. adb shell settings put system screen_brightness 100
2. adb shell settings get system screen_brightness
Tracked-On: OAM-73451
=> Fix testScreenBrightness failed in CtsStatsdHostTestCases Module

android_p/google_diff/cel_apl/frameworks/base/0024-WA-Decrease-the-duration-of-screen-off-animation-to-.patch, android_p/google_diff/celadon/frameworks/base/0024-WA-Decrease-the-duration-of-screen-off-animation-to-.patch
testWakelockState requires screen off before it's running.
But the current source code of case testPartialWakelock does not
guarantee that. This workaround will get screen off faster to
get the case pass.
Tracked-On: OAM-72680
=> [WA]Decrease the duration of screen-off animation to get CTS pass.

android_p/google_diff/cel_apl/frameworks/base/0024-GlobalActionsDialog-Fix-issue-with-shutdown-reboot.patch
Reset USB role to host before shutdown
to prevent shutdown hang.
Jira: OAM-71244
Signed-off-by: saranya <saranya.gopal@intel.com>
=> google_diff: Fix issue with shutdown

android_p/google_diff/cel_apl/frameworks/base/0024-CELADON-Bugfix-Screen-will-not-display-Power.patch
Screen will not display “Power/Restart/Sleep”
options after resume from S3. However this issue
was specific to APL.
Tracked-On: OAM-72731
=> [CELADON] Screen will not display “Power/Restart/Sleep”

android_p/google_diff/cel_apl/packages/apps/Car/SystemUpdater/0001-systemupdater-access-removable-storage.patch, android_p/google_diff/cel_apl/system/update_engine/0002-update_engine-to-media_rw.patch
1. Add update_engine to media_rw group, allow update_engine
to access the OTA file in removable storage.
2. Add WRITE_MEDIA_STORAGE permission in SystemUpdater,
allow it to select OTA package in removable storage,
such as USB stick or SD card.
Change-Id: Ibcb1c15acec151d6ffaa3957cd05580a0f338dfb
Tracked-On: OAM-73479
Signed-off-by: hengluo <heng.luo@intel.com>
Signed-off-by: phireg <philippe.regnier@intel.com>
Reviewed-on: https://android.intel.com:443/649670
=> Allow SystemUpdater&update_engine to access removable storage

android_p/google_diff/cel_apl/frameworks/native/0003-Make-DisplayInfo-struct-packed.patch, android_p/google_diff/celadon/frameworks/native/0003-Make-DisplayInfo-struct-packed.patch
When DisplayInfo is handled through binder transaction, especially
between a 32-bit client and 64-bit service, it may have different
size and client will receive incorrect values. Make this struct packed
and so it will keep the same size.
Tracked-On: OAM-71847
Signed-off-by: Hongcheng Xie <hongcheng.xie@intel.com>
=> Make DisplayInfo struct packed

android_p/google_diff/cel_apl/external/minigbm/0001-usb-the-private-drm-name.patch, android_p/google_diff/cel_apl/vendor/intel/external/project-celadon/hwcomposer/0001-use-the-private-drm-lib-name.patch, android_p/google_diff/cel_apl/vendor/intel/external/project-celadon/libdrm/0001-usb-the-private-drm-lib-name.patch, android_p/google_diff/cel_apl/vendor/intel/external/project-celadon/mesa/0001-use-the-private-drm-lib-name.patch, android_p/google_diff/celadon/external/minigbm/0001-usb-the-private-drm-name.patch, android_p/google_diff/celadon/vendor/intel/external/project-celadon/hwcomposer/0001-use-the-private-drm-lib-name.patch, android_p/google_diff/celadon/vendor/intel/external/project-celadon/libdrm/0001-usb-the-private-drm-lib-name.patch, android_p/google_diff/celadon/vendor/intel/external/project-celadon/mesa/0001-use-the-private-drm-lib-name.patch
To enable Treble, we need add Google's libdrm back and rename GFX libdrm to libdrm_pri
=> Rename GFX libdrm to libdrm_pri

android_p/google_diff/cel_apl/frameworks/av/services/0003-Allow-virtual-driver-to-be-used-as-primary.patch, android_p/google_diff/cel_apl/vendor/intel/external/project-celadon/audio/0001-Handle-dummy-sound-card-in-hal.patch
Handle dummy sound device as primary device
when no default sound card is present
Tracked-On: OAM-75019
=> Add support for dummy sound card

android_p/google_diff/cel_apl/bionic/0001-seccomp-Allow-readlink-2-in-x86_64-for-UBSan-s-sake.patch, android_p/google_diff/cel_apl/bionic/0002-seccomp-Allow-open-2-and-getdents-2-in-x86_64-for-UB.patch, android_p/google_diff/cel_kbl/bionic/0001-seccomp-Allow-readlink-2-in-x86_64-for-UBSan-s-sake.patch, android_p/google_diff/cel_kbl/bionic/0002-seccomp-Allow-open-2-and-getdents-2-in-x86_64-for-UB.patch, android_p/google_diff/celadon/bionic/0001-seccomp-Allow-readlink-2-in-x86_64-for-UBSan-s-sake.patch, android_p/google_diff/celadon/bionic/0002-seccomp-Allow-open-2-and-getdents-2-in-x86_64-for-UB.patch
Fix the CtsWrapWrapDebugMallocDebugTestCases and the
CtsWrapWrapDebugTestCases can not be executed.
Tracked-On: https://jira.devtools.intel.com/browse/OAM-71354
=> seccomp: Allow readlink(2) in x86_64 for UBSan's sake

android_p/google_diff/cel_apl/packages/apps/Car/Settings/0005-Fix-for-Audio-not-routing-to-DUT-after-BT-OFF-ON.patch
Reference phone Audio over Bluetooth is not routing
to IVI speakers after bluetoth turn OFF and ON from DUT car
settings.
Analysis: the root cause of the issue is as:
1. After BT OFF/ON from the Car Settings, when BT turns on,
it is initiating the scanning and also at the same time,
the connection to the already bonded devices starts.
2. As the controller is performing discovery of devices, so
when it receives "Create Connection" Command, it rejects the
command with the status "Command Disallowed- 0x0c".
3. Due to this, A2DPSink and HEADSET_CLIENT profiles are not
able to connect.
Fix: Removed StartScanning when BT turns on in Car Settings.
Scanning will not be initiated automatically on BT ON event
from Car Sttings App.
Test: BT Pairing, Audio routing after BT OFF/ON working fine …
=> Issue: Fix for Audio not routing to DUT after BT OFF/ON

android_p/google_diff/cel_kbl/bionic/0003-Adding-ceil-floor-sin-cos-assembly-files-in-libm-wit.patch
This patch adds optimized math functions ceil, sin, cos, floor
for AVX2
Tracked-On: OAM-75472
Signed-off-by: anuvarsh <anuvarshini.bc@intel.com>
=> Add AVX2 support for libm

android_p/google_diff/cel_apl/frameworks/base/0025-Not-to-save-and-dump-the-empty-approved-list.patch, android_p/google_diff/cel_kbl/frameworks/base/0025-Not-to-save-and-dump-the-empty-approved-list.patch, android_p/google_diff/celadon/frameworks/base/0025-Not-to-save-and-dump-the-empty-approved-list.patch
To dump a empty approved list will cause cts cases fail,
and also no need to save the empty ones.
Tracked-On: OAM-75159
=> Not to save and dump the empty approved list.

android_p/google_diff/cel_apl/packages/services/Car/0009-Fix-the-Add-new-user-text-is-not-visible.patch, android_p/google_diff/cel_kbl/packages/services/Car/0009-Fix-the-Add-new-user-text-is-not-visible.patch
Text is not visible due to use the dark text color.
Tracked-On: https://jira.devtools.intel.com/browse/OAM-75448
=> Fix the "Add new user?" text is not visible

android_p/google_diff/cel_apl/packages/apps/Car/Settings/0006-Fix-the-black-screen-was-observed-in-the-CarSettings.patch, android_p/google_diff/cel_kbl/packages/apps/Car/Settings/0004-Fix-the-black-screen-was-observed-in-the-CarSettings.patch
The black screen observed due to the mGridAdapter data
was cleared on the onStop status. Adding the mGridAdapter
data in the onStart status to recovery the data.
Test:
1) Set a pattern/pin lock as an owner
2) Click on the notification symbol and click "add new user"
3) Once UI is at new user screen > switch back to owner
4) When prompted to enter pattern/pin > click on "cancel"
5) Click on owner from "lock screen" > enter pattern > owner UI comes up
6) Click on car settings > observe
Tracked-On: https://jira.devtools.intel.com/browse/OAM-75447
=> Fix the black screen was observed in the CarSettings

android_p/google_diff/cel_apl/frameworks/native/0004-Disable-feature-android.software.app_widgets-on-the-.patch, android_p/google_diff/cel_kbl/frameworks/native/0004-Disable-feature-android.software.app_widgets-on-the-.patch
Car launcher doesn't implement AppWidgetHost to support "android.software.app_widgets".
Change-Id: I39b4f0379a2613e9a19ce7bb32440558cc025f8a
Tracked-On: https://jira.devtools.intel.com/browse/OAM-75541
=> Disable feature "android.software.app_widgets" on the automotive device.

android_p/google_diff/cel_apl/packages/apps/Car/Settings/0007-Add-primary-text-color-to-the-CarSettingTheme.patch, android_p/google_diff/cel_kbl/packages/apps/Car/Settings/0005-Add-primary-text-color-to-the-CarSettingTheme.patch
The base style from the "Theme.Car.Light", the primary
text color needs to be declared.
Tracked-On: https://jira.devtools.intel.com/browse/OAM-69588
=> Add primary text color to the CarSettingTheme

android_p/google_diff/cel_apl/external/wpa_supplicant_8/0002-Skip-private-commands-causing-vts-failure.patch, android_p/google_diff/cel_kbl/external/wpa_supplicant_8/0002-Skip-private-commands-causing-vts-failure.patch
As some of the vendor interfaces requires usage of
vendor specific commands and also some are not applicable or
handle internally inside firmware, complete the request as
success.
Tracked-On: OAM-75989
=> wpa_supplicant: Skip private commands causing vts failure

android_p/google_diff/cel_kbl/packages/apps/Car/Settings/0005-Fix-for-Audio-not-routing-to-DUT-after-BT-OFF-ON.patch, android_p/google_diff/cel_kbl/packages/apps/Settings/0002-Adding-only-one-pbap-profile-client-or-server-to-the.patch
Issue: Reference phone Audio over Bluetooth is not routing
to IVI speakers after bluetooth turn OFF and ON from DUT car
settings.
Analysis: the root cause of the issue is as:
1. After BT OFF/ON from the Car Settings, when BT turns on,
it is initiating the scanning and also at the same time,
the connection to the already bonded devices starts.
2. As the controller is performing discovery of devices, so
when it receives "Create Connection" Command, it rejects the
command with the status "Command Disallowed- 0x0c".
3. Due to this, A2DPSink and HEADSET_CLIENT profiles are not
able to connect.
Fix: Removed StartScanning when BT turns on in Car Settings.
Scanning will not be initiated automatically on BT ON event
from Car Sttings App.
Test: BT Pairing, Audio routing after BT OFF/ON working …
=> Fix for Audio not routing to DUT after BT OFF/ON

android_p/google_diff/celadon/external/wpa_supplicant_8/0002-Skip-private-commands-causing-vts-failure.patch, android_p/google_diff/celadon/frameworks/opt/net/wifi/0001-libwifi-hal-Add-libwifi-hal-for-intel.patch, android_p/google_diff/celadon/hardware/interfaces/0003-wifi-Disable-capabilities-not-yet-supported.patch
Changes include:
- libwifi-hal: Add libwifi-hal for intel
- wifi: Disable capabilities not yet supported
- wpa_supplicant: Skip private commands causing vts failure
Tracked-On: OAM-76167
=> celadon: Fix for wifi not working after treble specific changes

android_p/google_diff/cel_apl/system/netd/0001-REVERT-ME-Fallback-to-legacy-xt_qtaguid-network-traf.patch, android_p/google_diff/cel_kbl/system/netd/0001-REVERT-ME-Fallback-to-legacy-xt_qtaguid-network-traf.patch, android_p/google_diff/celadon/system/netd/0001-REVERT-ME-Fallback-to-legacy-xt_qtaguid-network-traf.patch
eBPF network traffic control is not yet working causing
many CTS test failures.
As a temporary fix, disable eBPF support. When eBPF support
is disabled, legacy(xt_qtaguid) network traffic control
will be used.
Tracked-On: OAM-76268
Signed-off-by: Harshita Goswami <harshita.goswami@intel.com>
Signed-off-by: Amrita Raju <amrita.raju@intel.com>
Signed-off-by: Nitin Rawat <nitin.rawat@intel.com>
=> [REVERT ME] Fallback to legacy(xt_qtaguid) network traffic control

android_p/google_diff/cel_apl/packages/services/Car/0009-Add-TelephonyManager-preload-class-to-fix-CTS-test-f.patch, android_p/google_diff/cel_kbl/packages/services/Car/0009-Add-TelephonyManager-preload-class-to-fix-CTS-test-f.patch
TelephonyManager class should be preloaded by zygote, com.android.cts.
webkit.WebViewHostSideStartupTest.testStrictMode in CtsSecurityTestCases
will use it.
Tracked-On: OAM-76469
Signed-off-by: Lei,RayX <rayx.lei@intel.com>
=> Add TelephonyManager preload class to fix CTS test failure

android_p/google_diff/cel_apl/device/intel/build/0001-WORKAROUND-CELADON-edit-make-publish_ci.patch, android_p/google_diff/cel_kbl/device/intel/build/0001-WORKAROUND-CELADON-edit-make-publish_ci.patch, android_p/google_diff/celadon/device/intel/build/0001-WORKAROUND-CELADON-edit-make-publish_ci.patch
gpt image is around 14G in size.
Hence, removing upload of *gpt_image to artifactory
untic artifactory speed is improved
<To be reverted once we have artifactory issue fixed>
Tracked-On: OAM-75233
=> [WORKAROUND][CELADON] edit 'make publish_ci'

android_p/google_diff/cel_apl/frameworks/opt/net/wifi/0002-Remove-the-interface-state-change-done-after-softap-.patch, android_p/google_diff/cel_kbl/frameworks/opt/net/wifi/0002-Remove-the-interface-state-change-done-after-softap-.patch, android_p/google_diff/celadon/frameworks/opt/net/wifi/0002-Remove-the-interface-state-change-done-after-softap-.patch
Wi-Fi hotspot is getting deactivated after few seconds
of activation.
After setting up the interface in AP mode, interface state
changed is triggered from setupInterfaceForSoftApMode function
to avoid any race conditions. As the interface state changed
received properly whenever link state is changed, updating
interface state changed after setup call results in hotspot
getting deactivated after few seconds of activation.
Remove the interface state changed done on setup interface.
Interface state change on link state changed event is enough to
properly update the SoftAp state machine.
Tracked-On: OAM-76271
Signed-off-by: Harshita Goswami <harshita.goswami@intel.com>
=> Remove the interface state change done after softap setup

android_p/google_diff/cel_apl/frameworks/base/0027-Fix-disallow-user-switch-from-Device-owner-Test-fail.patch, android_p/google_diff/cel_apl/packages/apps/Car/Settings/0008-Fix-disallow-user-switch-for-CTS-Device-owner-Test.patch, android_p/google_diff/cel_kbl/frameworks/base/0027-Fix-disallow-user-switch-from-Device-owner-Test-fail.patch, android_p/google_diff/cel_kbl/packages/apps/Car/Settings/0006-Fix-disallow-user-switch-for-CTS-Device-owner-Test.patch
If devices are managed by the admin, the current user doesn't allow
to manage USER.
Tracked-On: OAM-76693
=> Fix "disallow user switch" from "Device owner Test" failed

android_p/google_diff/cel_apl/packages/apps/Car/LensPicker/0003-Add-runtime-permission-request.patch, android_p/google_diff/cel_kbl/packages/apps/Car/LensPicker/0003-Add-runtime-permission-request.patch
request the runtime permission:
<uses-permission android:name="android.permission.GRANT_RUNTIME_PERMISSIONS" />
<uses-permission android:name="android.permission.INTERACT_ACROSS_USERS_FULL" />
Tracked-On: OAM-76346
=> Fix unable to open screenshot with the gallery

android_p/google_diff/cel_apl/frameworks/base/0028-Recover-shady-content-paths.patch, android_p/google_diff/cel_kbl/frameworks/base/0029-Recover-shady-content-paths.patch
paths, but most providers internally use UriMatcher to decide what
to do with an incoming Uri.
This causes trouble because UriMatcher uses Uri.getPathSegments(),
which quietly ignores "empty" paths.  Consider this example:
<path-permission android:pathPrefix="/private" ... />
uriMatcher.addURI("com.example", "/private", CODE_PRIVATE);
content://com.example//private
The Uri above will pass the security check, since it's not
technically a prefix match.  But the UriMatcher will then match it
as CODE_PRIVATE, since it ignores the "//" zero-length path.
Since we can't safely change the behavior of either path-permission
or UriMatcher, we're left with recovering these shady paths by
trimming away zero-length paths.
cherry-pick from:
https://android.googlesource.com/platform/frameworks/base/+/798 …
=> The path-permission element offers prefix or regex style matching of

android_p/google_diff/cel_apl/system/sepolicy/0006-Update-socket-ioctl-restrictions.patch, android_p/google_diff/cel_apl/system/sepolicy/0007-public-netd.te-allow-netd-to-operate-icmp_socket-tha.patch, android_p/google_diff/cel_kbl/system/sepolicy/0006-Update-socket-ioctl-restrictions.patch, android_p/google_diff/cel_kbl/system/sepolicy/0007-public-netd.te-allow-netd-to-operate-icmp_socket-tha.patch, android_p/google_diff/celadon/system/sepolicy/0006-Update-socket-ioctl-restrictions.patch, android_p/google_diff/celadon/system/sepolicy/0007-public-netd.te-allow-netd-to-operate-icmp_socket-tha.patch, android_p/google_diff/clk/system/sepolicy/0006-Update-socket-ioctl-restrictions.patch, android_p/google_diff/clk/system/sepolicy/0007-public-netd.te-allow-netd-to-operate-icmp_socket-tha.patch
=> SELinux: cherry-pick some AOSP sepolicy rules related with icmp_socket

android_p/google_diff/clk/hardware/intel/kernelflinger/0006-Revert-me-Don-t-use-nvme-passthru-when-erase-blocks-.patch
Since there is not any UEFI platform support the write zerror command
through passthru of NVMe, this command might cause some platform crash,
so does not use it at all.
Tracked-On: OAM-79434
Signed-off-by: Meng Xianglin <xianglinx.meng@intel.com>
=> Don't use nvme passthru for clk in UEFI platform

android_p/google_diff/cel_kbl/kernel/project-celadon/0007-usb-xhci-dbc-Add-a-dbc-raw-driver-to-provide-a-raw-i.patch, android_p/google_diff/cel_kbl/system/core/0025-System-Core-ADB-Adding-DBC-support-in-ADB-Daemon.patch
This patch provides a raw device interface on xhci Debug capability.
This abstracts dbc functionality to user space inorder to facilitate
various frameworks to utilize xhci debug capability.
Tracked-On: OAM-79899
=> usb: xhci: dbc: Add a dbc raw driver to provide a raw interface on DbC

android_p/google_diff/clk/frameworks/base/0030-Fix-data-source-for-HEIF-exif-extractor.patch
Do not allow the source to read past available bytes, since
the underlying input stream may not be able to seek after that.
For input streams from files, the available bytes is usually the
file size, and we usually don't have problem when the file is
of decent size. But when the file is very small, some of the
extractors (other than mp4) would request bytes past the end
of the file, which goes over the available range. Once that
condition is hit, we can't reset to the offet needed for
mp4 extractor and heif parsing would fail
Tracked-On: OAM-79903
Signed-off-by: varunjex <varunx.jeevangoudar@intel.com>
=> Fix data source for HEIF exif extractor

android_p/google_diff/cel_apl/hardware/intel/kernelflinger/0007-Implement-event-based-transport_run-for-usb-transpor.patch, android_p/google_diff/cel_kbl/hardware/intel/kernelflinger/0007-Implement-event-based-transport_run-for-usb-transpor.patch, android_p/google_diff/celadon/hardware/intel/kernelflinger/0007-Implement-event-based-transport_run-for-usb-transpor.patch, android_p/google_diff/clk/hardware/intel/kernelflinger/0007-Implement-event-based-transport_run-for-usb-transpor.patch
Polling based transport_run will be blocked when experiencing
longtime erasing or download, then the connection between
host and device will lost. Implement event based transport_run
for usb transport
efiwrapper doesn't support SetTimer, polling based transport_run
is still there for ABL.
Tracked-On: OAM-71603
Signed-off-by: Meng Xianglin <xianglinx.meng@intel.com>
=> Fix a bug cause flashing image failed by PFT on Windows

android_p/google_diff/cel_apl/frameworks/av/0001-Add-an-option-to-record-screen-with-Hevc-encoder.patch, android_p/google_diff/cel_kbl/frameworks/av/0001-Add-an-option-to-record-screen-with-Hevc-encoder.patch, android_p/google_diff/celadon/frameworks/av/0001-Add-an-option-to-record-screen-with-Hevc-encoder.patch, android_p/google_diff/clk/frameworks/av/0001-Add-an-option-to-record-screen-with-Hevc-encoder.patch
This change is to add an option in screen recorder to enable hevc encoder.
Tracked-On: OAM-79950
Signed-off-by: tianmi.chen <tianmi.chen@intel.com>
=> Add an option to record screen with Hevc encoder

android_p/google_diff/clk/hardware/intel/kernelflinger/0007-Disable-NVMe-RPMB-supported-in-WHL.patch
In WHL RVP, the NVMe RPMB is not supported and cause flash failed.
But we also need to support eMMC RPMB using one binary.
So we need to disable the NVMe RPMB suuport in clk lunch target.
Tracked-On: OAM-80029
Signed-off-by: Yanhongx.Zhou <yanhongx.zhou@intel.com>
=> Kernelflinger: Disable NVMe RPMB supported in WHL

android_p/google_diff/cel_apl/hardware/intel/kernelflinger/0008-adb-dbc-Adding-kernel-cmdline-for-DbC-Raw-serialno.patch, android_p/google_diff/cel_kbl/hardware/intel/kernelflinger/0008-adb-dbc-Adding-kernel-cmdline-for-DbC-Raw-serialno.patch, android_p/google_diff/celadon/hardware/intel/kernelflinger/0008-adb-dbc-Adding-kernel-cmdline-for-DbC-Raw-serialno.patch, android_p/google_diff/clk/hardware/intel/kernelflinger/0008-adb-dbc-Adding-kernel-cmdline-for-DbC-Raw-serialno.patch
Adding serial number support in kernel CMDLINE argument(xhci-dbgraw.serialno)
for DbC RAW driver.
Tracked-On: OAM-69212
=> kernelflinger: adb: dbc: Adding xhci-dbgraw.serialno in Kernel cmdline

android_p/google_diff/cel_kbl/kernel/project-celadon/0008-usb-xhci-dbc-Reading-serial-number-from-kernel-CMDLI.patch, android_p/google_diff/clk/kernel/project-celadon/0006-usb-xhci-dbc-Reading-serial-number-from-kernel-CMDLI.patch
Adding support to read platform serial number from the kernel cmdline
argument for DbC RAW driver.
Tracked-On: OAM-69212
=> usb: xhci: dbc: Reading serial number from kernel CMDLINE

android_p/google_diff/cel_apl/hardware/intel/kernelflinger/0009-Optimization-check-for-pointer-and-array.patch, android_p/google_diff/cel_kbl/hardware/intel/kernelflinger/0009-Optimization-check-for-pointer-and-array.patch, android_p/google_diff/celadon/hardware/intel/kernelflinger/0009-Optimization-check-for-pointer-and-array.patch, android_p/google_diff/clk/hardware/intel/kernelflinger/0009-Optimization-check-for-pointer-and-array.patch
1. Null check for pointer 'lun_str' before dereferenced.
2. Initialize 'file' and 'tree1d' array before dereferenced.
Tracked-On: OAM-80260
Signed-off-by: Meng Xianglin <xianglinx.meng@intel.com>
=> Optimization check for pointer and array

android_p/google_diff/clk/hardware/intel/kernelflinger/0009-Fix-the-issue-of-failed-to-use-simulate-RPMB-if-phys.patch
Use simulate RPMB if physical RPMB not found.But kernelflinger failed to
use simulate RPMB if physical RPMB is not found.
Tracked-On: OAM-80290
Signed-off-by: Yanhongx.Zhou <yanhongx.zhou@intel.com>
=> Fix the issue of failed to use simulate RPMB if physical RPMB not found

android_p/google_diff/clk/device/intel/project-celadon/0004-Enable-capture-source-for-WHL-target.patch
With this mixer_path patch we enabled Capture Source as Mic
and disabled Auto Mute mode.
Tracked-On: OAM-80371
Signed-off-by: Karan Patidar <karan.patidar@intel.com>
=> [WHL] Enabling capture source as mic

android_p/google_diff/cel_apl/frameworks/base/0029-Add-the-dedicated-btusb-device-to-blacklist.patch, android_p/google_diff/cel_kbl/frameworks/base/0030-Add-the-dedicated-btusb-device-to-blacklist.patch
Inorder to prevent car usb handler using the btusb devices,
these devices are added to the usb blacklist.
adding Jfp and Thp modules to the blacklist
Tracked-On: OAM-80209
=> Add dedicated BTUSB devices to USB blacklist

android_p/google_diff/clk/vendor/intel/external/project-celadon/hwcomposer/0001-Disable-RBC.patch
Disable RBC temporary as this issue block feature.
Test: 4K display works well, do not have other issue.
Tracked-On: OAM-80004
=> Fix the 4K eDP stuck issue

android_p/google_diff/cel_apl/trusty/app/keymaster/0001-Google-Diff-make-the-app-keymaster-build-pass.patch, android_p/google_diff/cel_apl/trusty/external/lk/0001-x64-64-enabling-patch-for-google-diff.patch, android_p/google_diff/cel_apl/trusty/lib/0001-enable-x86-64-google-diff.patch, android_p/google_diff/cel_apl/trusty/lk/trusty/0001-enable-x86-64-google-diff-patch.patch, android_p/google_diff/cel_kbl/trusty/app/keymaster/0001-Google-Diff-make-the-app-keymaster-build-pass.patch, android_p/google_diff/cel_kbl/trusty/external/lk/0001-x64-64-enabling-patch-for-google-diff.patch, android_p/google_diff/cel_kbl/trusty/lib/0001-enable-x86-64-google-diff.patch, android_p/google_diff/cel_kbl/trusty/lk/trusty/0001-enable-x86-64-google-diff-patch.patch, android_p/google_diff/celadon/trusty/app/keymaster/0001-Google-Diff-make-the-app-keymaster-build-pass.patch, android_p/google_diff/celadon/trusty/external/lk/0001-x64-64-enabling-patch-for-google-diff.patch, android_p/google_diff/celadon/trusty/lib/0001-enable-x86-64-google-diff.patch, android_p/google_diff/celadon/trusty/lk/trusty/0001-enable-x86-64-google-diff-patch.patch, android_p/google_diff/clk/trusty/app/keymaster/0001-Google-Diff-make-the-app-keymaster-build-pass.patch, android_p/google_diff/clk/trusty/external/lk/0001-x64-64-enabling-patch-for-google-diff.patch, android_p/google_diff/clk/trusty/lib/0001-enable-x86-64-google-diff.patch, android_p/google_diff/clk/trusty/lk/trusty/0001-enable-x86-64-google-diff-patch.patch
enable several security compile flags
enable stack protector for lk and TA
fix the banned C function usage issue in Trusty
optimize code for app/keymaster
Tracked-On: OAM-76456
Signed-off-by: Zhang, Qi <qi1.zhang@intel.com>
Signed-off-by: Yan, Shaopu <shaopu.yan@intel.com>
Signed-off-by: sheng wei <w.sheng@intel.com>
=> Optimize trusty lk

android_p/google_diff/cel_kbl/vendor/intel/external/project-celadon/hwcomposer/0001-Disable-RBC.patch
The RBC will cause 4k primary display stuck and messy screen when video playback
Test: 4K display works well, video playback well.
Tracked-On: OAM-79630
=> Disable RBC on KBL

android_p/google_diff/cel_apl/device/intel/build/0001-edit-make-publish_ci.patch, android_p/google_diff/cel_kbl/device/intel/build/0001-edit-make-publish_ci.patch, android_p/google_diff/celadon/device/intel/build/0001-edit-make-publish_ci.patch, android_p/google_diff/clk/device/intel/build/0001-edit-make-publish_ci.patch
gpt image is around 14G in size.
Hence, removing upload of *gpt_image to artifactory
untic artifactory speed is improved
<To be reverted once we have artifactory issue fixed>
Tracked-On: OAM-82994
=> edit 'make publish_ci'

android_p/google_diff/cel_kbl/kernel/project-celadon/0010-usb-xhci-dbc-Fixing-typo-error.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0011-usb-xhci-dbc-make-DbC-modular-introducing-dbc_functi.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0012-usb-xhci-dbc-DbC-TTY-driver-to-use-new-interface.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0013-usb-xhci-dbc-Provide-sysfs-option-to-configure-dbc-d.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0014-usb-xhci-dbc-Add-a-dbc-raw-driver-to-provide-a-raw-i.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0015-usb-xhci-dbc-Document-describe-about-dbc-raw-interfa.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0016-usb-xhci-dbc-Reading-serial-number-from-kernel-CMDLI.patch
Porting all the DbC patches to the latest kernel version
4.19.46 for KBL-NUC.
Tracked-On: OAM-83084
=> usb: xhci: dbc: Porting DbC to kernel version 4.19.46

android_p/google_diff/cel_apl/device/intel/project-celadon/0006-Enable-BT-SCO-HCI-driver.patch, android_p/google_diff/cel_apl/kernel/project-celadon/0009-Fix-kernel-panic-on-suspend-resume-and-rmmod-of-btus.patch, android_p/google_diff/cel_kbl/device/intel/project-celadon/0006-Enable-BT-SCO-HCI-driver.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0010-Fix-kernel-panic-on-suspend-resume-and-rmmod-of-btus.patch, android_p/google_diff/celadon/device/intel/project-celadon/0002-Enable-BT-SCO-HCI-driver.patch, android_p/google_diff/celadon/kernel/project-celadon/0007-Fix-kernel-panic-on-suspend-resume-and-rmmod-of-btus.patch
Fixes for kernel panic seen on rmmod
- URBs freed
- Sound card is disconnected
- Release USB interfaces
Fixes for kernel panic on suspend/resume
- Provide a dummy implementation for suspend/resume
- Enable BT SCO HCI driver
Tracked-On: OAM-80746
=> Fix kernel panic on suspend/resume and rmmod of btusb sco driver

android_p/google_diff/cel_kbl/device/intel/project-celadon/0001-PATCH-Modify-cpu-arch-for-cel_kbl.patch
when add keybox_provision parameter in mixins.sepc,it
conflict with this patch. what we change does not affect
the orginal function.
Tracked-On: OAM-83317
Signed-off-by: Zhang, Xuepeng <xuepeng.zhang@intel.com>
=>  resolution conflict for add keybox_provision

android_p/google_diff/cel_kbl/hardware/libhardware/modules/usbaudio/0002-CEL_KBL-Avoid-klocwork-errors.patch
Avoid null pointer dereferences and memory leaks detected by
klocwork.
Tracked-On: OAM-83539
Signed-off-by: Karan Patidar <karan.patidar@intel.com>
=> [CEL_KBL] Fix erros reported by klocwork

android_p/google_diff/cel_apl/kernel/project-celadon/0011-Fix-race-condition-in-btusb_sco_snd_card-driver.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0018-Fix-race-condition-in-btusb_sco_snd_card-driver.patch, android_p/google_diff/celadon/kernel/project-celadon/0009-Fix-race-condition-in-btusb_sco_snd_card-driver.patch
Issue: Race condition occurs in the prepare call.
Prepare for playback and capture will call configure_endpoints
method to configure the TX and RX endpoints. When the prepare
is called for playback first, configure_endpoints method is
called which sets and BTUSB_ISOC_TX_EP_CONFIGURED and proceed
to do endpoint configuration. Prepare call can be called for
the capture during this time which calls the configure_endpoints
again. Since the BTUSB_ISOC_TX_EP_CONFIGURED is already set,
the configure_enpoints for the capture returns and it will
proceed to initialise the capture URBs. Since the endpoints
were in the process of configuration, the EP descriptors are
not getting populated properly at the time of initialising
capture URB, submission of capture URB to fail. Similarly
issue will also …
=> Fix race condition in btusb_sco_snd_card driver

android_p/google_diff/cel_apl/external/sqlite/0001-Fix-sqlite-CTS-issue.patch, android_p/google_diff/cel_kbl/external/sqlite/0001-Fix-sqlite-CTS-issue.patch
This patch fixes Magellan SQLite Security Vulnerability as in
b/121156452
Download from https://www.sqlite.org/src/info/c255889bd95bd543
Get the Tarball or ZIP Archive, unzip it on linux machine then run:
mkdir bld; cd bld; ../configure; make sqlite3.c
Copy sqlite3.c, sqlite3.h, sqlite3ext.h, shell.c from bld directory
to dist/orig.
dist contains a copy of dist/orig, but with the Android.patch
file applied.
Bug: 121156452
Test: select sqlite_version() - returns 3.22.0
Test: atest cts/SQLiteDatabaseTest all passed.
Test: atest cts/SQLSecurityTest
Change-Id: Iea1cefe2577ac52da84b24b6d51e1769042e449a
Merged-In: Iad8c3d1d74d8591a75a4c033c8bf9d3956d2fe4f
(cherry picked from commit 7fbf27c91af1621264154cc09f0fdafb3ba69ed3)
Tracked-On: OAM-83586
Signed-off-by: johnzhax <johnx.zhang@intel.com> …
=> RESTRICT AUTOMERGE: Apply security patch to sqlite 3.22.

android_p/google_diff/cel_apl/frameworks/base/0027-Do-not-linkify-text-with-RLO-LRO-characters.patch, android_p/google_diff/cel_kbl/frameworks/base/0027-Do-not-linkify-text-with-RLO-LRO-characters.patch
Also don't show smart actions for selections in text with unsupported
characters.
Bug: 116321860
Test: atest android.view.textclassifier.TextClassificationManagerTest \
android.text.util.cts.LinkifyTest \
android.text.util.LinkifyTest \
android.widget.TextViewActivityTest
Tracked-On: OAM-83602
Signed-off-by: Lei,RayX <rayx.lei@intel.com>
=> RESTRICT AUTOMERGE Do not linkify text with RLO/LRO characters.

android_p/google_diff/cel_apl/frameworks/native/0005-Sanitize-InputMessage-before-sending.patch, android_p/google_diff/cel_kbl/frameworks/native/0005-Sanitize-InputMessage-before-sending.patch
The struct InputMessage has many fields, and is force-aligned to 8-byte
boundaries. There are also some padding fields that carry no
information.
This struct is typically allocated in the stack and populated with
various values before being sent across as a stream of bytes through the
socket.
Therefore, the "unused" data portions of the struct could contain
portions of the stack, since there aren't ever writes to those memory
locations.
To avoid this information leak, forcefully sanitize the struct. Create a
new struct that is explicitly set to zero. Next, only fill the
meaningful fields manually.
Bug: 115739809
Test: cts-tradefed run cts -m CtsSecurityBulletinHostTestCases -t android.security.cts.Poc18_12; adb shell monkey 100000
Change-Id: I7e44dacf1e8fa3156c8e4d2f7784ef0c53dab507 …
=> Sanitize InputMessage before sending

android_p/google_diff/celadon/frameworks/base/0030--Fix-unable-to-show-overview-button.patch, android_p/google_diff/clk/frameworks/base/0030--Fix-unable-to-show-overview-button.patch
Overview button is not show due to the menu_container's layout_width
is too large.
Tracked-On: OAM-83824
=> Fix unable to show overview button

android_p/google_diff/clk/device/intel/project-celadon/0005-usb-gadget-ACM-Enabling-USB-ACM-gadget-for-WHL.patch
Enable USB CDC ACM gadget for WHL platform.
Tracked-On: OAM-83964
=> usb: gadget: ACM: Enabling USB ACM gadget for WHL

android_p/google_diff/cel_kbl/frameworks/base/0031-Informing-app-idle-listeners-on-enabled-state-change.patch
Currently, if AppStandbyController is enabled after some listeners have
already registered, the listeners will be told that the system is in a
state of parole even though AppStandbyController thinks it's not in
parole. This change informs AppIdleStateChangeListeners when
AppStandbyController's enabled state changes as well so that they can be
in the correct state.
I also removed the call to setAppIdleEnabled() in onBootPhase() since
updateSettings() is called right afterwards and that also calls
setAppIdleEnabled().
Bug: 112329453
Test: atest AppStandbyControllerTests
also check logs to confirm that NetworkPolicyManagerService and
JobSchedulerService's listeners switch from ON to OFF when the system is
ready.
Tracked-On: https://jira.devtools.intel.com/browse/OAM-84021
Signed-off-by: …
=> Informing app idle listeners on enabled state changes.

android_p/google_diff/cel_kbl/frameworks/base/0032-Fix-for-CTS-testAllowWhileIdleJobInTempwhitelist.patch
In this test case when all constraints to run the jobs are satisfied,
then to make job ready to run, intent MSG_CHECK_JOB is send to job handler.
But this intent is not dispatched to job handler.
BUG: 113778907
Test:After these changes this CTS case always passed.
Change-Id: I8c63361dcd7ade19b724c9bc2fdf78d5f10c8d71
Merged-In: I8c63361dcd7ade19b724c9bc2fdf78d5f10c8d71
Feature: CTS(*)
Tracked-On: https://jira.devtools.intel.com/browse/OAM-
=> Fix for CTS testAllowWhileIdleJobInTempwhitelist

android_p/google_diff/clk/device/intel/project-celadon/0006-usb-gadget-NCM-Enabling-USB-NCM-gadget-for-WHL.patch
Enable USB CDC NCM gadget for WHL platform.
Tracked-On: OAM-83965
=> usb: gadget: NCM: Enabling USB NCM gadget for WHL

android_p/google_diff/clk/device/intel/project-celadon/0007-usb-ACM-Enabling-USB-Host-CDC-ACM-class.patch
Enable USB Host CDC ACM class for WHL.
Tracked-On: 84164
=> usb: ACM: Enabling USB Host CDC ACM class

android_p/google_diff/cel_kbl/kernel/project-celadon/0019-usb-dbc-fix-for-adb-root-issue.patch
freeing usb request into the callback function.
Tracked-On: OAM-84000
Signed-off-by: Balaji <m.balaji@intel.com>
=> usb: dbc: fix for adb root issue

android_p/google_diff/cel_apl/vendor/intel/external/project-celadon/hwcomposer/0001-Disable-RBC.patch, android_p/google_diff/celadon/vendor/intel/external/project-celadon/hwcomposer/0001-Disable-RBC.patch
The RBC will cause 4K display stuck
Test: 4K display works well, no regression.
Tracked-On: OAM-84580
=> Disable RBC on cel_apl and celadon

android_p/google_diff/clk/frameworks/base/0031-Fix-for-adb-dbc-offline-issue.patch, android_p/google_diff/clk/kernel/project-celadon/0023-usb-dbc-Fix-for-offline-issue.patch
Adb daemon doesnt know about dbc disconnect and connect.hence offline
issue occurs when replug.Changes made usb device manager to receive
usb dbc event from kernel and restart adb daemon.
Change-Id: I3973f68d0667d332792a9176e61c7a505c4c3101
Tracked-On: OAM-84534
Signed-off-by: Balaji <m.balaji@intel.com>
=> Fix for adb dbc offline issue

android_p/google_diff/clk/frameworks/base/0032-WHL_RVP-Improve-Wired-accessory-detection-logic.patch
WHL RVP board has issue with headset and line out events,
this results in failure to detect 3.5mm Headset correctly.
Applying changes as google_diff as its specific rvp board as
of now.
Tracked-On: OAM-85625
Signed-off-by: Karan Patidar <karan.patidar@intel.com>
=> [WHL_RVP] Improve headset detection logic

aosp_diff/preliminary/external/wpa_supplicant_8/679768_5-VtsHalWifiHostapdV1_1Target_module_has_multiple_methods_failing.patch
ACS(Automatic channel Selection) is not supported when creating
a WiFi Hotspot. Hence setting AP band to 2.4Ghz. Adding to check
on channel range to detect invalid channel range parameters.
Tracked-on:  OAM-85124
=> VtsHalWifiHostapdV1_1Target module has multiple methods failing

aosp_diff/celadon_ivi/frameworks/opt/net/wifi/678279_1-Fix-no-open-network-notification-issue.patch
The default notification user id is 0,but the current user id for car is
10.In CarNotificationListener,only posed notification for current user
and USER_ALL.So need to set userId for this notification.
Tracked-On: OAM-84682
Signed-off-by: Cao, KevinX <kevinx.cao@intel.com>
=>  Fix no open network notification issue

android_p/google_diff/clk/system/netd/0002-netd-Disable-Active-FTP-helper.patch
Wi-Fi Tethering fails as Active FTP helper ip rule
results in iptable update failure.
Tracked-On: OAM-85649
Signed-off-by: Gaganpreet kaur <gaganpreetx.kaur@intel.com>
=> netd: Disable Active FTP helper

aosp_diff/preliminary/bootable/recovery/678028-minui-Support-input-device-hotplug-in-recovery-mode.patch
In the old code, the recovery only enumerated the input devices at the
startup, and read the input events from these devices.
So if a USB input device is probed after the recovery startup, then the
recovery can't read the events from this device.
This patch use inotify to monitor /dev/input for new added input
device, then support input device hotplug in recovery mode.
Bug: 111847510
Test: can use USB keyboard hotplugged in recovery mode
Change-Id: I7e7dcbd619d3c66a2f40a43418f5dac6a50c859e
Tracked-On: OAM-86589
Signed-off-by: Liu Shuo A <shuo.a.liu@intel.com>
Signed-off-by: Ming Tan <ming.tan@intel.com>
Signed-off-by: Gao,ZiyiX <ziyix.gao@intel.com>
=> minul: Support input device hotplug in recovery mode.

aosp_diff/celadon_ivi/frameworks/av/680693_1-Change-HDMI-audio-priority-on-celadon.patch, aosp_diff/celadon_ivi/frameworks/base/680601_1-Handle-HDMI-audio-in-wiredaccessory-mgr.patch
Handle HDMI audio device in framework
Handle HDMI device in wired acc manager and default policy.
Tracked-On: OAM-84728
=> Handle HDMI audio device in framework

aosp_diff/celadon_ivi/packages/services/Car/681730_1-Set-config_quickSettingsSupported-to-false-for-IVI.patch
No quickSettings on IVI system, so disable it.
Tracked-On: OAM-88196
Signed-off-by: Xie, Shellyx <shellyx.xie@intel.com>
=> Set config_quickSettingsSupported to false for IVI

aosp_diff/caas/frameworks/av/03_1-Camera-Fix-crash-while-disconnecting-USB-Camera.patch, aosp_diff/caas/hardware/interfaces/02_1-Add-support-for-advanced-USB-3.x-based-Cameras.patch, aosp_diff/celadon_ivi/frameworks/av/03_1-Camera-Fix-crash-while-disconnecting-USB-Camera.patch, aosp_diff/celadon_ivi/hardware/interfaces/02_1-Add-support-for-advanced-USB-3.x-based-Cameras.patch, aosp_diff/celadon_tablet/frameworks/av/02_1-Camera-Fix-crash-while-disconnecting-USB-Camera.patch, aosp_diff/celadon_tablet/hardware/interfaces/02_1-Add-support-for-advanced-USB-3.x-based-Cameras.patch
Add USB camera hot-plug support and enabling
USB 3.X cameras.
Tracked-On: OAM-88490
Signed-off-by: Muhammad Aksar <muhammad.aksar@intel.com>
=> USB camera patches to support hotplug Feature and USB 3.x Cameras

aosp_diff/caas/system/core/02_1-system-core-init-Add-support-for-creation-of-usb-pri.patch
Create a dev node for usb printer and apply permissions for the same.
=> system:core: Changes to create dev node for usb printers

android/cic/frameworks/base/0001-Remove-selinux-related-operation.patch, android/cic_dev/frameworks/base/0001-Remove-selinux-related-operation.patch, android/cic_dev/system/core/0001-remove-secure-adb-for-cic_dev.patch
1. remove some selinux related operations, sicne currently
selinux is not enabled for both cic_dev and the new cic
target
2. remove secure adb for cic_dev basing on the requirement
of Lenovo.
Tracked-On: OAM-89793
=> [Revert me] Remove some security features for CIC

android/cic/external/selinux/0001-return-the-disabled-state-for-selinux.patch, android/cic_dev/external/selinux/0001-return-the-disabled-state-for-selinux.patch
Since SELinux is not enabled in cic now, there are many
APIs exsiting in frameworks need to take some actions basing
on the SELinux's state. They are often check the mount
point of /sys/fs/selinux, if it exists, then they think SELinux
is enabled. This is not a correct way for cic.
Since SELinux is not enabled in cic, so we always return the
disabled state for SELinux.
Tracked-On: OAM-89804
=> [Revert Me] Always return the disabled state for selinux

aosp_diff/caas/system/bt/0001-Fix-bluetooth-crash-when-stack-unable-to-start-HCI_M.patch
When BT is in Host controlled mode for CIV, if user tries
to turn ON, Bluetooth crashes continously. Added fix in
stack to gracefully shutdown HCI_MODULE if it is unable to
start it.
Tracked-On: OAM-89874
=> Fix bluetooth crash when stack unable to start HCI_MODULE

bsp_diff/caas/kernel/lts2019-chromium/04_0004-Fix-drm-i915-execlists-Use-per-process-HWSP-as-scrat.patch
Issue:
Android doesn't boot in VM setup.
Tracked-On: OAM-90590
=> Fix "drm/i915/execlists: Use per-process HWSP as scratch" merge issue

android/cic/system/core/0017-Align-the-dumpable-value-of-a-process-with-bare-meta.patch, android/cic/system/sepolicy/04_0001_1-BACKPORT-Policies-to-get-Android-booted-with-5.4-abo.patch
1. Add sepolicy rules for kernel 5.4
2. Fix some CTS test case issues
The dumpable value of some processes may be affected by suid_dumpable
defined in /proc/sys/fs/suid_dumpable. For the processes that have extra
capabilities assigned through init.rc or fs config files, their dumpable
vaules are set to suid_dumpable.
The value of suid_dumpable of bare metal android is SUID_DUMP_DISABLE(0),
but this value maybe be changed to SUID_DUMP_ROOT(2) in ubuntu by some
host services, such as apport. This may introduce some regressions for the
processes of android in container, and it may also impact the CTS result.
So we need to set suid_dumpable's value back to SUID_DUMP_DISABLE if we detect
its value was set to SUID_DUMP_ROOT.
Tracked-On: OAM-90488
Tracked-On: OAM-90692
Signed-off-by: ji, …
=> Add sepolicy rules for kernel 5.4 and fix some CTS issues

android/cic/system/core/0001-Align-the-dumpable-value-of-a-process-with-bare-meta.patch
The dumpable value of some processes may be affected by suid_dumpable
defined in /proc/sys/fs/suid_dumpable. For the processes that have extra
capabilities assigned through init.rc or fs config files, their dumpable
vaules are set to suid_dumpable.
The value of suid_dumpable of bare metal android is SUID_DUMP_DISABLE(0),
but this value maybe be changed to SUID_DUMP_ROOT(2) in ubuntu by some
host services, such as apport. This may introduce some regressions for the
processes of android in container, and it may also impact the CTS result.
So we need to set suid_dumpable's value back to SUID_DUMP_DISABLE if we detect
its value was set to SUID_DUMP_ROOT.
Tracked-On: OAM-90728
=> Fix some CTS test case issues

bsp_diff/caas/kernel/lts2018/03_0003-input-passthrough-virtio-input-device.patch, bsp_diff/caas/kernel/lts2019-yocto/05_0005-ANDROID-virtio-virtio_input-Set-the-amount-of-multit.patch
Enable virtio-input device for multi-touch device.
For kernel lts2018, we use a passthrough patch.
For kernel lts2019-yocto, we back ported a patch from Google.
Tracked-On: OAM-90659
Signed-off-by: Yang, Dong <dong.yang@intel.com>
=> enable passthrough virtio-input device

bsp_diff/caas/kernel/lts2019-yocto/06_0001-For-GVT-d-on-EHL-and-ICL-remove-VTD-activity.patch
Since all GPU resource will be pass-through to Guest.
No need to active VTD on guest.
Tests: Work well with GVT-d on EHL and ICL
Tracked-On: https://jira.devtools.intel.com/browse/OAM-90840
Signed-off-by: Shaofeng Tang <shaofeng.tang@intel.com>
=> For GVT-d on EHL and ICL, remove VTD activity

host/lts2018/usb/0003-uvc-gadget-Kernel-changes-to-enable-UVC-gadget.patch
dwc3 controller driver has issues with handling
isochronous data transfer. dwc3 should always request for
future frame from the UVC gadget. But, when an expired
frame is encountered, bus expiry error is seen and isoc
transfer is stopped. So, dwc3 driver should check for
frame number before kick starting the isoc data transfer.
Also, dwc3 should stop active transfer and restart the
request if it is queued too late. This was tested in KBL.
Tracked-On: OAM-90903
=> usb: dwc3: uvc: Changes for making UVC-gadget work

host/lts2018/usb/0003-uvc-gadget-Kernel-changes-to-enable-UVC-gadget.patch
This fixes space issues with the patch submitted for
enabling uvc-gadget.
Tracked-On: OAM-90910
=> usb: dwc3: Fix space issues with the patch

host/qemu/Disable-EDID-auto-generation-in-QEMU.patch
To fix refresh-rate issue, disable EDID auto generation in QEMU
Put the patch here.
Tracked-On: OAM-90886
Signed-off-by: Lu Yang A <yang.a.lu@intel.com>
=> Add QEMU patch for GVT-g

android/common/system/netd/0002-Ensure-icmp-redirects-are-always-ignored.patch
Even though ICMP redirects are disabled in init.rc, redirects
gets enabled.
ICMP redirects are getting enabled on ipv_forward disable.
Fix the issue by making sure ICMP redirects are disabled
on IP forward disable too.
Tracked-On: OAM-90968
=> Disable ICMP redirects

bsp_diff/caas/kernel/lts2019-yocto/08_0008-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch
This patch is for dumping the GFX memory usage data.
Tracked-On: OAM-91100
=> Added the memtrack bsp_diff patch for yocto 5.4 kernel.

bsp_diff/caas/kernel/lts2019-chromium/08_0008-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch
The patch provides features to dump the overall GFX memory usage summary
and per process GFX memory usage data.
Tracked-On: OAM-89902
=> Add the GFX memtrack patch

host/kernel/lts2019-chromium/0001-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch, host/kernel/lts2019-yocto/0001-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch
obj_shared_count == 0 shouldn't lead into syscall exception.
Just skip this false exception fixed the issue.
Tracked-On: OAM-90959
=> Fixed the Invalid Pamameter issue when cat memtrack sysfs files

bsp_diff/caas/kernel/lts2019-yocto/10_0001-Add-a-item-in-get_param-IOCTL-for-query-GVT-active.patch
When GVT is active, return true.
Tracked-On: OAM-90744
Signed-off-by: Shaofeng Tang <shaofeng.tang@intel.com>
=> Add a item in get_param IOCTL for query GVT active

bsp_diff/caas/kernel/lts2019-chromium/11_0011-uvc-Add-UVC-GET_DEF-probe-quirk-for-C922-camera.patch, bsp_diff/caas/kernel/lts2019-yocto/11_0011-uvc-Add-UVC-GET_DEF-probe-quirk-for-C922-camera.patch
Some camera devices will not have GET_DEF
request implemented for video probe and commit
controls. These devices may crash if they receive
GET_DEF request. So, add a quirk to avoid GET_DEF
request for these devices.
Tracked-On: OAM-91289
=> uvc: Add GET_DEF probe quirk for C922

bsp_diff/caas/kernel/lts2019-chromium/12_0001-Add-a-item-in-get_param-IOCTL-for-chromium-kernel-GV.patch
When GVT in chromium kernel is active, return true.
that is:
GVT-g --- true
GVT-d --- false
native --- false
Tracked-On: OAM-90744
Signed-off-by: Shaofeng Tang <shaofeng.tang@intel.com>
=> Add a item in get_param IOCTL for chromium kernel GVT active

aosp_diff/caas/frameworks/opt/net/ethernet/01_0001-Toggle-interface-state-after-proxt-settings-change.patch, aosp_diff/caas/packages/apps/Settings/01_0001-Add-settings-screen-to-set-ethernet-proxy-host-and-p.patch
Changes include
- Added ethernet proxy settings screen under
Network & Internet settings.
- Toggle inteface state for proxy settings to take effect.
Tracked-On: OAM-91281
=> Changes to update ethernet proxy settings from Settings UI

aosp_diff/caas/frameworks/base/04_0001-adb-dbc-tty-device-offline-issue.patch
Restarting the adb daemon when DbC device move to the dbc
state configured from dbc state enable.
Tracked-On: OAM-91445
=> adb: dbc: tty: device offline issue

bsp_diff/caas/kernel/lts2019-yocto/11_0011-Fix-HDMI-audio-for-EHL.patch
Back ported patch from:
https://github.com/thesofproject/linux/commit/d233c4941630af0ec2e14be7c2a693e9c9ce3087
Tracked-On: OAM-91411
Signed-off-by: gkdeepa <g.k.deepa@intel.com>
=> Add HDA HDMI support for EHL

bsp_diff/caas/vendor/intel/external/apps/01_0001-Handle-USB_HEADSET-device-type-to-fix-no-audio-on-vi.patch
When video recording is started with USB headset detected, audio
device doesn't return USB_DEVICE instead it returns USB_HEADSET.
So, preferred audio device is not set resulting in audio not
recorded on video recording.
Fix the issue by setting preferred device for device type
USB_HEADSET.
Tracked-On: OAM-91435
=> Handle USB_HEADSET device type to fix no audio on video recording

aosp_diff/caas/frameworks/base/03_0001-Handle-simultaneous-HDMI-WiredHeadphone-events.patch
Wired Headset sets these 2 bits in the device when connected:
SW_HEADPHONE_INSERT_BIT & SW_MICROPHONE_INSERT_BIT
Additionally, if HDMI device is connected, it sets the
SW_LINEOUT_INSERT_BIT event too.
The combination of these 3 bits has to be handled correctly.
Tracked-On: OAM-91511
Signed-off-by: akodanka <anoob.anto.kodankandath@intel.com>
=> Handle simultaneous HDMI & WiredHeadphone events

aosp_diff/caas/build/soong/0001-Disabled-avx-avx2-avx512-compiler-flags-by-default.patch
Not all cases there is benefit by enabling avx flags.
Hence, individual components need to enable it based on
performance gain
Tracked-On: OAM-91583
=> Disable avx avx2 avx512 flags by default

android/cic/bionic/0001-Remove-uid-gid-check-for-device-property-files.patch, android/cic/external/toybox/0001-Grant-the-mount-privilege-for-system-users.patch, android/cic/frameworks/native/0004-Let-installd-and-dumpstate-run-as-system-user.patch, android/cic/system/core/0018-Let-some-core-services-run-as-system-user.patch, android/cic/system/extras/0001-Let-perfprofd-run-as-system-user.patch, android/cic/system/netd/0001-Let-netd-run-as-system-user.patch, android/cic/system/vold/0001-Let-vold-run-as-system-user.patch
For security reason, our customer want all the processes of
a container to run as non-root user, so let some processes
that run as root user previously run as system user.
Tracked-On: OAM-90885
=> Let some processes of cic run as system user

android/cic/system/core/0015-Restore-rootfs-context-for-SELinux-enabling.patch
The /ipc dir is shared by host and cic, host or android-entry
may create some config files under /ipc before selinux rules
are loaded, these files won't be labeled correctly. We need to
force set the file contexts of ipc for every boot, or restorecon
may check the extended attr of ipc and skip the file contexts set
operation if it find ipc was ever set previously. This may leave
the files created by host/aic-manager/android-entry unlabeled.
Tracked-On: OAM-91327
=> Force set file contexts of ipc for every boot

android/cic/system/core/0018-Let-some-core-services-run-as-system-user.patch
Grant CAP_KILL capability to zygote, or uiautomator cannot
work normally.
Tracked-On: OAM-91952
=> Grant CAP_KILL capability to zygote

aosp_diff/preliminary/external/dng_sdk/0001-Targeted-minimal-fix-for-security-issue-in-CVE-2020-.patch
Integrate a CVE security patch 
Integrate security patch: Targeted minimal fix for security issue in CVE-2020-9589.
Bug 156261521
Tracked-On : [OAM-91943](https://jira.devtools.intel.com/browse/OAM-91943) 
=> Integrate security patch for CVE-2020-9589

android/cic/frameworks/base/0006-Fix-for-FakeWiFi-information-populated-in-UI.patch, android/cic_dev/frameworks/base/0006-Fix-for-FakeWiFi-information-populated-in-UI.patch
On very first boot, though wlan is down wifi status in Settings app showing
as enabled, fix is provided to display the right information.
Hardcoded WiFi MAC is shown in UI, changing it to actual physical MAC
address.
Tracked-On: OAM-91559
Signed-off-by: Raveendra Babu Chennakesavulu
<raveendra.babu.chennakesavulu@intel.com>
=>  Fix for FakeWiFi information populated in UI.

aosp_diff/cic/external/libdrm/0001-use-private-libdrm-instead-of-external-libdrm.patch, aosp_diff/preliminary/external/libdrm/0001-use-private-libdrm-instead-of-external-libdrm.patch
As we have one round of IA libdrm rebase work. We
need rebase the AOSP libdrm diff patch. This could
help fix the Android building issue.
Tracked-On: OAM-92079
Signed-off-by: Chenglei Ren <chenglei.ren@intel.com>
=> Rebase AOSP libdrm diff

bsp_diff/caas/kernel/lts2019-chromium/09_0009-drm-i915-gt-Schedule-request-retirement-for-gen10.patch
In CML, "Schedule request retirement when timeline idles" might
introduce random drm init failure during reboot. This change is
to enable schedule request retirement on Gen10+
Tracked-On: OAM-91972
Signed-off-by: Romli, Khairul Anuar <khairul.anuar.romli@intel.com>
Signed-off-by: Junxiao Chang <junxiao.chang@intel.com>
Signed-off-by: Shaofeng Tang <shaofeng.tang@intel.com>
=> drm/i915/gt: Schedule request retirement for gen10+

aosp_diff/caas/system/core/01_1-Add-support-for-creation-of-usb-pri.patch
This patch enabled the node access for USB Printer.
Tracked-On: OAM-92969
=> Add usb printer support

host/kernel/lts2019-chromium/0001-BACKPORT-v5.4-KVM-VMX-Consume-pending-LAPIC-INIT-event-when-exit-o.patch, host/kernel/lts2019-chromium/0002-BACKPORT-v5.4-KVM-x86-emulate-wait-for-SIPI-and-SIPI-VMExit.patch, host/kernel/lts2019-yocto/0001-BACKPORT-v5.4-KVM-VMX-Consume-pending-LAPIC-INIT-event-when-exit-o.patch, host/kernel/lts2019-yocto/0002-BACKPORT-v5.4-KVM-x86-emulate-wait-for-SIPI-and-SIPI-VMExit.patch
Add KVM patches which support wait-for-SIPI and SIPI-VMExit.
The patches are backported from:
https://patchwork.kernel.org/patch/11781275
https://patchwork.kernel.org/patch/11236869
Tracked-On: OAM-92942
Signed-off-by: Yadong Qi <yadong.qi@intel.com>
=> CiV: HOST kernel: Add KVM patch which support wait-for-SIPI and SIPI-VMExit

aosp_diff/caas/system/media/0001-Increase-period-size-to-improve-USB-Audio-quality.patch, bsp_diff/caas/vendor/intel/external/project-celadon/audio/01_679470_1-Tuning-period_size-and-period_count-for-QEMU-KVM.patch
Tuning Period size for USB Audio
Tracked-On: OAM-93003
Signed-off-by: Mandri, Padmashree <padmashree.mandri@intel.com>
=> Port Audio patches from Q to R

aosp_diff/caas/frameworks/av/0002-camera-fix-crash-while-disconnect-USB-camera.patch
camera framework patches was missing in android 11
Solution: ported the camera framework patches
Tracked-On: OAM-93078
Signed-off-by: Shiva Kumara shiva.kumara.rudrappa@intel.com
Signed-off-by: kbillore <kaushal.billore@intel.com>
=> porting camera framework patch from android 10 to android 11

aosp_diff/caas/build/make/0003-Fix-signapk.jar-path-for-RELEASE_BUILD-true-case.patch
When built with RELEASE_BUILD=true option builder tries to
call the signapk.jar file to generate the caas-sign***.zip file.
This signapk path is not set properly in Android 11.
The path is set relative to the script directory but it should
be relative to the output directory.
This patch fixes this issue and sets the path properly.
=> Fix signapk.jar not found in RELEASE_BUILD=true

aosp_diff/caas/system/vold/0001-PATCH-WA-CIV-Vold-SD-and-USB-handling-for-CIV.patch
This patch adds support in vold for co-existence of
sdcard and USB drive.
Tracked-On: OAM-93067
=> aosp_diff: Add support for sdcard and USB disk

bsp_diff/caas/kernel/lts2019-chromium/09_0009-fscrypt-support-passing-a-keyring-key-to-FS_IOC_ADD_.patch
Extend the FS_IOC_ADD_ENCRYPTION_KEY ioctl to allow the raw key to be
specified by a Linux keyring key, rather than specified directly.
This is useful because fscrypt keys belong to a particular filesystem
instance, so they are destroyed when that filesystem is unmounted.
Usually this is desired.  But in some cases, userspace may need to
unmount and re-mount the filesystem while keeping the keys, e.g. during
a system update.  This requires keeping the keys somewhere else too.
Tracked-On: OAM-93134
=> fscrypt: support passing a keyring key to FS_IOC_ADD_ENCRYPTION_KEY

aosp_diff/caas/packages/apps/Camera2/01_0001-Changes-to-support-external-camera.patch
Changes to support external camera
Solution: - Remove DisableCameraReceiver as it disables all camera
activities if camera is not plugged in during first boot.
- If camera device path has /, replace it with _ as / is
not allowed in file uri path.
- If no front camera found, return external camera facing
id.
Tracked-On: OAM-93144
Signed-off-by: shiva kumara <shiva.kumara.rudrappa@intel.com>
Signed-off-by: kbillore <kaushal.billore@intel.com>
=> Changes to support external camera

aosp_diff/caas/hardware/interfaces/05_0005-health-Health-HAL-needs-Intel-healthloop.patch
This patch adds Intel healthloop to health service 2.1
Tracked-On: OAM-92794
=> aosp_diff: Add Intel healthloop

bsp_diff/caas/kernel/lts2019-chromium/10_0010-9p-freezing-aborts-when-use-wait_event_killable.patch
Freezing of processes abort when a client is waiting uninterruptibly
for a response. Instead use wait_event_freezable() to fix it.
Tracked-On: OAM-94084
Signed-off-by: Shwetha B <shwetha.b@intel.com>
Signed-off-by: Kaushlendra Kumar <kaushlendra.kumar@intel.com>
=> bsp_diff for 9p: freezing aborts when use wait_event_killable()

aosp_diff/caas/prebuilts/clang/host/linux-x86/01_0001-Update-llvm-to-latest-toolchain-binaries.patch
When LTO, CFI is enabled in kernel, error is seen
due to toolchain path not present in path variable.
Added LZ4 and prebuilt toolchain path to path variable.
Tracked-On: OAM-94248
=> Add lz4 and kernel toolchain to path

bsp_diff/caas/kernel/lts2019-chromium/10_0010-iwlwifi-Vendor-command-support-in-iwlwifi-driver.patch
Adding vendor command support for querying driver & firmware
version.
Tracked-On: OAM-94267
Signed-off-by: Amrita Raju <amrita.raju@intel.com>
=> iwlwifi: Vendor command support in iwlwifi driver

aosp_diff/preliminary/bionic/03_0003-Make-avx-enablement-of-math-func-march-independent.patch, aosp_diff/preliminary/bionic/04_0004-Optimize-bionic-memory-functions-with-avx2-instructi.patch, aosp_diff/preliminary/bionic/05_0005-Optimize-bionic-string-functions-with-avx-implementa.patch, aosp_diff/preliminary/external/arm-optimized-routines/02_0002-Make-avx-enablement-of-sinf-cosf-expf-march-independ.patch
Following memory related functions are optimized with
avx2 implementation:
memcpy (for both 32-bit and 64-bit)
below functions ported from glibc 2.20 only for 64-bit
- memchr
- memcmp
- memmove
- memrchr
 
Following are the string functions that has been
optimized with avx2 implementation from glibc 2.32 version.
- strcmp, strncmp
- strlen, strnlen
- strchr, strrchr
- strcpy, strncpy
- stpcpy, stpncpy
- strcat, strncat
- wcscmp, wcsncmp
- wcslen, wcsnlen
- wcschr, wcsrchr
 
This patch also has necessary changes to pick up the right
version(avx/sse) of the functions at runtime using IFUNC.
This helps in building Unified Image for Android 11.
Tracked-On: OAM-94306
=> Implement/Port AVX2 optimizations to Bionic module.

aosp_diff/preliminary/art/01_0001-Fix-two-bugs-around-aput-object.patch
This bug was exposed by CTS test
run cts  -m vm-tests-tf -t dot.junit.opcodes.Test_aput_object#testN4
Original patch from aosp:
https://android-review.googlesource.com/c/platform/art/+/1309393
Tracked-On:
=> Fix two bugs around aput object

aosp_diff/preliminary/bionic/06_0006-Linker-changes-to-allow-perf-variants-of-an-.so.patch, aosp_diff/preliminary/frameworks/av/03_0003-Generate-avx2-version-of-libaudioprocessing-library.patch, aosp_diff/preliminary/frameworks/ml/01_0001-Generate-avx2-version-of-libneuralnetworks.patch, aosp_diff/preliminary/system/linkerconfig/01_0001-Config-changes-to-prefer-perf-variants-of-an-.so.patch
Enables us to have One-image catering to multiple
IA CPUs which may or may not support all ISA features.
Example: Pentium SKUs dont support AVX.
Tracked-On: OAM-94488
Signed-off-by: Vinay Kompella <vinay.kompella@intel.com>
=> Changes to allow multiple perf variants of an .so

aosp_diff/preliminary/art/03_0003-Generate-avx2-version-of-libart.so-and-libartd.so.patch, aosp_diff/preliminary/frameworks/rs/01_0001-Generate-avx2-version-of-libRSCpuRef.so.patch
Enables us to have One-image catering to multiple
IA CPUs which may or may not support all ISA features.
Example:  Pentium SKUs dont support AVX.
Tracked-On: OAM-94488
=> Changes to allow multiple perf variants libRSCpuRef.so

aosp_diff/preliminary/build/soong/0005-Filterout-isa-perf-libraries-from-vndk-list.patch
Currently we have added perf libs under vndksp,
filter them out as they are not new libraries,
rather avx2 implementations of existing libraries.
Should have no impact on GSI.
Tracked-On: OAM-94541
=> Filterout isa perf libraries from vndk list

bsp_diff/common/kernel/lts2019-chromium/12_0012-ACPI-PM-Propagate-power-button-event-to-user-space-w.patch
Sometimes power button does not wake up the systemm, we get suspends event
right after that. here Android needs to see KEY_POWER at resume. Otherwise, its
opportunistic suspend will kick in shortly.
However, other OS such as Ubuntu doesn't like KEY_POWER at resume. So
add a knob "/sys/module/button/parameters/key_power_at_resume" for users
to select.
Tracked-On: OAM-94240
Signed-off-by: Kaushlendra Kumar <kaushlendra.kumar@intel.com>
Signed-off-by: Shwetha B <shwetha.b@intel.com>
=> Propagate power button event to user space when device wakes up

bsp_diff/common/kernel/lts2019-chromium/13_0013-BACKPORT-FROMLIST-Update-Inline-Encryption-from-v5-t.patch, bsp_diff/common/kernel/lts2019-chromium/14_0014-ANDROID-block-fix-some-inline-crypto-bugs.patch, bsp_diff/common/kernel/lts2019-chromium/15_0015-ANDROID-block-export-symbols-needed-for-modules-to-u.patch, bsp_diff/common/kernel/lts2019-chromium/16_0016-FROMLIST-scsi-ufs-add-program_key-variant-op.patch, bsp_diff/common/kernel/lts2019-chromium/17_0017-ANDROID-ext4-f2fs-enable-direct-I-O-with-inline-encr.patch, bsp_diff/common/kernel/lts2019-chromium/18_0018-ANDROID-block-Introduce-passthrough-keyslot-manager.patch, bsp_diff/common/kernel/lts2019-chromium/19_0019-ANDROID-dm-add-support-for-passing-through-inline-cr.patch, bsp_diff/common/kernel/lts2019-chromium/20_0020-ANDROID-dm-enable-may_passthrough_inline_crypto-on-s.patch, bsp_diff/common/kernel/lts2019-chromium/21_0021-ANDROID-dm-add-dm-default-key-target-for-metadata-en.patch, bsp_diff/common/kernel/lts2019-chromium/22_0022-ANDROID-block-provide-key-size-as-input-to-inline-cr.patch, bsp_diff/common/kernel/lts2019-chromium/23_0023-ANDROID-dm-prevent-default-key-from-being-enabled-wi.patch, bsp_diff/common/kernel/lts2019-chromium/24_0024-statx-define-STATX_ATTR_VERITY.patch, bsp_diff/common/kernel/lts2019-chromium/25_0025-ext4-support-STATX_ATTR_VERITY.patch, bsp_diff/common/kernel/lts2019-chromium/26_0026-f2fs-support-STATX_ATTR_VERITY.patch
These patches were already in android common kernel, but not
in lts2019-chromium kernel. fsverity and metadata encryption
features have dependence on these patches. So they are needed
to be ported into lts2019-chromium kernel.
Tracked-On: OAM-94420
=> Enable fsverity and metadata encryption feature

aosp_diff/preliminary/frameworks/base/0001-adb-dbc-tty-device-offline-issue.patch, aosp_diff/preliminary/system/core/0001-adb-dbc-tty-add-adb-over-dbc-tty-support.patch
Added adb over dbc tty support in adb framework.
This implementation is based on Blocking I/O calls.
Set "setprop persist.vendor.sys.usb.adbover" android
property to "dbc" to use adb over dbc tty otherwise
set this property to "dwc" (which is the default value
of this property) to use adb over normal USB (which need
USB Device Mode IP to be enabled).
Tracked-On: OAM-94662
=> adb: dbc: tty: add adb over dbc tty support

bsp_diff/common/kernel/lts2019-chromium/27_0027-x86-e820-fix-the-function-type-for-e820__mapped_all.patch
e820__mapped_all is passed as a callback to is_mmconf_reserved, which
expects a function of type:
typedef bool (*check_reserved_t)(u64 start, u64 end, unsigned type);
This trips indirect call checking with Clang's Control-Flow Integrity
(CFI). Change the last argument from enum e820_type to unsigned to fix
the type mismatch.
Tracked-On: OAM-94510
=> x86/e820: fix the function type for e820__mapped_all

bsp_diff/common/vendor/intel/external/hwcomposer-intel/0001-Disable-HWC.patch
With Allocator & Mapper 4.0, we may encounter HWC crash when
playing video. To quick wa this issue, we disable HWC here.
Tracked-On: OAM-95365
=> Disable HWC

bsp_diff/common/kernel/lts2019-chromium/66_0001-btusb-snd-crash-while-disconnect.patch
removing the duplicacy of snd_card_free_when_closed()
function which is called inside btusb_sco_disconnect()
function.
Tracked-On: OAM-95334
Signed-off-by: Prabhat Chand Pandey prabhat.chand.pandey@intel.com
=> btusb : snd : crash while disconnect

bsp_diff/common/kernel/lts2019-chromium/67_0067-x86-relocs-Ignore-L4_PAGE_OFFSET-relocations.patch
L4_PAGE_OFFSET is a constant value, so don't warn about absolute
relocations.
Tracked-On: OAM-95581
Signed-off-by: Sami Tolvanen <samitolvanen@google.com>
=> x86, relocs: Ignore L4_PAGE_OFFSET relocations

aosp_diff/preliminary/frameworks/av/05_0005-Apply-the-correct-stride-for-HEVC-codec.patch
Remember the stride decoded from the header, so that
we can use the correct stride information when decoding
the frame. Currently since we do not remember this, there
is a mismatch with the stride we know and stride applied
during decode frame.
Tracked-On: OAM-95490
Signed-off-by: Vinay Kompella <vinay.kompella@intel.com>
=> Apply the correct stride for HEVC codec

host/kernel/lts2019-chromium/0003-v1-vfio-pci-Add-support-for-opregion-v2.0.patch
The VBT on tgl nuc is missing as the opregion version is v2.0+
Tracked-On: OAM-95662
=> Fix the TGL NUC HDMI doesn't work issue

aosp_diff/preliminary/hardware/interfaces/06_0006-wifi-Disable-capabilities-not-yet-supported.patch
As E2E support is not yet implemented for following capabilities,
removing them.
DEBUG_RING_BUFFER_VENDOR_DATA, DEBUG_HOST_WAKE_REASON_STATS,
DEBUG_ERROR_ALERTS and APF.
Tracked-On: OAM-95699
=> wifi: Disable capabilities not yet supported

bsp_diff/common/kernel/lts2019-chromium/16_0016-FROMLIST-Update-logic-to-program-AUD_FREQ_CNTRL-reg.patch
Earlier this register was configured by BIOS and driver discovered the
value at init. This is no longer recommended and instead for driver
should set the values based on the hardware revision. This change
applies for all GEN12+ hardware.
Add the recommended values for all supported hardware. Extend the debug
print to also include values of the register as written by BIOS. This
can help debug rare cases where an older BIOS configures an incorrect
value.
Bspec: 49279
once the patch gets reviewed we need to back port the patch
http://intel-gfx-pw.fi.intel.com/series/7315/
Tracked-On: OAM-95837
Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>
Signed-off-by: Deepa G K <g.k.deepa@intel.com>
=> Update logic to program AUD_FREQ_CNTRL register based on new guidance.

aosp_diff/preliminary/hardware/interfaces/07_0007-enable-fixed-performance-mode.patch, aosp_diff/preliminary/system/sepolicy/03_0003-Selinux-for-power-related-system-property.patch
This will be removed when Power hal Aidl is
moved to vendor/intel/hardware/interfaces
Currently in AIDL, only fixed performance mode
is enabled. Other mode/Hints are handled in
Power hal directly.
Tracked-On: OAM-95866
Signed-off-by: Shwetha B <shwetha.b@intel.com>
=> Diff for setting the fixed performance mode

aosp_diff/preliminary/hardware/interfaces/06_0006-wifi-Disable-capabilities-not-yet-supported.patch
VTS test case GetCapabilities_1_3 is failing as the capabilities
returned is 0. Fix the issue by enabling DEBUG_ERROR_ALERTS
capability.
Tracked-On: OAM-95901
=> wifi: Enable DEBUG_ERROR_ALERTS capability

aosp_diff/preliminary/packages/apps/Camera2/03_0003-google-camera-target-sdk-version-update.patch
aosp camera application target sdk version pointing to 28
Solution: changed the target sdk version to 30
Tracked-On: OAM-95874
Signed-off-by: shiva kumara R <shiva.kumara.rudrappa@intel.com>
=> aosp camera target sdk version upgrade

aosp_diff/preliminary/packages/screensavers/PhotoTable/01_0001-target-version-upgrade-for-screen-saver.patch
screensaver application target sdk version points to 28
Solution: changed the target sdk version to 30
Tracked-On: OAM-95874
Signed-off-by: shiva kumara R <shiva.kumara.rudrappa@intel.com>
=> screensaver target sdk version change

bsp_diff/common/hardware/intel/wlan/libwifihal/open/02_0002-Ignore-start-and-stop-offloading-packet-request.patch
Following test cases in CtsNetTestCases module is failing
as  wifi_start_sending_offloaded_packet and
wifi_stop_sending_offloaded_packet requestes are completed
with not supported error code.
- testSocketKeepaliveUnprivileged, testCreateTcpKeepalive
and testSocketKeepaliveLimitWifi.
As network will still work even if we drop start/stop
offload packet request, complete the start/stop requests with
WIFI_SUCCESS to pass the CTS tests
Tracked-On: OAM-96073
=> Ignore start and stop offloading packet request

aosp_diff/preliminary/hardware/libhardware/0001-Keymaster-Add-new-keymaster-error-code-for-provision.patch
Add new error code KM_ERROR_KEYBOX_ALREADY_PROVISIONED to indicate the error
type of trying to provision device which has been already provisioned.
Tracked-On: OAM-95939
Signed-off-by: Zhong,Fangjian <fangjian.zhong@intel.com>
=> Keymaster: Add new keymaster error code for provisioning

host/kernel/lts2019-chromium/0005-Fix-device-hang-on-TGL-RVP.patch
This change is to help fix device hang on TGL
RVP when launch GVT-d
Tracked-On: OAM-96268
=> Fix device hang on TGL RVP

aosp_diff/preliminary/frameworks/av/06_0006-Add-a-null-check-in-RTSPSource-stop.patch, aosp_diff/preliminary/frameworks/opt/net/wifi/02_0002-ClientModeImpl-Reset-WifiInfo-on-NETWORK_DISCONNECTI.patch
This patch will integrate the following aosp patches:
1) ClientModeImpl: Reset WifiInfo on NETWORK_DISCONNECTION_EVENT
2) Add a null check in RTSPSource::stop
Tracked-On: OAM-96486
=> Merge 2 mandatory/strongly-recommended aosp patches

bsp_diff/common/kernel/lts2019-chromium/17_0017-Bluetooth-btusb-Add-reset-on-close-quirk-for-Intel-a.patch
Intel Bluetooth adapter is not exiting the loopback mode on bluetooth
socket closure. So, when bluetooth socket is opened again, bluetooth is
not working.
As per Bluetooth core specification, bluetooth adapter should exit loop
back mode on hci reset. Add HCI quirk reset to make sure adapter exits
loopback mode on bluetooth socket closure.
Tracked-On: OAM-96067
=> Bluetooth: btusb: Add reset on close quirk for Intel adapters

aosp_diff/preliminary/hardware/interfaces/0002-Fix-setLightState-VTS-failure.patch
Make setLightState return UNSUPPORTED for invalid light ID
Tracked-On: OAM-96799
Signed-off-by: Swee Yee Fonn <swee.yee.fonn@intel.com>
=> [PATCH] Fix setLightState VTS failure

aosp_diff/preliminary/system/sepolicy/04_0004-sepolicy-allow-system_server-to-read-proc-locks.patch
Access to /proc/locks is necessary to activity manager to determine
wheter a process holds a lock or not prior freezing it.
Tracked-On: OAM-96736
=> sepolicy: allow system_server to read /proc/locks

aosp_diff/preliminary/frameworks/base/21_0021-Allow-batteryless-device-for-system-update.patch
SytemUpdate CTS tests will pass only if battery is available.
Fixed it to allow for batteryless device also. Identified the
batteryless device based on the below document.
https://source.android.com/devices/tech/power/batteryless
Tracked-On: OAM-97111
Signed-off-by: Jaikrishna Nemallapudi <nemallapudi.jaikrishna@intel.com>
=> Allow batteryless device for system update.

aosp_diff/preliminary/external/v8/02_0002-Update-v8-cfi-blocklist.bulletin.patch
ASB patches in external/v8 from June
ASB bulletin
Tracked-On: OAM-97168
=> ASB patches in external-v8

bsp_diff/common/kernel/lts2019-chromium/21-0021-Bluetooth-btusb-Fix-failing-to-init-controllers-with.patch
BT is not working in CIV with 5.4.121 kernel as it is unable
to get the required firmware file. BT chip will be operational
mode when CIV is launched. In the new firmware download flow, the
firmware version and revision are checked to see if the firmware
in the device is latest. But the firmware returns wrong device
information, which leads to error in BT firmware download flow
Fix: Soft links are created so that ibt-19-16-0* pointing to
ibt-19-0-4*
Patch will be reverted once the firmware changes are available
Tracked-On: OAM-97192
=> Bluetooth: btusb: Fix failing to init controllers with operation firmware

aosp_diff/preliminary/system/sepolicy/05_0005-Allow-adbd-to-use-vsock_socket.patch, aosp_diff/preliminary/system/sepolicy/06_0006-prebuilt-Allow-adbd-to-use-vsock_socket.patch
Backport patch to allow adbd to use vsock socket.
Origin: https://android-review.googlesource.com/c/platform/system/sepolicy/+/1626224
Tracked-On: OAM-97464
Signed-off-by: Yadong Qi <yadong.qi@intel.com>
=> sepolicy: Allow adbd to use vsock socket

bsp_diff/common/hardware/interfaces/thermal/0001-Fix-for-VTS-issue-in-thermal.patch
Removing the thermal 1.0 HAL interface from 2.0
service.
Tracked-On: OAM-97800
Signed-off-by: Deepa g.k.deepa@intel.com
=> VTS fix in thermal

aosp_diff/caas_cfc/frameworks/av/0001-Using-RGB565-in-case-YV12-is-not-supported.patch
VirtIO GPU doesn't support video format, so convert
video format to RGB565
Tracked-On: OAM-98107
=> Using RGB565 in case YV12 is not supported

aosp_diff/caas_cfc/system/core/0001-Disable-adb-authentication-for-PGP.patch
Looking Glass of PGP has dependence on adb. In user build
the adb is disabled by default, so the UI cannot be displayed
by LG. And to turn on adb, we need to access the UI, we are
stuck in a deadlock.
Tracked-On: OAM-98789
=> Enable adb in user build by default for caas_cfc

host/lg/0015-Fixed-the-looking-glass-client-rendering-messed-issu.patch
The fix is to refresh the app window if resize detected.
Tracked-On: OAM-98766
=> Fixed the looking glass client rendering messed issue.

host/lg/0016-Fixed-the-app-window-not-refreshed-issue-after-resum.patch, host/lg/0017-Fixed-the-render-thread-frame-thread-race-codition.patch
Fixed 2 render issues:
1) App screen is not refreshed when resumed from sleep; 
Tracked-On: OAM-99165
2) Webchat app screen is not refreshed when switching between contacts and discovery tabs.
Tracked-On: OAM-98782
=> Lg render fix

bsp_diff/common/kernel/lts2020-yocto/15_0015-Fix-for-btusb_sco_snd_card-not-getting-probed.patch
=> Fix for btusb_sco_snd_card driver not getting probed

bsp_diff/common/kernel/lts2019-chromium/23_0023-i915-drm-civ-vts-if-we-use-the-emulated-device-on-TG.patch
…k/warning
The commit ab22227679950117082f368a72361a26a186310a is to help differentiate TGL-U and TGL-Y.
On CIV, some of PCI devices are simulated by Qemu, so it can't get host device info rightly,
which the first pci device is simulated by Qemu instead of reading from host.
if Qemu simulates the first PCI device, we skip the check/warning.
Tracked-On: OAM-98234
Signed-off-by: Kanli Hu <kanli.hu@intel.com>
=> i915/drm: civ-vts if we use the emulated device on TGL, skip the check/warning

aosp_diff/caas_cfc/frameworks/base/0002-Hide-the-Status-Bar-and-grant-runtime-permissions-by.patch
Based on the customer requirement, we need to remove the
status bar and disable the permission grant pop-up window.
Tracked-On: OAM-96162
=> Hide status bar and grant runtime permission by default

bsp_diff/common/kernel/lts2020-yocto/16_0016-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch
This patch is for dumping the GFX memory usage data.
Tracked-On: OAM-99250
=> Add the memtrack bsp_diff patch for yocto 5.10 kernel

aosp_diff/caas_cfc/frameworks/base/0002-Disable-the-Status-Bar-and-grant-runtime-permissions.patch
Disable the status bar, it will be unresponsive for the
user's click actions. Set the status bar's height to a
very small value in the overlay configuration, this is
a workaround to hide the status bar.
Tracked-On: OAM-99354
=> Disable the status bar

host/lg/0018-input-support-for-600x960-resolution.patch
touchscreen support for LG_client window 600x960
Tracked-On: OAM-99341
Signed-off-by: Rajani Ranjan <rajani.ranjan@intel.com>
=> lg-input support for 600x960 resolution

aosp_diff/preliminary/external/drm_hwcomposer/0004-Set-the-primary-display-as-internal-display.patch
Celadon connect monitor with HDMI/DP/Type-C port, which is
regarded as external display, but android by default assume
there is one internal display, so need to set the primary
display as internal display.
Tracked-On: OAM-99729
Signed-off-by: Li, HaihongX <haihongx.li@intel.com>
=> Set the primary display as internal display

aosp_diff/caas_cfc/frameworks/base/0003-set-guest-cursor-visibility-to-false.patch
As we are using host cursor pointer, 
fix 2 mouse cursor issue by disabling android cursor pointer.
Tracked-On: OAM-98091
Signed-off-by: Rajani Ranjan <rajani.ranjan@intel.com>
=> Set guest cursor visibility to false

host/lg/0020-enabling-long-press-on-the-touch-screen.patch
enabling long press touch features to take video in wechat app
Tracked-On:OAM-99821
Signed-off-by: Rajani Ranjan <rajani.ranjan@intel.com>
=> enabling long press on the touch screen

bsp_diff/common/kernel/lts2019-chromium/69_0069-i915-Fix-CFI-violation-in-show_dynamic_id-function.patch
clang's Control Flow Integrity requires that every indirect call has a
valid target, which is based on the type of the function pointer. The
show_dynamic_id()functions is written as if it will be called
from dev_attr_show(); however, it will be called from
sysfs_kf_seq_show() because the files were created by
sysfs_create_group() and the sysfs ops are based on kobj_sysfs_ops
because of kobject_add_and_create(). Because the show_dynamic_id()
functions do not match the type of the show() member in struct
kobj_attribute, there is a CFI violation.
Tracked-On: OAM-99958
Signed-off-by: Patibandla, KiranX Kumar <kiranx.kumar.patibandla@intel.com>
=> i915: Fix CFI violation in show_dynamic_id function

bsp_diff/caas/device/intel/mixins/0003-TrebleSysProptest-VendorPropertyNames-fix-in-mixin.patch, bsp_diff/caas/device/intel/sepolicy/0003-TrebleSysProptest-VendorPropertyNames-fix-in-sepolic.patch
Fix for testVendorPropertyNames.
Changing sys.display.size to vendor.display.size
Tracked-On: OAM-99594
Signed-off-by: Patibandla, KiranX Kumar <kiranx.kumar.patibandla@intel.com>
=> TrebleSysProptest VendorPropertyNames fix

bsp_diff/common/kernel/lts2020-chromium/19_0019-Bluetooth-btintel-Fix-bdaddress-comparison-with-garb.patch
Intel Read Verision(TLV) data is parsed into a local structure variable
and it contains a field for bd address. Bd address is returned only in
bootloader mode and hence bd address in TLV structure needs to be validated
only if controller is present in boot loader mode.
Signed-off-by: Kiran K <kiran.k@intel.com>
Reviewed-by: Tedd Ho-Jeong An <tedd.an@intel.com>
Signed-off-by: Marcel Holtmann <marcel@holtmann.org>
=> Bluetooth: btintel: Fix bdaddress comparison with garbage value

bsp_diff/common/kernel/lts2019-chromium/71_0071-Revert-back-changes-for-ieee80211_if_remove.patch
Below patch is not merged properly for iwl7000 driver
So revert it back
====================================================
commit 2fe8ef106238b274c505c480ecf00d8765abf0d8
Author: Johannes Berg <johannes.berg@intel.com>
Date:   Fri Jan 22 16:19:42 2021 +0100
cfg80211: change netdev registration/unregistration
semantics
====================================================
Tracked-On: OAM-100104
Signed-off-by: Zhuo Peng <zhuo.peng@intel.com>
=> Revert back changes for ieee80211_if_remove()

aosp_diff/preliminary/external/drm_hwcomposer/0007-switch-to-drm-AtomicCommit-as-non-block-operation.patch
This is used to resolve framerate downgrade issue when multiple monitors
connected. If only add DRM_MODE_ATOMIC_NONBLOCK, flashing issue occurred.
Then we need additionally poll the out fence after commit.
Tracked-On: OAM-99990
Signed-off-by: Fei Jiang <fei.jiang@intel.com>
=> switch to drm AtomicCommit as non-block operation

host/kernel/lts2020-chromium/build_weekly.sh
-Build script is updated to compile for weekly and on latest tip
Tracked-On: OAM-100157
=> kernel: Update build script for ref host kernel v5.10.77

aosp_diff/caas_cfc/system/sepolicy/0001-update-policy-for-3rd-party-App-function.patch, bsp_diff/caas_cfc/device/intel/sepolicy/0001-update-policy-for-3rd-party-App-function.patch
some 3rd-party apps have dependence on vendor_file to translate instructions
to x86, we update sepolicy in both intel and system sepolicy folder to allow that.
Tracked-On: OAM-100126
Signed-off-by: Ruan, Hongfu <hongfu.ruan@intel.com>
=> update policy for 3rd party App function

bsp_diff/common/kernel/lts2019-chromium/26_0001-WA-Fix-for-BT-suspend-resume-issue-in-Tasmania.patch
In the specific hardware configuration power is cut to
the Bluetooth controller every time system enter S3 suspend
In some cases when frequent usb connect and disconnect
occurs, there is a chance that hci dev registration happens
even before cleanup is done for the existing hci device. Delay
is added in this case to allow enough time for cleanup of existing
device before registering a new one.
Tracked-On: OAM-99203
=> WA Fix for BT suspend resume issue in Tasmania

host/kernel/lts2020-chromium/build_weekly.sh
-Build script is updated to compile for weekly and on latest tip
Tracked-On: OAM-100286
=> kernel: Update build script for ref host kernel v5.10.82

host/kernel/lts2019-chromium/build_weekly.sh
Update build script to point to the latest tip of master branch of
linux-intel-lts2019-chromium project
Tracked-On: OAM-100296
=> kernel: Update commit hash in build script

host/kernel/lts2020-chromium/build_weekly.sh
-Build script is updated to compile for weekly and on latest tip
Tracked-On: OAM-100712
=> kernel: Update build script for ref host kernel v5.10.91

aosp_diff/preliminary/frameworks/native/05_0005-servicemanager-restart-more-services-on-crash.patch
This patch is available in Android 12 and
not available in Android 11. But it is needed
for fixing STS issue:
TC:  android.security.sts.CVE_2021_0310#testPocCVE_2021_0310
Tracked-On: OAM-100715
=> Adding Google patch to fix STS issue

aosp_diff/preliminary/external/drm_hwcomposer/0008-Fix-display-flickering-issue-occurred-in-clock-alarm.patch
In alarming UI, only one layer presented, then it was set as "DEVICE"
rendering type, while there is sychronization issue, just force
setting all layers as "CLIENT" type as workaroud solution.
Tracked-On: OAM-100414
Signed-off-by: Fei Jiang <fei.jiang@intel.com>
=> drm-hwc: Fix display flickering issue occurred in clock alarming UI

bsp_diff/common/kernel/lts2019-chromium/69_0069-ion_system_heap-support-X86-archtecture.patch
we see tons of warning like:
[   45.846872] x86/PAT: NDK MediaCodec_:3753 map pfn RAM range req
write-combining for [mem 0x1e7a80000-0x1e7a87fff], got write-back
[   45.848827] x86/PAT: .vorbis.decoder:4088 map pfn RAM range req
write-combining for [mem 0x1e7a58000-0x1e7a58fff], got write-back
[   45.848875] x86/PAT: NDK MediaCodec_:3753 map pfn RAM range req
write-combining for [mem 0x1e7a48000-0x1e7a4ffff], got write-back
[   45.849403] x86/PAT: .vorbis.decoder:4088 map pfn RAM range
req write-combining for [mem 0x1e7a70000-0x1e7a70fff], got write-back
check the kernel Documentation/x86/pat.txt, it says:
A. Exporting pages to users with remap_pfn_range, io_remap_pfn_range,
vm_insert_pfn
Drivers wanting to export some pages to userspace do it by using
mmap interface and a combination of …
=> ion_system_heap: support X86 archtecture

aosp_diff/preliminary/frameworks/base/13-0013-WA-Aquire-wakelock-when-BluetoothManagerService-retr.patch
com.android.bluetooth process crashes on system resume if power is
cut to the bluetooth chip during suspend. If system suspends again
before bluetooth is enabled, the crash repeats, and which will result
in the subsequent retries to fail. After many suspsed resume cycles
the retry counter will exceed the maximum limit and BT will remain in
Off state.
Workaround solution is to acquire wakelock when the service tries to
restart BT
Change-Id: Ib696f064fc9123350fb7a6093d9a15aaa2a843c6
Tracked-On: OAM-100721
=> [WA] Aquire wakelock when BluetoothManagerService retries enable BT

aosp_diff/preliminary/external/drm_hwcomposer/0009-Add-DP-training-failure-handling.patch
Handle DP training failure at
userland.
Check for link status when recv
KMS uevent and current and prev
status is connected. If link is
bad, retrigger modeset to
trigger DP retraining.
Tracked-On: OAM-100493
Signed-off-by: Swee Yee Fonn <swee.yee.fonn@intel.com>
=> drm-composer: Add DP training failure handling

aosp_diff/preliminary/system/core/02_0002-Enable-virtual-ab-compression-feature.patch
Need this patch to enable virtual ab compression feature,
or the system sometimes cannot boot up after the OTA completes.
Simply speaking, snapuserd is needed to be started before
the init second stage, since system partition need to be
setup after the snapuserd is started, or the system partition
cannot be accessed. However, init second stage needs to
access the system partition, So add this patch to make sure
snapuserd is started before init second stage.
Will report a bug to Google, and this patch also will be removed
once this issue is resovled.
Tracked-On: OAM-100724
=> Enable virtual ab compression ota

aosp_diff/caas_cfc/system/sepolicy/0001-Update-policy-for-media-provider.patch, bsp_diff/caas_cfc/packages/providers/MediaProvider/0001-Set-new-umask-value-for-mediaprovider-app.patch
1. Grant access permissions of p9fs2 files to all apps.
2. Modify the umask value of mediaprovider app to 0, so
mediaprovider app can accsess the files created by itself
in /sdcard/Pictures.
Currently the umask value of mediaprovider app is 0077, that
means the other and group users cannot access the files created
by mediaprovider app. However, /sdcard/Pictures is a directory
shared by VM and Host and 9pfs is mounted on it. The user and
group of /sdcard/Pictures is system and ratio, so mediaprovier
app is a other user to this directory and its files, that means
mediaprovider app cannot access the files created by itself, this
is unreasonable. Set the umask value of mediaprovider app to 0, so
it can access the files created by itself.
Tracked-On: OAM-100485
Signed-off-by: ji, zhenlong z …
=> Grant access permissions of p9fs2 files to all apps

aosp_diff/preliminary/external/libdrm/0001-use-private-libdrm-instead-of-external-libdrm.patch
Rename external libdrm from libxxx to libxxx_orig, so that we use can
libdrm-intel instead of external libdrm, and bunches of libdrm_pri
renaming patches could also be removed.
Tracked-On: OAM-101163
Signed-off-by: yifang ma <yifangx.ma@intel.com>
Signed-off-by: Chenglei Ren <chenglei.ren@intel.com>
Signed-off-by: wei, wushuangx <wushuangx.wei@intel.com>
=> use private libdrm instead of external libdrm

aosp_diff/caas_cfc/frameworks/base/0002-Disable-the-Status-Bar-and-grant-runtime-permissions.patch
Previously status bar is disabled in DisplayPolicy, however,
the status bar still appear in some scenarios. Do the
disable operation in the activity layout context to cover more
circumstances.
Tracked-On: OAM-101104
=> Disable the status bar in activity layout context

aosp_diff/caas_cfc/frameworks/base/0008-Don-t-show-force-resize-warning-window.patch
This is to help disable force resize warning window
on external display
Tracked-On: OAM-100858
=> Don't show force resize warning window

aosp_diff/caas_cfc/frameworks/base/0010-Fixed-screen-flicking-caused-by-display-mirror-mecha.patch
Display 0 mirror to display 1 caused UI flicking and more bad
case that 2 displays showed the same content. The fix is do
display mirror on very limited conditions.
Tracked-On: OAM-101229
=> Fixed screen flicking caused by display mirror mechanism.

aosp_diff/caas_cfc/frameworks/base/04_0004-Launch-the-app-directly-after-successful-update.patch
Launch the App directly after it has been updated
sucessfully, without giving option for user to
select "Done" or "Launch". This is given as
an interim fix.
Tracked-On: OAM-100841
=> Launch the app directly after successful update.

bsp_diff/common/kernel/lts2020-chromium/20_0020-ACPI-PM-Propagate-power-button-event-to-user-space-w.patch
Add bsp_diff patch in kernel to propagate power button
event to user space.
Tracked-On: OAM-101964
Signed-off-by: Kaushlendra Kumar <kaushlendra.kumar@intel.com>
=> [bsp_diff:kernel/ACPI]: add bsp diff patch

aosp_diff/preliminary/external/drm_hwcomposer/0011-Shouldn-t-call-AddFB2-in-HWC-for-every-commit.patch
Cache framebuffer object into drm_fb_id_handle_cache_
(std::map<GemHandle, std::weak_ptr<DrmFbIdHandle>>),can find
framebuffer from cache at next time. Unfortunately framebuffer
will be closed after composition, in order to make framebuffer
long-time valid, so change weak_ptr to shared_ptr.
Tracked-On: OAM-101868
Signed-off-by: Li, HaihongX <haihongx.li@intel.com>
=> Shouldn't call AddFB2 in HWC for every commit

host/kernel/lts2020-chromium/0009-ISH-driver-Support-for-AlderLake.patch
Added Alderlake configurations to create
IIO entry in sys/bus which will be used
by Sensor devices
Tracked-On: OAM-102023
Signed-off-by: Vilas R K <vilas.r.k@intel.com>
=> ISH driver Support for AlderLake

bsp_diff/common/kernel/lts2019-chromium/27_0027-VIRTIO-Freeze-and-Restore-Implementation.patch
[VIRTIO] Freeze and Restore Implementation.
Whenever VM goes for suspend if there are any
active VSOCK connections used to communicate with host,
respective vsock connections were unable to resume as
freeze and restore functionality was not implemented in
virtio driver.
This change will fix VSOCK reconnect in case
of Suspend and Resume
In freeze case:
Change will reset all connected sockets when the device
disappears and flush all device writes and interrupts
and also delete virtqueues and flush outstanding
callbacks if any.
In Restore case:
Change will initialize all the necessary parameter to
make the virtio device ready
Tracked-On: OAM-100107
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
Vilas R K <vilas.r.k@intel.com>
Bharat Panda <bharat.b.panda@intel.com>
=> [VSOCK] Support for Suspend & Resume.

bsp_diff/common/kernel/lts2020-yocto/25_0025-drm-i915-dp-HACK-remove-TPS4-to-avoid-LT-failure-iss.patch, bsp_diff/common/kernel/lts2020-yocto/26-0026-drm-i915-gem-Don-t-evict-unmappable-VMAs-when-pinning-with-PIN_MAPPABLE-v2.patch
This commit can enable 8K 60FPS mode and solve screen flickering problem
Tracked-On: OAM-102536
Signed-off-by: Kanli Hu <kanli.hu@intel.com>
=> drm/i915: enable 8K60

aosp_diff/preliminary/build/soong/0010-Allow-sgdisk-and-mmd-to-make-USB-disk-installer-imag.patch
The two commands is used to make USB installer image.
we can install the CIV image from USB without UEFI
shell.
Tracked-On: OAM-102736
Signed-off-by: Chen, Gang G <gang.g.chen@intel.com>
=> Allow sgdisk and mmd to make USB disk installer image

aosp_diff/preliminary/test/vts-testcase/kernel/gki/0001-Excluding-gki-testcases-for-android_x86-x86_64.patch
As we do-not have gki support for android_x86/x86_64.
Excluding gki test-cases.
Tracked-On: OAM-102789
=> Excluding gki-testcases for android_x86/x86_64

host/kernel/lts2020-chromium/build_weekly.sh
Updated SHA ID in build script to point to latest kernel cve fix commit
Tracked-On: OAM-102862
=> kernel: Update build script with latest commit hash

bsp_diff/common/kernel/lts2020-chromium/21_0021-VIRTIO-Freeze-and-Restore-Implementation.patch
Whenever VM goes for suspend if there are any
active VSOCK connections used to communicate with host,
respective vsock connections were unable to resume as
freeze and restore functionality was not implemented in
virtio driver.
This change will fix VSOCK reconnect in case
of Suspend and Resume
In freeze case:
Change will reset all connected sockets when the device
disappears and flush all device writes and interrupts
and also delete virtqueues and flush outstanding
callbacks if any.
In Restore case:
Change will initialize all the necessary parameter to
make the virtio device ready
Tracked-On: OAM-102904
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
Signed-off-by: Vilas R K <vilas.r.k@intel.com>
Signed-off-by: Bharat Panda <bharat.b.panda@intel.com>
Signed-off-by: RajaniRanjan …
=> Freeze and Restore Implementation.

host/kernel/lts2020-chromium/build_weekly.sh
Updated SHA ID in build script to point to latest kernel cve fix
- vt: drop old FONT ioctls
Tracked-On: OAM-103477
=> kernel: Update build script with latest commit hash - ww39

aosp_diff/preliminary/build/soong/0006-Allow-build-commands-to-make-Celadon-as-ISO-format-i.patch
The commands are required by generating ISO file format images
Tracked-On: OAM-103667
Signed-off-by: Chen, Gang G <gang.g.chen@intel.com>
=> Allow build commands to make Celadon as ISO format image

host/kernel/lts2021-chromium/build_weekly.sh
Updated SHA ID in build script to point to 5.15.44 kernel commit.
Tracked-On: OAM-103751
=> kernel: Update build script with latest commit hash for 5.15.44

host/kernel/lts2021-chromium/0005-Fix-device-hang-on-TGL-RVP.patch, host/kernel/lts2021-chromium/build_weekly.sh
With the latest 5.15 kernel + host kernel diff patches, build error is seen due to change in function prototype. Also, build script expects the user to clone vendor-intel-utils project for it to work.
Fix the build error and also modify the script so one can compile by downloading the build script alone.
Tracked-On: OAM-103824
=> kernel: Fix patch conflict and build script issues

bsp_diff/common/kernel/lts2021-chromium/20_0020-VIRTIO-Freeze-and-Restore-Implementation.patch
porting sensorservice@2.0 for android T.
clearing bsp_diff patches of sensors reverted
changes and applying kernal patch for vsock
suspend and resume.
Tracked-On: OAM-103828
Signed-off-by: vilasrk <vilas.r.k@intel.com>
=>  upgrading sensors@1.0service to sensors@2.0service

aosp_diff/preliminary/packages/services/Telephony/01_0001-Fix-phone-process-crash-when-there-is-no-modem.patch
Phone process keeps crashing with ArrayIndexOutOfBoundsException exception.
When there is no modem, tm.getSupportedModemCount returns 0. mTelephonyCallbacks object array is created with 0 but index 1 is accessed resulting in ArrayIndexOutOfBoundsException exception.
Fix the issue by allocating and accessing mTelephonyCallbacks only when tm.getSupportedModemCount is greater than 0.
Tracked-On: OAM-103825
=> Fix phone process crash when there is no modem

bsp_diff/common/kernel/lts2019-chromium/72-0072-drm-i915-Factor-out-i915_ggtt_suspend_vm-i915_ggtt_r.patch, bsp_diff/common/kernel/lts2019-chromium/73-0073-drm-i915-Improve-on-suspend-resume-time-with-VT-d-en.patch
Cherry-pick 2 i915 patches from Patchwork Intel GFX
1.drm/i915: Factor out i915_ggtt_suspend_vm/i915_ggtt_resume_vm()
https://patchwork.freedesktop.org/patch/461948/
2.drm/i915: Improve on suspend / resume time with VT-d enabled
https://patchwork.freedesktop.org/series/102187/
Tracked-On: OAM-103652
Signed-off-by: Zhuo Peng <zhuo.peng@intel.com>
=> Fix i915 driver crash while system resume

aosp_diff/preliminary/build/soong/0007-Add-support-for-overide_lib_name-for-IA-perf-variant.patch
override_lib_name soong variable support is
required by IPP patch.
Tracked-On: OAM-103597
=> Port "Add support for override_lib_name" to Android-13

host/kernel/lts2021-chromium/build_weekly.sh
Host kernel build fails with implicit declaration of function ‘pcie_has_flr’ error.
Updated SHA ID in build script to point to vendor/intel/utils commit hash having the correct diff patch. Commit hash corresponds to "kernel: Fix patch conflict and build script issues" commit.
Tracked-On: OAM-103945
=> kernel: Fix host kernel build issue

bsp_diff/common/kernel/lts2020-yocto/50_0050-Update-VIRTIO_ID_TRUSTY_IPC-from-13-to-14.patch
VIRTIO ID 13 is assigned to MEMORY BALLON from kernel 5.15, in order to avoid conflict on VIRTIO ID assignment, update ID for TRUSTY_IPC device from 13 to 14.
Tracked-On: OAM-103995
=> Update VIRTIO_ID_TRUSTY_IPC from 13 to 14

aosp_diff/preliminary/hardware/interfaces/10_0010-Fix-for-VTS-issue-in-thermal.patch
To Keep the source directory cleaner and
more readable above mentioned movement
of diff patch is done.
Tracked-On: OAM-103812
Signed-off-by: Vilas R K <vilas.r.k@intel.com>
=> Moving Thermal Diff patch from BSP to AOSP diff

host/qemu/0008-Fix-drawing-delay-issue-in-cases-of-resize-and-rotat.patch
gd_egl_draw does not flush anything when draw_submitted=false, this inludes the cases of resize and rotation, so add one time flush to fix it.
Tracked-On: OAM-104047
Signed-off-by: Lu Yang A <yang.a.lu@intel.com>
=> Fix drawing delay issue in cases of resize and rotation for SRIOV

aosp_diff/preliminary/external/drm_hwcomposer/0012-hwc-DrmFbImporter-cache-manager-need-to-erase-drm_fb.patch
when plug-out external display
we will find the framebuffer obj will be increase
we can use the following command to find it
cat /sys/kernel/debug/dri/128/framebuffer
this bug was caused by
commit c857539fdc26fb8f11eeff795c9ab19de7f036a0
Author: Li, HaihongX <haihongx.li@intel.com>
Date:   Thu Apr 14 18:16:16 2022 +0800
Shouldn't call AddFB2 in HWC for every commit
in this patch we modify the
DrmFbImporter.h
-  std::map<GemHandle, std::weak_ptr<DrmFbIdHandle>> drm_fb_id_handle_cache_;
+  std::map<GemHandle, std::shared_ptr<DrmFbIdHandle>> drm_fb_id_handle_cache_;
we need to erase the drm_fb_id_handle_cache_ when the display is disconnected
Tracked-On: OAM-103715
Signed-off-by: Kanli, Hu <kanli.hu@intel.com>
=> hwc: DrmFbImporter cache manager need to erase drm_fb_id

bsp_diff/common/kernel/lts2020-chromium/43_0043-Fix-volume-up-down-button-issue-with-3.5mm.patch
This patches resolves volume up/down button
not working issue, when no music is playing.
Tracked-On: OAM-102723
Signed-off-by: Pshou <pshou@realtek.com>
Signed-off-by: pmandri <padmashree.mandri@intel.com>
=> Fix volume up/down button issue with 3.5mm

host/kernel/lts2020-chromium/build_weekly.sh
CVE-2022-2905 - Applied
CVE-2022-2663 - Applied
CVE-2022-36946 - Applied
CVE-2022-0480  - Applied
CVE-2022-39188 - Applied
CVE-2022-2327  - Applied
CVE-2022-3176  - Applied
CVE-2022-3303  - Applied
CVE-2022-42719 - Applied
CVE-2022-42721 - Applied
CVE-2022-42722 - Applied
CVE-2022-42720 - Applied
CVE-2022-41674 - Applied
CVE-2019-15794 - Applied
Tracked-On: OAM-104375
=> CVE: Update build script with latest commit hash for v5.10.118

aosp_diff/preliminary/bionic/0001-Optimize-bionic-memory-functions-with-avx2-instructi.patch, aosp_diff/preliminary/bionic/0002-Optimize-bionic-string-functions-with-avx-implementa.patch, aosp_diff/preliminary/bionic/0003-Linker-changes-to-allow-perf-variants-of-an-.so.patch
Port required bionic patches from Android-12
to Android-13. Patches include:
- avx2 memory APIs
- avx2 string APIs
- linker patch to allow multiple .so variants
Tracked-On: OAM-104407
=> Port required bionic patches to Android-13

host/kernel/lts2020-chromium/build_weekly.sh
Updating new tag: lts-v5.10.118-20221103-r1
Contains following CVE fixes:
CVE-2022-21123 - Applied
CVE-2022-21125 - Applied
CVE-2022-21166 - Applied
CVE-2022-1972/CVE-2022-2078 - Applied
CVE-2022-3028 - Applied
CVE-2022-1184 - Applied
CVE-2022-2959 - Applied
CVE-2022-2503 - Applied
CVE-2022-36123 - Applied
CVE-2022-36879 - Applied
CVE-2021-33655 - Applied
CVE-2022-3577 - Applied
CVE-2022-3594 - Applied
CVE-2022-20422 - Applied
CVE-2022-20421 - Applied
Tracked-On: OAM-104461
=> Kernel_v5.10.118: Update build script with latest CVE fixes

aosp_diff/preliminary/frameworks/base/63_0063-Add-isVisible-public-API.patch
Task visibilty info will help us decide if correspoding LG window should be closed or not.
This patch also adds TASK permission to ClipboardAgent private app.
Tracked-On: OAM-104429
=> Add isVisible public API.

aosp_diff/preliminary/packages/modules/Bluetooth/0006-Change-enhanced-SCO-setup-data-path-to-HCI.patch
Intel BT chip is expecting SCO data path as 0x00 (HCI), But Android by default setting data path as 0x01 (PCM), which is not supported in Intel BT chip, so call audio is not routing to Bluetooth headset.
Refer Bluetooth core spec section 7.1.45
Enhanced Setup Synchronous Connection command:
Input_Data_Path,
Output_Data_Path.
After setting data path to 0x00 (HCI), now call audio packets are sent to BT chip via HCI and routed to BT headset.
Tracked-On: OAM-104716
=> Change enhanced SCO setup data path to HCI

host/kernel/lts2021-chromium/build_weekly.sh
CVE-2022-3623 - Applied
Tracked-On: OAM-104676
=> CVE: Update build_weekly.sh with latest commit tag for v5.15.74

aosp_diff/preliminary/external/libavc/0001-Libavc-Intel-Intrinsics-Avx2-Support.patch, aosp_diff/preliminary/external/libavc/0002-Libavc-Intel-Intrinsics-Avx2-Support.patch
Each of the inter prediction, inverse transform and deblocking filter kernels of the H.264 decoding works by handling the 16x16 macro block of 256-bit vectors  in two operations 128-bit each in the current  SIMD support. By inferencing with hand-written code logic using AVX2 intrinsic we are able to process the same number of data with a single instruction and hence help in improving the performance of the software decoder.
The overhead(%) for cpu-cycles on the module : libcodec2_soft_avcdec has been reduced by ~15% impact when we collected the simpleperf data by playing 1024 resolution video playback on the Galley App with HW decoder disabled on Android T. Other Benchmark KPIs had no impact as this patch is related to s/w video decoding.
Tracked-On: OAM-104805
Signed-off-by: Priyanka …
=> Optimizing avc SW-Decoder with handwritten AVX2 intrinsic

host/kernel/lts2020-chromium/build_weekly.sh
CVE-2022-43750 - Applied
CVE-2022-3623 - Applied
CVE-2022-3625 - Applied
CVE-2022-3629 - Applied
CVE-2022-20409 - Applied
Tracked-On: OAM-104870
=> CVE: Update build_weekly.sh with latest commit tag for v5.10.118

host/kernel/lts2020-chromium/build.sh, host/kernel/lts2020-chromium/build_weekly.sh
CVE-2022-3435 - Applied
CVE-2022-3169 - Applied
CVE-2022-2978 - Applied
CVE-2022-3619 - Applied
CVE-2022-3564 - Applied
Tracked-On: OAM-104942
=> CVE: Update build scripts with latest commit tag for v5.10.118

aosp_diff/preliminary/frameworks/opt/net/ethernet/0001-Device-going-to-offline-during-cts-tests.patch
While it remove the user, then all services which had requested for ethernet network, request for release network. After that since there is no request pending, it stop ethernet.
Here we need to take network reference count in consideration if ethernet start due to interface link state change.
Tracked-On: OAM-102974
Signed-off-by: Ankit Agrawal <ankit.agarwal@intel.com>
=> Device going to offline during cts tests.

aosp_diff/preliminary/packages/apps/Camera2/04_0004-Fix-for-can-not-open-AOSP-Camera-from-Android-home-T.patch
When launching the app from  home task bar, then it try to match intent filter with the requested launch activity. Launcher category was missing from Camera2 manifest, so there was no exact match.
Tracked-On: OAM-104947
Signed-off-by: Ankit Agrawal <ankit.agarwal@intel.com>
=> Fix for AOSP Camera Launch Issue from Task Bar.

host/qemu/0035-hw-display-fix-virgl-reset-regression.patch
This issue can be reproduced on both s/t platform, when qemu version is v6.0.0. Need apply this upstream patch, or use new qemu version like v7.0.0.
Tracked-On: OAM-102548
Signed-off-by: chenyanxzhu <chenyanx.zhu@intel.com>
=> Fix qemu 6.0.0 virtio mode reboot crash issue

host/kernel/lts2021-chromium/build_weekly.sh
New commit tag - lts-v5.15.74-20221208-r6
CVE-2022-3524 - Fix Applied
CVE-2022-3594 - Fix Applied
CVE-2022-3567 - Fix Applied
CVE-2022-3543 - Fix Applied
CVE-2022-3522 - Fix Applied
Tracked-On: OAM-105208
=> CVE: Update build_weekly.sh with latest commit tag for v5.15.74 kernel

host/qemu/0009-Add-the-rgba-rgbx-support.patch
Fix the SRIOV boot fail on 5.15 kernel.
Tracked-On: OAM-105230
=> Add the RGBA/RGBX format support in Qemu

aosp_diff/preliminary/packages/apps/Settings/21_0021-Fix-for-adb-disconnecting-during-Monkey-Test-Run.patch
When running the monkey test, its going in tethering page inside Settings app and enabling ethernet tethering. Due to get adb connection is getting lost.
Guarding ethernet tethering option when monkey test is running, it will not display ethernet tethering option during monkey test.
Tracked-On: OAM-103750
Signed-off-by: Ankit Agrawal <ankit.agarwal@intel.com>
=> Fix for adb disconnecting during Monkey Test Run.

aosp_diff/preliminary/frameworks/base/99-0103-Prevent-apps-from-spamming-addAccountExplicitly-See-comment.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0104-DO-NOT-MERGE-Move-accountname-and-typeName-length-check-from.bulletin.patch
Zip file correction for CVE-2021-0934 bulletin_2022_12_preview_v2.zip. Provided on Dec 7th, 2022 did not include the complete patch details for CVE-2021-0934. Android 11 partners, who did not apply the patch from the zip file. Must apply the CVE-2021-0934 patch from bulletin_2022_12_preview_v3.zip. to fully remediate this CVE. No other Android versions are impacted with this changes.
Patches details
1)Prevent-apps-from-spamming-addAccountExplicitly-See-comment.bulletin.patch 2)DO-NOT-MERGE-Move-accountname-and-typeName-length-check-from.bulletin.patch
Tracked-On: OAM-105311
=> CVE-2021-0934 fix for ASB-December-2022 - rmr0_stable

aosp_diff/common/frameworks/base/0121-Prevent-apps-from-spamming-addAccountExplicitly-See-comment.bulletin.patch, aosp_diff/common/frameworks/base/0122-DO-NOT-MERGE-Move-accountname-and-typeName-length-check-from.bulletin.patch
Zip file correction for CVE-2021-0934 bulletin_2022_12_preview_v2.zip. Provided on Dec 7th, 2022 did not include the complete patch details for CVE-2021-0934. Android 11 partners, who did not apply the patch from the zip file. Must apply the CVE-2021-0934 patch from bulletin_2022_12_preview_v3.zip. to fully remediate this CVE. No other Android versions are impacted with these changes.
Patches details
1)Prevent-apps-from-spamming-addAccountExplicitly-See-comment.bulletin.patch 2)DO-NOT-MERGE-Move-accountname-and-typeName-length-check-from.bulletin.patch
Tracked-On: OAM-105319
=> CVE-2021-0934 fix for ASB-December-2022  - android_cloud

aosp_diff/preliminary/bionic/0010-Modify-sse2-avx2-memcpy-memmove-to-AOSP-memmove.patch
Optimization was targeted seperately for memmove
and memcpy. But this means no support for
overlapping copy when using memcpy. So modify
sse2/avx2 version of memcpy and memmove to
point to AOSP's memmove
=> Modify sse2/avx2 memcpy & memmove to AOSP memmove

aosp_diff/caas/frameworks/av/0001-CCodecBufferChannel-Report-an-error-after-reallocati.patch
Output buffer conversion failures trigger endless reallocations of output buffers. Report an error in the case.
This changes are taken from horizontal celadon(Android-T).
Google source code commit reference:
https://android.googlesource.com/platform/frameworks/av/+/8ceef4d17fad183bafc2afb587bdca667c4cff1e
Tracked-On: OAM-105281
Signed-off-by: Vasoya,Nikhilx <nikhilx.vasoya@intel.com>
=> CCodecBufferChannel: Report an error after reallocation failures.

aosp_diff/preliminary/bionic/0012-avx2-implementation-for-memset-api.patch
This patch includes handwritten avx2
assembly for memset 64-bit. Uses
non-temporal stores for very large sizes.
Also includes dynamic dispatch for APIs
having multiple implementations.
Convincing benchmark improvements for sizes above 512 bytes, and
although the slight regression for small sizes is unfortunate, it's
probably small enough to be okay?
Tracked-On: OAM-103728
=> avx2 implementation for memset.

bsp_diff/common/hardware/intel/gmmlib/0001-Add-Android.mk-for-intel-gmmlib-22.3.0.patch, bsp_diff/common/hardware/intel/media-driver/0001-Add-changes-to-build-latest-media-driver-in-Android.patch, bsp_diff/common/hardware/intel/media-driver/0002-Resolved-compilation-issue-for-media-driver.patch, bsp_diff/common/hardware/intel/media-driver/0003-Revert-Decode-Enhance-robustness-of-ddi-for-AV1.patch
Changes are done on top of below tag versions:
media-driver: tag: intel-media-22.6.1
gmmlib: tag: intel-gmmlib-22.3.0
Change-Id: Ia23cd16f49af380994e65358a9e958e67ecb5c11
Tracked-On: OAM-105094
Signed-off-by: Yerriswamy <yerriswamy.kt@intel.com>
=> Resolving the media-driver and gmmlib warnings

aosp_diff/preliminary/frameworks/base/101_0101-Add-safety-checks-on-KEY_INTENT-mismatch-.bulletin.patch
Manual porting of the patch due to merge conflicts.
Ported from:
Add safety checks on KEY_INTENT mismatch.
For many years, Parcel mismatch typed exploits has been using the
AccoungManagerService's passing of KEY_INTENT workflow, as a foothold of
launching arbitrary intents. We are adding an extra check on the service
side to simulate the final deserialization of the KEY_INTENT value, to
make sure the client side won't get a mismatched KEY_INTENT value.
Bug: 250588548
Bug: 240138294
Test: atest CtsAccountManagerTestCases
Test: local test, also see b/250588548
(cherry picked from commit eb9a0566a583fa13f8aff671c41f78a9e33eab82)
Commit-id : I433e34f6e21ce15c89825044a15b1dec46bb25cc
Tracked-On: OAM-105691
=> Fix for commit id issue patch

host/kernel/lts2021-chromium/build_weekly.sh
CVE-2022-4378 - Fix Applied
CVE-2022-47940 - Fix Applied
CVE-2023-23454 - Fix Applied
CVE-2023-23455 - Fix Applied
New commit tag lts-v5.15.78-20230206-r9
Tracked-On: OAM-105544
Signed-off-by: Boppana, Tej Kiran <tej.kiran.boppana@intel.com>
=> CVE: Update build_weekly.sh with latest commit tag for v5.15.78

host/ovmf/0002-Fix-vla-parameter-error.patch
Make vla buffer types consistent in declarations and definitions. 
Resolve build error when using -Werror due to "vla-parameter".
Tracked-On: OAM-105735
=> Fix vla-parameter error

bsp_diff/common/kernel/lts2020-yocto/0043-Bluetooth-btintel-Fix-bdaddress-comparison-with-garb.patch, bsp_diff/common/vendor/linux/firmware/0004-WA-Delete-iwlwifi-ty-a0-gf-a0.pnvm-for-Intel-AX210.patch
Move vertical changes to Horizontal.
Intel Read Verision(TLV) data is parsed into a local structure variable and it contains a field for bd address. Bd address is returned only in bootloader mode and hence bd address in TLV structure needs to be validated only if controller is present in boot loader mode.
Tracked-On: OAM-105473
Signed-off-by: Kothapeta, BikshapathiX <bikshapathix.kothapeta@intel.com>
=> Bluetooth: btintel: Fix bdaddress with garbage

aosp_diff/preliminary/frameworks/base/99_0100--DO-NOT-MERGE-Fix-permanent-denial-of-service-via-setCompon.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0101-Add-safety-checks-on-KEY_INTENT-mismatch-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0102-Validate-package-name-passed-to-setApplicationRestrictions-.bulletin.patch
Below patches numbering is not proper,
so patch application sequence is incorrect.
Correcting the same.
Present patches numbering
100_0100--DO-NOT-MERGE-Fix-permanent-denial-of-service-via-setCompon.bulletin.patch
101_0101-Add-safety-checks-on-KEY_INTENT-mismatch-.bulletin.patch
102_0102-Validate-package-name-passed-to-setApplicationRestrictions-.bulletin.patch
Modified patches numbering
99_0100--DO-NOT-MERGE-Fix-permanent-denial-of-service-via-setCompon.bulletin.patch
99_0101-Add-safety-checks-on-KEY_INTENT-mismatch-.bulletin.patch
99_0102-Validate-package-name-passed-to-setApplicationRestrictions-.bulletin.patch
Tracked-On: OAM-105740
=> Correcting the patches numbering

autopatch.sh
As of now autopatch only checks for 100 patches in a folder to apply "Already applied" tag. Increasing the same to 500 as the number of Patches in framework-base folder is more than 100. This will enable Lunch to not try and apply already applied patches till the number of Patches in a folder reaches 500+.
Tracked-On: OAM-105763
=> Increase number of patches limit from 100 to 500 for autopatch

host/qemu/0009-Qemu-6-Add-support-for-IPv6-host-forwarding.patch
Changes made netslirp to add support for ipv6 packet parsing and forwarding from host to guest.
Tracked-On: OAM-105532
Signed-off-by: Bharat B Panda <bharat.b.panda@intel.com>
=> [Qemu 6]Add support for IPv6 host forwarding

aosp_diff/cic_cloud/frameworks/av/0001-Change-H263-and-VP8-software-decoders-from-Codec2.0-.patch
Some of the H263 and VP8 files are not getting played when Codec2.0 software codec is used.
Fix the issue to use OMX software decoders for VP8 and H263 files.
Tracked-On: OAM-105820
=> Change H263 and VP8 software decoders from Codec2.0 to OMX

aosp_diff/cic_cloud/frameworks/av/0003-Fix-delayed-loading-and-distorted-thumbnails-observe.patch
With few files, thumbnails are distorted.
Software codec is used for thumbnails. Using Codec2.0 software codecs is resulting in delay in loading the thumbnail and also some of the thumbnails are distorted.
Fix the issue by enabling Codec2.0 decoder only for AV1. For rest of the formats, OMX decoder is used.
Tracked-On: OAM-105931
=> Fix delayed loading and distorted thumbnails observed in Gallery App

bsp_diff/common/hardware/intel/onevpl/0002-Fix-for-HEVC-rendering-failing-with-usptream-ffmpeg.patch
With upstream FFmpeg setting of extended device id config filter properties fails resulting in the HEVC rendering failure.
Extended device id are under ONEVPL_EXPERIMENTAL macro. As the ONEVPL_EXPERIMENTAL is not enabled, vpl returns failure on set config filter property request.
Define macro ONEVPL_EXPERIMENTAL to fix the issue.
Change-Id: I76ce4907bfa5658230ebb42846dc0651fba31aa4
Tracked-On: OAM-106567
=> Fix for HEVC rendering failing with usptream ffmpeg

aosp_diff/preliminary/frameworks/base/58_0058-Fix-for-Home-Button-When-Google-Assistant-is-disable.patch, aosp_diff/preliminary/packages/apps/Launcher3/0001-Fix-for-Home-Button-When-Google-Assistant-is-disable.patch
When user disables long press of home button option in settings to launch Google assistant, still it launch Google assistant on doing long press of Home button.
Added flag to check, if Google assistant is disabled or not.
Tracked-On: OAM-106871
=> Fix for Home Button When Google Assistant is disabled.

bsp_diff/common/hardware/intel/external/mesa3d-intel/0001-INTERNAL-WA-to-disable-virgl-disk-cache-for-VirtIO-b.patch
Android S stable use the 5.10 kernel, still need
this WA to boot virtio-gpu
Tracked-On: OAM-108599
=> Fix the Virtio boot fail on Android S stable

bsp_diff/celadon_ivi/vendor/intel/hardware/interfaces/0001-disable-wakeup-while-polling-for-netlink-event.patch
Dislable device wakeup when polling
for netlink event.
Solves suspend failure in Baremetal.
Tracked-On: OAM-108832
=> health: disable wakeup while polling for netlink event

aosp_diff/celadon_ivi/frameworks/base/0001-Allow-install-unknown-source-apks-in-ivi-by-default.patch
There is no "Allow unknown source apks" option in IVI Settings.
With this patch, all the applications are allowed to install
irrespective of user choice.
Tracked-On: OAM-108915
=> [REVERT ME] Allow install unknown source apks in ivi by default

bsp_diff/celadon_ivi/hardware/intel/kernelflinger/0001-REVERT-ME-Set-device-as-unlocked-state-by-default-on.patch
This is only WA patch to set device as unlocked.
The patch should be removed if fastboot is supported for BM.
With this patch, device will be unlocked on userdebug build; For user build, it still locked.
Tracked-On: OAM-108853
Author: Chen, Gang G <gang.g.chen@intel.com>
=> revertme: Set device as unlocked state by default on userdebug

aosp_diff/preliminary/packages/services/Telephony/03_0003-Fix-for-android.security.cts.CVE_2023_20913-failure.patch
VoicemailSettings Activity is default to portrait mode. Removing the hard fix.
Tracked-On: OAM-109681
=> Fixing the sts CVE-2023-20913 for VoicemailSettings

aosp_diff/celadon_ivi/packages/services/Car/0001-Fix-EVS-sample-driver-not-getting-started-as-service.patch
EVS sample driver not getting started as service due to missing sepolicies and onrestart automotive_display trigger.
Changes done to fix the issue:
Allow carservice_app with service find rights
Allow carservice_app with open, read and search access for sysfs dir Allow carservice_app with search access for data folder
Tracked-On: OAM-108929
=> Fix EVS sample driver not getting started as service

bsp_diff/common/hardware/intel/external/mesa3d-intel/0005-vulkan-fix-buf-map-failure-in-32bits-app.patch, bsp_diff/common/hardware/intel/external/mesa3d-intel/0006-Fix-Android-Swapchain-alignment-issue.patch
0005-vulkan-fix-buf-map-failure-in-32bits-app.patch
1) fix buf map failure in 32bits app
2) and when has_tiling_uapi is false
return I915_TILING_NONE which means ISL_TILING_LINEAR
On mesa, it returns -1, will cause vulkan app always crash
has_tiling_uapi is always false, because DRM_IOCTL_I915_GEM_SET_TILING
is not supported in has_get_tiling() function
0006-Fix-Android-Swapchain-alignment-issue.patch
1) fix gfxbench vulkan test show glitching image
Tracked-On: OAM-109724
Signed-off-by: Kanli Hu kanli.hu@intel.com
=> Fix gfxbench vulkan test fail

aosp_diff/celadon_ivi/packages/services/Car/0004-Fix-for-AOSP-and-EVS-cameras-not-working.patch, aosp_diff/celadon_ivi/packages/services/Car/0005-Fix-EVS-sample-driver-not-getting-started-as-service.patch
AOSP camera app not working as app fail to connect camera service. On reverse gear from vehicle HAL EVS Application failed to start.
Camera server is disabled resulting in camera app not able to connect to camera server. EVS application failed to started as the EVS services are disabled.
Fixed the issues by enabling camera server, EVS app, EVS manager. Also updated camera Id and display port for EVS application to work on reverse gear event.
Tracked-On: OAM-109740
=> Fix for AOSP and EVS cameras not working

host/kernel/linux-intel-lts2021/build_weekly.sh
linux-intel-lts2021 kernel
CVE-2023-0045 - Fix Applied
New commit tag lts-v5.15.71-20230504-r1
Tracked-On: OAM-109705
=> Update build_weekly.sh with latest commit tag for

aosp_diff/celadon_ivi/packages/services/Car/0006-WA-Force-stop-bootanimation-when-CarLauncher-UI-read.patch
The default bootanimation has all its segments' type set to 'c',wihch means "this part will play to completion, no matter what".
On ADL IVI platform, it takes less than 2 seconds from bootanimation start to boot finished (and system property 'service.bootanim.exit' set). But the default bootanimation is about 6 seconds long, which means the bootanimation will continue playing for 3~4 seconds after the system boot finished and UI ready.
This change is a workaround to force stop bootanimation when CarLauncer UI ready, so as to benchmark the time from cold boot to launcher UI correctly.
Tracked-On: OAM-109795
=> Force stop bootanimation when CarLauncher UI ready

aosp_diff/preliminary/build/make/0005-Add-allowZip64-True-for-ZipFile-in-RebuildAndWriteSu.patch
Zip failure will be seen if the size of super image is larger than 4G. So, fix the issue by setting allowZip64 to true.
Tracked-On: OAM-110072
=> Add allowZip64=True for ZipFile in RebuildAndWriteSuperImages

bsp_diff/common/hardware/intel/gmmlib/0001-Add-Android.mk.patch, bsp_diff/common/hardware/intel/libva/0001-Update-Android.mk-for-libva-2.18.0.patch, bsp_diff/common/hardware/intel/libva/0002-Support-media-stack-on-specified-render-node.patch, bsp_diff/common/hardware/intel/media-driver/0001-Add-changes-to-build-latest-media-driver-in-Android.patch, bsp_diff/common/hardware/intel/media-driver/0002-Resolved-compilation-issue-for-media-driver.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0001-Changes-for-OneVPL-integration.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0002-Restore-SG1-as-a-VPL-platform.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0003-Resolved-runtime-error-for-onevpl.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0004-Remove-ITT-vtune-support.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0005-Fix-for-HEVC-rendering-failing-with-usptream-ffmpeg.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0006-Changes-to-be-in-sync-with-features-enabled-in-linux.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0007-Enable-avx2.patch, bsp_diff/common/hardware/intel/onevpl/0001-Changes-for-OneVPL-integration.patch, bsp_diff/common/hardware/intel/onevpl/0002-Fix-for-HEVC-rendering-failing-with-usptream-ffmpeg.patch
Included versions:
* libva: 2.18.0 (same as before)
* gmmlib: 22.3.5 (same as before)
* media-driver: 23.2.1 (was 23.1.4)
* onevpl-gpu: 23.2.1 (was 23.1.4)
* oneVPL: v2023.2.1 (was v2023.1.3)
Tracked-On: OAM-110543
=> update media stack to media 23.2.1 release (devel-647)

aosp_diff/preliminary/system/media/0002-Expand-audio-framework-max-channel-count-to-24.patch
Update FCC_LIMIT to FCC_24 for audio 16 channel user case
Tracked-On: OAM-110582
=> Expand audio framework max channel count to 24

aosp_diff/celadon_ivi/frameworks/av/services/camera/libcameraservice/0001-Camera-fix-uvc-cameraid-mNumberOfCameras-issue.patch, aosp_diff/celadon_ivi/frameworks/base/0001-Condition-check-change-of-uvc-camera-id-in-jni.patch
which is larger than the real camera numbers and causes Invalid cameraId errors. Hence, Android app failed to use uvc camera through external cameraHAL. The fix contains two parts:
- libcameraservice.so: change the condition check of cameraId, iterate check app required cameraId with deviceIds;
- Camera Jni: remove cameraId > NumberOfCameras condition. This patch is delivered in base/core/jni project.
Bug: OAM-109947
Test: verify camera functionalities with meeting/camera apps
=> The cameraId of uvc camera is video device number + CameraIdOffset,

aosp_diff/celadon_ivi/packages/services/Car/0008-Save-app-setting-of-Peak-Performance-to-database-imm.patch
From the code, save to database only when system shutdown, data will not be saved if the system reboot or shutdown unexpectly, so we save the data when it is changed.
Tracked-On: OAM-108706
=> Save app setting of "Peak Performance" to database immediately.

host/qemu/0001-Revert-audio-exit-1-if-audio-backend-failed-to-be-fo.patch, host/qemu/0002-Revert-Remove-the-slirp-submodule-i.e.-compile-only-.patch, host/qemu/0003-Revert-ui-console-fix-qemu_console_resize-regression.patch, host/qemu/0004-Revert-Revert-vfio-pci-quirks.c-Disable-stolen-memor.patch, host/qemu/0005-qemu-change-fence-poll-time-by-current-workload.patch, host/qemu/0006-Disable-EDID-auto-generation-in-QEMU.patch, host/qemu/0007-Add-the-rgba-rgbx-support.patch, host/qemu/0008-ui-gtk-new-param-monitor-to-specify-target-monitor-f.patch, host/qemu/0009-Adapt-APP-landscape-or-portrait-mode-display-dynamic.patch, host/qemu/0010-CiV-SRIOV-virtio-gpu-power-management-qemu.patch, host/qemu/0011-Fix-drawing-delay-issue-in-cases-of-resize-and-rotat.patch, host/qemu/0012-Add-support-for-IPv6-host-forwarding.patch
The 0001 revert the commit 0f957c53c84d, causes qemu launch fail.
It exit(1) if audio backend failed to be found or initialized.
The 0002 revert the commit 5890258aeeba, causes qemu launch fail.
It remove the slirp submodule, since QEMU 7.1 don't support
Ubuntu 18.04 anymore.
The 0003 revert the commit 88738ea40bee, causes SRIOV boot fail.
It will cause display corrupt when changing screen color depth
since 7.0.
The 0004-0012 are the 9 patches porting from qemu 7.0.0.
Tracked-On: OAM-110647
=> Update the host patches for qemu 7.2.3

aosp_diff/celadon_ivi/packages/services/Car/0010-Fix-for-Calendar-App-to-Launch-in-Passenger-zone.patch
Provider packages were not installed for profile type user, So user was not able to launch following apps in passenger zone-:
Calendar, Contacts & Phone Apps.
Added provider packages for above apps in pre-installed list.
Tracked-On: OAM-106801
=> Fix for Calendar App to Launch in Passenger zone.

aosp_diff/preliminary/frameworks/base/99_0141-Add-null-check-for-intent-in-KeyguardManager.patch
intent should not be null before starting the activity. This null check will avoid that.
Tracked-On: NA
=> Add null check for intent in KeyguardManager

aosp_diff/celadon_ivi/packages/apps/Car/libs/0001-Fix-for-Local-Media-Player-in-Passenger-Zone.patch, aosp_diff/celadon_ivi/packages/services/Car/0011-Fix-for-Local-Media-Player-in-Passenger-Zone.patch
Currently MultiDisplay launcher does not have capability to show launcher icons for media services app, as these apps does not have any launcher category, So it does not show icon in launcher app.
Querying all MediaBrowsingService apps and adding them in launcher.
Tracked-On: OAM-106796
=> Fix for Local Media Player in Passenger zone.

aosp_diff/celadon_ivi/frameworks/av/cmds/stagefright/0002-Update-stagefright-for-more-audio-source-format.patch
Enable stagefright and recorder for debug
Tracked-On: OAM-111132
=> Enable stagefright and recorder for debug

aosp_diff/celadon_ivi/frameworks/base/0002-Enable-Bluetooth-on-AX210-Typ2.patch
Allow hci0 interface for Bluetooth initialization.
AX210 Typ2 <8087:0032>  btusb interface is initialized by USBHostManager. So, Bluetooth HAL is denied access to the card.
Added patch to deny Typ2 from USB initialization, so that Bluetooth HAL takes control of it and does the Bluetooth initialization.
Verified the BT on/off functionality on RPL board with AX210.
Tracked-On: OAM-111142
=> Enable Bluetooth on AX210 Typ2

aosp_diff/celadon_ivi/packages/apps/Bluetooth/0001-Update-BT-HFP-call-state-to-audio-manager.patch
As we are using btusb loopback device, there is no audio output if we open btusb card during DIALING/RINGING call state.
Audio is routed properly when btusb loopback device is opened after call is picked up (i.e., call state to ACTIVE).
We are updating this call state to audio manager, so that audio manager can open/close the btusb loopback device.
Voice call verified on ADL NUC.
Tracked-On: OAM-111143
=> Update BT HFP call state to audio manager

aosp_diff/celadon_ivi/system/core/0001-Set-selinux-to-permissive-mode-in-user-build.patch
Currently there are some SELinux issues blocking the boot of
IVI user build. Set SELinux to permissive mode in user build
temporarily, will revert this patch once resolving the issues.
Tracked-On: OAM-111194
=> Set selinux to permissive mode in user build

aosp_diff/preliminary/frameworks/base/99_0174-Strip-transition-information-from-activityoptions-when-sent-.bulletin.patch
STS failed details
Module - x86_64 CtsSecurityTestCases
Test Case-  android.security.cts.ActivityManagerTest#testActivityManager_stripTransitionFromActivityOptions This patch released on ASB-OCT-2022 and missed in the 12.1 codebase . We ported the patch in 12.1 and STS failure is resolved.
Patch details
1)0001-Strip-transition-information-from-activityoptions-when-sent-.bulletin.patch
Tracked-On: OAM-111062
=> Fix for STS failure

bsp_diff/common/hardware/intel/gmmlib/0001-Enable-compilation-on-android.patch, bsp_diff/common/hardware/intel/libva/0001-Update-Android.mk-for-libva-2.19.0.patch, bsp_diff/common/hardware/intel/libva/0002-Support-media-stack-on-specified-render-node.patch, bsp_diff/common/hardware/intel/libva/0003-Fixed-crashes-due-to-wrong-environment-name.patch, bsp_diff/common/hardware/intel/media-driver/0001-Add-changes-to-build-latest-media-driver-in-Android.patch, bsp_diff/common/hardware/intel/media-driver/0002-Resolved-compilation-issue-for-media-driver.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0001-Changes-for-OneVPL-integration.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0002-Restore-SG1-as-a-VPL-platform.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0003-Resolved-runtime-error-for-onevpl.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0004-Remove-ITT-vtune-support.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0005-Fix-for-HEVC-rendering-failing-with-usptream-ffmpeg.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0006-Changes-to-be-in-sync-with-features-enabled-in-linux.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0007-Enable-avx2.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0008-Fix-crash-seen-during-unloading-of-oneVPL-GPU-runtim.patch
Included versions:
* libva: 2.19.0 (was 2.18.0)
* gmmlib: 22.3.7 (was 22.3.5)
* media-driver: 23.2.4 (was 23.2.1)
* onevpl-gpu: 23.2.4 (was 23.2.1)
* oneVPL: v2023.3.0 (was v2023.2.1)
Tracked-On: OAM-111192
=> update media stack to media 23.2.4 release (devel-682)

bsp_diff/common/kernel/linux-intel-lts2021/0019-updating-dummy-cpufreq_frequency_table.patch, bsp_diff/common/kernel/lts2021-chromium/0023-updating-dummy-cpufreq_frequency_table.patch
updating frequency tables that represent the available CPU frequencies from ADL for scaling the CPU's clock frequency dynamically. This structure allows the kernel to manage the CPU's operating frequency based on the system's workload and power-saving requirements.
Reference platform (ADL-NUC):
Model name: 12th Gen Intel(R) Core(TM) i7-1260P
CPU min MHz: 400MHz
CPU max MHz: 4700MHz
Tracked-On: OAM-111324
=> updating dummy cpufreq_frequency_table

aosp_diff/celadon_ivi/packages/services/Car/0013-Fixed-for-crash-in-Multidisplay-launcher.patch
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.flattenToString()' on a null object reference at com.android.car.multidisplay.launcher.LauncherActivity.onAppPicked(LauncherActivity.java:382)
When try pinning any media app in launcher home screen, then it try to fetch component name, but for media apps component name was not set.
Tracked-On: OAM-111351
=> Fixed for crash in Multidisplay launcher.

aosp_diff/preliminary/frameworks/base/99_0175-Fixed-for-crash-in-webview_shell-during-monkey-test.patch
FATAL EXCEPTION: main
Process: org.chromium.webview_shell, PID: 22973
java.lang.RuntimeException: StrictMode ThreadPolicy violation Caused by: android.os.strictmode.DiskWriteViolation
Added StrictMode ThreadPolicy for disk write.
Tracked-On: OAM-110732
=> Fixed for crash in webview_shell during monkey test.

aosp_diff/celadon_ivi/packages/apps/Car/LocalMediaPlayer/0001-Fixed-for-crash-in-Local-media-player-during-monkey-.patch
java.lang.RuntimeException: Unable to create service com.android.car.media.localmediaplayer.LocalMediaBrowserService: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
Use device protected storage to Access shared preference before reboot complete.
Tracked-On: OAM-111435
=> Fixed for crash in Local media player during monkey test.

aosp_diff/celadon_ivi/packages/apps/Car/libs/0002-Fixed-for-crash-in-Alert-Dialog-Builder-during-monke.patch
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference at com.android.car.ui.AlertDialogBuilder.lambda$new$0$AlertDialogBuilder(AlertDialogBuilder.java:125)
Tracked-On: OAM-111429
=> Fixed for crash in Alert Dialog Builder during monkey test.

bsp_diff/common/vendor/intel/external/project-celadon/mediasdk-omx/0008-Fix-for-static-analysis-issues.patch
Changes include:
- Typecast the variables to appropriate type.
- Fix for unreachable code by removing unnecessary checks.
- Fix for vaMapBuffer unchecked return value
- Add copy constructor, assignment operator an destructor to be complaint with three/five/zero rule.
Change-Id: I37973107bfa5658230ebb42846dc0651fba31aa4
Tracked-On: OAM-111598
=> Fix for static analysis issues

aosp_diff/celadon_ivi/packages/services/Car/0014-Fix-crash-on-EmbeddedKitchenSink.patch
Getting following error while running monkey test-: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@fa52119 – permission denied for window type 2038
at android.view.ViewRootImpl.setView(ViewRootImpl.java:1213)
Permission isn't set before app add dialog, we check it first and set it by hand
Tracked-On: OAM-111431
=> Fix crash on EmbeddedKitchenSink.

aosp_diff/preliminary/frameworks/base/99_0182-Support-test-skipping-when-power-save-modes-aren-t-e.patch
STS failed details
Module -x86_64 CtsSecurityBulletinHostTestCases
Test Case- android.security.cts.CVE_2023_21128#testPocCVE_2023 As below patch was resolved the STS issue.
Patch details
1)99_0182-Support-test-skipping-when-power-save-modes-aren-t-e.patch
Tracked-On: OAM-111684
=> Fix for STS failure -CVE-2023-21128

bsp_diff/caas/kernel/lts2020-yocto/0001-drm-virtio-Improve-DMA-API-usage-for-shmem-BOs.patch, bsp_diff/caas/kernel/lts2020-yocto/0002-virtio-gpu-api-multiple-context-types-with-explicit-.patch, bsp_diff/caas/kernel/lts2020-yocto/0003-drm-virtio-implement-context-init-probe-for-feature.patch, bsp_diff/caas/kernel/lts2020-yocto/0004-drm-introduce-fb_modifiers_not_supported-flag-in-mod.patch, bsp_diff/caas/kernel/lts2020-yocto/0005-drm-virtio-set-fb_modifiers_not_supported.patch, bsp_diff/caas/kernel/lts2020-yocto/0006-drivers-virtgpu-Add-support-for-gem-buffer-import.patch, bsp_diff/caas/kernel/lts2020-yocto/0007-drivers-virtgpu-Add-virtio-gpu-tiling-format-support.patch, host/qemu/0036-dm-virtio-gpu-Add-virtio-gpu-plane-format-modifier-s.patch
Porting patches from celadon_ivi(lts2021 kernel)/ACRN to caas(lts2020 kernel)/QEMU. Add missing patches from lts2021 to lts2020, to make tiling patch work.
=> Add virtio tiling mode support for SRIOV

aosp_diff/celadon_ivi/packages/apps/Car/SystemUI/0001-Fix-Loading-dialog-not-hidden-timely-after-user-SWIT.patch
Sometimes a "Loading" dialog is seen during boot for several seconds before launcher show up. Two problems found in Car SystemUI app may lead to this issue. This patch contains two fixes for it, and improves about 3 seconds boot time KPI.
1. Fix CalledFromWrongThreadException in function UserNameViewController.updateUser(). This exception will interrupt the user SWITCHING event delivery and cause this issue.
2. Fix the race condition when checking mShowing in UserSwitchTransitionViewController.handleHide(). The race condition may lead to skipping the actual hide action and cause this issue.
Tracked-On: OAM-111369
=> Fix "Loading" dialog not hidden timely after user SWITCHING event

aosp_diff/preliminary/packages/apps/Gallery2/0001-Fixed-for-crash-in-Gallery-during-monkey-test.patch
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayOptions(int)' on a null object reference at com.android.gallery3d.filtershow.FilterShowActivity.loadXML(FilterShowActivity.java:352)
if any Activity can is embedded inside another activity, then embedded activity can not get action bar. Use parent activity to get action bar.
Tracked-On: OAM-111347
=> Fixed for crash in Gallery during monkey test.

aosp_diff/celadon_ivi/frameworks/base/0003-Fix-random-crash-on-Ximalaya-app.patch
When zooming in/out on main screen of Ximalaya app, it will crash if the point index is invalid, so check it before using.
Tracked-On: OAM-111908
=> Fix random crash on Ximalaya app.

bsp_diff/common/kernel/linux-intel-lts2021/0023-Add-support-for-Marvell-88q2122-phy-driver.patch
Marvell 88Q2xxx driver support is added for Marvell 88q2122 phy.
Tracked-On: OAM-110351
=> Add support for Marvell 88q2122 phy driver

aosp_diff/celadon_ivi/system/core/0001-WA-remove-some-code-to-fix-a-reboot-bug.patch
This WA aims to solve the problem that [IVI_BM]The first boot after flashing will reboot twice.
This deletes some code belongs to commit a7635718c459b95c45a09c409460570e564037dc "Pass wiped and fs_type to vold to format encrypted partition".
Tracked-On: OAM-111863
=> [WA] Add a patch which remove some code to fix a reboot bug

bsp_diff/common/kernel/linux-intel-lts2021/0001-WA-Revert-f2fs-Fix-f2fs_truncate_partial_nodes-ftrac.patch
This commit adds a patch which revert 14bb1fb893db1d915c98fce24263c0f42c259579 to fix the Pefetto problem.
Tracked-On: OAM-112068
=> [WA] Add a revert patch to fix a perfetto issue

aosp_diff/preliminary/frameworks/base/99_0197-Fix-for-Pointer-location-in-Developer-options.patch
Add SYSTEM_FLAG_SHOW_FOR_ALL_USERS to show
pointer_location for all users.
Reference-: https://cs.android.com/android/_/android/platform/frameworks/base/+/9762753c0a05fecf7d75d2253929225f0f8474cb
Tracked-On: OAM-110075
=> Fix for Pointer location in Developer options.

aosp_diff/celadon_ivi/external/perfetto/0001-ftrace-Ignore-f2fs-f2fs_truncate_partial_nodes.nid-f.patch
The field has a different format on kernels before and after 0b04d4c0542e("f2fs: Fix f2fs_truncate_partial_nodes ftrace event"). Perfetto is not able to understand the new format anyway and it would hit a DCHECK (abort in non debug builds).
Skipped test code for it's too new to merge into current perfetto(v15.0).
Tracked-On:
=> ftrace: Ignore f2fs/f2fs_truncate_partial_nodes.nid field

bsp_diff/common/kernel/linux-intel-lts2021/0025-Fix-Automotive-Ethernet-can-not-boot-up-success.patch
Add some delay after tx_enable.
TODO: this may needs to be fixed for a better way.
Test:
after add this patch, Automotive ethernet can
boot up success, adb connect through this interface success
Tracked-On: OAM-112426
=> Fix Automotive Ethernet can not boot up success

bsp_diff/common/device/intel/mixins/0005-Fix-for-VtsHalGraphicsComposerV2_4TargetTest-Case.patch
while running the vts module following fail to
push error is occurring-: Attempting to push dir
'VtsHalGraphicsComposerV2_4TargetTest' to an
existing device file /data/local/tmp/.
When it try to push directory, it always shows that dir already exists even if it is not there. this
was checking dir using 'ls' command and check for
'No such file or directory' output. But 'ls' command was giving always 'Invalid argument' and in that case it was always returning showing dir exists.
During 'ls' command syscall for 'prctrl' was assiging VMA name, but VMA feature was not enabled, so it was assiging default error code EINVAL.
Enabling this feature by enabling this flag-:
CONFIG_ANON_VMA_NAME
Test:
Run 'ls' command in adb shell for some file or directory which does not exists, it should give output …
=> Fix for VtsHalGraphicsComposerV2_4TargetTest Case

aosp_diff/common/bionic/0010-avx2-implementation-for-memset-api.patch, aosp_diff/common/bionic/0011-avx2-implementation-for-memmove-api.patch
This patch includes handwritten avx2 assembly
implementation for memset and memmove 64-bit.
Tracked-On: OAM-112465
=> Porting avx2 implementation for memset and memmove api from CIV.

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/libxml2/0001-malloc-fail-Fix-OOB-read-after-xmlRegGetCounter.bulletin.patch, aosp_diff/preliminary/external/webp/0001-update-to-v1-2-0-8-g20ceff7e.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0188-DO-NOT-MERGE-ActivityManager-killBackgroundProcesses-can-kill-c.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0189-Limit-the-number-of-supported-v1-and-v2-signers.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0190-Verify-URI-permissions-for-EXTRA_REMOTE_INPUT_HISTORY_ITEMS-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0191-Verify-URI-permissions-for-notification-shortcutIcon.patch, aosp_diff/preliminary/frameworks/base/99_0192-Import-translations-DO-NOT-MERGE-ANYWHERE.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0193-DO-NOT-MERGE-Revert-Verify-URI-permissions-for-EXTRA_REMOTE_INP.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0194-Verify-URI-permissions-for-EXTRA_REMOTE_INPUT_HISTORY_ITEMS-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0195-Do-not-share-key-mappings-with-JNI-object.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0196-DO-NOT-MERGE-Verify-URI-Permissions-in-Autofill-RemoteViews.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0197-Disallow-loading-icon-from-content-URI-to-PipMenu.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0198-Fixing-DatabaseUtils-to-detect-malformed-UTF-16-strings.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0200-RESTRICT-AUTOMERGE-SettingsProvider-exclude-secure_frp_mode-fr.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0201--RESTRICT-AUTOMERGE-Ignore-small-source-rect-hint.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0202-Add-placeholder-when-media-control-title-is-blank.patch, aosp_diff/preliminary/frameworks/native/19_0019-Fix-for-heap-use-after-free-in-GPUService-cpp.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/35_0035--RESTRICT-AUTOMERGE-Restrict-ApnEditor-settings.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/36_0036-RESTRICT-AUTOMERGE-Catch-exceptions-from-setLockCredential-.bulletin.patch, aosp_diff/preliminary/packages/modules/Wifi/0009-Add-pre-share-key-check-for-wapi.bulletin.patch, aosp_diff/preliminary/packages/modules/Wifi/0010-Update-password-check-for-WAPI.bulletin.patch, aosp_diff/preliminary/packages/providers/MediaProvider/08_0008-Fix-path-traversal-vulnerabilities-in-MediaProvider.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/12_0012-Fix-vulnerability-in-CallRedirectionService-.bulletin.patch, aosp_diff/preliminary/system/bt/39_0039-Fix-an-integer-underflow-in-build_read_multi_rsp.bulletin.patch, aosp_diff/preliminary/tools/apksig/0001-Limit-the-number-of-supported-v1-and-v2-signers.bulletin.patch
ASB - Security Patch integration October 2023
Test done: STS TCs Passed
Tracked-On: OAM-112412
=> ASB - Security Patch integration October 2023

bsp_diff/common/kernel/linux-intel-lts2021/0027-Add-marvell-MDIO-phy-test-mode-register-read-write-f.patch
Tests:
1, Download MDIO tools: https://github.com/PieVo/mdio-tool.git 2, Compile the tool to binary "mdio-tool", and adb push to system/bin 3, Open Marvell PHY test mode 1 : mdio-tool w eth1 0x904 0x2000 4, Open Marvell PHY loop back mode : mdio-tool w eth1 0x900 0x4000
Tracked-On: OAM-112419
=> Add Marvell MDIO PHY test mode registor read/write function

apply_patch.sh
Increase number of patches limit  for apply_patch
As of now apply_patch only checks for 200 patches in a folder to apply "Already applied" tag. 
Increasing the same to 250 as the number of Patches in framework-base folder is more than 200.
This will enable Lunch to not try and apply already applied patches till the number of Patches in a folder reaches 250+.
Tracked-On: OAM-112678
=> REVERTME: Increase number of patches limit  for apply_patch

aosp_diff/preliminary/frameworks/base/99_0198-Fix-for-default-notification-sound.patch
"Default notification sound" value is set 'none' in Settings->Sound option. this was due to missing file Tethys.ogg.
Added Tethys.ogg file for audio notification.
Test:
Open Settings->Sound option in Settings app and check for "Default notification sound" value. it should not be none.
Tracked-On: OAM-112674
=> Fix for default notification sound.

aosp_diff/preliminary/packages/services/Car/0016-Fix-duplicated-app-icons-navigation-keys-issues-on-M.patch
MultiDisplay launcher is having following 2 issues: 1) Some apps include media service, in those few apps do not have launcher activity. these apps are getting included in launcher by querying all MediaBrowsingService apps. Now some apps are getting included two times, one based on MediaBrowsingService & second based on launcher category.
2) Navigation keys are showing in MD Launcher app for driver user. Driver user uses Car Launcher and it already is having navigation bar.
Include apps based on only launcher category, if it have launcher activity. Also Hide navigation keys in MD launcher for driver user.
Tests:
Install some media app ex. prime video and open MD launcher. it should show prime video app only one time and also MD launcher should not show navigation keys.
Tracked-On: …
=> Fix duplicated app icons & navigation keys issues on MD Launcher.

aosp_diff/preliminary/packages/services/Car/0001-Remove-NetworkPreferenceApp-and-CarRadioApp-from-def.patch
Remove NetworkPreferenceAPP and CarRadioApp for now since they are not used.
Tests done: Verified device boot to UI. Verified the mentioned apps are removed.
Tracked-On: OAM-112837
=> Remove NetworkPreferenceApp and CarRadioApp from default installed APP

bsp_diff/caas/device/intel/mixins/0001-Upgrading-API-to-34-for-android-U.patch
for r2 build local lunch is failing for caas.
This patch will rebase the patch causing conflict.
Test:
$lunch caas-userdebug
on local workspace.
Tracked-On: OAM-112925
=> Fixing lunch issue with the patch

host/kernel/lts2022-chromium/build_weekly.sh
Added base buld_weekly.sh script for building host kernel. Base kernel version based on commit ae3fc1d is 6.1.34.
Tracked-On: OAM-112652
=> Add build_weekly.sh for building host kernel based on specific commit

bsp_diff/cic_cloud/vendor/intel/external/project-celadon/minigbm/0007-Fix-for-green-overlay-during-video-playback-with-SG1.patch
Buffer is created with 32 lines alignment for SG1 whereas the omx uses 64 lines alignment which causes the green bar in top.
Fix the issue by modifying the alignment to 64 while creating the buffer for all platforms.
Change-Id: I89346107bfa5658230ebb42846dc0651fba31aa4
Tracked-On: OAM-112867
=> Fix for green overlay during video playback with SG1

aosp_diff/preliminary/packages/services/Car/0017-Fixed-for-Unnecessary-app-shortcut-icon-in-MD-Launch.patch
When User try to add app shortcut from MD launcher settings in Home screen, some time it also add other apps shortcut app icons as well.
It was adding all media services app shortcut while user try to add any media service app. it should add only pinned apps.
Tests:
Go to add app shortcut option in MD launcher home screen settings option and add app shortcut for local media app. it add app shortcut only for this app.
Tracked-On: OAM-113019
=> Fixed for Unnecessary app shortcut icon in MD Launcher.

aosp_diff/preliminary/packages/apps/Gallery2/0002-Fix-javaCrash-on-com.android.gallery3d-with-null-obj.patch
mContainer is used but not initialized, so check it before it is used.
Tracked-On: OAM-113169
=> Fix javacrash on com.android.gallery3d with null object

aosp_diff/preliminary/external/thermal_daemon/0001-Disable-Thermal-Daemon-logs.patch
This commit disables the logging of Thermal Daemon to reduce log clutter and improve system performance.
By Default logs will be disabled it can be enabled by setting the following the below mentioned procedure.
Steps:
1. adb shell
2. setprop persist.vendor.disable.thermal.logs true
Tracked-On: OAM-113302
=> Disable thermal daemon excessive logs.

bsp_diff/common/kernel/linux-intel-lts2021/0028-Add-88q2122-eth-phy-suspend-resume-code.patch
Add 88Q2122 eth phy suspend resume code,
Delete some useless warning.
Tests:
on A1 board, ethernet can suspend/resume
success, ethernet power go down when it suspend.
Tracked-On: OAM-113125
=> Add 88Q2122 eth phy suspend resume code

aosp_diff/preliminary/packages/apps/Gallery2/0004-Fixed-for-JavaCrash-in-Gallery-app.patch
When try to crop or edit the image in gallery app, sometime app is crashing as it try to set new action bar which already has an action bar.
Check for action bar before creating new action bar.
Tests:
Launch Gallery app and try to edit/crop image and it should work fine.
Tracked-On: OAM-113325
=> Fixed for JavaCrash in Gallery app.

aosp_diff/preliminary/packages/modules/Wifi/0011-Set-5G-band-as-default-for-Wifi-AP-mode.patch
Set 5G band as default for Wifi AP mode
Tests:
open wifi hotspots on android setting,
use "iw wlan1 info" command.
it will show log as below, 5785MHz means AP run on 5G Interface wlan1
ifindex 12
wdev 0x2
addr e2:6f:96:66:ae:ae
ssid AndroidAP_6776
type AP
wiphy 0
channel 157 (5785 MHz), width: 20 MHz, center1: 5785 MHz
Tracked-On: OAM-113448
=> Set 5G band as default for Wifi AP mode

bsp_diff/common/kernel/linux-intel-lts2021/0028-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch
There is a requirement of a new interface for achieving below functionalities:
Need to provide Client based detailed information about the distribution of Graphics memory
Need to provide an interface which can provide info about the sharing of Graphics buffers between the clients.
The client based interface would also aid in debugging of memory usage/consumption by each client & debug memleak related issues.
With this new interface,
In case of memleak scenarios, we can easily zero in on the culprit client which is unexpectedly holding on the Graphics buffers for an inordinate amount of time.
We can get an estimate of the instantaneous memory footprint of every Graphics client.
We can now trace all the processes sharing a particular Graphics buffer.
By means of this patch we try to provide …
=> drm/i915: Sysfs interface to get GFX shmem usage

bsp_diff/common/kernel/linux-intel-lts2021/0033-Fix-88Q2122-eth-phy-remote-wakeup-disable-failed-issue.patch
when remote FDHU do not suspend, RDHU can
not suspend success.
Test:
Connect FDHU and RDHU, keep FDHU alive,
suspend RDHU, RDHU can suspend success
Tracked-On: OAM-113634
=> Fix 88Q2122 eth phy remote wakeup disable failed issue

aosp_diff/preliminary/bootable/recovery/03_0003-Modify-systemupdatersample-to-support-OTA-from-U-dis.patch
Udisk will be mounted as adoptable storage, and SystemUpdater will have no permissions to access the files on Udisk directly.
Test done: SystemUpdater won't crash when Udisk is mounted as
adoptable storage
Tracked-On: OAM-113511
=> Don't let SystemUpdater app access files on Udisk

aosp_diff/preliminary/packages/apps/Car/LocalMediaPlayer/0002-Fix-IndexOutOfBoundsException-on-LocalMediaPlayer.patch
Playlist is changed when the media is playing, so we should rebuild queue before we play or pause the media.
Tracked-On: OAM-113421
=> Fix IndexOutOfBoundsException on com.android.car.media.localmediaplayer

aosp_diff/preliminary/packages/apps/DeskClock/0002-Fix-fragment-java-crash-on-com.android.deskclock.patch
Fragment StopwatchFragment don't attach to window, so we need check it before geting resource of the Fragment.
Tracked-On: OAM-113328
=> Fix fragment java crash on com.android.deskclock

host/kernel/lts2022-chromium/build_weekly.sh
Updated utils commit hash in host kernel build script for v6.1.61 rebase.
Tests done:
- Host kernel build and boot.
Tracked-On: OAM-114109
=> Update utils commit hash in host kernel build script

aosp_diff/base_aaos/packages/apps/Gallery2/0005-Fixed-for-Crashes-in-Gallery-App.patch
During monkey test run, observing following crash
1) java.lang.RuntimeException: Unable to destroy activity {com.android.gallery3d/com.android.gallery3d.filtershow .FilterShowActivity}
2) ava.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.gallery3d.filtershow.data.UserPresetsManager.close()' on a null object reference
3) com.android.gallery3d java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.gallery3d.filtershow .pipeline.ImagePreset.contains(byte)' on a null object reference 4) com.android.gallery3d java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
5) com.android.gallery3d java.lang.NullPointerException: Attempt to invoke interface …
=> Fixed for Crashes in Gallery App.

aosp_diff/base_aaos/packages/apps/Contacts/0001-Fixed-for-Crash-in-Contact-app-during-Monkey-Test.patch, aosp_diff/base_aaos/packages/services/Car/0018-Fixed-for-Crash-in-KitchenSink-app-During-Monkey-Tes.patch
During monkey test run, observing following crash
1) android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java:1088) at android.app.ContextImpl.startActivity(ContextImpl.java:1064) at android.content.ContextWrapper.startActivity(ContextWrapper.java:411) at com.google.android.car.kitchensink.UserNoiticeDemoUiService .startDialog(UserNoiticeDemoUiService.java:122)
we cannot start an activity from a non-activity context unless you pass the intent flag FLAG_ACTIVITY_NEW_TASK. If you attempt to start an activity without passing this flag.
2) java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState …
=> Fixed for Crashes During Monkey Test.

bsp_diff/base_aaos/kernel/linux-intel-lts2021/0034-drm-i915-Fix-i915-crash-issue.patch
Encountered i915 crash during Monkey test
Add filelist mutex if access device file list to avoid race conditions
Tests Done:
-Boot with iGPU
-i915 debugfs check
-Reboot
Tracked-On: OAM-114178
=> drm/i915: Fix i915 crash issue

aosp_diff/base_aaos/packages/apps/Car/LatinIME/0001-Fixed-for-Soft-Keyboard-Color-key-size.patch
Currently soft keyboard keys are dark and not visible properly due to dark background and also key size is small.
Changed the key color and size.
Tests:
Open any Editor, it pop up soft keyboard. it has key visible poperly.
Tracked-On: OAM-114379
=> Fixed for Soft Keyboard Color & key size.

aosp_diff/preliminary/frameworks/base/99_0224-add-flag-to-skip-removing-permissions-in-clearApplic.patch
this PR gives users an option to keep App permissions even when clear data
operation is called under certain cases. It reads system property to decide the
behavior. By default, the property is not set, so no effect on the system.
It benefits automation test, in which App data needs to be cleared but its
permissions need to be kept.
Test done:
- boot up Android, run "adb shell pm clear com.wedobest.fivechess", found
all granted permissions of fivechess are cleared.
- run "adb shell setprop skip.reset.permission" and above pm clear cmd, the
granted permissions are still there.
Tracked-On: OAM-114234
=> add flag to skip removing permissions at cleardata

bsp_diff/base_aaos/kernel/linux-intel-lts2021/0034-drm-i915-Fix-i915-crash-issue.patch
Add filelist mutex if access device file list to avoid race conditions
Tests Done:
-Boot with iGPU
-i915 debugfs check
-Reboot
Tracked-On: OAM-114325
=> Refine previous patch for fixing i915 crash issue

aosp_diff/base_aaos/packages/apps/Gallery2/0006-Fixed-to-support-playing-mkv-ts-videos-from-File-A.patch
When user trying to play .mkv/.ts video from File app, it could not find any player app to play this file.
Adding support in Gallery app to play these video files.
Tests:
Open File app, and play .mkv/.ts video. it plays successfully.
Tracked-On: OAM-114430
=> Fixed to support playing .mkv & .ts videos from File App.

aosp_diff/base_aaos/packages/apps/Car/Settings/0005-Fixed-for-Toast-message-size-view.patch
When tap on build number in settings to enable developer option, it shows toast message which is very small in size.
Increased size of Toast message.
Tests: Enable developer option from settings and able to see toast message clearly.
Tracked-On: OAM-114463
=> Fixed for Toast message size view.

aosp_diff/base_aaos/frameworks/base/0001-Add-AppOverrideSettings-to-hack-app-layout-behavious.patch
Support forceFullscreen and forceLandscape flag by per app setting.
The settings is set by Andnroid prop as
debug.app.override_settings="<appName1>=<flags1>,
<appName1>=<flags1>,...". flags is a bitset for override features,
bit0 is forceFullscreen and bit1 is forceLandscape.
Other bits are not defined.
Tests done: Set the property and checked the App for
both full screen and landscape modes.
Tracked-On: OAM-113267
Signed-off-by: Marc Mao <marc.mao@intel.com>
Signed-off-by: Gao, HuadongX <huadongx.gao@intel.com>
=> [WA] Add AppOverrideSettings to hack app layout behavious

aosp_diff/base_aaos/frameworks/base/99_0241-Make-caller-wait-for-installd-to-become-available.patch
Tests: delay installd binding, observe no crashes and calls eventually succeed.
Tracked-On: OAM-114512
=> Fixed for boot to recovery mode after G3 boot and Cold boot.

aosp_diff/base_aaos/frameworks/base/99_0242-Fixed-for-crashe-during-Monkey-test-run.patch
Following crash were observed
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.statusbar.phone.NotificationPanelView Controller.setQsScrimEnabled(boolean)' on a null object reference
Check for null condition, so during monkey test run, if view is destroyed (which is very rare in manual test), then it can safely handle.
Tests:
Run monkey test and observe, test is pass.
Tracked-On: OAM-114271
=> Fixed for crashe during Monkey test run.

aosp_diff/base_aaos/packages/apps/Car/Settings/05_0005-Fix-null-pointer-dereference-coverity.patch
Fix null pointer dereference coverity
CID 200863: (https://github.com/projectceladon/vendor-intel-utils/pull/1 of 1): Dereference null return value (NULL_RETURNS)
Do null check before accessing the network interfaces.
Tracked-On: OAM-115263
=> Fix null pointer dereference coverity

aosp_diff/base_aaos/packages/apps/Bluetooth/06_0006-Revert-Remove-uuid-when-device-leaves-bonded-state.patch
Revert "Remove uuid when device leaves bonded state"
This reverts commit f7aa659bc7a3d9d89e54d9e154876a054c5bc269.
Reason for revert: Breaks devices with sensitive SDP/SMP timing conditions
Issue:
During device pairing, the device uuids are being removed from the cache
because of wrong bond state check, resulting in failure in profile
connections.
Solution:
Clear cached uuids only when the bond state is NONE.
Cherry picked from AOSP:
https://android-review.googlesource.com/c/platform/packages/modules/Bluetooth/+/2511479
Commit-id: 2305dc8ad1a8d0944abbad5fa1ef1bec6da8556a
Tracked-On: OAM-114062
Signed-off-by: Chris Manton <cmanton@google.com>
=> Revert "Remove uuid when device leaves bonded state"

aosp_diff/base_aaos/packages/modules/StatsD/0001-Fix-binder-cookie-memorie-leak.patch
Statsd was only deleting cookies for binder deaths when the death notifier was invoked. However, it is possible for the binder to get overwritten and for the client process to never die.
The fix for now is to not call LinkToDeath and avoid cookies entirely. We lazily remove objects from the maps when we receive a dead object exception on them.
Other options and more details are at go/statsd-binder-cookie-leak.
Test: atest statsd_test
Bug: 180471118
Bug: 202499776
Change-Id: Ie6ee3176e73a8602ca906396c0afc7df332deed1
Tracked-On: OAM-115526
=> [Statsd] Fix binder cookie memorie leak

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/cts/0001-Change-open-jpeg-folder-name.bulletin.patch, aosp_diff/preliminary/frameworks/av/34_0034-Update-mtp-packet-buffer.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0231-DO-NOT-MERGE-Disallow-Wallpaper-service-to-launch-activity-from-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0232-DO-NOT-MERGE-Hide-Android-data-obb-sanbox-on-shared-storage.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0233-Unbind-TileService-onNullBinding.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0234-Restrict-activity-launch-when-caller-is-running-in-the-backgroun.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0235--RESTRICT-AUTOMERGE-Check-permission-of-Autofill-icon-URIs.bulletin.patch, aosp_diff/preliminary/packages/providers/DownloadProvider/0003-DO-NOT-MERGE-Consolidate-queryChildDocumentsXxx-implementatio.bulletin.patch, aosp_diff/preliminary/system/bt/50_0050-Fix-an-OOB-bug-in-btif_to_bta_response-and-attp_build_value_cmd.bulletin.patch, aosp_diff/preliminary/system/bt/51_0051-Fix-an-OOB-write-bug-in-attp_build_read_by_type_value_cmd.bulletin.patch, aosp_diff/preliminary/system/core/03_0003-Add-seal-if-ashmem-dev-is-backed-by-memfd.bulletin.patch
Test done: STS r23 TCs Passed
Tracked-On: OAM-115406
=> ASB - February 2024 Security Patches integration

aosp_diff/base_aaos/packages/services/Car/0020-Fix-javacrash-on-com.google.android.car.kitchensink.patch
It's regression of previous patch, calling package is not allowed to draw overlays and the permission of SYSTEM_APPLICATION_OVERLAY is not permitted, meanwhile the activity to handle intent "android.settings.action.MANAGE_OVERLAY_PERMISSION" is not exist on car system, only exist on phone system, so skip the dialog.
Tracked-On: OAM-115329
=> Fix javacrash on com.google.android.car.kitchensink

aosp_diff/base_aaos/system/bt/53_0053-Revert-tL2C_TX_COMPLETE_CB_INFO-is-unused.patch, aosp_diff/base_aaos/system/bt/54_0054-Revert-L2cap-fixed-channel-tx-complete-is-unused.patch, aosp_diff/base_aaos/system/bt/55_0055-Revert-SMP-Assume-L2cap-tx-completes-immediately.patch
[Problem]
In SMP layer, the acknowledgement for packets being sent is not checked properly, causing the SMP control block to reset, which is flushing the unsent smp packets in l2cap queue. This packet drop is causing the remote reference device to disconnect with DUT as pairing is incomplete. SMP signing info cmd is flushed in l2cap layer.
[Solution]
So SMP to register the tx_complete_cb with l2cap for getting the acknowledgement for sent pkts. Wait for all sent pkts acknowledgement, until then do not reset the SMP control block.
Now SMP signing info cmd is being sent to reference device and able to see DUT in reference device paired devices list.
Tracked-On: OAM-112831
Signed-off-by: Bharat B Panda …
=> Revert aosp l2cap/smp patches to fix BT connection issue

aosp_diff/base_aaos/frameworks/base/99_0247-Allow-install-unknown-source-apks-in-ivi-by-default.patch
To fix a issue reported by Coverity previously, a patch is removed but the replacement patch is forgotten to be committed. Need to commit the missed patch.
Test Done: Unknown source apks can be installed.
Tracked-On: OAM-115697
=> Allow uknown source apks to be installed

aosp_diff/base_aaos/system/core/04_0004-overlayfs-Use-userxattrs-on-supporting-kernels.patch
In previous kernels, overlayfs stored its xattrs with a "trusted." prefix. This requires CAP_SYS_ADMIN. As a workaround, we carried out-of-tree kernel patches to bypass the security checks on these attrs.
The 5.15 kernel however has a new mount option "userxattr". When this is set, the "trusted." prefix is replaced with "user.", which eliminates the CAP_SYS_ADMIN requirement.
On kernels >= 5.15 we can use this feature and drop some of our out-of-tree patches.
Test done: Device can boot up successfully after pushing files to /vendor/etc/vintf/manifest
Tracked-On: OAM-114073
=> overlayfs: Use userxattrs on supporting kernels.

aosp_diff/base_aaos/frameworks/base/99_0250-Allow-SystemUpdater-app-access-udisk-files.patch
SystemUpdater app is used by customers to do full ota on Intel IVI devices, it reads ota packages from udisk. To read udisk files, SystemUpdater app must run in media_rw group. This patch checks the app name and the signed certificate, third party apps have no chances to run in media_rw group. And SystemUpdater app won't be shipped with the customers' final release build, so this patch should have no security impact to IVI devices.
Test done: SystemUpdater app can do the full ota successfully.
Tracked-On: OAM-115742
=> Allow SystemUpdater app access udisk files

aosp_diff/base_aaos/packages/apps/Gallery2/0007-WA-Fix-Monkey-Test-Failure-in-Gallery-App.patch
Monkey Test reported below error:
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at com.android.gallery3d.filtershow.editors
.EditorPanel.showImageStatePanel
Use commitAllowingStateLoss() instead of commit() so that it will not throw an exception if state loss occurs.
Tracked-On: OAM-115689
=> WA: Fix Monkey Test Failure in Gallery App

aosp_diff/base_aaos/packages/apps/Camera2/06_0006-Fix-JavaCrash-of-com.android.camera2.patch
It's corner case, if removed item is mViewItems[BUFFER_CENTER] and the item is last item, the item will be null and crash will happen, so we need add protection for this case.
Test: Run monkey test and observe, no crash happen.
Tracked-On: OAM-115328
=> Fix JavaCrash of com.android.camera2

aosp_diff/base_aaos/frameworks/native/0001-Add-the-support-for-Vulkan-1.3.patch
This patch will be applied to frameworks/native/ .
Currently, the vulkaninfo will show the Vulkan instance version is 1.1. Actually, our mesa implementation already supports version 1.3. This change will help to fix it.
Note,the reason I'm not using VK_API_VERSION_1_3 here is that it hasn't been defined in prebuilts/xxx/vulkan_core.h yet. In the latest AOSP code, vulkan_core.h will include this definition, this code will also be updated to use "*pApiVersion = VK_API_VERSION_1_3;" in the commit of '628c41a'.
When we upgrade to the latest AOSP version, we need to remove this patch.
Tracked-On: OAM-115564
Signed-off-by: Li,Gaoshun gaoshun.li@intel.com
=> Add the support for Vulkan 1.3

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch
This patch will upgrade the AOSP tag to r11 from r8.
Tests Done: Build and boot
Tracked-On: OAM-116549
=> Upgrade AOSP 12L tag to 12.1.0_r11

aosp_diff/preliminary/bionic/0001-Optimize-bionic-memory-functions-with-avx2-instructi.patch, aosp_diff/preliminary/bionic/0002-Optimize-bionic-string-functions-with-avx-implementa.patch, aosp_diff/preliminary/bionic/0003-avx2-implementation-for-memmove-api.patch
Port required bionic patches from Android-13
to Android-14.
- Optimize-bionic-string-functions-with-avx
- Optimize-bionic-memory-functions-with-avx2
- AVX2-implementation-for-memmove-api.patch
Tracked-On: OAM-113078
=> Port required Utils bionic patches to Android-14

aosp_diff/base_aaos/packages/apps/Gallery2/0008-Fix-JavaCarsh-on-com.android.gallery3d-when-clicking.patch
resetting history
User click the menu of resetting history, App should do nothing when there is no primary image.
Test: Run monkey test and observe, no crash happen.
Tracked-On: OAM-116645
=> Fix JavaCarsh on com.android.gallery3d when clicking the menu of

aosp_diff/base_aaos/packages/apps/Car/Launcher/0002-Fixed-for-CarLauncher-issue-during-suspend.patch
When device goes in suspend state and resume back, map place holder activity get killed.
Restart maps place holder activity, if it is not running.
Tests: adb shell; echo mem > /sys/power/state
device goes to sleep state and now press any keyboard key to wake up, Maps placeholder is blank.
Tracked-On: OAM-114651
=> Fixed for CarLauncher issue during suspend.

aosp_diff/base_aaos/frameworks/base/99_0254-Fixed-for-SystemUI-crash-during-cold-boot-cycle-test.patch
Prevent ConcurrentModificationException while accessing mListeningUris. Swapped ArrayMap with ConcurrentHashMap to allow multi-threaded access to mListeningUris.
Tests: Flash the build having this change. Device is booting. Systemui is showing normally.
Tracked-On: OAM-116766
=> Fixed for SystemUI crash during cold boot cycle test.

aosp_diff/base_aaos/packages/apps/DeskClock/0003-WA-Fix-Monkey-Test-crash-in-DeskClock.patch
Below crash was seen during MonkeyTest:
java.lang.IllegalStateException: FragmentManager
is already executing transactions
Use commitNowAllowingStateLoss instead of commitAllowingStateLoss. commitNowAllowingStateLoss executes the transaction immediately on the calling thread unlike commitAllowingStateLoss which schedules the transaction to be executed asynchronously on the main thread.
NOTE: commitNowAllowingStateLoss may potentially lead to ANR if the transaction takes a long time to execute.
Tracked-On: OAM-116600
=> WA - Fix Monkey Test crash in DeskClock

aosp_diff/base_aaos/frameworks/base/99_0256-Set-default-value-of-display-hardware-settings.patch, aosp_diff/base_aaos/packages/apps/Car/Settings/06_0006-Reset-all-display-hardware-settings-to-default-value.patch
Set default value of display hardware settings, include Hue, Contrast, Saturation, Whitebalance and Luminance.
Test: Feature funciotn is ready, test OK.
Tracked-On: OAM-116761
=> Set default value of display hardware settings

aosp_diff/preliminary/hardware/interfaces/11_0001-Enable-graphics.composer3-AIDL-HAL-service.patch
dumpsys SurfaceFlinger command is crashing system due to usage of uninitialized string variable's data address.
Fixed it by allocating memory before accessing address of string variable data.
Testdone: Verified with dumpsys and dumpsys SurfaceFlinger
No crash observed.
Tracked-On: OAM-116838
=> Fix to hwcomposer dump api

aosp_diff/base_aaos/packages/apps/Car/Settings/07_0007-Fixed-for-Coverity-issue-in-Car-Settings-app.patch
There may be null pointer exception when using volume items to create volume preference seek bar.
If volume item is null, then move to next one.
Tests: Open Settings->Sound option, Volume slider is displaying and able to slide it.
Tracked-On: OAM-115481
=> Fixed for Coverity issue in Car Settings app.

aosp_diff/base_aaos/packages/apps/Gallery2/0009-Fixed-for-issue-in-Gallery-during-monkey-test-run.patch
Observing following crash during monkey test run
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Collection.com.android.gallery3d.filtershow.pipeline .ImagePreset.getGeometryFilters()' on a null object reference
Check for null condition.
Tests: Launch Gallery app, open some image to edit.
Tracked-On: OAM-116905
=> Fixed for issue in Gallery during monkey test run.

aosp_diff/base_aaos/frameworks/av/40_0040-WA-Extended-time-to-check-for-timeout.patch, aosp_diff/base_aaos/frameworks/base/99_0257-Use-a-private-thread-to-replace-the-public-one-in-in.patch
Use a private Thread to instead of the common BackgroundThread in pm.installer, to prevent the callback handler not to be blocked by the other tasks.
Pm.installer will try to reconnect installd if necessary, but sometimes the reconnection function cannot be performed due to the callback thread, as well as BackgroundThread becomes busy.
In the corner case, audioserver and audiopolicyservice might be crashed due to the same reason in stability testing.
Tracked-On: OAM-116189
=> Refine the pm.installer reconnection about installd

aosp_diff/base_aaos/packages/apps/Car/Settings/06_0006-Reset-all-display-hardware-settings-to-default-value.patch
Reset default value for display white balance as the design doc is changed. Refer to:
https://jira.devtools.intel.com/secure/Tests.jspa#/testCase/OATV-T61955
Test: Reset to default value and check it, test OK.
Tracked-On: OAM-117067
=> Reset default value for display white balance.

bsp_diff/base_aaos/kernel/linux-intel-lts2021/0043-Handle-auto-suspend-for-btusb_sco-driver.patch
Add support for auto-suspend in btusb sco driver, so that when the driver is not busy (no Tx/Rx), it goes to suspend state. When any Tx/Rx, its back to active.
Tests done:
Check the runtime power status of BT usb during below scenario.
1. BT connection
2. BT music streaming
3. BT file transfer
4. BT call
Tracked-On: OAM-116918
=> Handle auto-suspend for btusb_sco driver

aosp_diff/base_aaos/frameworks/base/99_0259-Fix-BT-profile-initialization-by-multiple-tasks.patch
[Problem]
During stability cycle tests, below error is observed. java.lang.IllegalStateException: Task appeared more than once: #1
BT profile initiatlization done twice because of timing issue, causing FATAL exception and systemUI is crashing.
[Solution]
Make the profile initialization code synchronized, so that one task can execute at a time.
Tests done:
Flash apollo-ivi image and verify BT on/off.
Tracked-On: OAM-115576
=> Fix BT profile initialization by multiple tasks

aosp_diff/base_aaos/frameworks/base/99_0256-Update-color-transform-reboot-setting.patch
Add properties to persist and restore the display's color transform setting, upon reboot, reads values and applies to set the display color transform accordingly
Tracked-On: OAM-117073
=> Update color transform reboot setting

aosp_diff/base_aaos/frameworks/base/99_0260-Fixed-for-crashe-during-Monkey-test-run.patch
Following crash were observed
java.lang.NullPointerException: Attempt to invoke interface method 'void android.service.dreams.IDreamManager.awaken()' on a null object reference at com.android.systemui.statusbar.phone.StatusBar.lambda $awakenDreams$37(StatusBar.java:3899)
Get dream service during api runtime & also check for null condition, so during monkey test run, then it can safely handle.
Tests:
Run monkey test and observe, test is pass.
Tracked-On: OAM-117071
=> Fixed for crash during Monkey test run.

aosp_diff/base_aaos/packages/apps/Car/LocalMediaPlayer/0003-LocalMediaPlayer-fix-sound-is-still-output-when-focu.patch
Sometimes, playing audio with local media player in background, switch to video play in photos, audio and video sound will be mixed.
This is because there is contest between audio playback pause and audio playback switching to next song.
Tests done: smoke test Pass
Tracked-On: OAM-115548
=> LocalMediaPlayer: fix sound is still output when focus is lost

bsp_diff/common/kernel/lts2022-chromium/0008-ACPI-PM-Propagate-power-button-event-to-user-space-w.patch
Sometimes power button does not wake up the systemm and we get suspends event right after that. Here Android needs to see KEY_POWER at resume. Otherwise, its opportunistic suspend will kick in shortly.
However, other OS such as Ubuntu doesn't like KEY_POWER at resume. So add a knob "/sys/module/button/parameters/key_power_at_resume" for users to select.
Tests Done:
1. Check guest standalone suspend/resume with input keyevent 26
2. Use telnet qmp capabilities to wake the device so that android screen is up
Tracked-On: OAM-117467
=> ACPI/PM:Propagate power button event to user space

aosp_diff/base_aaos/frameworks/base/99_0258-Enable-AX210-and-AX201-Bluetooth-for-Android-Automot.patch
The BT chip is loaded as USB interface as hci0, the UsbHostManager
is taking control of hci0 interface and doing initialization.
Because of which Bluetooth-HAL is not able to send HCI cmds via
hci0 interface, causing the hci_timeout_abort() crash.
So BT is not enabled.
Add BT chip vendor id and product id in config deny list, so that
UsbHostManager skips the USB interface intialization for hci0.
Tests:
Open bluetooth in Settings app,
bluetooth device can be found.
Tracked-On:  OAM-118006
=> Enable AX210 and AX201 Bluetooth for Android Automotive

aosp_diff/base_aaos/system/bt/61_0061-Fix-a2dp-reconnection-issue.patch
When two reference devices are connected, switching media profile
between them is causing frequent disconnection. The BTIF AV stream
state machine is allowing incoming remote a2dp connection even
if we disconnect from DUT side.
Handle the stream close properly in all of the AV stream states
transition in BTIF.
Following commits are ported from latest Android BT codebase:
Add for fix audio track null point
Immediately disable to prevent unstable state inspection
A2DP: Only apply valid BtifAvPeer to be active
Ignore a2dp connection request in StateClosing
Tests done:
1. Build, flash and boot as BM
2. Connect 1st Pixel 3XL and see media profile is connected
3. Connect 2nd Pixel 3XL and see media profile is disconnected
4. Toggle the media profile between the pixel devices
5. 10 trails of …
=> Fix a2dp reconnection issue

aosp_diff/base_aaos/frameworks/base/99_0262-Remove-more-than-once-task-appeared-check.patch
Sometimes remove apk task, but framework did not real notify wmshell onTaskVanished success due to remoteException, if this task appeared again, should follow and grant this time appear.
Cherry-pick: https://android-review.googlesource.com/c/platform/frameworks/base/+/2929814
Tracked-On: OAM-118069
=> Remove more than once task appeared check

aosp_diff/base_aaos/hardware/interfaces/0001-Update-default-KeyMint-version-to-3.patch
Backport Google's patch to update default KeyMint version to 3 to fix vts issue.
Test Done:
run vts -m vts_treble_vintf_vendor_test
Tracked-On: OAM-118540
=> Update default KeyMint version to 3

aosp_diff/base_aaos/frameworks/base/99_0267-Fixed-crash-for-com.android.systemui-during-Monkey.patch
Following crash were observed:
java.lang.NullPointerException: Attempt to invoke interface method 'void android.service.dreams.IDreamManager.awaken()' on a null object reference at com.android.systemui.statusbar.phone.StatusBar.lambda $awakenDreams$37(StatusBar.java:3901)
Re-set mDreamManager in runtime to avoid the first null init conditon.
Tests:
Run monkey test and observe, test is pass.
Tracked-On: OAM-118790
=> Fix com.android.systemui crash during Monkey test

aosp_diff/base_aaos/packages/apps/Bluetooth/07_0007-Fix-a2dp-state-machine-java-crash.patch
Multiple threads trying to execute the a2dp state machine block, where the message is sent even before starting the state machine, resulting in FATAL exception on com.android.bluetooth.
Make the state machine block synchronized to avoid multiple threads accessing the same resource at a time.
Tests done:
1. Flash bare metal
2. Check BT on success
3. Connect Pixel
4. Toggle A2DP media profile 20 times
5. With Pixel connected, toggle BT on/off 20 times
6. No crash observed, no hang observed
7. Every time BT ON and A2DP connect success
Tracked-On: OAM-116660
=> Fix a2dp state machine java crash

aosp_diff/preliminary/build/soong/0007-Add-support-for-overide_lib_name-for-IA-perf-variant.patch, aosp_diff/preliminary/build/soong/0009-Filterout-isa-perf-libraries-from-vndk-list.patch, aosp_diff/preliminary/frameworks/av/0004-Generate-avx2-version-of-libaudioprocessing-library.patch, aosp_diff/preliminary/frameworks/av/0005-Modify-IA-Perf-variants-of-library-to-have-same-name.patch, aosp_diff/preliminary/frameworks/rs/0001-Generate-avx2-version-of-libRSCpuRef.so.patch, aosp_diff/preliminary/frameworks/rs/0002-Modify-IA-Perf-variants-of-library-to-have-same-name.patch, aosp_diff/preliminary/packages/modules/NeuralNetworks/0001-Generate-avx2-versions-of-libnueralnetworks.so.patch, aosp_diff/preliminary/packages/modules/NeuralNetworks/0002-Modify-IA-perf-variant-of-library-to-have-same-name-.patch, aosp_diff/preliminary/system/linkerconfig/02_0002-Config-changes-to-prefer-perf-variants-of-an-.so.patch
Port required One image Optimization patches from Android-12 to Android-14.
- Generate-avx2-version-of-libaudioprocessing-library
- Generate-avx2-version-of-libRSCpuRef
- Generate-avx2-versions-of-libnueralnetworks
- Modify-IA-Perf-variants-of-library-to-have-same-name
Tracked-On: OAM-113540
=> Port required Utils One image patches to Android-14

aosp_diff/preliminary/hardware/intel/wlan/libwifihal/open/0001-wifi-hal-fix-VtsHalWifiStaIfaceTargetTest-vts-test.patch
this patch can fix below vts fail:
wifi_sta_iface_->getApfPacketFilterCapabilities(&apf_caps).isOk()
Test:
after put on this patch
VtsHalWifiStaIfaceTargetTest will pass
Tracked-On: OAM-120203
=> [VTS FIX] wifi hal: fix VtsHalWifiStaIfaceTargetTest vts test

aosp_diff/preliminary/frameworks/base/53_0053-Ported-CTS-fixes-from-Google-QPR1-Release.patch
Porting below CTS fixes-
https://android-review.googlesource.com/c/platform/frameworks/base/+/2855186 https://android-review.googlesource.com/c/platform/frameworks/base/+/2855185 https://android-review.googlesource.com/c/platform/frameworks/base/+/2855166
Disable `sync_disabled_mode` in `DeviceConfigTest` runs. Fix HorizontalScrollViewFunctionsTest
Ensure that DebuggerWindow is shown on headless systems.
on headless systems, user-0 is invisible. And hence windows started by user-0 process are not visible.
Tests: Build EB is successfull and booting to home screen.
Tracked-On: OAM-120405
=> Ported CTS fixes from Google QPR1 Release.

bsp_diff/common/kernel/lts2022-chromium/0009-Enable-sco-driver-for-AX211.patch
btusb sco snd card driver is not present in caas.
Add btusb sco snd card driver to enable BT HFP call in caas.
Tests done:
1. Flash BM
2. Check btusb_sco_snd_card.ko in vendor/lib/modules
3. Check dmesg for btusb_sco driver registered
4. In adb shell #>cat proc/asound/cards, it should list btaudiosource
5. Install zoom application
6. Connect BT headset
7. Make zoom call
8. Check uplink and downlink works
Tracked-On: OAM-120501
=> Enable sco driver for AX211

bsp_diff/caas/device/intel/mixins/0001-Enable-wifi-RTT-and-NAN-features.patch
RTT and NAN features are not enabled in caas.
Enabled RTT and NAN for caas.
Tests done:
1. Flash BM
2. In adb shell #>pm list features | grep wifi
3. Verify RTT and wifi aware service is running from logcat
Tracked-On: OAM-120503
=> Enable wifi RTT and NAN features

aosp_diff/base_aaos/packages/services/Telephony/0001-Fix-java-crash-when-Bluetooth-MAP-profile-connects.patch
When Bluetooth MAP profile connects, Persistent bundle is accessed even before its being populated in the constructor resulting in ArrayIndexOutOfBoundsException.
Add a proper check for bundle initialization before querying for its configuration.
Tests done:
1. Flash Bare Metal
2. BT on success
3. Connect Pixel reference phone
4. Connect MAP
5. Disconnect/Connect MAP profile 20 times
6. No crash observed
Tracked-On: OAM-119041
=> Fix java crash when Bluetooth MAP profile connects

aosp_diff/base_aaos/packages/services/Car/0001-Enable-HID-and-OPP-profiles-for-aaos.patch
HID and OPP profiles were not enabled in car-service.
Enable HID and OPP profiles in bluetooth.prop car-service.
Tests done:
1. Flash Bare Metal
2. BT on success
3. Connect HID sony joystick
4. Hover the mouse pointer and press keys
5. Connect Pixel reference device
6. Validate Bluetooth file transfer from both side
Tracked-On: OAM-120401
=> Enable HID and OPP profiles for aaos

bsp_diff/caas/device/intel/mixins/0002-Fix-for-VtsHalLoudnessEnhancerTargetTest-Case.patch
while running the vts module following fail to push error is occurring: Attempting to push dir 'VtsHalGraphicsComposerV2_4TargetTest' to an existing device file /data/local/tmp/.
When it try to push directory, it always shows that dir already exists even if it is not there. this was checking dir using 'ls' command and check for 'No such file or directory' output. But 'ls' command was giving always 'Invalid argument' and in that case it was always returning showing dir exists. During 'ls' command syscall for 'prctrl' was assigning VMA name, but VMA feature was not enabled, so it was assigning default error code EINVAL. Enabling this feature by enabling this flag-: CONFIG_ANON_VMA_NAME
Test:
Run 'ls' command in adb shell for some file or directory which does not exists, it should give …
=> Fix for VtsHalLoudnessEnhancerTargetTest Case

aosp_diff/base_aaos/build/soong/0001-solve-pahole-is-not-allowed-to-be-used-in-build-issu.patch, bsp_diff/base_aaos/hardware/intel/kernelflinger/0055-Solve-the-32-bit-Integer-Multiplication-Overflow-Iss.patch
Call pause_us() to sleep 1S doesn't take effect, the reason is that multiply overflow
Tracked-On: OAM-121142
=> Solve the 32-bit Integer Multiplication Overflow Issue

aosp_diff/base_aaos/packages/apps/Gallery2/0010-Fixed-crash-in-Gallery-during-monkey-test-run.patch
Observed following crash during monkey test run
android.os.FileUriExposedException: file:///storage/emulated/14/Movies /MUTE_20240606_225943.mp4 exposed beyond app through Intent.getData()
Porting fix from open source-
fix b/218791647 [AOSP] Gallery app crash when press on Mute button and saving trimmed video reason for crash was an api change in sdk 24 https://developer.android.com/google/play/requirements/target-sdk fixed thi issue following https://developer.android.com/training/secure -file-sharing/setup-sharing
+ Specify file provider in manifest
+ Specify shareable directories
+ Generate uri with FileProvider
ChangeId- I34190720790e0b69d6695474461e461b9c6f61e5
Tests: Compiled and launched Gallery app successfully.
Tracked-On: OAM-120512
=> Fixed crash in Gallery during monkey test run.

aosp_diff/base_aaos/packages/modules/Bluetooth/0001-Disabling-WBS-in-the-BT-stack.patch, bsp_diff/base_aaos/vendor/intel/hardware/interfaces/0001-Add-BT-HFP-support-for-TyP2.patch
btusb_sco_snd_card not listing for AX210 card.
Add the vendor id and product id to list the sound card.
Tests done:
1. Flash BM
2. Check cat /proc/asound/cards
3. It should list btaudio sound card
Tracked-On: OAM-121421
=> Enable BT HFP for AX210 card

aosp_diff/base_aaos/packages/apps/Browser2/0001-Fix-crash-in-Webview-Browser-during-MonkeyTest.patch
Getting below crash when running monkey test:
java.lang.RuntimeException: StrictMode ThreadPolicy violation
Caused by: android.os.strictmode.UnbufferedIoViolation
Allow UnbufferedIo in StrictMode builder.
Test Dome: Boot check
Tracked-On: OAM-118786
=> Fix crash in Webview Browser during MonkeyTest

aosp_diff/base_aaos/packages/services/Car/0002-Modify-evs-HAL-API-version-to-2.patch
V2 version of evs HAL API has been used, so modify the version to 2 in the manifest files.
Test Done:
vts -m vts_treble_vintf_vendor_test
Tracked-On: OAM-122020
=> Add patch which modifies evs HAL API version to 2

bsp_diff/common/device/intel/sepolicy/0001-Add-graphics-related-sepolicy-for-hal_sensors_defaul.patch
Fix VTS sensors issues.
-DirectChannelGralloc/0_android_hardware_sensors_ISensors_default
Test Done:
run vts -m VtsAidlHalSensorsTargetTest
Tracked-On: OAM-118440
=> Add graphics related sepolicy for hal_sensors_default

aosp_diff/preliminary/frameworks/av/0007-Dynamically-disable-audio-codes.patch
Set a property in Nuplayer to dynamically disable the audio codec. In order to quickly eliminate the audio cause when video freezes occur in the future.
Tests Done
Disable audio decoding:
-setprop persist.sys.disable.audio true
-reboot
Enable audio decoding:
-setprop persist.sys.disable.audio false
-reboot
Tracked-On:OAM-116765
=> Dynamically disable audio codes

bsp_diff/common/device/intel/sepolicy/06_0001-Add-sepolicy-for-composer3-AIDL-HAL-service.patch
This is used to fix the failed case of GTS:
com.google.android.security.gts.SELinuxHostTest#testNoExemptionsForDataBetweenCoreAndVendor
Test done: testNoExemptionsForDataBetweenCoreAndVendor can pass with this patch.
Tracked-On: OAM-118907
=> Remove the data violators for hal_graphics_composer

aosp_diff/preliminary/frameworks/base/57_0057-Avoid-HIGH_ACCURACY-request-from-stationary-throttli.patch, aosp_diff/preliminary/frameworks/base/58_0058-Apply-pending-transactions-always.patch
Applying High Security patches from Google
Avoid HIGH_ACCURACY request from stationary throttling
Bug: 319054085
Apply pending transactions always
Bug: 334901521
Test Done: Build and Boot success
Basic sanity test pass successfully
Tracked-On: OAM-122204
=> Avoid HIGH_ACCURACY request from stationary throttling

aosp_diff/base_aaos/packages/apps/Car/LatinIME/0001-WA-Fixed-for-Soft-Keyboard-Color-key-size.patch
Currently soft keyboard keys are dark and not visible properly due to dark background and also key size is small.
Changed the key color and size.
Tests:
Open any Editor, it pop up soft keyboard. it has key visible poperly.
Tracked-On: OAM-121431
=> [WA] Fixed for Soft Keyboard Color & key size.

bsp_diff/caas/hardware/intel/external/minigbm-intel/0001-Fix-android-boot-issue-in-SRIOV-mode.patch, bsp_diff/caas/kernel/linux-intel-lts2022/0001-Revert-Fix-CtsDeqpTestCases-test-failures.patch
Reverted kernel and minigbm patches that causes
android boot issue in SRIOV mode.
Tests done:
- caas boot in GVT-d and SRIOV mode
- aaos boot in GVT-d and SRIOV mode
- dGPU GVT-d boot
- Wi-Fi, Bluetooth on/off/connect/disconnect
- adb reboot
- adb remount
- CtsDeqpTestCases with 0 failures in GVT-d mode
Tracked-On: OAM-117334
=> Fix android boot issue in SRIOV mode

aosp_diff/preliminary/packages/apps/Car/LocalMediaPlayer/0001-Add-some-permissions-for-Local-Media-Player.patch
Local Media Player can't play audio and videos as the app has not some permissions, add them to fix the issues.
Test: Open Local Media Player and play audio and video files.
Tracked-On: OAM-122382
=> Add some permissions for Local Media Player

bsp_diff/aaos_iasw/hardware/intel/kernelflinger/0056-Fix-Resource-leaks-and-Uninitialized-pointer-reads.patch, bsp_diff/aaos_iasw/hardware/intel/kernelflinger/0057-Fix-Resource-leaks-and-32-bit-time_t-usage.patch, bsp_diff/aaos_iasw/hardware/intel/kernelflinger/0058-Fix-Out-of-bounds-access-and-32-bit-time_t.patch
Port coverity related patches from base_aaos to aaos_iasw, which solved resource leaks, uninitialized pointer reads, 32-bit time_t usage and Out-of-bounds access.
Tracked-On: OAM-122919
=> Fix Coverity high impact issues under kernelflinger component

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/base_aaos/frameworks/av/40_0040-libmediatranscoding-handle-death-recipient-cookie-ownership-dif.bulletin.patch, aosp_diff/base_aaos/frameworks/av/41_0041-StagefrightRecoder-Disabling-B-frame-support.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0282-Fix-error-handling-for-non-dynamic-permissions.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0283-Fix-security-vulnerability-of-non-dynamic-permission-removal.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0284-RESTRICT-AUTOMERGE-Backport-preventing-BAL-bypass-via-bound-serv.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0285-Rate-limiting-PiP-aspect-ratio-change-request.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0286-Restrict-USB-poups-while-setup-is-in-progress.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0287-Add-the-protection-to-avoid-data-overflow-in-BinaryXmlSerializer.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0288-Hide-SAW-subwindows.bulletin.patch, aosp_diff/base_aaos/hardware/interfaces/13_0013-Keep-track-of-DeathMonitor-cookies.bulletin.patch, aosp_diff/base_aaos/system/bt/59_0059-Fix-heap-buffer-overflow-in-sdp_utils-cc.bulletin.patch
Test done: STS r29 TCs Passed.
Tracked-On: OAM-122527
=> ASB-Aug 2024 Security Patches integration

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/0031-libmediatranscoding-handle-death-recipient-cookie-ownership-dif.bulletin.patch, aosp_diff/preliminary/frameworks/av/0032-StagefrightRecoder-Disabling-B-frame-support.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0200-Fix-error-handling-for-non-dynamic-permissions.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0201-Fix-security-vulnerability-of-non-dynamic-permission-removal.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0202-RESTRICT-AUTOMERGE-Backport-preventing-BAL-bypass-via-bound-serv.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0203-Rate-limiting-PiP-aspect-ratio-change-request.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0204-Restrict-USB-poups-while-setup-is-in-progress.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0205-Add-the-protection-to-avoid-data-overflow-in-BinaryXmlSerializer.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0206-Hide-SAW-subwindows.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0207-RESTRICT-AUTOMERGE-Fix-READ-WRITE-operation-access-issues-on-Res.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0208-Security-fix-for-VPN-app-killable-via-lockscreen-.bulletin.patch, aosp_diff/preliminary/hardware/interfaces/12_0012-Use-onUnlinked-in-health-HAL.bulletin.patch, aosp_diff/preliminary/hardware/interfaces/13_0013-Keep-track-of-DeathMonitor-cookies.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/58_0058-Fix-heap-buffer-overflow-in-sdp_utils-cc.bulletin.patch
Test done: STS r29 TCs Passed.
Tracked-On: OAM-122613
=> ASB-August 2024 Security Patches integration

bsp_diff/aaos_iasw/hardware/intel/kernelflinger/0059-Fix-Coverity-very-high-issue-with-medium-impact.patch, bsp_diff/base_aaos/hardware/intel/kernelflinger/0059-Fix-Coverity-very-high-issue-with-medium-impact.patch
Solved static scanned issues including unintentional integer overflow, wrong sizeof argument, Dereference before null check and explicit null dereferenced.
Tracked-On: OAM-122933
=> Fix Coverity very high issue with medium impact

bsp_diff/caas/device/intel/mixins/0004-Remove-32bit-support-in-AOSP14.patch
This patch will remove support for 32bit from the apilist
Tests Done: #getprop | grep abilist
This should not show 32bit support
Tracked-On: OAM-118704
=> Removing support for 32bit since Android removed it

bsp_diff/caas/device/intel/mixins/0005-Remove-omx-interface-in-AAOS14.patch, bsp_diff/caas/vendor/intel/mediasdk_c2/0001-Make-c2-service-64bit.patch
Remove obsolete omx interface declaration in manifest file
Test Done: Build and boot successfully.
sdcard file pushing supporting.
Tracked-On: OAM-123433
=> AAOS14 does not support 32bit any more. So change hwcodec2.0 to 64bit.

aosp_diff/preliminary/frameworks/av/0009-By-default-disable-HDR-support-for-VP9-codec.patch
Currently VP9 HDR is not supported in mediasdk_c2, but in framework VP9 HDR is set to supported by default and caused some cts tests run failed.
Will need to revert this patch when VP9 HDR support is added in mediasdk_c2.
Tracked-On: OAM-122909
=> Disable VP9 HDR support by default

aosp_diff/aaos_iasw/packages/services/BuiltInPrintService/0001-Skip-print-job-if-print-feature-is-not-defined.patch
System doesn't enabel the feature "android.software.print", so we skip the print job.
Test: run monkey test, no crash happen
Tracked-On: OAM-123126
=> Skip print job if print feature is not defined

aosp_diff/aaos_iasw/packages/modules/Bluetooth/0001-Disabling-WBS-in-the-BT-stack.patch, bsp_diff/aaos_iasw/vendor/intel/hardware/interfaces/0001-Add-BT-HFP-support-for-TyP2.patch
changes:
- Add AX210 intel controller
- Support only NB
Tracked-On: OAM-123206
=> Enable BT-HFP AX210

aosp_diff/base_aaos/packages/modules/Bluetooth/0002-Fix-metadata-issue-when-reconnect-pixel.patch
When reconnecting pixel some times metadata is not synced. bt-stack issuing two AVRC browse channel, one as acceptor, other as initator, which is causing collision in lcid and resulting in l2cap disconnection of avrc browse channel, resulting in metadata sync issue.
Don't initiate avrc browse channel as initiator, open only as acceptor. Now browse channel is always success and metadata is seen everytime.
Tests-done:
1. Flash BM
2. Connect Pixel
3. Play Music and do adb reboot
4. Everytime the metadata should sync on home screen
5. Trail 20 times
Tracked-On: OAM-123252
=> Fix metadata issue when reconnect pixel

aosp_diff/base_aaos/hardware/interfaces/0001-Allow-modification-of-Vehicle-HAL-properties.patch
- When "persist.vendor.emulate.vehiclehal" is set to false, the code checks the access permissions. If the property does not have write access, it returns an ACCESS_DENIED status.
- When persist.vendor.emulate.vehiclehal is set to true, the code allows writing to Vehicle HAL properties.
Test
Ex: adb shell setprop persist.vendor.emulate.vehiclehal true dumpsys car_service set-property-value <prop-Id> <area Id> value. dumpsys car_service set-property-value 0x11400400 0x11400400 4
Tracked-On: OAM-123892
=> Allow modification of Vehicle HAL properties.

aosp_diff/preliminary/hardware/interfaces/15_0015-Fix-for-coverity-issue-for-memtrack_module.patch
The memtrack_module variable was going out of scope and function was exiting without freeing it. Free memtrack_module if return nullptr.
Tests Done: Build and boot.
Tracked-On: OAM-122303
=> Fix for coverity issue for memtrack_module

aosp_diff/aaos_iasw/packages/apps/Car/LocalMediaPlayer/0001-Fix-error-when-playback-can-t-be-resumed-on-LocalMed.patch
Do not check permission during playback every time, permissions have been checked when APP start, and system don't pregrant some permissions for LocalMediaPlayer, can't resume playback if the permission check failed.
Test: play music on LocalMediaPlayer then pause and resume.
Tracked-On: OAM-123021
=> Fix error when playback can't be resumed on LocalMediaPlayer

vendorsetup.sh
This patch will set the TARGET_RELEASE version and enable lunch menu options list.
TARGET_RELEASE needs to be updated based on new AOSP updates.
Tracked-On: OAM-121983
=> Enable Displaying lunch menu for A15

bsp_diff/common/device/intel/sepolicy/0002-fix-for-OTA-update-through-script-failure.patch
OTA update was failing due to sepolicy permission denial. 
Added file context for vendor_boot_a|b partition.
Tests done: Run command ./update_device.py caas-ota-CR0000094.zip
Tracked-On: OAM-124799
=> fix for OTA update through script failure

aosp_diff/aaos_iasw/packages/services/Car/0002-Post-power-state-listener-broadcast-calls-to-handler.patch
Handle power state listener broadcasts on a separate thread to prevent more than one broadcast being active at one time.
Bug: 323603048
Bug: 323603043
Test: atest CarPowerManagementServiceUnitTest
Tracked-On: OAM-124540
=> Post power state listener broadcast calls to handler

bsp_diff/base_aaos/device/intel/mixins/0003-Add-test-kernel-module-for-system-and-odm-DLKM-parti.patch
The vts_dlkm_partition_test vts test case will check if
“/<system/odm>/lib/modules” is a symlink to
“/<system/odm>_dlkm/lib/modules. If there is no module
in the partition, symlink will not be created.
So this is a WA patch to pass the VTS. The WA patch can be removed if enable GKI on X86 platform.
Test Done:
Boot
vts_dlkm_partition_test
Tracked-On: OAM-118469
=> Add test kernel module for system and odm DLKM partition

aosp_diff/base_aaos/frameworks/base/100_Fix-method-not-found-for-NotProvisionedException-hidden-api.patch
The patch was ported from google to fix the error
(:Missing patch https://r.android.com/2770659 ) of ats case wvts.MediaDrmParameterizedTests#testInvalidDrmDeviceCertResponse[L3]
Tests done:
Running testInvalidDrmDeviceCertResponse[L3] case
Tracked-On: OAM-119851
=> Fix method not found for NotProvisionedException hidden api

aosp_diff/preliminary/packages/modules/Bluetooth/0012-Trigger-RNR-during-reconnect-and-BT-power-cycle.patch
Changes made to the remote reference device (Pixel) Bluetooth name do not update in DUT's BT settings. Remote Name Request(RNR) is not issued during reference device reconnect or BT on/off. So the updated name is not fetched from reference device.
Issue RNR from bt-stack during device reconnection and BT power cycle. And handle the RNR response, update the latest name in NVRAM and notify the same to JNI.
Tests done:
1. Boot Android
2. Pair reference device (Pixel) with DUT
3. Modify reference device name (Pixel 123)
4. Observe the latest name reflected on DUT (Pixel 123)
5. Modify reference device name (Pixel 123456)
6. Observe the latest name reflected on DUT (Pixel 123456)
Tracked-On: OAM-123706
=> Trigger RNR during reconnect and BT power cycle

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/base_aaos/frameworks/base/99_0291-Fail-parseUri-if-end-is-missing.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0292-Update-AccountManagerService-checkKeyIntent-.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0293-Prevent-Sharing-when-FRP-enforcement-is-in-effect.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0294-RESTRICT-AUTOMERGE-Check-whether-installerPackageName-contains.bulletin.patch, aosp_diff/base_aaos/libcore/02_0002-Do-not-accept-zip-files-with-invalid-headers-.bulletin.patch, aosp_diff/base_aaos/packages/apps/Settings/42_0042-RESTRICT-AUTOMERGE-FRP-bypass-defense-in-App-battery-usage-page.bulletin.patch
Test done: STS r31 TCs Passed.
Tracked-On: OAM-125586
=> ASB-OCT 2024 Security Patches integration

aosp_diff/base_aaos/packages/apps/Car/SystemUI/0001-Fixed-for-SystemUI-crash-in-Passenger-Display.patch
In concurrent multi-user mode, SystemUI crash has seen for passenger display. It was crashing due to missing audio configuration for passenger zone.
If audio configuartion is not present for any of zone, then it should always use PRIMARY_AUDIO_ZONE.
Tests: Enabled concurrent multi-user feature and passenger display is working fine. it is showing system ui components.
Tracked-On: OAM-126129
=> Fixed for SystemUI crash in Passenger Display.

aosp_diff/aaos_iasw/frameworks/native/0001-WA-Fix-error-on-joystick-operation.patch
The event of joystick will be actived on the foucus window, it is only related with display ID, but is not related with user, so force to enable it on main display.
Tracked-On: OAM-125665
=> [WA]Fix error on joystick operation

aosp_diff/aaos_iasw/packages/apps/Gallery2/0002-Fix-error-of-setting-new-action-bar-in-Gallery-app.patch
When try to crop or edit the image in gallery app, sometime app is crashing as it try to set new action bar which already has an action bar.
Check for action bar before creating new action bar.
Tests:
Launch Gallery app and try to edit/crop image and it should work fine.
Tracked-On: OAM-125981
=> Fix error of setting new action bar in Gallery app.

aosp_diff/preliminary/frameworks/base/73_0073-Enable-capture-capapbilities.patch, aosp_diff/preliminary/packages/services/Car/0001-Enable-capture-capapbilities.patch
This patch adds permission of capture audio output, which is required by echo-reference device to capture output for looopback purpose.
Tracked-On: OAM-126457
=> Enable capture capabilities

aosp_diff/caas/include_preliminary, bsp_diff/caas/include_common
This patch will add comments explaining what will happen if we add include_common and include_preliminary files in a build target folder.
Tests Done: source and lunch
Tracked-On: OAM-126841
=> Add comment explaining the use of include_** files.

aosp_diff/preliminary/packages/apps/QuickSearchBox/0001-Fixed-for-crash-in-QuickSearchBox.patch
Observed NullPointerException in QuickSearchBox app Caused by: java.lang.NullPointerException
at com.android.quicksearchbox.ui.SuggestionsAdapterBase .getSuggestions(SuggestionsAdapterBase.kt:63)
at com.android.quicksearchbox.ui.DelayingSuggestionsAdapter .getSuggestions(DelayingSuggestionsAdapter.kt:98)
Removing null assert condition as it is already handled by further null check condition.
Tests: Launch QuickSearchBox app and type something in search box. Press Home button. There is no crash.
Tracked-On: OAM-126864
=> Fixed for crash in QuickSearchBox.

aosp_diff/preliminary/art/0004-Implement-AVX2-instructions-in-x64-assembler.patch, aosp_diff/preliminary/art/0005-Introduce-the-notion-of-vector-registers.patch, aosp_diff/preliminary/art/0006-Implement-AVX2-based-Vectorization-for-x86_64.patch
This patch includes-
-Implement-AVX2-instructions-in-x64-assembler
-Introduce-the-notion-of-vector-registers
-Implement-AVX2-based-Vectorization-for-x86_64
Observed significant gains in tests:
JBench - 19%
SpecJVM (scimark.lu.small) - 35%
(scimark.lu.large) - 19%
Test done: Build and boot is fine, Run the benchmarks suite.
Tracked-On: OAM-126116
=> Port art avx2 patches to A15

aosp_diff/caas/hardware/interfaces/0001-ExternalCameraHAL-Fix-incorrect-nullptr-check-on-buf.patch
Incorrect bufPtr nullptr check caused "null pointer dereference" error during video record stop. Fix to check nullptr on bufPtr without dererencing it.
Tracked-On: OAM-123571
=> ExternalCameraHAL: Fix incorrect nullptr check on bufPtr

aosp_diff/caas/hardware/interfaces/0002-Change-Lens-Facing-to-External-for-External-Camera-H.patch, aosp_diff/caas/packages/apps/Camera2/0001-WA-Reorder-Preference-Screen-in-Settings-Activity.patch
1)First Preference Screen in CameraSettingsActivity is not getting displayed.
Reordered the Preference Screen to display the Resolution Screen.
Tracked-On: OAM-127026
2)Change Lens Position to External for External Camera HAL
Changed the Lens Position metadata from Back to External for External Camera HAL
Tracked-On: OAM-127055
=> WA for Resolution Screen Not Displayed

aosp_diff/aaos_iasw/packages/services/Car/0003-Fix-JavaCrash-of-android.car.usb.handler.patch
Monkey test open two tasks of android.car.usb.handler at the same time, they use one sqlite database, one task has been destoried, database is closed meanwhile other task is using the database, so crash happen, add instance count to check if database is used.
TEST: run monkey test, no crash happen.
Tracked-On: OAM-116601
=> Fix JavaCrash of android.car.usb.handler

aosp_diff/base_aaos/packages/apps/Car/DialerPrebuilt/0001-Add-run-time-permissions-for-CarDialer-application.patch
Grant the runtime permissions of CarDialerApp by default to display dialer context in dialer app with Bluetooth connected: android.permission.READ_CALL_LOG
android.permission.WRITE_CALL_LOG
android.permission.READ_PHONE_STATE
android.permission.CALL_PHONE
android.permission.SEND_SMS
Tests done: PBAP contact sync
1.Enable Bluetooth and connect to mobile.
2.Open dialer application
3.Check for the contacts are able to sync.
Tracked-On: OAM-127645
=> Add run time permissions for CarDialer application

aosp_diff/aaos_iasw/packages/apps/Gallery2/0003-Fix-CursorIndexOutOfBoundsException-on-com.android.g.patch
Media file is not exist on some pathes, so the cursor of the path is not null but the size is zero, so need check both.
Tracked-On: OAM-126618
=> Fix CursorIndexOutOfBoundsException on com.android.gallery3d

aosp_diff/base_aaos/packages/apps/Car/Settings/0001-Fix-for-improper-text-alignment-in-bluetooth-rename-.patch
The default font size for this dialog box is 32.0 which causes the text to become cropped.
Fixed by reducing the font size by 6.0 units to fit the Text field properly
Tracked-On: OAM-127240
=> Fix for improper text alignment in bluetooth rename dialogbox

aosp_diff/aaos_iasw/frameworks/native/0002-Fix-error-on-joystick-operation.patch
The event of joystick will be actived on the foucus window, it is only related with display ID, but is not related with user, so force to enable it on main display.
Tracked-On: OAM-127719
=> Fix error on joystick operation

aosp_diff/preliminary/packages/apps/Camera2/05_0005-Apply-Window-Insets-for-MainCameraActivity.patch
Window Insets were not applied to MainCameraActivity Leading to Delete Button in FilmStripBottomControls being not displayed on the screen
Applied Padding to MainActivityLayout acccording to the windowinsets
Tracked-On: OAM-127727
Signed-off-by : NaveenVenturi1203 <venturi.naveen@intel.com>
=> Apply WindowInsets for MainCameraActivity

aosp_diff/aaos_iasw/packages/services/Car/0004-Increase-carpowerpolicyd-connecting-to-VHAL-timeout.patch
cherry-pick a fix from aosp.
Tracked-On: OAM-128121
=> Increase carpowerpolicyd connecting to VHAL timeout

aosp_diff/aaos_iasw/packages/apps/Gallery2/0003-Fix-javacrash-of-com.android.gallery3d-on-a-null-obj.patch
Galley will copy old image set when it shows presentation again, and it initializes new image set according old set, it will crash when the old set is null, so check it before copy.
Tracked-On: OAM-127639
=> Fix javacrash of com.android.gallery3d on a null object reference

bsp_diff/common/kernel/lts2023-chromium/0001-PATCH-ACPI-PM-Propagate-power-button-event.patch
Propagate power button event to user space when
device wakes up. Sometimes power button does not
wake up the systemm and we get suspends event
right after that.
Here Android needs to see KEY_POWER at resume.
Otherwise, its opportunistic suspend will kick in shortly.
However, other OS such as Ubuntu doesn't like KEY_POWER at resume. So add a knob "/sys/module/button/parameters/key_power_at_resume" for users to select.
Tests Done: Suspend resume Functionality on Baremetal
Tracked-On: OAM-128221
=> [PATCH] ACPI/PM: Propagate power button event

bsp_diff/caas/hardware/interfaces/0006-Enable-HDMI-audio.patch
This patch adds changes to enable HDMI audio in A15 and also fallabck to Dummy when no HDMI device
connected.
Tracked-On: OAM-127579
=> Enable HDMI audio

aosp_diff/aaos_iasw/packages/apps/Car/Launcher/0001-Fix-duplicated-app-icons-on-Car-Launcher.patch
Some apps include media service, Car Launcher will draw app icon twice if it isn't defined on
packages/apps/Car/libs/car-media-common/res/values/config.xml, and remove duplicated icons on availableActivities.
Tracked-On: OAM-128342
=> Fix duplicated app icons on Car Launcher

aosp_diff/aaos_iasw/packages/services/Car/0005-Remove-duplicated-icons-on-second-home-launcher.patch
AppEntrys from PackageManagerService may be duplicated, then launcher will display duplicated icons, so remove it before it displays.
Tracked-On: OAM-128330
=> Remove duplicated icons on second home launcher

aosp_diff/base_aaos/packages/modules/Bluetooth/0002-Enable-NBS-as-sco-driver-supports-it.patch
BT USB SCO driver does not support WBS, resulting in HFP sco call not heard on remote side.
Disable WBS and enable NBS. Now call audio heard on both side.
Tests done:
1. Connect BT headset
2. Install MS teams
3. #>cat proc/asound/cards
4. Check btaudio_source sound card listed
5. #>tinycap /data/caputre.dump -D 1 -d 0 -c 1 -r 8000
6. #>tinyplay /data/playback.dump -D 1 -d 0 -c 1 -r 8000
7. Validate the audio heard on both side
Tracked-On: OAM-129007
=> Enable NBS as sco driver supports it

aosp_diff/aaos_iasw/packages/apps/DeskClock/0001-Fixed-crash-in-DeskClock-during-monkey-test.patch
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter event at com.android.deskclock.LabelDialogFragment$ImeDoneListener.onEditorAction(Unknown Source:7)
event parameter is currently declared as non null. it can be null also, So declaring it as null parameter.
Tracked-On: OAM-128844
=> Fixed crash in DeskClock during monkey test.

aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/giflib/0001-Fix-potential-overflow-when-calculating-ImageSize.bulletin.patch, aosp_diff/preliminary/frameworks/base/82_0082-RingtoneManager-allow-video-ringtone-URI.patch, aosp_diff/preliminary/frameworks/base/83_0083-enforce-limits-for-VisualVoicemailSmsFilterSettings-properties.bulletin.patch, aosp_diff/preliminary/frameworks/base/84_0084-Fix-allowlist-token-issues.patch, aosp_diff/preliminary/frameworks/base/85_0085-Update-checkKeyIntent.bulletin.patch, aosp_diff/preliminary/frameworks/base/86_0086-Always-show-all-approved-apps.bulletin.patch, aosp_diff/preliminary/frameworks/base/86_0086-Pass-SafeActivityOptions-with-actual-caller-for-startActivityInT.bulletin.patch, aosp_diff/preliminary/frameworks/libs/net/0001-Handle-v4-mapped-v6-address-in-Struct-parsing.bulletin.patch, aosp_diff/preliminary/frameworks/libs/net/0002-Add-util-method-to-generate-IPv4-mapped-IPv6-address-from-IPv4-a.bulletin.patch, aosp_diff/preliminary/frameworks/native/08_0008-binder-fix-FD-handling-in-continueWrite.bulletin.patch, aosp_diff/preliminary/frameworks/native/09_0009-libbinder-Parcel-grow-rejects-large-data-pos.bulletin.patch, aosp_diff/preliminary/frameworks/native/10_0010-libbinder-Parcel-validate-read-data-before-write.bulletin.patch, aosp_diff/preliminary/packages/apps/DocumentsUI/0001-Prevent-clickjacking-attack-in-DocsUi-.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/21_0021--CDM-NLS-Check-if-the-NLS-service-has-an-intent-filter.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/22_0022-Disable-factory-reset-in-DSU-mode.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0018-RESTRICT-AUTOMERGE-Disallow-unexpected-incoming-HID-connections.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0019-Resolve-incomplete-fix-for-SMP-authentication-bypass.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0001-netd-bpf-implement-ingress-discard-based-on-dstip-ifindex-.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0002-Add-java-class-for-Ingress-discard-bpf-map-key-value.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0003-Add-methods-for-updating-ingressDiscardRule-bpf-map-to-BpfNetMap.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0004-Drop-packets-to-VPN-address-ingressing-via-non-VPN-interface.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0005-Skip-adding-ingress-discard-rule-to-legacy-VPN.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0006-Skip-adding-ingress-discard-rule-to-OEM-VPN.bulletin.patch, aosp_diff/preliminary/packages/modules/Permission/0002-Fix-Dynamic-Permission-group-auto-grant-behaivor.bulletin.patch, aosp_diff/preliminary/packages/services/Telephony/04_0004-enforce-the-calling-package-is-the-default-dialer-for-VisualVoic.bulletin.patch
Test done: STS r34 TCs Passed.
Tracked-On: OAM-128964
=> ASB JAN 2025 Security Patches integration

aosp_diff/preliminary/frameworks/base/74_0074-Check-more-URIs-in-notifications.patch
This is cherry-picked from Andriod ASB, it's used to resolve CVE_2024_43084.
Tracked-On: OAM-128987
=> Add visitUri method to Person and MessagingStyle.Message

aosp_diff/aaos_iasw/packages/apps/Camera2/0001-Fix-NullPointerException-of-com.android.camera2.patch
App will fill the removed item by left shift, but some items maybe invalid, so check the itme before filling, and protect the item when it is set Visibility.
Tracked-On: OAM-129043
=> Fix NullPointerException of com.android.camera2

aosp_diff/preliminary/packages/modules/NetworkStack/0001-Fix-for-Android-15-Ip-Provisioning-Failure.patch
In Android 15, Wifi is not working due to ip provisioning failure. This is because of DHCP Accept packet being filtered out by DhcpFilter from jni level.
By checking the DHCP handling logic from Android 14, which does not include the problematic macros, we found that one of the macro had wrong jump statement. Now, DHCP accept packets are not filtered and can reach the router.
Tests Done:
1. Boot android image for both caas and base_aaos with this change
2. Go to settings and Connect to Wifi from router and from Mobile Hotspot
3. Wifi Connects Succesfully
Tracked-On: OAM-129211
=> Fix for Android 15 Ip Provisioning Failure

aosp_diff/preliminary/external/angle/0001-Vulkan-Don-t-require-renderability-in-AHBs.patch, aosp_diff/preliminary/external/angle/0002-Vulkan-populate-ycbcr-conversionDesc-for-yuv-VkForma.patch, aosp_diff/preliminary/frameworks/base/0001-HWUI-Fallback-to-Medium-priority-when-high-is-not-pe.patch
This set of patches fix the visual artifacts seen in the System UI when Angle is used as the primary OpenGL ES driver with vulkan as the backend renderer. This also fix the crash seen while running video playback with Angle enabled.
Tests done:
- Android boot with Angle and vulkan as backend
- System UI is working correctly without any artifacts
- Video playback working correctly
- No visual artifacts seen in the Gallery App
Tracked-On: OAM-126014
=> Add support for angle as the OpenGL ES driver

aosp_diff/aaos_iasw/packages/apps/Gallery2/0006-Fix-IllegalStateException-issue-on-gallery-app.patch
After activity onSaveInstanceState, can't commit Fragment task as we should not change the fragment status, use commitAllowingStateLoss to avoid the limitation.
Tracked-On: OAM-128556
=> Fix IllegalStateException issue on gallery app

aosp_diff/aaos_iasw/packages/apps/Camera2/0002-Fix-arithmeticException-crash-of-com.android.camera2.patch
Preview video with camera, app will animate bar to a single stop button, but the canvas of button does not exist or not intialized, ignore animation action.
Tracked-On: OAM-129041
=> Fix arithmeticException crash of com.android.camera2

aosp_diff/aaos_iasw/packages/apps/Gallery2/0007-Fix-NullPointerException-of-com.android.gallery3d.patch
Activity has been resumed but the FrameLayout is not saved, so app will crash when it opens again, so save the framelayout and add portection before it is used.
Tracked-On: OAM-128558
=> Fix NullPointerException of com.android.gallery3d

aosp_diff/preliminary/frameworks/base/0021-Revert-Cleanup-always_persist_do.patch
DevicePolicyManagerTest tests were failing with below error:
E TestRunner: java.lang.NoSuchMethodError: No static method
alwaysPersistDo()Z in class Landroid/app/admin/flags/Flags;
or its super classes (declaration of 'android.app.admin.flags.Flags'
appears in /system/framework/framework.jar)
Tests Done: atest FrameworksServicesTests:DevicePolicyManagerTest
Tracked-On: OAM-129869
=> Fix failures in DevicePolicyManagerTest

aosp_diff/preliminary/packages/apps/Camera2/06_0006-Prevent-Activity-Restart-on-Keyboard-Connection.patch
Camera Activity restarting on keyboard connection leading to camera preview on/off, Android treats keyboard
connection/disconnection as configuration change.
Added Keyboard Config Changes in AndroidManifest to ignore keyboard connection/disconnection events
Tracked-On: OAM-127079
=> Prevent Activity Restart on Keyboard Connection

aosp_diff/base_aaos/external/thermal_daemon/0001-Fix-static-analysis-issues-for-thermal-daemon.patch
and deprecate KBL support.
Below issues will be solved with this change.
+------------------------------------+
|Unchecked return value from library |
+------------------------------------+
KBL is not supported anymore, therefore deprecating.
Tracked-On: OAM-129601
=> Fix static analysis issues for thermal daemon

aosp_diff/preliminary/art/0007-Don-t-bind-mount-optional-partitions-if-they-don-t-e.patch
This patch fix failure of cts test
android.compilation.cts.PreRebootDexoptTest
Test done: run cts -m CtsCompilationTestCases -t android.compilation.cts.PreRebootDexoptTest#test
Tracked-On: OAM-127863
=> Fix PreRebootDexoptTest Failure

aosp_diff/preliminary/bootable/recovery/04_0004-Refine-udisk-mount-function.patch
An udisk device name in android may be sda/sda1/sda2, sdb/sdb1/sdb2, or sdc/sdc1/sdc2 etc. But currently only udisk devices whose name are sda1/sdb1 can be mounted, this result in the udisk devices whose name are not sda1/sdb1 cannot be recognized by recovery UI.
Add mount function in recovery handle as many udisk devices as possible, and support both ext4 and vfat simultaneously.
Tracked-On: OAM-130565
=> Refine udisk mount function in recovery

aosp_diff/preliminary/bootable/recovery/04_0004-Refine-udisk-mount-function.patch
An udisk device name in android may be sda/sda1/sda2, sdb/sdb1/sdb2, or sdc/sdc1/sdc2 etc. But currently only udisk devices whose name are sda1/sdb1 can be mounted, this result in the udisk devices whose name are not sda1/sdb1 cannot be recognized by recovery UI.
Add mount function in recovery handle as many udisk devices as possible, and support both ext4 and vfat simultaneously.
Tracked-On: OAM-130558
=> Refine the udisk mount function in recovery

aosp_diff/base_aaos/packages/apps/Car/Settings/07_0007-Fix-apps-being-able-to-turn-on-bluetooth-scanning.patch
Any apps can get Bluetooth device picker activity and enable always discoverable and connectable scanning, which is vulnerable as anyone can connect to it.
Fixes CVE_2022_20429 vulnerability issue by allowing only settings and system UI packages to turn on always discoverable BT scanning.
Cherry picked from
https://cs.android.com/android/_/android/platform/packages/apps/Car/Settings/+/7adb8ff6d30a1ab8f83c7b1fbddf04d76cfd9642
Tests-done:
1. Flash AAOS
2. BT on success
3. run android.security.cts.CVE_2022_20429.CVE_2022_20429#testPocCVE_2022_20429
4. Test pass
Tracked-On: OAM-130677
=> Fix apps being able to turn on bluetooth scanning

aosp_diff/preliminary/frameworks/base/0028-Ensure-device_owners2.xml-is-always-written.patch
Ensure that the device_owners2.xml is always written. 
cherry picked from: https://android.googlesource.com/platform/ \ frameworks/base/+/688e5c3012eb0a4ea88361588cf5026c10e4a42
Test Done: STS Test passed (module: StsHostTestCases,
Test: android.security.sts.CVE_2024_34742#testPocCVE_2024_34742)
Tracked-On: OAM-130275
=> Fixing the STS failure related to CVE-2024_34742

bsp_diff/caas/hardware/intel/kernelflinger/0002-WA-Set-device-to-unlocked-state-to-enable-BM-user.patch
This patch will disable flashing lock check for USER build since Trusty and TPM is disabled.
Tests Done: Build and boot USER BM image
Tracked-On: OAM-127732
=> WA-Set device to unlocked state to enable BM user

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/dng_sdk/0001-Catch-null-HuffmanTables-when-decoding-jpeg.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0304-Restrict-access-to-directories.patch, aosp_diff/preliminary/frameworks/base/99_0305-DO-NOT-MERGE-Hide-Android-data-obb-sanbox-on-shared-.patch, aosp_diff/preliminary/frameworks/base/99_0306-Resolve-cross-account-user-icon-validation-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0308-Check-account-type-returned-by-AbstractAccountAuthenticator-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0309-RESTRICT-AUTOMERGE-PM-Fix-the-profile-issue-in-UninstallerActi.bulletin.patch, aosp_diff/preliminary/frameworks/native/24_00240001-servicemanager-set-consistent-flags-for-self-reg.bulletin.patch, aosp_diff/preliminary/packages/apps/Bluetooth/07_0007-backport-opp-validate-that-content-uri-belongs-to-current-user.bulletin.patch, aosp_diff/preliminary/packages/apps/Bluetooth/08_0008-Reset-permissions-for-not-bonded-device.bulletin.patch, aosp_diff/preliminary/packages/providers/DownloadProvider/0004-Ensure-ownership-validation-in-downloadprovider-insert-method.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/16_0016-Resolve-cross-account-user-icon-validation-.bulletin.patch, aosp_diff/preliminary/system/bt/68_0068-Prevent-use-after-free-of-HID-reports.patch, aosp_diff/preliminary/system/bt/69_0069-Use-encrypted-link-for-avdtp-and-avctp-channels.bulletin.patch
Integrating Google Android Security Bulletin Patches.
Test done: STS r36 All TCs Passed except
2 TCs failed as Kernel LTS Update required,
Test:
KernelLts Test#testRequiredKernelLts_ENFORCING
KernelLts Test#testRequiredKernelLts_WARN
Tracked-On: OAM-130583
=> ASB MAR 2025 Security Patches integration

aosp_diff/aaos_iasw/packages/apps/Car/Notification/0001-Disable-notification-heads-up-on-automotive-platform.patch
Heads up notification always pops up when the app receive notification broadcast. It will influence the driver, so we disable it.
Tracked-On: OAM-131383
=> Disable notification heads up on automotive platform

aosp_diff/aaos_iasw/packages/apps/Car/Notification/0001-Add-property-to-disable-notification-heads-up-on-aut.patch
Heads up notification always pops up when the app receive notification broadcast. It will influence the driver, so we disable it. Add property "persist.disable.notification.headsup" to control heads up notification, when the property set to true, notification will be disabled.
Tracked-On: OAM-131570
=> Add property to disable notification heads up on automotive platform

aosp_diff/base_aaos/packages/apps/Car/Settings/0001-Fix-for-improper-text-alignment-in-bluetooth-rename-.patch
The default font size for the Bluetooth rename dialog box causes the text to become cropped.
This issue is resolved by reducing the font size to BLUETOOTH_DEFAULT_TEXT_SIZE, if the font size is more than the default size
Test Done:
1. Boot the device with changes.
2. Go to Settings.
3. Navigate to Bluetooth.
4. Rename the device name.
5. Verify that the text is not cropped.
Tracked-On: OAM-130987
=> Fix for improper text alignment in bluetooth rename dialog box

aosp_diff/preliminary/frameworks/av/0008-Fix-CTS-issue-c2.android.av1.encoder-bitrate-oversho.patch
CTS Module: MctsMediaCodecTestCases
Test case:
android.media.codec.cts.VideoCodecTest#testBasic[9_c2.android.av1.encoder_video/av01_1]
Moderately increase the rc_min_quantizer value to reduce the resulting average bitrate.
Tracked-On: OAM-130965
=> Fix CTS issue - c2.android.av1.encoder bitrate overshooted

aosp_diff/base_aaos/packages/apps/DeskClock/0001-PATCH-Fixed-crash-in-DeskClock-during-monkey-test.patch
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter event at com.android.deskclock.LabelDialogFragment$ImeDoneListener.onEditorAction(Unknown Source:7)
event parameter is currently declared as non null. it can be null also, So declaring it as null parameter.
Tracked-On: OAM-129799
=> [PATCH] Fixed crash in DeskClock during monkey test.

aosp_diff/aaos_iasw/packages/apps/Camera2/0004-Add-Select-camera-menu-on-the-settings-of-camera-app.patch
Open different cameras based on the settings value, including taking photos and recording videos, and remove the icons of selecting front and rear cameras for image preview and video preview.
Tracked-On: OAM-132044
=> Add "Select camera" menu on the settings of camera app

bsp_diff/caas/hardware/intel/kernelflinger/0003-Fix-for-android-boot-failure-with-trusty.patch
Android fails to boot on MTL platforms when trusty is enabled, this is caused by a vmcall to activate VTD.
After enabling VTD from the bios settings this vmcall is not required.
Tests Done:
1. Flash the image in MTL nuc and CiV
2. Android is booting fine
Tracked-On: OAM-132238
=> Fix for android boot failure with trusty

aosp_diff/preliminary/packages/apps/Camera2/07_0007-Fix-Potential-Null-Pointer-Crash-in-CameraActivity.patch
Uri Null pointer is not verified before getting type
Validated URI before fetching mimetype
Tracked-On: OAM-128685
=> Fix Potential Null Pointer Crash in CameraActivity
