autopatch.sh
Throw error and list all repo names when conflict arises
Jira: None
Test: lunch works fine
=> [CELADON] Update for autopatch.sh

android_p/google_diff/cel_apl/frameworks/base/0005-Add-a-blacklist-of-vendorid-and-productid-to-hide-th.patch, android_p/google_diff/cel_apl/frameworks/base/0006-bluetooth-Fix-for-Can-t-enter-Connected-devices-afte.patch, android_p/google_diff/cel_apl/hardware/interfaces/0001-cel_apl-Changes-to-get-bluetooth-working.patch, android_p/google_diff/cel_apl/hardware/interfaces/0002-Revert-Bluetooth-Remove-random-MAC-addresses.patch, android_p/google_diff/cel_apl/packages/apps/Bluetooth/0001-Fix-for-audio-getting-paused-on-streaming-audio-over.patch, android_p/google_diff/cel_apl/system/bt/0001-Reintroduce-libbt-vendor-needed-for-Intel-bluetooth.patch, android_p/google_diff/cel_apl/system/bt/0002-Fix-for-BLE-pairing-failure-in-slave-role.patch
=> Patches for enabling bluetooth, A2DP playback and BLE

autopatch.sh
Tracked-On: None
Test: No warnings should be observed while applying
patch
=> [CELADON] Workaround to remove warnings

android_p/google_diff/cel_apl/system/sepolicy/0003-CELADON_P-Disabling-for-user-build.patch, android_p/google_diff/celadon/system/sepolicy/0003-CELADON_P-Disabling-for-user-build.patch
=> [CELADON_P] Added handling for user build we have to revert

android_p/google_diff/cel_apl/art/0001-Making-modifications-to-Android.mk-for-Android-P-cel.patch, android_p/google_diff/cel_apl/build/blueprint/0001-Enable-ART-ext-on-Celadon-P.patch, android_p/google_diff/celadon/art/0001-Making-modifications-to-Android.mk-for-Android-P-cel.patch, android_p/google_diff/celadon/build/blueprint/0001-Enable-ART-ext-on-Celadon-P.patch, vendorsetup.sh
Tracked-On: OAM-67515
Signed-off-by: Priyanka Bose <priyanka.bose@intel.com>
=> Google-diff for enabling art-extension on Android-P celadon

android_p/google_diff/cel_apl/device/intel/project-celadon/0001-Integrate-the-GAS-applicaton.patch, android_p/google_diff/cel_apl/device/intel/project-celadon/0002-Enable-setup-wizard-mode.patch, android_p/google_diff/celadon/device/intel/project-celadon/0001-Integrate-the-GMS-applicaton-for-celadon.patch, android_p/google_diff/celadon/device/intel/project-celadon/0002-Enable-setup-wizard-mode.patch
Signed-off-by: rugnathr <rugnath.ram@intel.com>
=> Adding google diff for GMS/GAS application

android_p/google_diff/cel_apl/external/wpa_supplicant_8/0001-Code-Changes-for-WIFI-MAC-address-display.patch, android_p/google_diff/cel_apl/packages/apps/Bluetooth/0002-Fix-for-Headset-icon-shown-for-reference-phone-after.patch, android_p/google_diff/celadon/external/wpa_supplicant_8/0001-Code-Changes-for-WIFI-MAC-address-display.patch, android_p/google_diff/celadon/hardware/interfaces/0001-celadon-Changes-to-get-bluetooth-working.patch, android_p/google_diff/celadon/hardware/interfaces/0002-Revert-Bluetooth-Remove-random-MAC-addresses.patch, android_p/google_diff/celadon/system/bt/0001-Reintroduce-libbt-vendor-needed-for-Intel-bluetooth.patch
@swaroopbalan @RakeshReddyGunda @aiswaryacyriac
=> Wi-Fi and BT enablement patches

android_p/google_diff/cel_apl/packages/services/Car/0002-sleep-5s-to-wait-for-unlock-user-operation.patch
Tracked-On: OAM-68187
Signed-off-by: Hongcheng Xie <hongcheng.xie@intel.com>
=> [WR] Avoid smart lock failed in CarBleTrustAgent

autopatch.sh
=> [CELADON] Pick additional private patches if exist

android_p/google_diff/cel_apl/external/f2fs-tools/0001-mkfs.f2fs-add-root_owner-to-give-uid-gid.patch, android_p/google_diff/cel_apl/external/f2fs-tools/0002-mkfs.f2fs-add-R-0-0-by-default-for-android.patch, android_p/google_diff/cel_apl/external/f2fs-tools/0003-f2fs-tools-add-g-to-give-default-options.patch, android_p/google_diff/cel_apl/system/vold/0001-add-paras-g-android-to-mkfs.f2fs.patch, android_p/google_diff/celadon/external/f2fs-tools/0001-mkfs.f2fs-add-root_owner-to-give-uid-gid.patch, android_p/google_diff/celadon/external/f2fs-tools/0002-mkfs.f2fs-add-R-0-0-by-default-for-android.patch, android_p/google_diff/celadon/external/f2fs-tools/0003-f2fs-tools-add-g-to-give-default-options.patch, android_p/google_diff/celadon/system/vold/0001-add-paras-g-android-to-mkfs.f2fs.patch
fix bug for adoptable storage
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-68617
Signed-off-by: Zhiwei Li <zhiwei.li@intel.com>
=> fix bug for adoptable storage

android_p/google_diff/cel_apl/hardware/interfaces/0003-Fix-the-sync-issue-between-HVAC-app-and-KitchSink-ap.patch
=> [CELADON] Fix the sync issue between HVAC app and KitchSink app

android_p/google_diff/cel_apl/kernel/project-celadon/0001-Enabling-USB-ROLE-SWITCH-QUIRK-for-INTEL_SUNRISEPOIN.patch, android_p/google_diff/cel_apl/kernel/project-celadon/0002-role-Toggle-role-in-probe-to-make-device-mode-work.patch, android_p/google_diff/celadon/kernel/project-celadon/0001-Enabling-USB-ROLE-SWITCH-QUIRK-for-INTEL_SUNRISEPOIN.patch, android_p/google_diff/celadon/kernel/project-celadon/0002-role-Toggle-role-in-probe-to-make-device-mode-work.patch
Tracked-On: None
Signed-off-by: Swaroop Balan <swaroop.balan@intel.com>
=> [CELADON] Enabled ADB over USB on COMMERCAIL-NUC

android_p/google_diff/cel_apl/frameworks/base/0016-CELADON-GlobalActions-Handle-sleep-action.patch, android_p/google_diff/cel_apl/packages/services/Car/0006-CELADON-Enabling-suspend-on-IVI-after-clicking-sleep.patch
the power button menu.
Tracked-on: OAM-56502
=> [CELADON]Enabling suspend on IVI after clicking sleep from

android_p/google_diff/cel_apl/frameworks/av/services/0001-enable-seccomp-filter-for-x86_64.patch, android_p/google_diff/celadon/frameworks/av/services/0001-enable-seccomp-filter-for-x86_64.patch
=> enable seccomp filter for x86_64

android_p/google_diff/cel_apl/build/core/0001-Add-new-arch-variant-goldmont.patch, android_p/google_diff/cel_apl/build/soong/0003-Add-new-arch-variant-goldmont-and-feature-avx2.patch, android_p/google_diff/cel_apl/device/intel/project-celadon/0005-Add-arch-variant-for-cel_apl.patch
Tracked-On : OAM-70167
Signed-off-by: Shalini Salomi Bodapati <shalini.salomi.bodapati@intel.com>
=> Add new arch variant goldmont and cpu feature avx2 for cel-apl

android_p/google_diff/cel_apl/system/netd/0001-Set-optlen-for-UDP-encap-check-in-XfrmController.patch
Please remove the diff patch once aosp rebased.
Tracked-On: OAM-71338
=> Back-port the aosp patch to fix cts issues.

android_p/google_diff/cel_apl/packages/apps/Car/LatinIME/0002-Fix-issue-that-Virtual-keypad-ducks-down-when-trying.patch
Tracked-on: OAM-71763
Signed-off-by: rugnathr <rugnath.ram@intel.com>
=> Fix issue where Virtual keypad ducks down when trying typing with mouse

android_p/google_diff/cel_apl/packages/apps/Settings/0001-Disable-restricted-profile-for-automotive-device.patch
Tracked-On: OAM-72296
Signed-off-by: robinz1x <robinx.zhang@intel.com>
=> Disable restricted profile for automotive device

android_p/google_diff/cel_apl/external/aac/0001-Fix-Audio-CTS-issue.patch, android_p/google_diff/cel_apl/frameworks/av/0006-Fix-Audio-CTS-issue-in-mediaplayer.patch
=> Fix for Audio AAC CTS issue

android_p/google_diff/cel_apl/kernel/project-celadon/0005-Fix-adb-not-working-with-3.0-cable-issue.patch
Jira: OAM-71783
Signed-off-by: saranya <saranya.gopal@intel.com>
=> Fix adb not detected over USB 3.0 port

android_p/google_diff/cel_apl/build/core/0001-Adding-dependancies-for-Capstone-Disassembler-in-Ven.patch, android_p/google_diff/cel_apl/build/soong/0003-Adding-dependancies-for-Capstone-Disassembler-in-Ven.patch, android_p/google_diff/cel_apl/external/capstone/0001-Fixing-the-Capstone-Disassembler-build-to-compile-fo.patch, android_p/google_diff/celadon/build/core/0001-Adding-dependancies-for-Capstone-Disassembler-in-Ven.patch, android_p/google_diff/celadon/build/soong/0003-Adding-dependancies-for-Capstone-Disassembler-in-Ven.patch, android_p/google_diff/celadon/external/capstone/0001-Fixing-the-Capstone-Disassembler-build-to-compile-fo.patch
Tracked-On: OAM-72473
Signed-off-by: yasoda.aravapalli@intel.com
=> Enable Auto Fast Jni optimization on Android P for ART-Silver

android_p/google_diff/cel_apl/frameworks/base/0023-Align-the-pageBlockOrder-to-the-kerne-4.19-kernel.patch
Tracked-On: OAM-72682
Signed-off-by: he, bo <bo.he@intel.com>
=> Align the pageBlockOrder to the kerne 4.19 kernel

android_p/google_diff/cel_apl/frameworks/base/0022-Check-whether-guest-user-is-already-created-or-not.patch, android_p/google_diff/cel_apl/packages/apps/Car/Settings/0003-Check-whether-guest-user-is-already-created-or-not.patch, android_p/google_diff/cel_apl/packages/services/Car/0008-Check-whether-guest-user-is-already-created-or-not.patch
Implement findCurrentGuestUser() api in UserManagerHelper and
CarUserManagerHelper, check whether the guest user is created
when click "Guest" icon in UserGridRecyclerView or "Switch"
button in Car settings GuestFragment.
If guest user already created, switch to it;
otherwise, create a new guest user.
Tracked-On: OAM-72293
Signed-off-by: robinz1x <robinx.zhang@intel.com>
=> Check whether guest user is already created or not.

android_p/google_diff/cel_apl/packages/apps/Car/Settings/0003-Get-the-attributes-for-unknown-usage-so-that-ducking.patch, android_p/google_diff/cel_apl/packages/apps/Car/Settings/0004-Ducking-audio-in-car-audio-settings.patch
=> Resolve momentary audio glitch in car settings

android_p/google_diff/cel_apl/trusty/lk/trusty/0001-enable-x86-64-google-diff-patch.patch, android_p/google_diff/celadon/trusty/lk/trusty/0001-enable-x86-64-google-diff-patch.patch
Tracked-On: OAM-72198
Signed-off-by: Chen Gang G <gang.g.chen@intel.com>
Signed-off-by: sheng wei <w.sheng@intel.com>
=> trusty: reduce trusty lib logs to optimize cold boot time

android_p/google_diff/cel_apl/vendor/intel/external/project-celadon/libva/0001-use-the-private-drm-lib-name.patch, android_p/google_diff/celadon/vendor/intel/external/project-celadon/libva/0001-use-the-private-drm-lib-name.patch
=> Rename libdrm to libdrm_pri in libva

android_p/google_diff/cel_kbl/frameworks/av/services/0003-Allow-virtual-driver-to-be-used-as-primary.patch, android_p/google_diff/cel_kbl/vendor/intel/external/project-celadon/audio/0001-Handle-dummy-sound-card-in-hal.patch
=> Add dummy sound device on KBL target

android_p/google_diff/cel_apl/system/libhidl/0001-Split-vr_hwc-manifest-entry.patch, android_p/google_diff/cel_kbl/system/libhidl/0001-Split-vr_hwc-manifest-entry.patch, android_p/google_diff/celadon/system/libhidl/0001-Split-vr_hwc-manifest-entry.patch
Port https://android.intel.com/#/c/649808/ from master
to celadon.
Tracked-On:OAM-75099
Signed-off-by: Hongcheng Xie <hongcheng.xie@intel.com>
Signed-off-by: Bo Tong <bo.tong@intel.com>
=> Split vr_hwc manifest entry

android_p/google_diff/cel_apl/device/intel/project-celadon/0020-Fix-typo-error-for-vulkan-library.patch, android_p/google_diff/cel_kbl/device/intel/project-celadon/0020-Fix-typo-error-for-vulkan-library.patch
Pull below PR:
https://github.com/projectceladon/device-androidia/pull/245
Tracked-On:
=> [CELADON] Enable treble

android_p/google_diff/cel_kbl/vendor/intel/external/project-celadon/libva/0001-use-the-private-drm-lib-name.patch
Tracked-On: OAM-75206
Signed-off-by: varun <varunx.jeevangoudar@intel.com>
=> [Celadon] porting libva patch from cel_apl

android_p/google_diff/cel_kbl/bionic/0003-Optimize-libc-function-wmemset-with-AVX2.patch, android_p/google_diff/cel_kbl/bionic/0004-Optimize-libc-function-wmemset-with-AVX2.patch
Tracked-On: OAM-75482
Signed-off-by: Shalini Salomi Bodapati <shalini.salomi.bodapati@intel.com>
=> Optimize libc function wmemset with AVX2.

android_p/google_diff/cel_kbl/bionic/0004-Adding-rint-rintf-trunc-truncf-assembly-files-in-lib.patch
Tracked-On:https://jira.devtools.intel.com/browse/OAM-75566
Signed-off-by: Atul Bajaj <atul.bajaj@intel.com>
=> LIBM changes for function rint, rintf, trunc and truncf.

android_p/google_diff/cel_apl/frameworks/base/0026-Enable-the-mAddUserView-after-adding-a-user.patch, android_p/google_diff/cel_kbl/frameworks/base/0026-Enable-the-mAddUserView-after-adding-a-user.patch, android_p/google_diff/cel_kbl/vendor/intel/art-extension/0001-Enabling-libart-with-haswell-flag.patch
mAddUserView is disabled in adding a user,
so enable it after adding done.
Tracked-On: OAM-75529
=> Enable the mAddUserView after adding a user.

android_p/google_diff/cel_kbl/vendor/intel/art-extension/0001-Enabling-haswell-only-for-kbl-nuc.patch
Tracked-On: OAM-75970
Signed-off-by: anuvarsh <anuvarshini.bc@intel.com>
=> Enabling haswell for libart - kblnuc

android_p/google_diff/cel_apl/frameworks/opt/net/wifi/0001-libwifi-hal-Add-libwifi-hal-for-intel.patch, android_p/google_diff/cel_apl/hardware/interfaces/0004-wifi-Disable-capabilities-not-yet-supported.patch, android_p/google_diff/cel_kbl/frameworks/opt/net/wifi/0001-libwifi-hal-Add-libwifi-hal-for-intel.patch, android_p/google_diff/cel_kbl/hardware/interfaces/0004-wifi-Disable-capabilities-not-yet-supported.patch
Tracked-On: OAM-75990
Signed-off-by: Amrita Raju <amrita.raju@intel.com>
=> libwifi-hal: Add libwifi-hal for intel

android_p/google_diff/cel_apl/frameworks/base/0025-Not-to-save-and-dump-the-empty-approved-list.patch, android_p/google_diff/cel_kbl/frameworks/base/0025-Not-to-save-and-dump-the-empty-approved-list.patch, android_p/google_diff/celadon/frameworks/base/0025-Not-to-save-and-dump-the-empty-approved-list.patch
To save the settings even it's empty.
Tracked-On: OAM-76029
=> Fix bug of Notification Listener Test

android_p/google_diff/cel_kbl/system/update_engine/0003-Parallelize-delta-read-non-file-data.patch, android_p/google_diff/cel_kbl/system/update_engine/0004-Sort-FileDeltaProcessor.patch, android_p/google_diff/cel_kbl/system/update_engine/0005-Improve-logging-when-generating-delta.patch, android_p/google_diff/cel_kbl/system/update_engine/0006-Check-if-FileDeltaProcessor-succeeded.patch, android_p/google_diff/cel_kbl/system/update_engine/0007-Produce-ZERO-operations-directly-for-zero-blocks.patch, android_p/google_diff/cel_kbl/system/update_engine/0008-Fragment-each-file-s-operations-in-parallel.patch
Porting a few Google patches that optimize ota package generation.
Test: generate incremental ota package
Tracked-On: OAM-76242
Signed-off-by: phireg <philippe.regnier@intel.com>
=> ota: port Google patch for incremental ota generation

cap_checker.py
=> Adding capchecker to vendor/intel/utils

android_p/google_diff/cel_kbl/frameworks/base/0027-Avoids-Going-to-Blank-screen-when-Max-useres-are-Cre.patch, android_p/google_diff/cel_kbl/frameworks/base/0028-Fix-the-behavior-of-keyguard-bouncer-in-a-corner-cas.patch
Tracked-On: OAM-76010
Signed-off-by: varun <varunx.jeevangoudar@intel.com>
=> Avoids going to blank screen when Max users are created & Fix the behavior of keyguard bouncer in a corner case

android_p/google_diff/cel_kbl/device/intel/mixins/0001-Add-new-cpu-arch.patch, android_p/google_diff/cel_kbl/device/intel/project-celadon/0001-Modify-cpu-arch-for-cel_kbl.patch
Tracked-On: OAM-76094
Signed-off-by: Shalini Salomi Bodapati <shalini.salomi.bodapati@intel.com>
=> Mixin changes to add TARGET_ARCH_VARIANT for cel-kbl

android_p/google_diff/cel_kbl/frameworks/ml/nn/0001-MLX-Bench-Improvement-Patch-Pinnacle.patch
Tracked-On: OAM-78359
Signed-off-by: anuvarsh <anuvarshini.bc@intel.com>
=> MLX Benchmark Improvement Pinnacle

android_p/google_diff/cel_apl/frameworks/base/0028-Handle-HDMI-audio-in-accessory-manager.patch, android_p/google_diff/cel_apl/hardware/intel/audio_media/hdmi/0001-Enable-HDMI-audio-HAL-for-celadon.patch, android_p/google_diff/cel_kbl/frameworks/base/0029-Handle-HDMI-audio-in-accessory-manager.patch, android_p/google_diff/cel_kbl/hardware/intel/audio_media/hdmi/0001-Enable-HDMI-audio-HAL-for-celadon.patch, android_p/google_diff/celadon/frameworks/base/0029-Handle-HDMI-audio-in-accessory-manager.patch, android_p/google_diff/celadon/hardware/intel/audio_media/hdmi/0001-Enable-HDMI-audio-HAL-for-celadon.patch, android_p/google_diff/clk/frameworks/base/0029-Handle-HDMI-audio-in-accessory-manager.patch, android_p/google_diff/clk/hardware/intel/audio_media/hdmi/0001-Enable-HDMI-audio-HAL-for-celadon.patch
=> Add HDMI audio hal support for celadon

android_p/google_diff/cel_apl/hardware/libhardware/modules/usbaudio/0001-CEL-BT-HFP-Support-from-Audio-side.patch, android_p/google_diff/cel_kbl/hardware/libhardware/modules/usbaudio/0001-CEL-BT-HFP-Support-from-Audio-side.patch
Test patch for checking loopback functionality.
Signed-off-by: karanpat <karan.patidar@intel.com>
=> BT-HFP Audio Changes

android_p/google_diff/cel_apl/hardware/intel/kernelflinger/0005-Optimization-check-for-pointer-and-array-index-range.patch, android_p/google_diff/cel_kbl/hardware/intel/kernelflinger/0005-Optimization-check-for-pointer-and-array-index-range.patch, android_p/google_diff/celadon/hardware/intel/kernelflinger/0005-Optimization-check-for-pointer-and-array-index-range.patch, android_p/google_diff/clk/hardware/intel/kernelflinger/0005-Optimization-check-for-pointer-and-array-index-range.patch
Port fixes from issue OAM-78889
Tracked-On: OAM-79044
Signed-off-by: phireg <philippe.regnier@intel.com>
=> [REVERT ME] port kernelflinger static analysis fixes to Celadon

android_p/google_diff/cel_apl/vendor/intel/external/project-celadon/dldt/0001-Android-enabling-changes-in-DLDT-OPENVINO.patch, android_p/google_diff/cel_kbl/vendor/intel/external/project-celadon/dldt/0001-Android-enabling-changes-in-DLDT-OPENVINO.patch, android_p/google_diff/celadon/vendor/intel/external/project-celadon/dldt/0001-Android-enabling-changes-in-DLDT-OPENVINO.patch
Tracked-On: OAM-76180
Signed-off-by: Atul Vaish <atul.vaish@intel.com>
=> Android Enabling Changes in OPENIVNO

android_p/google_diff/cel_apl/packages/apps/Car/libs/0002-Add-setToggleEnable-to-IconToggleLineItem.patch, android_p/google_diff/cel_apl/packages/apps/PackageInstaller/0001-DO-NOT-MERGE-According-to-the-status-of-permission-e.patch, android_p/google_diff/cel_kbl/packages/apps/Car/libs/0002-Add-setToggleEnable-to-IconToggleLineItem.patch, android_p/google_diff/cel_kbl/packages/apps/PackageInstaller/0001-DO-NOT-MERGE-According-to-the-status-of-permission-e.patch
Patch port from Google:
https://android-review.googlesource.com/c/platform/packages/apps/Car/libs/+/856911
https://android-review.googlesource.com/c/platform/packages/apps/PackageInstaller/+/856890
Tracked-On: OAM-79165
=> Fix AOSP packageInstaller for CTS & CtsVerifier

android_p/google_diff/cel_apl/packages/apps/Car/Hvac/0001-Car-Service-Enabling-Fan-direction-UI.patch, android_p/google_diff/cel_kbl/packages/apps/Car/Hvac/0001-Car-Service-Enabling-Fan-direction-UI.patch
Changes ported from master branch.
Tracked-On: https://jira.devtools.intel.com/browse/OAM-76407
Signed-off-by: rbabub <ramesh.babu.b@intel.com>
=> [Car Service] Enabling Fan direction UI

android_p/google_diff/cel_apl/device/intel/project-celadon/0005-Add-Kernel-Config-for-BTUSB-sound-card-driver.patch, android_p/google_diff/cel_apl/kernel/project-celadon/0006-Virtual-PCM-device-driver-for-enabling-BT-HFP.patch, android_p/google_diff/cel_apl/packages/apps/Contacts/0002-Fix-the-issue-unable-to-send-outgoing-call-in-Contac.patch, android_p/google_diff/cel_apl/packages/services/Telecomm/0001-Do-not-check-the-config_voice_capable-when-make-a-ca.patch, android_p/google_diff/cel_apl/system/bt/0004-Disable-Wideband-Support.patch, android_p/google_diff/cel_kbl/device/intel/project-celadon/0005-Add-Kernel-Config-for-BTUSB-sound-card-driver.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0006-Virtual-PCM-device-driver-for-enabling-BT-HFP.patch, android_p/google_diff/cel_kbl/packages/apps/Contacts/0002-Fix-the-issue-unable-to-send-outgoing-call-in-Contac.patch, android_p/google_diff/cel_kbl/packages/services/Telecomm/0001-Do-not-check-the-config_voice_capable-when-make-a-ca.patch, android_p/google_diff/cel_kbl/system/bt/0004-Disable-Wideband-Support.patch
Tracked-On: https://jira.devtools.intel.com/browse/OAM-75510
=> Bluetooth Patches to enable HFP

android_p/google_diff/clk/device/intel/project-celadon/0003-Enable-master-playback-switch.patch
Updating default value of master playback switch to 1
for CLK target.
Tracked-On: OAM-80076
Signed-off-by: Karan Patidar <karan.patidar@intel.com>
=> Enable Master Playback Swtich

android_p/google_diff/clk/kernel/project-celadon/0006-Fix-adb-not-working-with-3.0-cable-issue.patch
Tracked-On: OAM-79985
Signed-off-by: saranya <saranya.gopal@intel.com>
Signed-off-by: revatipx <revatix.prasad@intel.com>
=> usb: adb: Fixing adb not working with 3.0 cable

android_p/google_diff/cel_apl/hardware/intel/kernelflinger/0010-usb-fix-automatic-transport-layer-fallback.patch, android_p/google_diff/cel_kbl/hardware/intel/kernelflinger/0010-usb-fix-automatic-transport-layer-fallback.patch, android_p/google_diff/celadon/hardware/intel/kernelflinger/0010-usb-fix-automatic-transport-layer-fallback.patch, android_p/google_diff/clk/hardware/intel/kernelflinger/0010-usb-fix-automatic-transport-layer-fallback.patch
Tracked-On: OAM-80318
Signed-off-by: Meng Xianglin <xianglinx.meng@intel.com>
=> usb: fix automatic transport layer fallback

android_p/google_diff/clk/kernel/project-celadon/0009-mmc-sdhci-pci-core-Selecting-3rd-GPIO-source-for-CNP.patch
Tracked-On: OAM-79955
Signed-off-by: shyjumon <shyjumon.n@intel.com>
=> [WHL] SD card detect issue

android_p/google_diff/cel_apl/kernel/project-celadon/0008-Fix-Possible-null-pointer-dereference-in-btusb_sco_s.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0009-Fix-Possible-null-pointer-dereference-in-btusb_sco_s.patch, android_p/google_diff/celadon/kernel/project-celadon/0006-Fix-Possible-null-pointer-dereference-in-btusb_sco_s.patch
=> Fix Possible null pointer dereference in btusb_sco_snd_card driver

android_p/google_diff/cel_apl/kernel/project-celadon/0010-Fix-KW-errors-introduced-due-to-suspend-resume-fix.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0017-Fix-KW-errors-introduced-due-to-suspend-resume-fix.patch, android_p/google_diff/celadon/kernel/project-celadon/0008-Fix-KW-errors-introduced-due-to-suspend-resume-fix.patch
=> Fix KW errors introduced due to suspend/resume fix

android_p/google_diff/cel_apl/vendor/intel/external/project-celadon/dldt/0002-openvino-klocwork-critical-fixes.patch, android_p/google_diff/cel_kbl/vendor/intel/external/project-celadon/dldt/0002-openvino-klocwork-critical-fixes.patch, android_p/google_diff/celadon/vendor/intel/external/project-celadon/dldt/0002-openvino-klocwork-critical-fixes.patch
Tracked-On: OAM-81035
Signed-off-by: Nagamani Chennuboina <nagamani.chennuboina@intel.com>
=> openvino klocwork critical fixes

android_p/google_diff/cel_apl/vendor/intel/external/project-celadon/mesa/0001-WA-for-random-vulkan-link-error-on-Celadon.patch, android_p/google_diff/cel_kbl/vendor/intel/external/project-celadon/mesa/0001-WA-for-random-vulkan-link-error-on-Celadon.patch, android_p/google_diff/celadon/vendor/intel/external/project-celadon/mesa/0001-WA-for-random-vulkan-link-error-on-Celadon.patch, android_p/google_diff/clk/vendor/intel/external/project-celadon/mesa/0001-WA-for-random-vulkan-link-error-on-Celadon.patch
We may encounter random vulkan link error on build bot
with a low reproduced rate(5%). This WA to help fix the
random link issue.
Tracked-On: OAM-83401
Signed-off-by: Chenglei Ren <chenglei.ren@intel.com>
=> WA for random vulkan link error on Celadon

android_p/google_diff/clk/device/intel/project-celadon/0005-Add-Kernel-Config-for-BTUSB-sound-card-driver.patch, android_p/google_diff/clk/kernel/project-celadon/0017-Virtual-PCM-device-driver-for-enabling-BT-HFP.patch, android_p/google_diff/clk/kernel/project-celadon/0018-Fix-Possible-null-pointer-dereference-in-btusb_sco_s.patch, android_p/google_diff/clk/kernel/project-celadon/0019-Fix-kernel-panic-on-suspend-resume-and-rmmod-of-btus.patch, android_p/google_diff/clk/kernel/project-celadon/0020-Fix-race-condition-in-btusb_sco_snd_card-driver.patch, android_p/google_diff/clk/kernel/project-celadon/0021-Fix-KW-errors-introduced-due-to-suspend-resume-fix.patch, android_p/google_diff/clk/packages/services/Telecomm/0001-Do-not-check-the-config_voice_capable-when-make-a-ca.patch
-Enable the config for btusb_sco_snd_card_driver
-Add btusb_sco_snd_card_driver
-Fixes for btusb_sco_snd_card driver
=> Add BT-HFP support for CLK

android_p/google_diff/clk/kernel/project-celadon/0022-usb-dbc-fix-for-adb-root-issue-in-WHL-platform.patch
freeing usb request into the callback function.
Tracked-On: 84333
Signed-off-by: Balaji <m.balaji@intel.com>
=> usb: dbc: fix for adb root issue in WHL platform

aosp_diff/cic/bionic/0001-Disable-SELINUX-Tmp-patch-to-disable-selinux-it-shou.patch, aosp_diff/cic/build/make/0001-fsconfig-need-all-partitions-has-arguments.patch, aosp_diff/cic/build/soong/0001-Macro-which-should-be-removed-later.patch, aosp_diff/cic/build/soong/0002-import-from-1A-to-resolve-mesa-compilation.patch, aosp_diff/cic/frameworks/base/0001-Tmp-patches-to-disable-SELINUX-revert-it-later.patch, aosp_diff/cic/frameworks/base/0002-a-corncase-in-network-which-should-be-upstreaming.patch, aosp_diff/cic/frameworks/native/0001-Tmp-patch-to-disable-selinux-it-should-be-reverted.patch, aosp_diff/cic/system/core/0001-Tmp-patch-to-disable-selinux-it-should-be-reverted.patch, aosp_diff/cic/system/core/0002-this-patch-is-used-to-deal-with-multiple-input-devic.patch, aosp_diff/cic/system/core/0003-emulate-kernel-cmdline-to-deal-with-parameters.patch, aosp_diff/cic/system/core/0004-Add-Wno-unused-function-to-solve-compile-issue.patch, aosp_diff/cic/system/core/0005-remove-check-for-some-fs-mount.patch, aosp_diff/cic/system/core/0006-Remove-check-for-init-pid.patch, aosp_diff/cic/system/core/0007-now-cmdline-does-not-exist-add-property-and-remove-c.patch, aosp_diff/cic/system/core/0008-aic-has-its-own-sdcard.patch, aosp_diff/cic/system/hwservicemanager/0001-Tmp-patch-to-disable-selinux-it-should-be-reverted.patch, aosp_diff/cic/system/security/0001-Tmp-patch-to-disable-selinux-it-should-be-reverted.patch, aosp_diff/cic/system/vold/0001-Tmp-patch-to-disable-selinux-it-should-be-reverted.patch, bsp_diff/cic/hardware/intel/external/drm-intel/0001-port-from-Q-for-Q-already-has-drm-in-external.patch, bsp_diff/cic/hardware/intel/external/mesa3d-intel/0001-mesa3d-intel-make-mesa-can-pass-build-in-ctnr-tree.patch, bsp_diff/cic/hardware/intel/external/mesa3d-intel/0002-UPSTREAM-mesa-android-Remove-unnecessary-dependency-.patch, bsp_diff/cic/hardware/intel/external/mesa3d-intel/0003-use-intel-s-lib.patch, bsp_diff/cic/hardware/intel/external/minigbm-intel/0001-minigbm-intel-add-framebuffer-device-implementation-.patch, bsp_diff/cic/hardware/intel/external/minigbm-intel/0002-minigbm-intel-fix-minigbm-can-t-work-on-kernel-4.4.patch, bsp_diff/cic/hardware/intel/external/minigbm-intel/0003-multidroid-support-multi-instances-on-multi-screens.patch, bsp_diff/cic/hardware/intel/external/minigbm-intel/0004-minigbm-intel-let-minigbm-support-gralloc-vhal.patch, bsp_diff/cic/hardware/intel/external/minigbm-intel/0005-minigbm-fix-black-screen-on-some-machines.patch, bsp_diff/cic/hardware/intel/external/minigbm-intel/0006-minigbm-open-render-node-instead-of-master-node.patch, bsp_diff/cic/hardware/intel/external/minigbm-intel/0007-use-our-own-drm-library.patch, bsp_diff/cic/hardware/intel/external/minigbm-intel/0008-Add-a-new-definition-for-hal.patch
1. Add AOSP and BSP diff patches
2. Add pulish_ci buildbot support for CIC
Change-Id: Ib4f81c8c0598f7cc64b0e0c8fbef66fc901895ea
Tracked-On: OAM-86511
Signed-off-by: Wang, Liang <liang.wang@intel.com>
=> Add support for CIC target

bsp_diff/common/vendor/intel/external/project-celadon/nn-hal/0002_1-fix-for-depthwise-convolution-vts-testcases-failing-.patch
=> Fix for depthwise convolution vts failing testcases

bsp_diff/common/vendor/intel/external/project-celadon/nn-hal/0003_1-Fix-for-nn-hal-Klocwork-issues.patch
=> Fix-for-nn-hal-Klocwork-issues

bsp_diff/cic/hardware/intel/external/minigbm-intel/0002-minigbm-intel-fix-minigbm-can-t-work-on-kernel-4.4.patch
Tracked-On: OAM-86735
Signed-off-by: Wang, Liang <liang.wang@intel.com>
=> CIC: rebase minigbm patches to minigbm latest stable branch.

aosp_diff/preliminary/bootable/recovery/671840_2-Avoid-key_queue_mutex-deadlock-in-waitkey.patch
Tracked-On: OAM-86652
Signed-off-by: sunxunou <xunoux.sun@intel.com>
=> Avoid key_queue_mutex deadlock in waitkey()

bsp_diff/common/vendor/intel/external/project-celadon/nn-hal/0004_1-Fix-for-mPadReq-uninitialized-Klocwork-issue.patch
=> Fix for mPadReq uninitialized Klocwork issue

autopatch.sh, vendorsetup.sh
1. check if existing include_preliminary or include_common file
under TARGET folder to decide if it's necessary to apply
aosp/preliminary or bsp/common diff patches;
In this way, any TARGET requires to apply aosp/preliminary or
bsp/common diff pathces, just to add include_preliminary or
include_common file into aosp/<TARGET>/ or bsp/<TARGET>/ folder.
Tracked-On: OAM-86827
Signed-off-by: Sun, Yi J <yi.j.sun@intel.com>
=> restruct utils working rule

aosp_diff/preliminary/system/sepolicy/0001-CELADON-VtsHalGraphicsMapperV2_1Target-module-is-ski.patch
=> [CELADON] VtsHalGraphicsMapperV2_1Target module is skipped

bsp_diff/common/vendor/intel/external/project-celadon/dldt/0002-Enable-cldnn-and-cldnn_plugin-compiling-in-Celadon.patch, bsp_diff/common/vendor/intel/external/project-celadon/nn-hal/0005-add-OpenCL-GPU-support-in-intel_nn_hal.patch, bsp_diff/common/vendor/intel/external/project-celadon/nn-hal/0006-enable-cldnn-and-cldnn-plugin-compiling-in-Celadon.patch, bsp_diff/common/vendor/intel/external/project-celadon/nn-hal/0007-make-cpu-and-gpu-instance-run-in-parallel.patch
Tracked-On: OAM-86770
Signed-off-by: dengliqiang <liqiangx.deng@intel.com>
=> integrate OpenCL into OpenVINO to enable clDNN

aosp_diff/preliminary/bionic/0001-binoic-add-avx2-support.patch, aosp_diff/preliminary/build/soong/0001-Add-avx2-instruction-support.patch, aosp_diff/preliminary/external/compiler-rt/0001-compiler-rt-avx-support.patch
=> Add patches related to support avx2

aosp_diff/celadon_ivi/packages/services/Car/678871_1--WA-patch-Delay-the-system-to-go-to-sleep-when-screen.patch
Tracked-On: OAM-87069
Signed-off-by: Ting Li <ting.li@intel.com>
=> release full wakelock when screen off to let system enter sleep

aosp_diff/preliminary/build/soong/0001-Set-DIST-env-while-call-publish-target.patch
Tracked-On: OAM-86839
Signed-off-by: chen yangyang <yangyangx.chen@intel.com>
=> Set DIST env while call publish target

aosp_diff/preliminary/trusty/app/gatekeeper/680313_1-Fix-compile-errors.patch
Tracked-On: OAM-86819
Signed-off-by: sheng wei <w.sheng@intel.com>
=> Add patch to fix compile errors for trusty gatekeeper TA

android_p/google_diff/cel_apl/build/make/0001-add-dist-into-publish-on-config.mk.patch, android_p/google_diff/cel_apl/build/soong/0001-add-dist-into-publish.patch, android_p/google_diff/cel_kbl/build/make/0001-add-dist-into-publish-on-config.mk.patch, android_p/google_diff/cel_kbl/build/soong/0001-add-dist-into-publish.patch, android_p/google_diff/celadon/build/make/0001-add-dist-into-publish-on-config.mk.patch, android_p/google_diff/celadon/build/soong/0001-add-dist-into-publish.patch, android_p/google_diff/clk/build/make/0001-add-dist-into-publish-on-config.mk.patch, android_p/google_diff/clk/build/soong/0001-add-dist-into-publish.patch
Tracked-On: OAM-88214
Signed-off-by: chen yangyang <yangyangx.chen@intel.com>
=> Add dist into publish on Celadon P

aosp_diff/celadon_ivi/frameworks/native/680531_5-Remove-feature-android.software.print.patch
Remove feature:android.software.print
Tracked-On: OAM-86901
=> Remove feature:android.software.print

aosp_diff/preliminary/hardware/interfaces/0001-ITS3-JIRA-OAM-86918-Vehicle-HAL-CTS-test-cases-fixes.patch
Tracked-On: OAM-86918
Signed-off-by: mogilisx <rohinix.mogilisetty@intel.com>
=> [PATCH] [ITS3 JIRA][OAM-86918] Vehicle HAL CTS test cases fixes

aosp_diff/preliminary/hardware/interfaces/0002-OAM-88339-APL-CELADON-Q-CTS-testSetProperty-fix.patch
Tracked-On: OAM-88339
Signed-off-by: mogilisx <rohinix.mogilisetty@intel.com>
=> OAM-88339 -[APL-IVI-Celadon-Q] CTS-testSetProperty fix

android_p/google_diff/cel_apl/vendor/intel/external/project-celadon/dldt/0001-Android-enabling-changes-in-DLDT-OPENVINO.patch, android_p/google_diff/cel_apl/vendor/intel/external/project-celadon/dldt/0002-openvino-klocwork-critical-fixes.patch, android_p/google_diff/cel_kbl/vendor/intel/external/project-celadon/dldt/0001-Android-enabling-changes-in-DLDT-OPENVINO.patch, android_p/google_diff/cel_kbl/vendor/intel/external/project-celadon/dldt/0002-openvino-klocwork-critical-fixes.patch, android_p/google_diff/celadon/vendor/intel/external/project-celadon/dldt/0001-Android-enabling-changes-in-DLDT-OPENVINO.patch, android_p/google_diff/celadon/vendor/intel/external/project-celadon/dldt/0002-openvino-klocwork-critical-fixes.patch
Tracked-On: OAM-88883
Signed-off-by: Nagamani Chennuboina <nagamani.chennuboina@intel.com>
=> Changes to enable dldt 2019 R1.1 with Android

android/common/system/vold/0002-Revert-me-Remove-selinux-related-option-since-selinu.patch
Tracked-On: OAM-89794
Signed-off-by: Zhiwei Li <zhiwei.li@intel.com>
=> [Revert me]Remove selinux related option since selinux is disabled

cap_checker.py
=> [CELADON] [CIV][Platform Config] Upgrade Python2 scripts

aosp_diff/caas/system/media/0001-Increase-period-size-to-improve-USB-Audio-quality.patch
Signed-off-by: padmashree9110 <padmashree.mandri@intel.com>
=> Increase period size to improve USB Audio quality

cap_checker.py
=> upgrading python 2 to 3

android_p/google_diff/cel_apl/kernel/project-celadon/0012-LSM-Update-xfrm_policy_lookup-prototype-to-fix-build.patch, android_p/google_diff/cel_apl/kernel/project-celadon/0013-Fix-prototype-error-in-platform_driver-and-usb_drive.patch, android_p/google_diff/cel_apl/kernel/project-celadon/0014-kernel-Disable-ASM_GOTO-support.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0021-LSM-Update-xfrm_policy_lookup-prototype-to-fix-build.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0022-Fix-prototype-error-in-platform_driver-and-usb_drive.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0023-kernel-Disable-ASM_GOTO-support.patch, android_p/google_diff/cel_kbl/kernel/project-celadon/0024-Fix-build-error-in-dbc.patch, android_p/google_diff/celadon/kernel/project-celadon/0010-LSM-Update-xfrm_policy_lookup-prototype-to-fix-build.patch, android_p/google_diff/celadon/kernel/project-celadon/0011-Fix-prototype-error-in-platform_driver-and-usb_drive.patch, android_p/google_diff/celadon/kernel/project-celadon/0012-kernel-Disable-ASM_GOTO-support.patch, android_p/google_diff/clk/kernel/project-celadon/0024-LSM-Update-xfrm_policy_lookup-prototype-to-fix-build.patch, android_p/google_diff/clk/kernel/project-celadon/0025-Fix-prototype-error-in-platform_driver-and-usb_drive.patch, android_p/google_diff/clk/kernel/project-celadon/0026-kernel-Disable-ASM_GOTO-support.patch, android_p/google_diff/clk/kernel/project-celadon/0027-Fix-build-error-in-dbc.patch
=> kernel: patches for toolchain switch from gcc to clang

android_p/google_diff/cel_apl/vendor/intel/external/project-celadon/dldt/0003-Changes-to-fix-dldt-klocwork-critical-issues-for-Cel.patch, android_p/google_diff/cel_kbl/vendor/intel/external/project-celadon/dldt/0003-Changes-to-fix-dldt-klocwork-critical-issues-for-Cel.patch, android_p/google_diff/celadon/vendor/intel/external/project-celadon/dldt/0003-Changes-to-fix-dldt-klocwork-critical-issues-for-Cel.patch
=> Changes to fix dldt klocwork critical issues for Celadon P

bsp_diff/common/vendor/intel/external/project-celadon/dldt/0004_1-Changes-to-fix-dldt-klocwork-critical-issues.patch
=> Changes to fix dldt klocwork critical issues

android/common/system/vold/0003-USB-formatting-issue-for-Android-in-Container.patch
Tracked-On: OAM-90476
Signed-off-by: Nitisha Tomar <nitisha.tomar@intel.com>
=> USB formatting issue in CIC

bsp_diff/common/vendor/intel/external/apps/camera/0001-Camera-switch-new-implementation.patch
Tracked-On : OAM-90226
Signed-off-by: Shiva Kumara  <shiva.kumara.rudrappa@intel.com>
Signed-off-by: kbillore <kaushal.billore@intel.com>
=> Camera switch implementation to address stability issues

android/cic/system/core/0004-Add-secure-storage-daemon-support.patch
Signed-off-by: Huang Yang <yang.huang@intel.com>
Tracked-On: OAM-90554
=> Fix a deadloop

aosp_diff/preliminary/system/sepolicy/04_0001_1-BACKPORT-Policies-to-get-Android-booted-with-5.4-abo.patch, bsp_diff/caas/kernel/lts2019-chromium/01_678430_1-WA-for-missing-depmod-tool-in-host-environment.patch, bsp_diff/caas/kernel/lts2019-chromium/02_679376_1-make-vmmouse-report-relative-values.patch, bsp_diff/caas/kernel/lts2019-chromium/03_0003-greybus-Remove-Android.mk.patch, bsp_diff/caas/kernel/lts2019-yocto/01_678430_1-WA-for-missing-depmod-tool-in-host-environment.patch, bsp_diff/caas/kernel/lts2019-yocto/02_679376_1-make-vmmouse-report-relative-values.patch, bsp_diff/caas/kernel/lts2019-yocto/03_0003-ANDROID-Revert-x86-mm-Identify-the-end-of-the-kernel.patch, bsp_diff/caas/kernel/lts2019-yocto/04_0004-greybus-Remove-Android.mk.patch
=> Add kernel diff patches for lts2019

bsp_diff/caas/kernel/lts2019-chromium/05_0005-REVERT-ME-Fallback-to-available-firmware-if-latest-f.patch
=> [REVERT ME] Fallback to available firmware if latest fw not found

bsp_diff/caas/kernel/lts2019-chromium/06_0006-e1000e-Add-support-for-Comet-Lake.patch
=> e1000e: Add support for Comet Lake

host/ovmf/OvmfPkg-add-IgdAssgingmentDxe-for-qemu-4_2_0.patch, host/qemu/0001-Revert-Revert-vfio-pci-quirks.c-Disable-stolen-memor.patch
Signed-off-by: Lu Yang yang.a.lu@intel.com
Tracked-On: OAM-90222
=> Maintain the patches of QEMU and OVMF for CiV GVT-d

android/common/vendor/intel/external/project-celadon/audio/0001-Use-TARGET_PRODUCT-for-cic-audio-hal.patch
Tracked-On: OAM-90733
Signed-off-by: pmandri <padmasree.mandri@intel.com>
=> [CIC] update change-id for audio patches

android/common/frameworks/av/0001-PATCH-Added-surround_sound_configuration_5_0.xml-fil.patch
[Rebased the patch to add change-id for the
existing patch]
Tracked-On: OAM-90731
=> Added surroun sound configuration_5_0.xml

android/common/system/vold/0001-SD-card-formatting-issue-for-Android-in-Container.patch, android/common/system/vold/0003-USB-formatting-issue-for-Android-in-Container.patch
Tracked-On: OAM-90767
Signed-off-by: nitishat <nitisha.tomar@intel.com>
=> Rebasing the patches and adding missing change

bsp_diff/common/kernel/lts2018/12_0001_1-greybus-Remove-android-make-file.patch, bsp_diff/common/kernel/lts2019-chromium/01_0001-greybus-Remove-Android.mk.patch, bsp_diff/common/kernel/lts2019-yocto/01_0001-greybus-Remove-Android.mk.patch
=> Fix compilation issue when many kernels are supported

aosp_diff/caas/hardware/interfaces/03_add-kernel-5.4-support-in-Android-Q.patch, aosp_diff/caas/kernel/configs/01_add-kernel-5.4-support-in-Android-Q.patch
Tracked-On: OAM-90729
Signed-off-by: Xihua Chen <xihua.chen@intel.com>
=> add kernel-5.4-support-in-Android-Q

android/apply_patch.sh
=> Adding the condition check to throw error if change-id is missing in the

aosp_diff/caas/frameworks/av/04_0001-Change-HDMI-audio-priority-on-celadon.patch, aosp_diff/caas/frameworks/base/03_0001-Handle-HDMI-audio-device-in-framework.patch
Handle HDMI audio device in framework
Tracked-On: OAM-90930
Signed-off-by: padmashree9110 <padmashree.mandri@intel.com>
=> Update priority for audio devivces

host/kernel/lts2019-chromium/build.sh
=> Update host kernel commit hash

android/common/frameworks/base/0001-Hide-view-decors-and-send-task-id-to-SurfaceFlinger.patch, android/common/frameworks/native/0001-Add-layer-task-info-support.patch, android/common/hardware/interfaces/0001-Add-layer-task-info-support.patch, android/common/hardware/interfaces/0002-Add-setLayerStackInfo-for-Hwc2On1Adapter.patch, android/common/hardware/libhardware/0001-Add-layer-task-info-support.patch
Tracked-On: OAM-90954
Signed-off-by: bxu10x <bingx.xu@intel.com>
=> Enable multi-windows feature

android/cic_dev/device/intel/mixins/0001-Adding-lenovo-features-to-cic_dev-target.patch, android/cic_dev/device/intel/project-celadon/0001-Mixinup-patch-of-adding-lenovo-features-to.patch, android/cic_dev/vendor/intel/cic/0001-Make-aic-as-daemon-and-update-status-to-systemd.patch
Changes-include:
-Adding lenovo features to cic_dev target
-Mixinup patch for these changes
Tracked-On: OAM-90809
=> Adding bsp_diff patches to cic_dev

host/kernel/lts2019-chromium/build_weekly.sh
… every build a user triggers
Tracked-On: OAM-91065
=> Added build_weekly.sh to reproduce the kernel used in weekly

host/kernel/lts2019-yocto/0001-Add-PCH-slow-clock-wa-for-EHL-GPU-flr.patch, host/kernel/lts2019-yocto/README, host/kernel/lts2019-yocto/build.sh, host/kernel/lts2019-yocto/build_weekly.sh
Changes include:
- Added host kernel patches done on top of yocto kernel base.
- Added repo tip build and weekly build script
- Added README file
Tracked-On: OAM-91113
=> yocto/host: host kernel patches, build scripts and README

android/cic_dev/system/core/0003-Disable-SELINUX-Tmp-patch-to-disable-selinux-it-shou.patch
=> Resolving the lunch conflict on cic_dev target

aosp_diff/caas/system/vold/01_0001-Vold-SD-and-USB-coexist-handling.patch
Tracked-On: OAM-91130
Signed-off-by: Salih <muhammadhx.salih@intel.com>
Signed-off-by: N,Shyjumon <shyjumon.n@intel.com>
=> Vold: SD and USB coexist-handling

bsp_diff/caas/kernel/lts2019-chromium/09_0009-input-passthrough-virtio-input-device.patch
Tracked-On: OAM-91172
Signed-off-by: Jaikrishna Nemallapudi <nemallapudi.jaikrishna@intel.com>
=> enable passthrough virtio-input device

android/common/frameworks/base/0001-Force-to-support-freeform-for-some-apps.patch
Tracked-On: OAM-91115
Signed-off-by: Hongcheng Xie <hongcheng.xie@intel.com>
=> Force to support freeform for some apps

android/common/frameworks/base/0001-Hide-view-decors-and-send-task-id-to-SurfaceFlinger.patch
Tracked-On: OAM-91005
Signed-off-by: bxu10x <bingx.xu@intel.com>
=> Add property to control freeform mode.

bsp_diff/caas/kernel/lts2019-chromium/10_0001-Bluetooth-SCO-USB-driver.patch, bsp_diff/caas/kernel/lts2019-yocto/09_0001-Bluetooth-SCO-USB-driver.patch
This driver is required if you want to use Bluetooth devices
with USB interface to support SCO.
Tracked-On:
Signed-off-by: Amalendu Prasad Das <amalendu.prasad.das@intel.com>
=> Bluetooth SCO USB driver.

android/cic/system/keymaster/0001-Fix-GGC-compilation-errors.patch
Tracked-On: OAM-91323
Signed-off-by: Yan, Shaopu <shaopu.yan@intel.com>
=> Add a missing patch for system/keymaster which is used to fix GGC compilation errors

aosp_diff/caas/external/arm-optimized-routines/0001-Build-support-to-add-avx2-optimized-math-routines-fo.patch
=> Build Support to add avx optimizations in bionic

aosp_diff/caas/frameworks/av/0004-Supported-FMA-Intrinsics-in-Audio-Resampler-FIR-proc.patch, aosp_diff/caas/frameworks/ml/0001-Enable-generation-of-Intel-R-AVX-AVX2-Instructions.patch, aosp_diff/caas/frameworks/rs/0001-Inferenced-AVX2-FMA-Intrinsics-in-frameworks-renders.patch
=> AVX Optimizations in frameworks module

android/common/vendor/intel/external/project-celadon/dldt/0001-Android-enabling-changes-in-DLDT-OPENVINO.patch, android/common/vendor/intel/external/project-celadon/dldt/0002-openvino-klocwork-critical-fixes.patch, android/common/vendor/intel/external/project-celadon/dldt/0003-Changes-to-fix-dldt-klocwork-critical-issues-for-Cel.patch
Change-Id: Ic087067f704f1bf9a9042199c35f9732bd4abb76
Tracked-On: OAM-91705
=> Added dldt patches for android specific changes

android/common/packages/apps/Settings/0001-Add-settings-screen-to-set-ethernet-proxy-host-and-p.patch
=> Fix null pointer dereference issue

android/common/frameworks/native/0001-Change-value-format-to-fix-KW-issues.patch
Tracked-On: OAM-91869
Signed-off-by: bxu10x <bingx.xu@intel.com>
=> Change value format to fix KW issues.

autopatch.sh
=> autopatch script improvements

aosp_diff/caas/bionic/0002-Optimized-version-of-memcpy-for-x86_64.patch
=> Optimize memcpy for x86_64

autopatch.sh, bsp_diff/common/device/intel/mixins/0001-Add-PRODUCT_STATIC_BOOT_CONTROL_HAL-bootctrl.intel.s.patch, bsp_diff/common/device/intel/project-celadon/0001-Add-PRODUCT_STATIC_BOOT_CONTROL_HAL-bootctrl.intel.s.patch
Also, improve autopatch speed
Tracked-On: OAM-91670
=> Add PRODUCT_STATIC_BOOT_CONTROL_HAL := bootctrl.intel.static

bsp_diff/caas/kernel/lts2019-chromium/04_0004-Add-AB24-support-for-virtio-on-Android.patch, bsp_diff/caas/kernel/lts2019-chromium/05_0005-Bluetooth-SCO-USB-driver.patch, bsp_diff/caas/kernel/lts2019-chromium/06_0006-uvc-Add-UVC-GET_DEF-probe-quirk-for-C922-camera.patch, bsp_diff/caas/kernel/lts2019-chromium/07_0007-Add-a-item-in-get_param-IOCTL-for-chromium-kernel-GV.patch, bsp_diff/caas/kernel/lts2019-chromium/08_0008-drm-i915-gt-Schedule-request-retirement-for-gen10.patch, bsp_diff/caas/kernel/lts2019-yocto/05_0005-ANDROID-virtio-virtio_input-Set-the-amount-of-multit.patch, bsp_diff/caas/kernel/lts2019-yocto/06_0006-For-GVT-d-on-EHL-and-ICL-remove-VTD-activity.patch, bsp_diff/caas/kernel/lts2019-yocto/07_0007-Add-AB24-support-for-virtio-on-Android.patch, bsp_diff/caas/kernel/lts2019-yocto/08_0008-Bluetooth-SCO-USB-driver.patch, bsp_diff/caas/kernel/lts2019-yocto/09_0009-Add-a-item-in-get_param-IOCTL-for-query-GVT-active.patch, bsp_diff/caas/kernel/lts2019-yocto/10_0010-uvc-Add-UVC-GET_DEF-probe-quirk-for-C922-camera.patch, bsp_diff/caas/kernel/lts2019-yocto/11_0011-Fix-HDMI-audio-for-EHL.patch
Ported kernel diff partches from Android 10 branch.
Tracked-On: OAM-92995
=> Add lts2019-chromium and lts2019-yocto kernel diff patches

bsp_diff/caas/kernel/lts2019-chromium/10_0010-mm-hugetlb-fix-a-race-between-hugetlb-sysctl-handler.patch, bsp_diff/caas/kernel/lts2019-chromium/11_0011-rbd-require-global-CAP_SYS_ADMIN-for-mapping-and-unm.patch, bsp_diff/caas/kernel/lts2019-yocto/12_0012-mm-hugetlb-fix-a-race-between-hugetlb-sysctl-handler.patch, bsp_diff/caas/kernel/lts2019-yocto/13_0013-rbd-require-global-CAP_SYS_ADMIN-for-mapping-and-unm.patch
=> Patches for CVE issues CVE-2020-25285 and CVE-2020-25284

aosp_diff/caas/hardware/interfaces/03_0003-Add-support-for-advanced-USB-3.x-based-Cameras.patch, aosp_diff/caas/hardware/interfaces/04_0004-Retry-device-nodes-reading.patch
Signed-off-by: Shiva Kumara <shiva.kumara.rudrappa@intel.com>
Signed-off-by: kbillore <kaushal.billore@intel.com>
=> patch porting from android Q to R

autopatch.sh
Change-Id: Idb8ed8bab62bd883cdaa2eb7b664bb845e65f28e
Tracked-On: OAM-93064
Signed-off-by: Amalendu Prasad Das <amalendu.prasad.das@intel.com>
=> improvement autopatch script

bsp_diff/caas/kernel/lts2019-chromium/13_0013-net-packet-fix-overflow-in-tpacket_rcv.patch, bsp_diff/caas/kernel/lts2019-yocto/14_0014-net-packet-fix-overflow-in-tpacket_rcv.patch
=> Fix for kernel CVE issue CVE-2020-14386

aosp_diff/caas/frameworks/base/03_0001-Handle-simultaneous-HDMI-WiredHeadphone-events.patch, aosp_diff/preliminary/packages/apps/Gallery2/03_669505_1-Fix-the-audio-and-video-flicker-problem-when-seeking.patch
Fixing audio and video flicker during seek.
Tracked-On: OAM-92734
Signed-off-by: Mandri, Padmashree <padmashree.mandri@intel.com>
=> Fix audio and video flicker during seek.

bsp_diff/caas/kernel/lts2019-chromium/14_0014-ext4-fix-potential-negative-array-index-in-do_split.patch, bsp_diff/caas/kernel/lts2019-yocto/15_0015-ext4-fix-potential-negative-array-index-in-do_split.patch
=> Fix for CVE issue CVE-2020-14314

aosp_diff/caas/bootable/recovery/01_0001-Support-ota-update-from-udisk.patch
Tracked-On: OAM-93149
Signed-off-by: Xihua Chen <xihua.chen@intel.com>
=> Add support ota update from udisk

aosp_diff/preliminary/build/soong/0004-Add-lowerswitch-to-cflags.patch, aosp_diff/preliminary/libcore/0001-Source-optimizations-in-luni.patch
- Add lowerswitch to cflags
- Source optimizations in luni
Tracked-On: OAM-94354
=> Porting below cic patches to Android 11

aosp_diff/preliminary/bootable/recovery/01_0001-Support-ota-update-from-udisk.patch
Tracked-On: OAM-94480
Signed-off-by: Xihua Chen <xihua.chen@intel.com>
=> Fix bug of ota update from udisk

aosp_diff/preliminary/art/02_0001-Read-isa-features-from-compiler-options-in-codegen.patch
Tracked-On: OAM-94505
Signed-off-by: shalini.salomi.bodapati <shalini.salomi.bodapati@intel.com>
=> Read isa features from compiler options in codegen

host/kernel/lts2019-chromium/build.sh, host/kernel/lts2019-chromium/build_weekly.sh
Immediately exit the build script if failed to apply patches.
Tracked-On: OAM-94572
Signed-off-by: Yadong Qi <yadong.qi@intel.com>
=> Exit the build script if failed to apply patches

aosp_diff/preliminary/bootable/recovery/02_0002-fastbootd-sleep-several-seconds-to-wait-for-ethernet.patch
Tracked-On: OAM-95299
Signed-off-by: Chen Gang G <gang.g.chen@intel.com>
=> fastbootd: Workaround patch to enable userspace fastboot over ethernet

bsp_diff/common/kernel/lts2019-chromium/05_0005-Bluetooth-SCO-USB-driver.patch, bsp_diff/common/kernel/lts2019-chromium/28_0028-Fix-to-make-BT-Chip-boot-with-latest-firmware-every-.patch
=> Resolve kernel conflict issues releted to BTSCO driver

aosp_diff/preliminary/art/04_0004-Modify-IA-perf-variant-of-library-to-have-same-name-.patch, aosp_diff/preliminary/build/soong/0006-Add-support-for-overide_lib_name-for-IA-perf-variant.patch, aosp_diff/preliminary/frameworks/av/04_0004-Modify-IA-Perf-variants-of-library-to-have-same-name.patch, aosp_diff/preliminary/frameworks/ml/02_0002-Modify-IA-perf-variant-of-library-to-have-same-name-.patch, aosp_diff/preliminary/frameworks/rs/02_0002-Modify-IA-Perf-variants-of-library-to-have-same-name.patch
=> Add support to have override lib name for IA-perf variants of lib

aosp_diff/preliminary/hardware/interfaces/0001-Enable-AIDL-interface-for-Light-HAL.patch
=> Enable AIDL Interface for Lights HAL

host/kernel/lts2019-chromium/0004-Revert-UPSTREAM-drm-i915-Force-state-modeset-true-wh.patch
=> Revert patch causing host boot with tgl

aosp_diff/preliminary/hardware/interfaces/0001-Fix-audio-crash-issue.patch, aosp_diff/preliminary/packages/apps/Settings/01_0001-Add-settings-screen-to-set-ethernet-proxy-host-and-p.patch
=> AOSP rebase  android-11.0.0_r27 changes to utils

host/qemu/0002-qemu-change-fence-poll-time-by-current-workload.patch
This will improve performance while waiting the fence in 3D renderering
Tracked-On: OAM-95756
Signed-off-by: Kanli Hu <kanlix.hu@intel.com>
=> qemu: change fence poll time by current workload

aosp_diff/preliminary/system/netd/01_0001-Do-not-destroy-adb-socket-when-it-is-running-over-TC.patch, aosp_diff/preliminary/system/sepolicy/01_0001-Allow-vendor_init-to-set-service.adb.tcp.port.patch, aosp_diff/preliminary/system/sepolicy/02_0002-Fix-sepolicy-to-netd.patch
=> Google Test patches for Ikev2Vpn test

aosp_diff/preliminary/frameworks/base/04_0004-Stop-keeping-freeform-activities-visible.patch
=>  AOSP Patch to fix cts issue

aosp_diff/preliminary/external/drm_hwcomposer/0001-update-drm-hwcomposer.patch
update drm-hwcomposer from freedesktop
git clone https://gitlab.freedesktop.org/drm-hwcomposer/drm-hwcomposer/
commit:
fa0023394b883cf77dc26365041e9f3d95a21157
composer@2.4 HAL support
Tracked-On: OAM-96352
Signed-off-by: Kanli Hu <kanlix.hu@intel.com>
=> drm_hwcomposer: composer@2.4 HAL support

aosp_diff/preliminary/bionic/08_0008-Fixing-stpncpy-implementation.patch
=> Fixing stpncpy implementation

bsp_diff/common/vendor/intel/external/project-celadon/dldt/01_0001-Changes-to-compile-libinference-and-its-dependencies.patch, bsp_diff/common/vendor/intel/external/project-celadon/dldt/02_0002-Changes-to-fix-compatibility-issues-with-ngraph-ops.patch, bsp_diff/common/vendor/intel/external/project-celadon/mkl-dnn/01_0001-Add-mkl-dnn-version-header-and-Android.bp-file.patch
Tracked-On: OAM-96219
Signed-off-by: Jaikrishna Nemallapudi <nemallapudi.jaikrishna@intel.com>
=> Update inference libraries to OV-2021.2

autopatch.sh
Pass git name as $1 and get patches applied only for that git
Tracked-On: OAM-96467
=> Improve autopatch.sh to allow apply patch for selected git

bsp_diff/common/kernel/lts2019-chromium/17_0017-replace-cond_resched-with-usleep_range-to-avoid-dead.patch
Signed-off-by: feijiang1 <fei.jiang@intel.com>
=> replace cond_resched with usleep_range to avoid deadlock

aosp_diff/preliminary/hardware/interfaces/0001-Porting-light-HIDL-implement-to-AIDL-side.patch
Tracked-On: OAM-95912
Signed-Off-By: Liu, Yuanzhe <yuanzhe.liu@intel.com>
=> Porting light HIDL implement to AIDL side

aosp_diff/preliminary/frameworks/base/20_0020-Fix-for-testPinnedStackInBoundsAfterRotation.patch
=>  Fix for testPinnedStackInBoundsAfterRotation CTS test

aosp_diff/preliminary/frameworks/av/10_0010-Improve-handling-MediaCodec-linkToDeath-resource-man.patch
=> ASB patch from May-2021 bulletin

autopatch.sh
Update the autopatch script to consider
only the first occurance of "Date:"
Tracked-On: OAM-97168
=> Update in autopatch script

aosp_diff/preliminary/frameworks/base/28-0028-WA-Aquire-wakelock-when-BluetoothManagerService-retr.patch, bsp_diff/common/kernel/lts2019-chromium/22-0022-btusb-add-prepare-suspend-blocker.patch
=> btusb: add prepare suspend blocker

bsp_diff/common/vendor/intel/external/project-celadon/dldt/03_0003-Changed-threading-to-oneTBB-for-InferenceEngine.patch, bsp_diff/common/vendor/intel/external/project-celadon/mkl-dnn/02_0002-Changed-threading-to-oneTBB-for-MKL-DNN.patch, bsp_diff/common/vendor/intel/external/project-celadon/oneTBB/01_0001-Changes-to-compile-oneTBB-for-Android.patch
- Changed default threading OMP to TBB
- Compiled oneTBB for Android
Tracked-On: OAM-97456
Signed-off-by: Nagamani Chennuboina <nagamani.chennuboina@intel.com>
=> Added support for oneTBB in openvino 2021.2

aosp_diff/preliminary/frameworks/native/01_0001-Use-BRGA-as-default-format-for-software-rendering.patch, bsp_diff/common/kernel/lts2019-chromium/04_0004-Add-AB24-and-AR24-support-for-virtio-on-Android.patch, bsp_diff/common/kernel/lts2019-yocto/07_0007-Add-AB24-and-AR24-support-for-virtio-on-Android.patch
=> Fix the software rendering color abnormal issue.

aosp_diff/preliminary/build/soong/0009-Adding-the-dpkg-deb-package-needed-to-create-deb.patch
Tracked-On: OAM-97473
Signed-off-by: "swaroopb <swaroop.balan@intel.com>"
=> New Lunch Target caas_var added for PGP

aosp_diff/preliminary/system/libvintf/0001-REVERT-ME-Disable-kernel-compatibility-check.patch, bsp_diff/common/kernel/lts2020-yocto/02_679376_1-make-vmmouse-report-relative-values.patch, bsp_diff/common/kernel/lts2020-yocto/03_0003-greybus-Remove-Android.mk.patch, bsp_diff/common/kernel/lts2020-yocto/05_0005-Bluetooth-SCO-USB-driver.patch, bsp_diff/common/kernel/lts2020-yocto/06_0006-uvc-Add-UVC-GET_DEF-probe-quirk-for-C922-camera.patch, bsp_diff/common/kernel/lts2020-yocto/07_0007-btusb-snd-crash-while-disconnect.patch, bsp_diff/common/kernel/lts2020-yocto/08_0008-Bluetooth-btusb-Add-reset-on-close-quirk-for-Intel-a.patch, bsp_diff/common/kernel/lts2020-yocto/09_0009-9p-freezing-aborts-when-use-wait_event_killable.patch, bsp_diff/common/kernel/lts2020-yocto/10_0010-iwlwifi-Vendor-command-support-in-iwlwifi-driver.patch, bsp_diff/common/kernel/lts2020-yocto/11_0011-x86-e820-fix-the-function-type-for-e820__mapped_all.patch, bsp_diff/common/kernel/lts2020-yocto/12_0012-x86-relocs-Ignore-L4_PAGE_OFFSET-relocations.patch, bsp_diff/common/kernel/lts2020-yocto/13_0013-replace-cond_resched-with-usleep_range-to-avoid-dead.patch, bsp_diff/common/kernel/lts2020-yocto/14_0014-Use-clang-toolchain-from-prebuilts-instead-of-gcc.patch
=> kernel: Add diff patches for lts2020-yocto

bsp_diff/caas_cfc/kernel/lts2019-chromium/0001-Add-kvmfr-kernel-changes.patch
This is to help add KVMFR kernel module
Tracked-On: OAM-98135
=> Add kvmfr kernel support

host/lg/0001-UPSTREAM-common-fix-build-for-newer-versions-of-binu.patch, host/lg/0002-INTERNAL-Don-t-close-LG-client-when-spice-is-disconn.patch, host/lg/0003-INTERNAL-Fix-spice-fouce-issue.patch, host/lg/0004-INTERNAL-Add-support-for-dynamic-window-name.patch, host/lg/0005-INTERNAL-Flag-LG-client-is-ready-to-receive-frame.patch, host/lg/0006-Add-support-for-virtual-input.patch, host/lg/0007-INTERNAL-Remove-debug-info-log.patch, host/lg/0008-When-frame-is-rotated-rotate-it-in-shader.patch, host/lg/0009-Exchange-Width-and-Height-when-rotating.patch, host/lg/0010-INTERNAL-Improve-LG-Client-performace.patch, host/lg/0011-Add-clipboard-support-over-vsock.patch, host/lg/0012-Handle-XError-gracefully-to-avoid-crash.patch, host/lg/0013-Add-input-support-in-Landscape-from-Rotate-operation.patch, host/lg/0014-Revert-Add-input-support-in-Landscape-from-Rotate-op.patch
This is to help add LG Client changes
Tracked-On: OAM-98189
=> Add LG Client changes for PGP

aosp_diff/caas/build/make/0001-use-a-dynamic-timestamp.patch
Signed-off-by: jialei.feng <jialei@otc-aes-1604>
=> [NOT MERGE] use a dynamic timestamp

aosp_diff/preliminary/external/libavc/02_0002-Decoder-Update-check-for-increment-u2_cur_slice_num.patch, aosp_diff/preliminary/external/skia/01_0001-Only-treat-PNG_COLOR_TYPE_RGB-as-565.patch, aosp_diff/preliminary/frameworks/base/18_0018SubscriptionGroup-is-exposed-to-unprivileged-callers.patch, aosp_diff/preliminary/frameworks/base/19_0019-Fix-race-condition-between-lockNow-and-updateLockscr.patch, aosp_diff/preliminary/frameworks/base/20_0020-Remove-ParsedIntentInfo-CREATOR.patch, aosp_diff/preliminary/frameworks/base/21_0021-BG-FGS-start-while-in-use-permission-restriction-imp.patch, aosp_diff/preliminary/frameworks/base/22_0022-DO-NOT-MERGE-Add-cross-user-check-for-getDefaultSmsP.patch, aosp_diff/preliminary/frameworks/base/23_0023-Fix-side-effects-of-trace-ipc-and-dumpheap-commands.patch, aosp_diff/preliminary/frameworks/base/24_0024-Improve-ellipsize-performance.patch, aosp_diff/preliminary/frameworks/base/25_0025-Avoid-locking-profile-task-when-it-is-already-lock.patch, aosp_diff/preliminary/frameworks/base/26_0026-Don-t-attach-private-Notification-to-A11yEvent-when-.patch, aosp_diff/preliminary/frameworks/base/27_0027-Don-t-export-HeapDumpProvider.patch, aosp_diff/preliminary/frameworks/base/28_0028-Use-IntentFilter-CREATOR-directly-for-serializing-Pa.patch, aosp_diff/preliminary/frameworks/native/02_0002-Do-not-modify-vector-after-getting-references.patch, aosp_diff/preliminary/frameworks/opt/telephony/02_0002-filter-deviceIdentifiers-for-subscriptionInfo-if-cal.patch, aosp_diff/preliminary/frameworks/opt/telephony/03_0003-SubscriptionGroup-is-exposed-to-unprivileged-callers.patch, aosp_diff/preliminary/packages/apps/Launcher3/01_0001-Set-FLAG_IMMUTABLE-flag-on-FirstScreenBroadcast-Pend.patch, aosp_diff/preliminary/packages/apps/Nfc/04_0004-Add-HIDE_NON_SYSTEM_OVERLAY_WINDOWS-permission-to-Nf.patch, aosp_diff/preliminary/packages/apps/Settings/09_0009-RESTRICT-AUTOMERGE-Update-string.patch, aosp_diff/preliminary/packages/apps/Settings/10_0010-RESTRICT-AUTOMERGE-Fix-phishing-attacks-over-Bluetoo.patch, aosp_diff/preliminary/system/sepolicy/07_0007-system_app-remove-adb-data-loader-permissions.patch
=> Integrate Sep 2021 ASB patches

aosp_diff/preliminary/system/bt/0003-Fix-for-crash-during-SDP-due-to-garbage-memory-acces.patch
=> Fix for crash during SDP due to garbage memory access

aosp_diff/preliminary/system/linkerconfig/02_0002-add-namespace-change-for-houdini.patch
Signed-off-by: kexx <xiaox.ke@intel.com>
=> namespace change for houdini

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch
=> Update security_patch_level string

host/kernel/lts2019-chromium/build_weekly.sh
=> Update commit hash to include fix for CVE-2021-37159

host/lg/0016-Add-Fullscreen-input-support-for-looking-glass.patch
=> Add input support in fullscreen window

aosp_diff/caas_cfc/frameworks/base/0001-Allow-clipboard-access-to-intel-packages.patch
=> Port PGP copy paste to caas_cfc target

bsp_diff/common/hardware/interfaces/thermal/0001-Fix-for-VTS-issue-in-thermal.patch
Tracked-On: OAM-99289
Signed-off-by: Deepa G K <g.k.deepa@intel.com>
=> remove 1.0 service from rc file

bsp_diff/common/kernel/lts2019-chromium/23-0023-iwl7000-Update-header-config-to-allow-older-fw-versi.patch
Tracked-On: OAM-99180
Signed-off-by: Bharat B Panda <bharat.b.panda@intel.com>
=> Update header config to allow older fw

aosp_diff/preliminary/system/sepolicy/08_0008-Allow-tcp-socket-permission-for-sensor-domain.patch
Tracked-On: OAM-97787
Signed-off-by: Jaikrishna Nemallapudi <nemallapudi.jaikrishna@intel.com>
=> Allow sensor domain to use tcp_socket

autopatch.sh
Tracked-On: OAM-98783
Signed-off-by: Sivaramakrishnan, UdhayanX <udhayanx.sivaramakrishnan@intel.com>
=> support_lunch for vertical_prod patches

aosp_diff/preliminary/external/drm_hwcomposer/0005-Fix-drm-hwc-import-buffer-failure-issue.patch
Set format is DRM_FORMAT_NV12 if DRM_FORMAT_NV12_Y_TILED_INTEL.
Don't close the same handle several times.
Tracked-On: OAM-99497
Signed-off-by: Li, HaihongX <haihongx.li@intel.com>
=> Fix drm-hwc import buffer failure issue

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/robolectric-shadows/01_0001-Add-implementation-for-UserManager-getAllProfiles.patch, aosp_diff/preliminary/external/sonivox/01_0001-sonivox-Fix-global-buffer-overflow-in-WT_Interpolate.patch, aosp_diff/preliminary/frameworks/base/33_0033-Send-targeted-broadcasts-to-prevent-other-apps-from-.patch, aosp_diff/preliminary/frameworks/base/34_0034-Make-sure-that-only-the-owner-can-call-stopVpnProfil.patch, aosp_diff/preliminary/frameworks/base/35_0035-camera2-Fix-exception-swallowing-in-params-classes-c.patch, aosp_diff/preliminary/frameworks/base/36_0036-Fix-parsing-code-parcelling-errors.patch, aosp_diff/preliminary/frameworks/base/37_0037-Bluetooth-Fix-formatting-in-getAlias.patch, aosp_diff/preliminary/frameworks/base/38_0038-Backporting-the-change-of-ag-15629060-to-rvc-dev.patch, aosp_diff/preliminary/frameworks/base/39_0039-Changed-INTERACT_ACROSS_PROFILES-appop-to-be-set-per.patch, aosp_diff/preliminary/frameworks/native/03_0003-libbinder-uptimeMillis-returns-int64_t-am-3ba4963f5b.patch, aosp_diff/preliminary/hardware/nxp/nfc/01_0001-OOBW-in-phNxpNciHal_process_ext_rsp.patch, aosp_diff/preliminary/packages/apps/Contacts/02_0002-Add-permission-to-start-NFC-activity-to-ensure-it-is.patch, aosp_diff/preliminary/packages/apps/ManagedProvisioning/01_0001-Grant-MANAGE_APP_OPS_MODES-to-Managed-Provisioning.patch, aosp_diff/preliminary/packages/apps/ManagedProvisioning/02_0002-Fix-INTERACT_ACROSS_PROFILES-appop-issue-for-shared-.patch
=> Integrate Nov 2021 ASB Patches

bsp_diff/common/kernel/lts2019-chromium/25_0025-iwl7000-Vendor-command-support-in-iwl7000-driver.patch
Tracked-On: OAM-99914
Signed-off-by: Basanagouda Koppad <basanagoudax.n.koppad@intel.com>
=> iwl7000 vendor commands support drv, fw

bsp_diff/common/kernel/lts2019-chromium/25_0025-iwl7000-Vendor-command-support-in-iwl7000-driver.patch
Tracked-On: OAM-10056
Signed-off-by: Basanagouda Koppad <basanagoudax.n.koppad@intel.com>
=> iwl7000 vendor command support fw, drv

aosp_diff/caas_cfc/packages/apps/Settings/0001-w-a-return-allowed-for-external-source-installation.patch
Tracked-On: OAM-99953
Signed-off-by: Ruan, Hongfu <hongfu.ruan@intel.com>
=> add w/a patch to return allowed for external app installation

aosp_diff/caas_cfc/frameworks/av/0002-Fix-volume-to-max.patch
Sets all audio stream volumes to maximum
Tracked-On: OAM-99971
Signed-off-by: pmandri <padmashree.mandri@intel.com>
=> Set audio volume to maximum

autopatch.sh
support_lunch for vertical_priv_prod patches in tpy branch
Creating Support to pullpatches from /vendor/intel/utils_vertical_priv_prod
Tracked-On: OAM-100064
Signed-off-by: Sivaramakrishnan, UdhayanX <udhayanx.sivaramakrishnan@intel.com>
=> support_lunch for vertical_priv_prod patches in tpy branch

aosp_diff/preliminary/external/drm_hwcomposer/0006-fix-static-bound-to-dynamically-bound.patch
Tracked-On:OAM-99492
Signed-off-by: Xiao HaowenX <haowenx.xiao@intel.com>
=> fix crtc connector static bound to dynamically bound

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/tremolo/0001-handle-cases-where-order-isn-t-a-multiple-of-dimensi.patch, aosp_diff/preliminary/frameworks/av/08_0008-Fix-heap-buffer-overflow-in-MPEG4Extractor-am-d13a4e.patch, aosp_diff/preliminary/frameworks/av/09_0009-C2SoftMp3Dec-fix-OOB-write-in-output-buffer.patch, aosp_diff/preliminary/frameworks/base/40_0040-Change-ownership-of-the-account-request-notification.patch, aosp_diff/preliminary/frameworks/base/41_0041-Fix-NPE-on-getTitle.patch, aosp_diff/preliminary/frameworks/base/42_0042-Fix-serialization-bug-in-GpsNavigationMessage.patch, aosp_diff/preliminary/frameworks/base/43_0043-Do-not-show-the-notification-footer-until-the-user-i.patch, aosp_diff/preliminary/frameworks/base/45_0045-Disallow-overlays-for-ResolverActivity.patch, aosp_diff/preliminary/packages/apps/Contacts/03_0003-Address-photo-editing-security-bug.patch, aosp_diff/preliminary/packages/apps/KeyChain/01_0001-DO-NOT-MERGE-Hide-overlay-on-KeyChainActivity.patch, aosp_diff/preliminary/packages/apps/KeyChain/02_0002-DO-NOT-MERGE-KeyChain-protect-against-overlays.patch, aosp_diff/preliminary/packages/apps/Nfc/05_0005-OOBW-due-to-incorrect-error-handling.patch, aosp_diff/preliminary/packages/apps/QuickSearchBox/01_0001-Secure-the-pendingIntent-in-SearchWidgetProvider.patch, aosp_diff/preliminary/packages/apps/Settings/11_0011-BluetoothSecurity-Add-BLUETOOTH_PRIVILEGED-permissio.patch, aosp_diff/preliminary/packages/providers/ContactsProvider/01_0001-Fix-issue-with-call-log-last-modified-not-being-upda.patch, aosp_diff/preliminary/packages/providers/MediaProvider/01_0001-Fix-use-after-free-bug-in-FuseDaemon.patch, aosp_diff/preliminary/system/bt/04_0004-osi-Prevent-memory-allocations-with-MSB-set.patch, aosp_diff/preliminary/system/tools/aidl/01_0001-An-enum-is-initialized-as-zero-if-it-doesn-t-have-de.patch
=> Integrate Dec 2021 ASB Patches

aosp_diff/caas_cfc/frameworks/base/0001-change-policy-of-REQUEST_INSTALL_PACKAGES-to-ALLOWED.patch
this is required for 3rd-party app upgrade.
Tracked-On: OAM-100139
Signed-off-by: Ruan, Hongfu <hongfu.ruan@intel.com>
=> change policy of REQUEST_INSTALL_PACKAGES to ALLOWED

host/lg/0021-keyboard-input-support-for-multi-windows.patch
keyboard input support for multi-APP(multi-windows).
keyboard virtual input device support for PGP
Tracked-On: OAM-100023
=> keyboard input support for multi-APP(multi-windows).

host/kernel/lts2019-chromium/build_weekly.sh
=> kernel: Update commit hash in build script

bsp_diff/caas_cfc/vendor/intel/external/project-celadon/camera-vhal/0003-Add-check-bit-for-every-frame-recv.patch
Need the aligned stream on host with this
change
=> New change to check valid frame

aosp_diff/preliminary/bootable/recovery/0001-Do-not-write-past-end-of-inotify-event-structure.patch, aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/10_0010-SimpleDecodingSource-Prevent-OOB-write-in-heap-mem.patch, aosp_diff/preliminary/frameworks/base/46_0046-Prevent-apps-from-spamming-addAccountExplicitly.-See.patch, aosp_diff/preliminary/frameworks/base/47_0047-Allow-forcing-status-bar-state-changes-and-do-so-whe.patch, aosp_diff/preliminary/frameworks/base/48_00048-Revert-Revert-pm-remove-old-stage-dirs-on-low-storag.patch, aosp_diff/preliminary/frameworks/native/04_0004-avoid-extra-release-of-unowned-objects-in-Parcel-err.patch, aosp_diff/preliminary/frameworks/opt/telephony/04_0004-fix-the-issue-that-clearCallingIdentity-before-appop.patch, aosp_diff/preliminary/frameworks/opt/telephony/05_0005-filter-deviceIdentifiers-for-subscriptionInfo-if-cal.patch, aosp_diff/preliminary/hardware/nxp/nfc/02_0002-Use-after-free-in-phTmlNfc_TmlThread.patch, aosp_diff/preliminary/packages/apps/Dialer/0001-Add-FLAG_IMMUTABLE-to-PendingIntent-in-LegacyModeSms.patch, aosp_diff/preliminary/packages/apps/Dialer/01_0001-Add-FLAG_IMMUTABLE-to-PendingIntent-in-LegacyModeSms.patch, aosp_diff/preliminary/packages/apps/Settings/12_0012-RESTRICT-AUTOMERGE-Fix-make-Bluetooth-discoverable-w.patch
=> Integrate JAN-2022 ASB patches

aosp_diff/caas_cfc/frameworks/base/03_0003-Add-whitelist-permissions-to-clipboardagent-privapp.patch
=> Add whitelist permissions to clipboardagent privapp

host/kernel/lts2020-chromium/build_weekly.sh
Weekly build script updated with 5.10.91 commit hash
Tracked-On: OAM-100742
=> kernel: Update build script for ref host kernel v5.10.91

bsp_diff/common/kernel/lts2020-chromium/19_0019-Add-support-for-AX211-GarfieldPeak-Gfp.patch
=> Add HFP support for AX211 GarfieldPeak (Gfp)

aosp_diff/caas_cfc/system/sepolicy/0001-Update-policy-for-media-provider.patch, bsp_diff/caas_cfc/device/intel/sepolicy/0001-Allow-wechat-to-access-9p-share-folder.patch
Defined p9fs2 in public folder
Allow mediaprovider to access 9p sharefolder
Tracked-On: OAM-100644
Signed-off-by: Ai, Ting <ting.a.ai@intel.com>
=> Update media provider policy

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/libavc/01_0001-Move-slice-increments-after-completing-header-parsin.patch, aosp_diff/preliminary/frameworks/av/06_0006-Better-buffer-overrun-prevention.patch, aosp_diff/preliminary/frameworks/av/07_0007-Safetynet-logging-for-b-204445255.patch, aosp_diff/preliminary/frameworks/av/08_0008-Prevent-out-of-bounds-read.patch, aosp_diff/preliminary/frameworks/base/05_0005-Add-missing-size-check-when-parsing-staged-aliases.patch, aosp_diff/preliminary/frameworks/base/06_0006-Controls-Do-not-recreate-intent.patch, aosp_diff/preliminary/packages/apps/ManagedProvisioning/01_0001-Fix-Managed-Provisioning-crash-on-OTA.patch, aosp_diff/preliminary/packages/apps/Settings/01_0001-Rephrase-dialog-message-of-clear-storage-dialog-for-.patch, aosp_diff/preliminary/packages/apps/Settings/02_0002-Add-non-system-overlay-flag-to-InstallCaCertificateW.patch, aosp_diff/preliminary/packages/apps/Settings/03_0003-Import-translations.-DO-NOT-MERGE-ANYWHERE.patch, aosp_diff/preliminary/packages/providers/MediaProvider/01_0001-Handle-content-uris-without-id-in-checkUriPermission.patch, aosp_diff/preliminary/system/bt/03_0003-security-Use-After-Free-in-btm_sec_-dis-connected.patch, aosp_diff/preliminary/system/bt/04_0004-Reset-the-IRK-after-all-devices-are-unpaired.patch, aosp_diff/preliminary/system/nfc/01_0001-Tag-mismatch-in-NFA_SendRawFrame.patch, aosp_diff/preliminary/system/tools/aidl/01_0001-Revert-Revert-Add-automatic-default-value-for-char-t.patch, aosp_diff/preliminary/system/tools/aidl/02_0002-Fix-sc-dev-plus-aosp-builds.patch
=> Integrate FEB-2022 ASB patches

host/lg/0022-keyboard-input-support-to-move-cursor-by-left-and-ri.patch
PGP keyboard input keys for left, right, up, down.
Tracked-On: OAM-100842
=> keyboard input support to move cursor by left and right keys

host/lg/0023-PGP-classin-blackboard-unaccepted-input-issue.patch
defined exact range for input coordinates.
Tracked-On: OAM-100934
=> PGP classin blackboard unaccepted input issue.

host/ovmf/0001-OvmfPkg-add-IgdAssignmentDxe.patch, host/qemu/0001-Revert-Revert-vfio-pci-quirks.c-Disable-stolen-memor.patch, host/qemu/0002-qemu-change-fence-poll-time-by-current-workload.patch, host/qemu/0003-Disable-EDID-auto-generation-in-QEMU.patch
=> Upgrade the qemu 4.2 to 6.0 patches

bsp_diff/common/kernel/lts2020-chromium/08_0008-Bluetooth-btusb-Add-reset-on-close-quirk-for-Intel-a.patch, bsp_diff/common/kernel/lts2020-chromium/18_0018-iwl7000-Add-driver-and-firmware-version-query-suppor.patch, host/kernel/lts2020-chromium/0006-Fix-device-hang-on-TGL-RVP.patch, host/kernel/lts2020-chromium/build_weekly.sh
=> kernel: Update bsp_diff patches for v5.10.101 rebase

aosp_diff/caas_cfc/frameworks/base/0007-Add-display-Id-of-calling-app-when-starting-activity.patch, aosp_diff/caas_cfc/frameworks/base/0008-Fixed-the-activity-showed-in-another-display-issue.patch, aosp_diff/caas_cfc/frameworks/base/0009-Fixed-the-toast-showed-in-wrong-display-issue.patch
Fixed activity showed in wrong display issue;
Fixed toast showed in wrong display issue;
Fixed activity launched by backend service showed in wrong display issue.
=> 0211 mdm fixes

host/kernel/lts2020-yocto/0001-v1-vfio-pci-Add-support-for-opregion-v2.0.patch, host/kernel/lts2020-yocto/build.sh, host/kernel/lts2020-yocto/build_weekly.sh
=> Fix the GVT-d boot fail on ADL with hdmi/type-c port

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/13_0013-C2AllocatorIon-protect-mMappings-using-mutex.patch, aosp_diff/preliminary/frameworks/av/14_0014-Safe-parsing-of-HEIF-framecount-information.patch, aosp_diff/preliminary/frameworks/base/58_0058-Prevent-apps-from-creating-blocked-channel-groups.patch, aosp_diff/preliminary/frameworks/base/59_0059-Restrict-AdbManager-broadcasts-to-apps-with-MANAGE_DEBUGGING.patch, aosp_diff/preliminary/frameworks/base/60_0060-BG-FGS-start-while-in-use-permission-restriction-imp.patch, aosp_diff/preliminary/frameworks/base/61_0061-Add-hide-non-system-overlay-flag-for-HarmfulAppWarni.patch, aosp_diff/preliminary/packages/apps/Settings/18_0018-Do-not-let-guest-user-disable-secure-nfc.patch, aosp_diff/preliminary/packages/providers/MediaProvider/03_0003-Restrict-legacy-apps-to-insert-files-to-other-private.patch, aosp_diff/preliminary/system/bt/07_0007-Security-fix-OOB-read-due-to-invalid-count-in-stack-.patch
Tracked-On: OAM-101565
Signed-off-by: Senapati, Rasmiranjan <rasmiranjan.senapati@intel.com>
=> Integrate APR-2022 ASB patches

aosp_diff/caas_cfc/frameworks/base/05_0005-Add-visibilty-info-to-TaskInfo.patch
=> Add visibilty info to TaskInfo

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch
=> PAtch modified for r28 rebase

host/kernel/lts2020-chromium/build_weekly.sh
=> kernel: Update build script with commit hash for v5.10.110 rebase

host/qemu/0032-Adapt-APP-landscape-or-portrait-mode-display-dynamic.patch
Add one gtk button to set window to landscape/portrait
mode.
Tracked-On: OAM-101263
Signed-off-by: Chenglei Ren <chenglei.ren@intel.com>
=> Adapt APP landscape or portrait mode display dynamically

host/kernel/lts2020-chromium/build_weekly.sh
=> kernel: Update build script with latest commit hash for v5.10.110

host/kernel/lts2020-yocto/README, host/kernel/lts2020-yocto/build.sh
Also modify the build.sh file
Tracked-On: OAM-102123
=> Add lts2020-yocto kernel README file

bsp_diff/common/kernel/lts2019-chromium/22-0022-btusb-add-prepare-suspend-blocker.patch, bsp_diff/common/kernel/lts2019-chromium/25_0025-iwl7000-Vendor-command-support-in-iwl7000-driver.patch, host/kernel/lts2019-chromium/build_weekly.sh
=> kernel: Update bsp_diff patches for v5.4.150 rebase

aosp_diff/preliminary/hardware/interfaces/09_0009-Add-the-memtrack-AIDL-HAL-implement.patch, aosp_diff/preliminary/system/sepolicy/11_0011-Change-the-memtrack-aidl-hal-service-name.patch
=> Add the memtrack AIDL HAL implement

.github/workflows/Runchecks.yaml
Signed-off-by: tprabhu <vignesh.t.prabhu@intel.com>
=> Added github actions for basic checks

bsp_diff/celadon_ivi/device/intel/sepolicy/0001-Adding-car-UI-lunch-target.patch, bsp_diff/celadon_ivi/vendor/intel/external/project-celadon/camera-vhal/0001-civ-changes-on-top-of-vhal-changes.patch, bsp_diff/celadon_ivi/vendor/intel/external/project-celadon/camera-vhal/0002-VHAL-changes-for-orien-w.r.t-facing.patch, bsp_diff/celadon_ivi/vendor/intel/external/project-celadon/camera-vhal/0003-Add-check-bit-for-every-frame-recv.patch, bsp_diff/celadon_ivi/vendor/intel/external/project-celadon/camera-vhal/0004-VTS-fixes-on-VHAL.patch, bsp_diff/celadon_ivi/vendor/intel/external/project-celadon/camera-vhal/0005-moving-to-new-VHAL-for-multi-resolution.patch, bsp_diff/celadon_ivi/vendor/intel/external/project-celadon/camera-vhal/0006-mjpeg-support-for-mediation.patch
=> Adding car UI lunch target

.github/workflows/Runchecks.yaml
Signed-off-by: tprabhu <vignesh.t.prabhu@intel.com>
=> Added PR LABEL in workflow

bsp_diff/common/kernel/lts2020-yocto/22_0022-Operations-on-FB-during-suspend-resume-only-when-dis.patch, bsp_diff/common/kernel/lts2020-yocto/23_0023-CiV-SRIOV-virtio-gpu-power-management-kernel.patch, host/qemu/0033-CiV-SRIOV-virtio-gpu-power-management-qemu.patch
CiV SRIOV virtio-gpu power management
Tracked-On: OAM-102664
Signed-off-by: kanli.hu <kanli.hu@intel.com>
=> [CIV] SRIOV virtio-gpu PM.

bsp_diff/common/kernel/lts2020-yocto/24_0024-ACPI-PM-Propagate-power-button-event-to-user-space-w.patch, host/qemu/0033-CiV-SRIOV-virtio-gpu-power-management-qemu.patch
propagate power button event to user space.
remove logs in virtio-gpu suspend and resume
Tracked-On: OAM-102669
Signed-off-by: Kanli, Hu<kanli.hu@intel.com>
=> [CiV] SRIOV power management POWER event

host/kernel/lts2020-yocto/0002-drm-i915-iov-Fix-suspend-hibernate-when-VFs-are-enab.patch
Tracked-On: OAM-102734
Signed-off-by: Kanli, Hu<kanli.hu@intel.com>
=> [CiV] SRIOV power management host suspend and wakeup

host/kernel/lts2020-chromium/build_weekly.sh
=> kernel: Update build script with latest commit hash for v5.10.118

host/kernel/lts2020-chromium/build_weekly.sh
=> kernel: Update build script with latest commit hash

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/12_0012-Avoid-read-out-of-bounds.bulletin.patch, aosp_diff/preliminary/frameworks/base/47_0047--RESTRICT-AUTOMERGE-Only-allow-system-and-same-app-to-apply-.bulletin.patch, aosp_diff/preliminary/frameworks/base/48_0048-DO-NOT-MERGE-Suppress-notifications-when-device-enter-lockdo.bulletin.patch, aosp_diff/preliminary/frameworks/base/49_0049-Make-sure-callingPackage-belongs-to-callingUid-when-checking.bulletin.patch, aosp_diff/preliminary/frameworks/base/50_0050-Clear-mInterface-before-calling-resetIkeState-.bulletin.patch, aosp_diff/preliminary/frameworks/base/51_0051-DO-NOT-MERGE-Add-a-permissions-check-to-LocationManagerServ.bulletin.patch, aosp_diff/preliminary/frameworks/base/52_0052-Remove-package-title-from-notification-access-confirmation-i.bulletin.patch, aosp_diff/preliminary/frameworks/base/53_0053-Stop-using-invalid-URL-to-prevent-unexpected-crash.bulletin.patch, aosp_diff/preliminary/frameworks/base/54_0054-Only-allow-the-system-server-to-connect-to-sync-adapters.bulletin.patch, aosp_diff/preliminary/frameworks/native/05_0005-DO-NOT-MERGE-SurfaceControl-Ensure-unused-fields-are-zeroe.bulletin.patch, aosp_diff/preliminary/frameworks/native/06_0006-RESTRICT-AUTOMERGE-SurfaceFlinger-fix-a-potential-race-cond.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/13_0013-Verify-ringtone-from-ringtone-picker-is-audio.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/14_0014-RESTRICT-AUTOMERGE-Make-bluetooth-not-discoverable-via-Slice.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/15_0015-Do-not-let-guest-user-disable-secuer-nfc-via-SettingsSlice.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/16_0016-RESTRICT-AUTOMERGE-Fix-policy-enforcement-for-location-wifi.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/17_0017--DO-NOT-MERGE-Fix-Settings-crash-when-setting-a-null-ringto.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/18_0018--DO-NOT-MERGE-Fix-can-t-change-notification-sound-for-work-.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/19_0019-Extract-app-label-from-component-name-in-notification-access.bulletin.patch, aosp_diff/preliminary/system/bt/11_0011-l2cap-Verify-number-of-channels-in-the-CoC-request.bulletin.patch, aosp_diff/preliminary/system/bt/12_0012-Removing-bonded-device-when-auth-fails-due-to-missing-keys.bulletin.patch
=> Integrate AUGUST-2022 ASB patches to celadon_smr0_stable

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/15_0015-Avoid-read-out-of-bounds.bulletin.patch, aosp_diff/preliminary/frameworks/base/56_0056--RESTRICT-AUTOMERGE-Only-allow-system-and-same-app-to-apply-.bulletin.patch, aosp_diff/preliminary/frameworks/base/57_0057-DO-NOT-MERGE-Suppress-notifications-when-device-enter-lockdo.bulletin.patch, aosp_diff/preliminary/frameworks/base/58_0058-Make-sure-callingPackage-belongs-to-callingUid-when-checking.bulletin.patch, aosp_diff/preliminary/frameworks/base/59_0059-Clear-mInterface-before-calling-resetIkeState-.bulletin.patch, aosp_diff/preliminary/frameworks/base/60_0060-Remove-package-title-from-notification-access-confirmation-i.bulletin.patch, aosp_diff/preliminary/frameworks/base/61_0061--RESTRICT-AUTOMERGE-Prevent-set-intent-on-non-leaf-tasks.bulletin.patch, aosp_diff/preliminary/frameworks/base/62_0062-Stop-using-invalid-URL-to-prevent-unexpected-crash.bulletin.patch, aosp_diff/preliminary/frameworks/base/63_0063-Only-allow-the-system-server-to-connect-to-sync-adapters.bulletin.patch, aosp_diff/preliminary/frameworks/native/06_0006-RESTRICT-AUTOMERGE-SurfaceFlinger-fix-a-potential-ra.patch, aosp_diff/preliminary/packages/apps/Settings/22_0022--DO-NOT-MERGE-Verify-ringtone-from-ringtone-picker-is-audio.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/23_0023-RESTRICT-AUTOMERGE-Make-bluetooth-not-discoverable-via-Slice.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/24_0024-Do-not-let-guest-user-disable-secuer-nfc-via-SettingsSlice.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/25_0025-RESTRICT-AUTOMERGE-Fix-policy-enforcement-for-location-wifi.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/26_0026--DO-NOT-MERGE-Fix-Settings-crash-when-setting-a-null-ringto.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/27_0027--DO-NOT-MERGE-Fix-Settings-crash-when-setting-a-null-ringto.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/28_0028-Extract-app-label-from-component-name-in-notification-access.bulletin.patch, aosp_diff/preliminary/packages/services/Car/01_0001-Extract-app-label-from-component-name-in-notification-access.bulletin.patch, aosp_diff/preliminary/system/bt/11_0011-Removing-bonded-device-when-auth-fails-due-to-missing-keys.bulletin.patch
=> Integrate August-2022 ASB patches to R- stable branch

aosp_diff/preliminary/frameworks/base/47_0047-Add-whitelist-permissions-to-clipboardagent-privapp.patch, aosp_diff/preliminary/frameworks/base/48_0048-Allow-clipboard-access-to-intel-packages.patch
Making ClipboardAgent available horizontally.
=> Add whitelist permissions to ClipboardAgent privapp -- Horizontal patch

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/expat/01_0001-Prevent-integer-overflow-in-copyString.bulletin.patch, aosp_diff/preliminary/external/expat/02_0002-Prevent-XML_GetBuffer-signed-integer-overflow.bulletin.patch, aosp_diff/preliminary/external/expat/03_0003-Prevent-integer-overflow-in-function-doProlog.bulletin.patch, aosp_diff/preliminary/external/expat/04_0004-Prevent-more-integer-overflows.bulletin.patch, aosp_diff/preliminary/frameworks/av/13_0013-Fix-Out-of-Bounds-read-in-TextDescriptions-cpp.bulletin.patch, aosp_diff/preliminary/frameworks/base/55_0055-Fix-duplicate-permission-privilege-escalation.bulletin.patch, aosp_diff/preliminary/frameworks/base/56_0056-Parcel-recycle-recycles.bulletin.patch, aosp_diff/preliminary/frameworks/base/57_0057-Remove-package-name-from-SafetyNet-logs.bulletin.patch, aosp_diff/preliminary/packages/providers/MediaProvider/03_0003-DO-NOT-MERGE-Avoid-path-traversal-in-MediaProvider-delete-ca.bulletin.patch
=> Integrate September-2022 ASB patches to celadon_smr0_stable

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/expat/01_0001-Prevent-integer-overflow-in-copyString.bulletin.patch, aosp_diff/preliminary/external/expat/02_0002-Prevent-XML_GetBuffer-signed-integer-overflow.bulletin.patch, aosp_diff/preliminary/external/expat/03_0003-Prevent-integer-overflow-in-function-doProlog.bulletin.patch, aosp_diff/preliminary/external/expat/04_0004-Prevent-more-integer-overflows.bulletin.patch, aosp_diff/preliminary/frameworks/av/16_0016-Fix-Out-of-Bounds-read-in-TextDescriptions-cpp.bulletin.patch, aosp_diff/preliminary/frameworks/base/64_0064-Fix-duplicate-permission-privilege-escalation.bulletin.patch, aosp_diff/preliminary/frameworks/base/65_0065-Parcel-recycle-recycles.bulletin.patch, aosp_diff/preliminary/frameworks/base/66_0066-Remove-package-name-from-SafetyNet-logs.bulletin.patch, aosp_diff/preliminary/packages/providers/MediaProvider/04_0004-DO-NOT-MERGE-Avoid-path-traversal-in-MediaProvider-delete-ca.bulletin.patch
=> Integrate September-2022 ASB patches to R- stable branch

aosp_diff/preliminary/build/make/0004-Update-Security-patch-level.patch, aosp_diff/preliminary/packages/apps/Settings/0001-Make-bluetooth-not-discoverable-via-large-screen-deep-link-f.bulletin.patch, aosp_diff/preliminary/packages/modules/Wifi/0001-Prevent-restricted-user-from-adding-network-through-camera.bulletin.patch, aosp_diff/preliminary/packages/providers/MediaProvider/0001-DO-NOT-MERGE-Avoid-path-traversal-in-MediaProvider-delete-ca.bulletin.patch
=> Integrate SEP-2022 ASB patches to T-MR0-CELADON-MASTER

bsp_diff/celadon_tv/device/intel/mixins/0001-Include-multicamera-only-for-caas.patch, bsp_diff/celadon_tv/device/intel/mixins/0003-TrebleSysProptest-VendorPropertyNames-fix-in-mixin.patch, bsp_diff/celadon_tv/device/intel/mixins/0004-Revert-Include-VHAL-for-camera.patch, bsp_diff/celadon_tv/device/intel/project-celadon/caas/0001-mixin-up-diff-for-including-multicamapp.patch, bsp_diff/celadon_tv/device/intel/sepolicy/0003-TrebleSysProptest-VendorPropertyNames-fix-in-sepolic.patch
=> Copying utils for the new lunch target

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/dtc/01_0001-FROMGIT-libfdt-fdt_offset_ptr-Fix-comparison-warnings.bulletin.patch, aosp_diff/preliminary/frameworks/av/14_0014-Cache-MMAP-client-silenced-state-.bulletin.patch, aosp_diff/preliminary/frameworks/av/15_0015-Add-missing-bounds-checks.bulletin.patch, aosp_diff/preliminary/frameworks/base/58_0058-Restrict-getInputMethodWindowVisibleHeight.bulletin.patch, aosp_diff/preliminary/frameworks/base/59_0059-Block-FullScreenIntent-while-device-is-in-use-if-notificatio.bulletin.patch, aosp_diff/preliminary/frameworks/base/60_0060-Fix-Notification-redaction-when-power-cycling-a-non-dozing-d.bulletin.patch, aosp_diff/preliminary/frameworks/base/61_0061-DO-NOT-MERGE-Exclude-TYPE_PRIVATE_PRESENTATION-app-visibli.bulletin.patch, aosp_diff/preliminary/frameworks/base/62_0062-Enforce-zen-rule-limit-on-a-package-level-.bulletin.patch, aosp_diff/preliminary/hardware/interfaces/10_0010-Fix-array-out-of-bound-in-audioTransportToHal-.bulletin.patch, aosp_diff/preliminary/packages/providers/ContactsProvider/02_0002-enforce-stricter-CallLogProvider-query.bulletin.patch, aosp_diff/preliminary/system/bt/13_0013-Fix-potential-interger-overflow-when-parsing-vendor-response.bulletin.patch, aosp_diff/preliminary/system/nfc/04_0004-The-length-of-a-packet-should-be-non-zero.bulletin.patch
=> Security Patch (ASB) integration Oct-2022

aosp_diff/preliminary/art/0001-Modify-install-hook-check-in-art.patch, aosp_diff/preliminary/art/0002-Auto-Fast-JNI-Optimization.patch
ART-Runtime Patches
Tracked-On: OAM-101795
Signed-off-by: Priyanka Bose <priyanka.bose@intel.com>
=> ART-Runtime Patches

aosp_diff/preliminary/build/make/0004-Update-Security-patch-level.patch, aosp_diff/preliminary/external/dtc/0002-0001-Fix-integer-wrap-sanitisation-.bulletin.patch, aosp_diff/preliminary/frameworks/av/0006--Fix-vulnerability-setSecurityLevel-in-clearkey.bulletin.patch, aosp_diff/preliminary/frameworks/base/10_0010-Stop-crashing-the-system-on-hitting-the-alarm-limit.bulletin.patch, aosp_diff/preliminary/frameworks/base/11_0011-Revert-Revert-Limit-the-number-of-concurrently-snoozed-not.bulletin.patch, aosp_diff/preliminary/frameworks/base/12_0012-switch-TelecomManager-List-getters-to-ParceledListSlice.bulletin.patch, aosp_diff/preliminary/frameworks/base/13_0013-Move-accountname-and-typeName-length-check-from-Account-java.bulletin.patch, aosp_diff/preliminary/frameworks/base/14-0014-Do-not-send-new-Intent-to-non-exported-activity-when-navigat.bulletin.patch, aosp_diff/preliminary/frameworks/base/15_0015-Do-not-send-AccessibilityEvent-if-notification-is-for-differ.bulletin.patch, aosp_diff/preliminary/frameworks/base/16_0016-Update-BaseBundle-to-not-use-LazyValues-when-using-ReadWrite.bulletin.patch, aosp_diff/preliminary/frameworks/base/17_0017-Check-rule-package-name-in-ZenModeHelper-addAutomaticRule.bulletin.patch, aosp_diff/preliminary/frameworks/base/18_0018-Fix-auto-grant-of-AR-runtime-permission-if-device-is-upgradi.bulletin.patch, aosp_diff/preliminary/frameworks/base/19_0019-Trim-any-long-string-inputs-that-come-in-to-AutomaticZenRule.bulletin.patch, aosp_diff/preliminary/frameworks/base/20_0020-Remove-legacy-WRITE_EXTERNAL_STORAGE-permission-check-for-In.bulletin.patch, aosp_diff/preliminary/frameworks/base/21_0021-Do-not-dismiss-keyguard-after-SIM-PUK-unlock.bulletin.patch, aosp_diff/preliminary/frameworks/base/22_0022-Fix-system-zen-rules-by-using-owner-package-name-if-caller-i.bulletin.patch, aosp_diff/preliminary/hardware/nxp/nfc/0001-OOBW-in-phNxpNciHal_write_unlocked-.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0006-Add-local-to-pan_api-cc.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0007-Add-negative-length-check-in-process_service_search_rsp.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0008-Add-buffer-in-pin_reply-in-bluetooth-cc.bulletin.patch, aosp_diff/preliminary/packages/modules/Wifi/0002--DO-NOT-MERGE-wifi-remove-certificates-for-network-factory.bulletin.patch, aosp_diff/preliminary/packages/providers/TelephonyProvider/0001-Check-dir-path-before-updating-permissions-.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/0001-switch-TelecomManager-List-getters-to-ParceledListSlice.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/0002-Fix-security-vulnerability-issue-for-multi-user-call-redirec.bulletin.patch
=> ASB - Security Patch integration November 2022 - T-MR0-MASTER

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/dtc/02_0002-Fix-integer-wrap-sanitisation-.bulletin.patch, aosp_diff/preliminary/frameworks/av/16_0016--Fix-vulnerability-setSecurityLevel-in-clearkey.bulletin.patch, aosp_diff/preliminary/frameworks/base/63_0063-Stop-crashing-the-system-on-hitting-the-alarm-limit.bulletin.patch, aosp_diff/preliminary/frameworks/base/64_0064-DO-NOT-MERGE-Move-accountname-and-typeName-length-check-from.bulletin.patch, aosp_diff/preliminary/frameworks/base/65_0065-switch-TelecomManager-List-getters-to-ParceledListSlice.bulletin.patch, aosp_diff/preliminary/frameworks/base/66_0066--RESTRICT-AUTOMERGE-Do-not-send-new-Intent-to-non-exported-.bulletin.patch, aosp_diff/preliminary/frameworks/base/67_0067-Do-not-send-AccessibilityEvent-if-notification-is-for-differ.bulletin.patch, aosp_diff/preliminary/frameworks/base/68_0068-DO-NOT-MERGE-Fix-auto-grant-of-AR-runtime-permission-if-devi.bulletin.patch, aosp_diff/preliminary/frameworks/base/69_0069-Check-rule-package-name-in-ZenModeHelper-addAutomaticRule.bulletin.patch, aosp_diff/preliminary/frameworks/base/70_0070-Trim-any-long-string-inputs-that-come-in-to-AutomaticZenRule.bulletin.patch, aosp_diff/preliminary/frameworks/base/71_0071-Fix-system-zen-rules-by-using-owner-package-name-if-caller-i.bulletin.patch, aosp_diff/preliminary/frameworks/base/72_0072-Make-sure-parallel-broadcasts-enforce-excluded-permissions.bulletin.patch, aosp_diff/preliminary/frameworks/base/73_0073--DO-NOT-MERGE-Do-not-dismiss-keyguard-after-SIM-PUK-unlock.bulletin.patch, aosp_diff/preliminary/frameworks/base/74_0074-Limit-the-number-of-concurrently-snoozed-notificatio.patch, aosp_diff/preliminary/hardware/nxp/nfc/0001-OOBW-in-phNxpNciHal_write_unlocked-.bulletin.patch, aosp_diff/preliminary/packages/modules/Permission/04_0004-Hide-overlays-on-ReviewPermissionsAtivity.bulletin.patch, aosp_diff/preliminary/packages/modules/Wifi/0001--DO-NOT-MERGE-wifi-remove-certificates-for-network-factory.bulletin.patch, aosp_diff/preliminary/packages/providers/TelephonyProvider/0001-Check-dir-path-before-updating-permissions-.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/03_0003-switch-TelecomManager-List-getters-to-ParceledListSlice.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/04_0004-DO-NOT-MERGE-Fix-security-vulnerability-issue-for-multi-user.bulletin.patch, aosp_diff/preliminary/system/bt/14_0014-Add-negative-length-check-in-process_service_search_rsp.bulletin.patch, aosp_diff/preliminary/system/bt/15_0015-resolve-merge-conflicts-of-9c93920de7a8d8106a1bc2e11ebfed79d.bulletin.patch
=> ASB - Security Patch integration November 2022 - smr0_stable

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/dtc/02_0002-Fix-integer-wrap-sanitisation-am-61e10c9c53-am-5a3e448a22.bulletin.patch, aosp_diff/preliminary/frameworks/av/18_0018-RESTRICT-AUTOMERGE-Fix-vulnerability-setSecurityLevel-in.bulletin.patch, aosp_diff/preliminary/frameworks/base/73_0073-Limit-the-number-of-concurrently-snoozed-notifications.bulletin.patch, aosp_diff/preliminary/frameworks/base/74_0074-Stop-crashing-the-system-on-hitting-the-alarm-limit.bulletin.patch, aosp_diff/preliminary/frameworks/base/75_0075-switch-TelecomManager-List-getters-to-ParceledListSlice.bulletin.patch, aosp_diff/preliminary/frameworks/base/76_0076--RESTRICT-AUTOMERGE-Do-not-send-new-Intent-to-non-exported-.bulletin.patch, aosp_diff/preliminary/frameworks/base/77_0077-Do-not-send-AccessibilityEvent-if-notification-is-for-differ.bulletin.patch, aosp_diff/preliminary/frameworks/base/78_0078-DO-NOT-MERGE-Fix-auto-grant-of-AR-runtime-permission.patch, aosp_diff/preliminary/frameworks/base/79_0079-Check-rule-package-name-in-ZenModeHelper-addAutomaticRule.bulletin.patch, aosp_diff/preliminary/frameworks/base/80_0080-Trim-any-long-string-inputs-that-come-in-to-AutomaticZenRule.bulletin.patch, aosp_diff/preliminary/frameworks/base/81_0081--RESTRICT-AUTOMERGE-Check-permission-for-VoiceInteraction.bulletin.patch, aosp_diff/preliminary/frameworks/base/82_0082-Fix-system-zen-rules-by-using-owner-package-name-if-caller-i.bulletin.patch, aosp_diff/preliminary/frameworks/base/83_0083-DO-NOT-MERGE-Move-accountname-and-typeName-length-check-from.bulletin.patch, aosp_diff/preliminary/frameworks/base/84_0084--DO-NOT-MERGE-Do-not-dismiss-keyguard-after-SIM-PUK-unlock.bulletin.patch, aosp_diff/preliminary/frameworks/opt/net/wifi/03_0003--DO-NOT-MERGE-wifi-remove-certificates-for-network-factory.bulletin.patch, aosp_diff/preliminary/hardware/nxp/nfc/03_0003-OOBW-in-phNxpNciHal_write_unlocked-.bulletin.patch, aosp_diff/preliminary/packages/apps/PermissionController/01_0001-Hide-overlays-on-ReviewPermissionsAtivity.bulletin.patch, aosp_diff/preliminary/packages/providers/TelephonyProvider/01_0001-Check-dir-path-before-updating-permissions-.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/03_0003-switch-TelecomManager-List-getters-to-ParceledListSlice.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/04_0004-DO-NOT-MERGE-Fix-security-vulnerability-issue-for-multi-user.bulletin.patch, aosp_diff/preliminary/system/bt/13_0013-Add-negative-length-check-in-process_service_search_rsp.bulletin.patch, aosp_diff/preliminary/system/bt/14_0014-Add-buffer-in-pin_reply-in-bluetooth-cc.bulletin.patch
=> ASB - Security Patch integration November 2022 - rmr0_stable

bsp_diff/common/kernel/lts2021-chromium/0001-make-vmmouse-report-relative-values.patch, bsp_diff/common/kernel/lts2021-chromium/0002-greybus-Remove-Android.mk.patch, bsp_diff/common/kernel/lts2021-chromium/0003-Bluetooth-SCO-USB-driver.patch, bsp_diff/common/kernel/lts2021-chromium/0004-uvc-Add-UVC-GET_DEF-probe-quirk-for-C922-camera.patch, bsp_diff/common/kernel/lts2021-chromium/0005-btusb-snd-crash-while-disconnect.patch, bsp_diff/common/kernel/lts2021-chromium/0006-Bluetooth-btusb-Add-reset-on-close-quirk-for-Intel-a.patch, bsp_diff/common/kernel/lts2021-chromium/0007-9p-freezing-aborts-when-use-wait_event_killable.patch, bsp_diff/common/kernel/lts2021-chromium/0008-iwlwifi-Vendor-command-support-in-iwlwifi-driver.patch, bsp_diff/common/kernel/lts2021-chromium/0009-x86-relocs-Ignore-L4_PAGE_OFFSET-relocations.patch, bsp_diff/common/kernel/lts2021-chromium/0010-drm-i915-replace-cond_resched-with-usleep_range-to-a.patch, bsp_diff/common/kernel/lts2021-chromium/0011-Prebuilts-tar-doesnot-support-I-option.-So-replaced-.patch, bsp_diff/common/kernel/lts2021-chromium/0012-Fix-for-btusb_sco_snd_card-not-getting-probed.patch, bsp_diff/common/kernel/lts2021-chromium/0013-Update-header-config-to-allow-older-fw-version.patch, bsp_diff/common/kernel/lts2021-chromium/0014-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch, bsp_diff/common/kernel/lts2021-chromium/0015-Revert-drm-i915-Sysfs-interface-to-get-GFX-shmem-usa.patch, bsp_diff/common/kernel/lts2021-chromium/0016-iwl7000-Add-driver-and-firmware-version-query-suppor.patch, bsp_diff/common/kernel/lts2021-chromium/0017-Add-HFP-support-for-AX211-GarfieldPeak-Gfp.patch, bsp_diff/common/kernel/lts2021-chromium/0018-ACPI-PM-Propagate-power-button-event-to-user-space-w.patch, bsp_diff/common/kernel/lts2021-chromium/0019-Freeze-and-Restore-Implementation.patch, bsp_diff/common/kernel/lts2021-chromium/0020-Skip-hw-pmu-for-VM-on-ADL.patch
rebasing kernel diff patches for 5.15.74 rebase
Tracked-On: OAM-104057
=> re-basing kernel diff patches for 5.15.74 re-base

host/kernel/lts2021-chromium/build.sh, host/kernel/lts2021-chromium/build_weekly.sh
updating build script for kernel-5.15.74 rebase
Tracked-On: OAM-104666
=> update build script for kernel-5.15.74 rebase

aosp_diff/preliminary/frameworks/base/0001-catch-IllegalArgumentException-from-getHarmfulAppWar.patch
Change-Id: I82147d667b487d70fb84dfc7042aeddd51552ef4
Tracked-On: OAM-104686
=> Add Critical patch from Google for GMS

host/kernel/lts2021-chromium/build.sh, host/kernel/lts2021-chromium/build_weekly.sh
rebased drm-i915-sysfs-memtrack patch for kernel-version 5.15.74
Tracked-On: OAM-104760
=> updating weekly build script for kernel-v5.15.74

aosp_diff/preliminary/frameworks/base/10_0010-Add-whitelist-permissions-to-clipboardagent-privapp.patch, aosp_diff/preliminary/frameworks/base/11_0011-Allow-clipboard-access-to-intel-packages.patch, aosp_diff/preliminary/frameworks/base/12_0012-Adds-GET_TASKS-permission-to-ClipboardAgent.patch
=> Port clipboard-agent to Android 13

host/kernel/lts2021-chromium/build.sh, host/kernel/lts2021-chromium/build_weekly.sh
new-tag, lts-v5.15.74-20221125-r4
Tracked-On: OAM-105007
=> update weekly build script with latest tag

aosp_diff/caas/system/sepolicy/0001-Grant-permission-for-mediatranscoding-hal_allocator-.patch, aosp_diff/caas/system/sepolicy/0002-Move-mediatranscoding-type-to-public.patch, bsp_diff/caas/device/intel/mixins/0001-Add-mediatranscode-sepolicy-rules-to-public.patch, bsp_diff/caas/device/intel/sepolicy/0001-Add-mediatranscode-sepolicy-rules-to-public.patch
As mediatranscode update in google moving from private to public
Tracked-On: OAM-105142
Signed-off-by: Kothapeta, BikshapathiX <bikshapathix.kothapeta@intel.com>
=> Add mediatranscode sepolicy rules to public.

host/kernel/linux-intel-lts2021/build.sh, host/kernel/linux-intel-lts2021/build_weekly.sh
Host kernel and diff patch commit hash/tag update to point to sriov boot issue fix "Fix guest not getting started in SRIOV mode"
Tracked-On: OAM-105229
=> Update host kernel diff version update to fix sriov boot issue

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/base/38_0038-Limit-length-and-number-of-MIME-types-you-can-set.bulletin.patch, aosp_diff/preliminary/frameworks/base/39_0039-Limit-lengths-of-fields-in-Condition-to-a-max-length-.bulletin.patch, aosp_diff/preliminary/frameworks/base/40_0040-Disable-all-A11yServices-from-an-uninstalled-package-.bulletin.patch, aosp_diff/preliminary/frameworks/base/41_0041--RESTRICT-AUTOMERGE-SettingsProvider-mem-limit-should-be-.bulletin.patch, aosp_diff/preliminary/frameworks/base/42_0042--RESTRICT-AUTOMERGE-SettingsProvider-key-size-limit-for-mu.bulletin.patch, aosp_diff/preliminary/frameworks/base/43_0043-Trim-the-activity-info-of-another-uid-if-no-privilege.bulletin.patch, aosp_diff/preliminary/frameworks/base/44_0044--SettingsProvider-workaround-for-DevicePolicyResourcesManag.bulletin.patch, aosp_diff/preliminary/frameworks/base/45_0045-Add-protections-against-queueing-a-UsbRequest-when-the-under.bulletin.patch, aosp_diff/preliminary/frameworks/base/46_0046-Fix-sharing-to-another-profile-where-an-app-has-multiple-tar.bulletin.patch, aosp_diff/preliminary/frameworks/base/47_0047-Ensure-that-only-SysUI-can-override-pending-intent-launch-fl.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/0003-Remove-Intent-selector-from-2-pane-deep-link-Intent.bulletin.patch, aosp_diff/preliminary/packages/providers/MediaProvider/0002-Set-intent-priority-for-PICK_IMAGES.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/0004-Fix-security-vulnerability-when-register-phone-accounts-.bulletin.patch, aosp_diff/preliminary/packages/services/Telephony/02_0002-prevent-overlays-on-the-phone-settings.bulletin.patch
=> ASB - Security Patch integration January 2023 - T-MR0-MASTER

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/base/98_0098-Limit-lengths-of-fields-in-Condition-to-a-max-length-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0099-Limit-length-and-number-of-MIME-types-you-can-set.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0100-Limit-length-and-number-of-MIME-types-you-can-set.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0101--DO-NOT-MERGE-Fix-conditionId-string-trimming-in-AutomaticZ.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0102--RESTRICT-AUTOMERGE-SettingsProvider-mem-limit-should-be-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0103-Backport-missing-permission-check-for-querying-main-activity.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0104--RESTRICT-AUTOMERGE-SettingsProvider-key-size-limit-for-mu.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0105-RESTRICT-AUTOMERGE-Trim-the-activity-info-of-another-uid-i.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0106-Add-protections-against-queueing-a-UsbRequest-when-the-under.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0107-Fix-sharing-to-another-profile-where-an-app-has-multiple-tar.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0108-Ensure-that-only-SysUI-can-override-pending-intent-launch-fl.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/06_0006-Fix-security-vulnerability-when-register-phone-accounts-.bulletin.patch, aosp_diff/preliminary/packages/services/Telephony/0002-prevent-overlays-on-the-phone-settings.bulletin.patch
=> ASB - Security Patch integration January 2023 - smr0_stable

aosp_diff/common/build/make/0002-Updating-Platform-Security-version.patch, aosp_diff/common/frameworks/base/0123-Limit-lengths-of-fields-in-Condition-to-a-max-length-.bulletin.patch, aosp_diff/common/frameworks/base/0124-Limit-length-and-number-of-MIME-types-you-can-set.bulletin.patch, aosp_diff/common/frameworks/base/0125-Disable-all-A11yServices-from-an-uninstalled-package-.bulletin.patch, aosp_diff/common/frameworks/base/0126--DO-NOT-MERGE-Fix-conditionId-string-trimming-in-AutomaticZ.bulletin.patch, aosp_diff/common/frameworks/base/0127--RESTRICT-AUTOMERGE-SettingsProvider-mem-limit-should-be-.bulletin.patch, aosp_diff/common/frameworks/base/0128--RESTRICT-AUTOMERGE-SettingsProvider-key-size-limit-for-mu.bulletin.patch, aosp_diff/common/frameworks/base/0129-Trim-the-activity-info-of-another-uid-if-no-privileg.patch, aosp_diff/common/frameworks/base/0130-Add-protections-against-queueing-a-UsbRequest-when-the-under.bulletin.patch, aosp_diff/common/frameworks/base/0131-Fix-sharing-to-another-profile-where-an-app-has-multiple-tar.bulletin.patch, aosp_diff/common/frameworks/base/0132-Ensure-that-only-SysUI-can-override-pending-intent-launch-fl.bulletin.patch, aosp_diff/common/packages/services/Telecomm/0007-Fix-security-vulnerability-when-register-phone-accounts-.bulletin.patch, aosp_diff/common/packages/services/Telephony/0001-prevent-overlays-on-the-phone-settings.patch
=> ASB - Security Patch integration January 2023 - android_cloud

aosp_diff/preliminary/frameworks/base/100_0100--DO-NOT-MERGE-Fix-permanent-denial-of-service-via-setCompon.bulletin.patch
Commit id this patch creating the problem
So adding the new patch
Tracked-On: OAM-105370
=> Fix for commit id issue

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/base/99_0105-Limit-lengths-of-fields-in-Condition-to-a-max-length-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0106-Limit-length-and-number-of-MIME-types-you-can-set.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0107-Disable-all-A11yServices-from-an-uninstalled-package-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0108--DO-NOT-MERGE-Fix-conditionId-string-trimming-in-AutomaticZ.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0109--RESTRICT-AUTOMERGE-SettingsProvider-mem-limit-should-be-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0110--RESTRICT-AUTOMERGE-SettingsProvider-key-size-limit-for-mu.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0111-Trim-the-activity-info-of-another-uid-if-no-privileg.patch, aosp_diff/preliminary/frameworks/base/99_0112-Add-protections-against-queueing-a-UsbRequest-when-the-under.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0113-Fix-sharing-to-another-profile-where-an-app-has-multiple-tar.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0114-Ensure-that-only-SysUI-can-override-pending-intent-launch-fl.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/06_0006-Fix-security-vulnerability-when-register-phone-accounts-.bulletin.patch, aosp_diff/preliminary/packages/services/Telephony/01_0001-prevent-overlays-on-the-phone-settings.patch
=> ASB - Security Patch integration January 2023 - rmr0_stable

bsp_diff/common/vendor/intel/external/project-celadon/cloud-streaming/0001-Add-entry-point-script-for-aic-cloud-env.patch
=> Integrate open source cloud streamer to ICS3A

aosp_diff/caas/frameworks/base/0001-Add-system_server-to-readtracefs-group.patch, aosp_diff/caas/frameworks/native/0001-Allow-gpuservice-to-read-tracefs-entries.patch, aosp_diff/caas/packages/modules/adb/0001-Allow-shell-to-read-tracefs-entries.patch, aosp_diff/caas/system/core/0001-Add-group-ID-for-reading-tracefs.patch
Added tracefs access for system.
This changes are taken from horizontal celadon(Android-T).
Google source code commit reference:
https://android-review.googlesource.com/q/topic:%22tracefs-access%22
Tracked-On: OAM-105049
Signed-off-by: Vasoya,Nikhilx <nikhilx.vasoya@intel.com>
=> Fix for CTS SimpleperfTestCases TCs

host/kernel/lts2021-chromium/build_weekly.sh, host/kernel/lts2021-chromium/x86_64_defconfig
New commit tag - lts-v5.15.78-20230121-r7
Tracked-On: OAM-105586
=> Rebase: Update build_weekly.sh with latest commit tag for 5.15 Kernel

aosp_diff/preliminary/bionic/0005-avx2-implementation-for-memset-api.patch
=> avx2 implemantation of memset

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/build/tools/02_0002-Support-chained-init_boot-partition-signing.bulletin.patch, aosp_diff/preliminary/external/expat/0001--CVE-2022-43680-Fix-overeager-DTD-destruction-fixes-649-.bulletin.patch, aosp_diff/preliminary/frameworks/av/0008-audio-fix-missing-package-name-in-attribution-source.bulletin.patch, aosp_diff/preliminary/frameworks/av/0009-Fix-Out-of-Bounds-Read-in-AAVCAssembler.bulletin.patch, aosp_diff/preliminary/frameworks/av/0010-audio-policy-fix-sensor-privacy-listener.bulletin.patch, aosp_diff/preliminary/frameworks/av/0011-move-MediaCodec-metrics-processing-to-looper-thread.bulletin.patch, aosp_diff/preliminary/frameworks/av/0012-RESTRICT-AUTOMERGE-Use-static-token-for-myAttributionSource-.bulletin.patch, aosp_diff/preliminary/frameworks/base/47_0047--DO-NOT-MERGE-Revert-Fix-system-zen-rules-by-using-owner-p.bulletin.patch, aosp_diff/preliminary/frameworks/base/48_0048--DO-NOT-MERGE-Revert-Check-rule-package-name-in-ZenModeHel.bulletin.patch, aosp_diff/preliminary/frameworks/base/49_0049--RESTRICT-AUTOMERGE-Correct-the-behavior-of-ACTION_PACKAGE_.bulletin.patch, aosp_diff/preliminary/frameworks/base/50_0050-Convert-argument-to-intent-in-ChooseTypeAndAccountActivity.bulletin.patch, aosp_diff/preliminary/frameworks/base/51_0051-Use-rule-package-name-in-addAutomaticZenRule-specify-andro.bulletin.patch, aosp_diff/preliminary/frameworks/base/52_0052-RESTRICT-AUTOMERGE-Use-chain-start-token-in-performOpTransac.bulletin.patch, aosp_diff/preliminary/frameworks/base/53_0053-Disallow-clicks-on-privacy-chip-before-provisioned.bulletin.patch, aosp_diff/preliminary/hardware/interfaces/11_0011-Add-additional-bounds-checks-to-NNAPI-FMQ-deserialize-utilit.bulletin.patch, aosp_diff/preliminary/packages/apps/EmergencyInfo/0003-Removes-unnecessary-permission-from-the-EmergencyInfo-app-.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/0004-RESTRICT-AUTOMERGE-Make-bluetooth-switch-not-discoverable-vi.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0019-Fix-OPP-comparison.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0020-Report-failure-when-not-able-to-connect-to-AVRCP.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0021-Add-bounds-check-in-avdt_scb_act-cc.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0001--RESTRICT-AUTOMERGE-Restrict-halfsheet-cancel-broadcast.bulletin.patch, aosp_diff/preliminary/packages/modules/NeuralNetworks/0001-Add-additional-bounds-checks-to-NNAPI-FMQ-deserialize-utilit.bulletin.patch, aosp_diff/preliminary/packages/modules/Wifi/0004-wifi-Reset-to-default-SAP-configuration-when-doing-factory-.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/0005-Fix-security-vulnerability-issue-for-multi-user-call-redirec.bulletin.patch, aosp_diff/preliminary/system/connectivity/wificond/0001-Use-sp-T-make-to-create-the-sp-pointer-for-EventLoopCallba.bulletin.patch
=> ASB - Security Patch integration February 2023 - T-MR0-MASTER

host/kernel/lts2021-chromium/build_weekly.sh
New commit tag - lts-v5.15.78-20230131-r8
Tracked-On: OAM-105220
Signed-off-by: Boppana, Tej Kiran <tej.kiran.boppana@intel.com>
=> Update build_weekly.sh with latest commit tag for 5.15 Kernel

aosp_diff/common/build/make/0002-Updating-Platform-Security-version.patch, aosp_diff/common/external/expat/0005--CVE-2022-43680-Fix-overeager-DTD-destruction-fixes-649-.bulletin.patch, aosp_diff/common/frameworks/av/0018-move-MediaCodec-metrics-processing-to-looper-thread.patch, aosp_diff/common/frameworks/base/0132-Make-Activites-touch-opaque-DO-NOT-MERGE.bulletin.patch, aosp_diff/common/frameworks/base/0133--DO-NOT-MERGE-Revert-Check-rule-package-name-in-ZenModeHel.bulletin.patch, aosp_diff/common/frameworks/base/0134--DO-NOT-MERGE-Revert-Fix-system-zen-rules-by-using-owner-p.bulletin.patch, aosp_diff/common/frameworks/base/0135--RESTRICT-AUTOMERGE-Correct-the-behavior-of-ACTION_PACKAGE_.bulletin.patch, aosp_diff/common/frameworks/base/0136-Convert-argument-to-intent-in-ChooseTypeAndAccountActivity.bulletin.patch, aosp_diff/common/frameworks/base/0137-Use-rule-package-name-in-addAutomaticZenRule-specify-andro.bulletin.patch, aosp_diff/common/frameworks/ml/0001-Add-additional-bounds-checks-to-NNAPI-FMQ-deserialize-utilit.bulletin.patch, aosp_diff/common/frameworks/native/0016-Allow-windowhandles-with-NO_INPUT_CHANNEL-DO-NOT-MERGE.bulletin.patch, aosp_diff/common/frameworks/opt/net/wifi/0002--DO-NOT-MERGE-wifi-Reset-to-default-SAP-configuration-when.bulletin.patch, aosp_diff/common/packages/apps/EmergencyInfo/0004-Removes-unnecessary-permission-from-the-EmergencyInfo-app-.bulletin.patch, aosp_diff/common/packages/apps/Settings/0023-RESTRICT-AUTOMERGE-Make-bluetooth-switch-not-discoverable-vi.bulletin.patch, aosp_diff/common/system/bt/0018-Report-failure-when-not-able-to-connect-to-AVRCP.bulletin.patch
=> ASB - Security Patch integration February 2023

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/expat/05_0005--CVE-2022-43680-Fix-overeager-DTD-destruction-fixes-649-.bulletin.patch, aosp_diff/preliminary/frameworks/av/19_0019-move-MediaCodec-metrics-processing-to-looper-thread.patch, aosp_diff/preliminary/frameworks/base/99_0115-Make-Activites-touch-opaque-DO-NOT-MERGE.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0116-Check-rule-package-name-in-ZenModeHelper-addAutomaticRule.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0117-Fix-system-zen-rules-by-using-owner-package-name-if-caller-i.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0118--DO-NOT-MERGE-Revert-Check-rule-package-name-in-ZenModeHel.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0119--DO-NOT-MERGE-Revert-Fix-system-zen-rules-by-using-owner-p.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0120--RESTRICT-AUTOMERGE-Correct-the-behavior-of-ACTION_PACKAGE_.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0121-Convert-argument-to-intent-in-ChooseTypeAndAccountActivity.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0122-Use-rule-package-name-in-addAutomaticZenRule-specify-andro.bulletin.patch, aosp_diff/preliminary/frameworks/ml/03_0003-Add-additional-bounds-checks-to-NNAPI-FMQ-deserialize-utilit.bulletin.patch, aosp_diff/preliminary/frameworks/native/13_0013-Allow-windowhandles-with-NO_INPUT_CHANNEL-DO-NOT-MERGE.bulletin.patch, aosp_diff/preliminary/frameworks/opt/net/wifi/04_0004--DO-NOT-MERGE-wifi-Reset-to-default-SAP-configuration-when.bulletin.patch, aosp_diff/preliminary/packages/apps/EmergencyInfo/04_0004-Removes-unnecessary-permission-from-the-EmergencyInfo-app-.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/32_0032-RESTRICT-AUTOMERGE-Make-bluetooth-switch-not-discoverable-vi.bulletin.patch, aosp_diff/preliminary/system/bt/20_0020-Report-failure-when-not-able-to-connect-to-AVRCP.bulletin.patch
=> ASB - Security Patch integration February 2023 - rmr0_stable

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/expat/05_0005--CVE-2022-43680-Fix-overeager-DTD-destruction-fixes-649-.bulletin.patch, aosp_diff/preliminary/frameworks/av/18_0018-audio-fix-missing-package-name-in-attribution-source.bulletin.patch, aosp_diff/preliminary/frameworks/av/19_0019-Fix-Out-of-Bounds-Read-in-AAVCAssembler.bulletin.patch, aosp_diff/preliminary/frameworks/av/20_0020-RESTRICT-AUTOMERGE-Use-static-token-for-myAttributionSource-.bulletin.patch, aosp_diff/preliminary/frameworks/av/21_0021-move-MediaCodec-metrics-processing-to-looper-thread.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0109-Do-not-clear-calling-identify-when-using-BiometricPr.patch, aosp_diff/preliminary/frameworks/base/99_0110-Make-Activites-touch-opaque-DO-NOT-MERGE.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0111-Check-rule-package-name-in-ZenModeHelper-addAutomaticRule.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0112-Fix-system-zen-rules-by-using-owner-package-name-if-caller-i.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0113-fpService-authWithPrompt-uses-correct-user-handle.patch, aosp_diff/preliminary/frameworks/base/99_0114--DO-NOT-MERGE-Revert-Fix-system-zen-rules-by-using-owner-p.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0115--DO-NOT-MERGE-Revert-Check-rule-package-name-in-ZenModeHel.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0116--RESTRICT-AUTOMERGE-Correct-the-behavior-of-ACTION_PACKAGE_.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0117-Convert-argument-to-intent-in-ChooseTypeAndAccountActivity.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0118-Use-rule-package-name-in-addAutomaticZenRule-specify-andro.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0119-RESTRICT-AUTOMERGE-Use-chain-start-token-in-performOpTransac.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0120-Disable-click-on-privacy-chip-before-provision.patch, aosp_diff/preliminary/frameworks/base/99_0121-Fix-for-ASB-Feb-2023-Build-issue.patch, aosp_diff/preliminary/frameworks/native/11_0011-Allow-windowhandles-with-NO_INPUT_CHANNEL-DO-NOT-MERGE.bulletin.patch, aosp_diff/preliminary/hardware/interfaces/11_0011-Add-additional-bounds-checks-to-NNAPI-FMQ-deserialize-utilit.bulletin.patch, aosp_diff/preliminary/packages/apps/EmergencyInfo/04_0004-Removes-unnecessary-permission-from-the-EmergencyInfo-app-.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/22_0022-RESTRICT-AUTOMERGE-Make-bluetooth-switch-not-discoverable-vi.bulletin.patch, aosp_diff/preliminary/packages/modules/NeuralNetworks/0003-Add-additional-bounds-checks-to-NNAPI-FMQ-deserialize-utilit.bulletin.patch, aosp_diff/preliminary/packages/modules/Wifi/0004--DO-NOT-MERGE-wifi-Reset-to-default-SAP-configuration-when.bulletin.patch, aosp_diff/preliminary/system/bt/21_0021-Add-bounds-check-in-avdt_scb_act-cc.bulletin.patch, aosp_diff/preliminary/system/connectivity/wificond/0001-Use-sp-T-make-to-create-the-sp-pointer-for-EventLoopCallba.bulletin.patch
=> ASB - Security Patch integration February 2023 - smr0_stable

bsp_diff/common/vendor/intel/external/project-celadon/cloud-streaming/0001-PATCH-Add-entry-point-script-for-aic-cloud.patch
=> added av1 in entry

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/zlib/0001-Fix-a-bug-when-getting-a-gzip-header-extra-field-with-inflat.bulletin.patch, aosp_diff/preliminary/frameworks/av/22_0022-C2SurfaceSyncObj-prevent-OOB-read-in-Import.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0122-RESTRICT-AUTOMERGE-Validate-permission-tree-size-on-permissi.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0123-RESTRICT-AUTOMERGE-Revoke-SYSTEM_ALERT_WINDOW-on-upgrade-pas.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0124-Move-service-initialization.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0125-Enable-user-graularity-for-lockdown-mode.patch, aosp_diff/preliminary/frameworks/base/99_0126-Reconcile-WorkSource-parcel-and-unparcel-code-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0127-Enforce-MediaButtonReceiver-extracted-component-name-matches.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0128-Enforce-MediaButtonReceiver-ComponentName-belongs-to.patch, aosp_diff/preliminary/packages/apps/Settings/23_0023-FRP-bypass-defense-in-the-settings-app.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/24_0024-Add-DISALLOW_APPS_CONTROL-check-into-uninstall-app-for-all-u.bulletin.patch, aosp_diff/preliminary/packages/modules/Permission/05_0005-Add-one-time-flag-to-permission-if-group-is-currently-one-ti.bulletin.patch, aosp_diff/preliminary/packages/modules/Wifi/0005--Passpoint-Add-more-check-to-limit-the-config-size.bulletin.patch, aosp_diff/preliminary/system/bt/22_0022-Report-failure-when-not-able-to-connect-to-AVRCP.bulletin.patch, aosp_diff/preliminary/system/bt/23_0023-Fix-an-OOB-Write-bug-in-gatt_check_write_long_terminate.bulletin.patch, aosp_diff/preliminary/system/bt/24_0024-Fix-an-OOB-access-bug-in-A2DP_BuildMediaPayloadHeaderSbc.bulletin.patch, aosp_diff/preliminary/system/bt/25_0025-Fix-an-OOB-write-in-SDP_AddAttribute.bulletin.patch
=> ASB - Security Patch integration March 2023

aosp_diff/preliminary/art/0004-Coverity-Fixes-ART.patch
Handled Coverity warnings of Uninitialized Pointer Field and copy to fixed buffer size issues.
Tracked-On: OAM-105869
=> Fixed ART-Runtime Coverity Issues

bsp_diff/common/hardware/intel/external/mesa3d-intel/0001-Add-two-macro-for-Android-S-build.patch, bsp_diff/common/hardware/intel/external/mesa3d-intel/0002-Revert-Android.mk-Filter-out-build-id-md5-linker-fla.patch
=> Add two macro and reverts commit 554b19b616a

aosp_diff/cic_cloud/external/drm_hwcomposer/0001-Disable-building-of-hwcomposer.drm_minigbm.patch, aosp_diff/cic_cloud/frameworks/base/0002-Check-the-property-before-starting-some-services.patch, aosp_diff/cic_cloud/frameworks/base/0005-Add-checkDumpPermission-for-soundtrigger_middleware.patch, aosp_diff/cic_cloud/frameworks/native/0001-Add-fix-for-sensor-meta-data-events.patch, aosp_diff/cic_cloud/frameworks/native/0003-Enable-fps-checking.patch, aosp_diff/cic_cloud/packages/apps/Camera2/0001-Remove-DisableCameraReceiver-feature-to-avoid-icon-n.patch, aosp_diff/cic_cloud/packages/apps/Gallery2/0001-Remove-DisableCameraReceiver-feature-to-avoid-icon-n.patch, aosp_diff/cic_cloud/packages/apps/SoundRecorder/0002-Fix-accessing-SD-card-error-for-recording.patch, aosp_diff/cic_cloud/packages/modules/NetworkStack/0001-Modify-checkDumpPermission-for-network_stack.patch, aosp_diff/cic_cloud/system/hardware/interfaces/0001-Check-android.permission.DUMP-for-suspend_control.patch, aosp_diff/common/external/arm-optimized-routines/0001-Avx-enablment-of-expf-sinf-cosf.patch, aosp_diff/common/external/libdrm/0001-remove-bp.patch, aosp_diff/common/external/zlib/0001-Fix-a-bug-when-getting-a-gzip-header-extra-field-wit.patch, aosp_diff/common/system/libhidl/0001-Don-t-sleep-1s-even-we-don-t-enforce-vintf.patch, aosp_diff/common/system/linkerconfig/0001-Config-changes-to-prefer-perf-variants-of-an-.so.patch, aosp_diff/common/system/vold/0003-Delete-some-opts-not-supported-on-common-kernel.patch, bsp_diff/cic_cloud/vendor/intel/external/project-celadon/nn-hal/0001-Compatibility-changes-to-build-nn-hal-for-Android-R.patch, bsp_diff/cic_cloud/vendor/intel/external/project-celadon/oneDNN/0001-Changes-to-add-oneDNN-for-OpenVINO-2022.3.0.patch, bsp_diff/cic_cloud/vendor/intel/external/project-celadon/oneTBB/0001-Changes-to-compile-oneTBB-for-Android.patch, bsp_diff/cic_cloud/vendor/intel/external/project-celadon/openvino/0001-Changes-to-integrate-openvino-2022.3.0.patch, bsp_diff/cic_cloud/vendor/intel/external/project-celadon/pugixml/0001-Changes-to-integrate-openvino-2022.3.0.patch
lunch target fails due to missing change-Id.
Added change-Id for camera app patch.
Change-Id: I76cdd907bfa5658230ebb42846dc0651fba3bbc4
Tracked-On: OAM-106953
=> Add change-Id information for patch

host/kernel/lts2021-chromium/build_weekly.sh
BDSA-2023-0655(CVE-2023-1195) - Fix Applied
CVE-2023-1281 - Fix Applied
Tracked-On: OAM-107234
=> CVE: Update build_weekly.sh with latest commit tag for v5.15.78

bsp_diff/common/kernel/lts2021-chromium/0021-fix-for-coverity-issues.patch
i915 module: avoid double free
btintel module: fix kmalloc validation by using right variable
Tracked-On: OAM-105549
=> fix for static analysis issues

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/build/soong/0008-Expose-avb_hash_algorithm-as-a-property-.bulletin.patch, aosp_diff/preliminary/external/angle/0001-Fix-a-bug-when-getting-a-gzip-header-extra-field-with-inflat.bulletin.patch, aosp_diff/preliminary/frameworks/base/58_0058-Revert-Trim-the-activity-info-of-another-uid-if-no-p.patch, aosp_diff/preliminary/frameworks/base/59_0059-Checking-if-package-belongs-to-UID-before-registering-broadc.bulletin.patch, aosp_diff/preliminary/frameworks/base/60_0060-Fix-checkKeyIntentParceledCorrectly-s-bypass.bulletin.patch, aosp_diff/preliminary/frameworks/base/61_0061-Encode-Intent-scheme-when-serializing-to-URI-string-RESTRICT.bulletin.patch, aosp_diff/preliminary/frameworks/base/62_0062-Strip-part-of-the-activity-info-of-another-uid-if-no.patch, aosp_diff/preliminary/frameworks/base/63_0063-DO-NOT-MERGE-Context-startInstrumentation-could-be-started-.bulletin.patch, aosp_diff/preliminary/frameworks/base/64_0064--RESTRICT-AUTOMERGE-Limit-length-of-the-name-in-uses-permi.bulletin.patch, aosp_diff/preliminary/frameworks/base/65_0065-Lower-per-app-NotificationChannelGroup-limit-.bulletin.patch, aosp_diff/preliminary/frameworks/base/66_0066-Fix-bypass-BAL-via-LocationManager-requestFlush.bulletin.patch, aosp_diff/preliminary/frameworks/base/67_0067--Fix-bypass-BAL-via-LocationManager-requestFlush.bulletin.patch, aosp_diff/preliminary/frameworks/native/03_0003-Mitigate-the-security-vulnerability-by-sanitizing-the-transa.bulletin.patch, aosp_diff/preliminary/hardware/nxp/nfc/0003-Revert-OOBR-in-NxpMfcReader-SendIncDecRestoreCmdPart2-.bulletin.patch, aosp_diff/preliminary/hardware/nxp/nfc/0004-OOBR-in-NxpMfcReader-SendIncDecRestoreCmdPart2.bulletin.patch, aosp_diff/preliminary/packages/apps/Launcher3/0001-Prevent-falling-into-OtherActivityInputConsumer-when-over-lo.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/0011-Fix-the-security-vulnerability-issue-in-AppLocalePickerActiv.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/0012-Only-primary-user-is-allowed-to-control-secure-nfc.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0025-Fix-a-use-after-free-bug-in-AttributionProcessor-OnWakelock.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0026-Add-mocking-support-for-now-function-in-AttributionProcessor.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0027-Add-regression-test-for-b-254774758.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0028-Fix-an-OOB-bug-in-register_notification_rsp.bulletin.patch, aosp_diff/preliminary/packages/modules/Virtualization/0001-Set-avb_hash_algorithm-sha256-for-system-vendor-img.bulletin.patch, aosp_diff/preliminary/packages/providers/MediaProvider/0003-Canonicalise-path-before-extracting-relative-path.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/0006-Ensure-service-unbind-when-receiving-a-null-call-screening-s.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/0007-DO-NOT-MERGE-do-not-process-content-uri-in-call-Intents.bulletin.patch, aosp_diff/preliminary/system/nfc/02_0002-OOBW-in-nci_snd_set_routing_cmd-.bulletin.patch
=> ASB - Security Patch integration April 2023

bsp_diff/common/hardware/intel/gmmlib/0001-Add-Android.mk-for-intel-gmmlib-22.3.5.patch, bsp_diff/common/hardware/intel/libva/0001-Update-Android.mk-for-libva-2.18.0.patch, bsp_diff/common/hardware/intel/libva/0002-Support-media-stack-on-specified-render-node.patch, bsp_diff/common/hardware/intel/media-driver/0001-Add-changes-to-build-latest-media-driver-in-Android.patch, bsp_diff/common/hardware/intel/media-driver/0002-Resolved-compilation-issue-for-media-driver.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0001-Changes-for-OneVPL-integration.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0002-Restore-SG1-as-a-VPL-platform.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0003-Resolved-runtime-error-for-onevpl.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0004-Remove-ITT-vtune-support.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0005-Fix-for-HEVC-rendering-failing-with-usptream-ffmpeg.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0006-Changes-to-be-in-sync-with-features-enabled-in-linux.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0007-Enable-avx2.patch, bsp_diff/common/hardware/intel/onevpl/0001-Changes-for-OneVPL-integration.patch, bsp_diff/common/hardware/intel/onevpl/0002-Fix-for-HEVC-rendering-failing-with-usptream-ffmpeg.patch
gmmlib: tag: intel-gmmlib-22.3.5
Onevpl dispatcher: tag: v2023.1.3
Onevpl runtime: tag: intel-onevpl-23.1.4
libva: tag:v2.18.0
Change-Id: I65acb16f49af380994e65358a9e958e67ecb5c11
Tracked-On: OAM-106860
=> media-driver: tag: intel-media-23.1.4

aosp_diff/preliminary/bootable/recovery/01_0001-Support-ota-update-from-udisk.patch
=> Fix Boot static scan issues

aosp_diff/preliminary/art/0005-Fixed-static-analysis-issue.patch
=> Fixed Coverity CID: 844633

host/grpc-host/0001-support-vsock-v1.46.2.patch, host/grpc-host/0002-Fix-a-bug-when-getting-a-gzip-header-extra-field-wit.patch
=> Enable grpc to compile with vsock

bsp_diff/common/vendor/intel/external/project-celadon/nn-hal/0001-WA-Disabled-operations-causing-VTS-failures.patch
=> Disabled operations causing VTS failures

bsp_diff/common/vendor/linux/firmware/LICENCE.Intel
This adds license for sof firmware
Tracked-On: OAM-108815
=> Add license for SOF

host/kernel/lts2020-chromium/build_weekly.sh
BDSA-2022-2245(CVE-2022-2585)    Fix Applied
BDSA-2023-0677(CVE-2023-1079)    Fix Applied
BDSA-2023-0821(CVE-2023-1829)    Fix Applied
BDSA-2023-0690(CVE-2023-1078)    Fix Applied
BDSA-2023-0689(CVE-2023-1073)    Fix Applied
BDSA-2022-4045(CVE-2023-28328)   Fix Applied
BDSA-2023-0685(CVE-2023-1074)    Fix Applied
BDSA-2023-0693(CVE-2023-1077)    Fix Applied
BDSA-2023-0697(CVE-2023-1076)    Fix Applied
Tracked-On: OAM-108775
=> CVE: Update build_weekly.sh with latest commit tag

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/base/99_0140-Drop-input-for-toast-and-child-surfaces.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0141-SurfaceControl-Add-setDropInputMode-api.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0142--RESTRICT-AUTOMERGE-pm-prevent-system-app-downgrades-of-ve.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0143--RESTRICT-AUTOMERGE-pm-still-allow-debuggable-for-system-a.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0144-RESTRICT-AUTOMERGE-pm-still-allow-debuggable-for-system-a.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0145-Uri-check-authority-and-scheme-as-part-of-determining-URI-p.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0146-enforce-stricter-rules-when-registering-phoneAccounts.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0147-Trim-strings-added-to-persistent-snoozed-notification-storag.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0148-Limit-the-number-of-shortcuts-per-app-that-can-be-retained-b.bulletin.patch, aosp_diff/preliminary/frameworks/native/12_0012-SurfaceControl-Add-setDropInputMode-api.patch, aosp_diff/preliminary/frameworks/native/13_0013-InputFlinger-Add-DROP_INPUT-feature-flags.bulletin.patch, aosp_diff/preliminary/frameworks/native/14_0014-SurfaceFlinger-Implement-drop-input-modes.bulletin.patch, aosp_diff/preliminary/frameworks/native/15_0015-Check-for-malformed-Sensor-Flattenable.bulletin.patch, aosp_diff/preliminary/frameworks/native/16_0016-Remove-some-new-memory-leaks-from-SensorManager.bulletin.patch, aosp_diff/preliminary/frameworks/native/17_0017-Add-removeInstanceForPackageMethod-to-SensorManager.bulletin.patch, aosp_diff/preliminary/hardware/nxp/nfc/0005-OOBR-in-AnalyzeMfcResp-in-NxpMfcReader-cc.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/26_0026--DO-NOT-MERGE-Enforce-INTERACT_ACROSS_USERS_FULL-permission.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/09_0009-enforce-stricter-rules-when-registering-phoneAccounts.bulletin.patch
=> ASB - Security Patch integration May 2023

bsp_diff/common/hardware/intel/external/mesa3d-intel/0007-Fix-32bit-mmap-issue.patch
Tracked-On: OAM-109725
Signed-off-by: Kanli Hu kanli.hu@intel.com
=> Fix 32bit mmap issue in opengles

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/base/68_0068--RESTRICT-AUTOMERGE-pm-prevent-system-app-downgrades-of-ve.bulletin.patch, aosp_diff/preliminary/frameworks/base/69_0069--RESTRICT-AUTOMERGE-pm-still-allow-debuggable-for-system-a.bulletin.patch, aosp_diff/preliminary/frameworks/base/70_0070-Checks-if-AccessibilityServiceInfo-is-within-parcelable-size.bulletin.patch, aosp_diff/preliminary/frameworks/base/71_0071-enforce-stricter-rules-when-registering-phoneAccounts.bulletin.patch, aosp_diff/preliminary/frameworks/base/72_0072-DO-NOT-MERGE-Isolated-processes-must-fail-registering-BRs-.bulletin.patch, aosp_diff/preliminary/frameworks/base/73_0073-Limit-the-number-of-shortcuts-per-app-that-can-be-retained-b.bulletin.patch, aosp_diff/preliminary/frameworks/base/74_0074-Re-enforce-MANAGE_ACTIVITY_TASKS-for-applySyncTransa.patch, aosp_diff/preliminary/frameworks/base/75_0075-Trim-strings-added-to-persistent-snoozed-notificatio.patch, aosp_diff/preliminary/frameworks/native/04_0004-Check-for-malformed-Sensor-Flattenable.bulletin.patch, aosp_diff/preliminary/frameworks/native/05_0005-Remove-some-new-memory-leaks-from-SensorManager.bulletin.patch, aosp_diff/preliminary/frameworks/native/06_0006-Add-removeInstanceForPackageMethod-to-SensorManager.bulletin.patch, aosp_diff/preliminary/hardware/nxp/nfc/0005-OOBR-in-AnalyzeMfcResp-in-NxpMfcReader-cc.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/0013--DO-NOT-MERGE-Enforce-INTERACT_ACROSS_USERS_FULL-permission.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/0008-enforce-stricter-rules-when-registering-phoneAccounts.bulletin.patch
Merging the ASB patches for May 2023.
Tracked-On: OAM-109745
Signed-off-by: Reddy, Alavala Srinivasa [alavala.srinivasa.reddy@intel.com](mailto:alavala.srinivasa.reddy@intel.com)
_____________________________________________________________________________
=> Merging the ASB patches for May 2023

aosp_diff/celadon_ivi/packages/apps/Car/Settings/02_0002-Show-IP-address-in-car-settings.patch
IP address is not shown in car settings "About" section. Add Preference Controller for showing host IP address.
Tracked-On: OAM-109694
=> Show IP address in car settings

bsp_diff/cic_cloud/vendor/intel/external/project-celadon/hwcomposer/0001-Add-quick-gralloc4-to-gralloc1-handle-conversion.patch, bsp_diff/cic_cloud/vendor/intel/external/project-celadon/minigbm/0001-Add-DRM_FORMAT_NV21-flex-layout-update-in-lockYCbCr.patch, bsp_diff/cic_cloud/vendor/intel/external/project-celadon/minigbm/0002-Enable-Gralloc4.0.patch, bsp_diff/cic_cloud/vendor/intel/external/project-celadon/minigbm/0003-Convert-specific-formats-to-standard-fourcc.patch, bsp_diff/cic_cloud/vendor/intel/external/project-celadon/minigbm/0004-Add-multi-gpu-support.patch
=> Add Gralloc4.0 support

bsp_diff/cic_cloud/vendor/intel/mediasdk_c2/0001-Changes-to-compile-codec2.0-in-Android-11.patch, bsp_diff/cic_cloud/vendor/intel/mediasdk_c2/0002-Add-external-buffer-tiling-flag-for-tiled-format.patch, bsp_diff/cic_cloud/vendor/intel/mediasdk_c2/0003-Fix-for-green-overlay-during-video-playback.patch, bsp_diff/common/vendor/intel/external/project-celadon/mediasdk-omx/0007-Fix-for-green-overlay-during-video-playback.patch
=> Remove codec2.0 software video decoders and encoders

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/0014-Fix-NuMediaExtractor-readSampleData-buffer-Handling.bulletin.patch, aosp_diff/preliminary/frameworks/base/76_0076-Prevent-sharesheet-from-previewing-unowned-URIs.patch, aosp_diff/preliminary/frameworks/base/77_0077--DO-NOT-MERGE-Wait-for-preloading-images-to-complete-before.bulletin.patch, aosp_diff/preliminary/frameworks/base/78_0078-Prevent-RemoteViews-crashing-SystemUi.patch, aosp_diff/preliminary/frameworks/base/79_0079-Check-key-intent-for-selectors-and-prohibited-flags.bulletin.patch, aosp_diff/preliminary/frameworks/base/80_0080-Use-PendingIntent-for-media-click-action-over-locksc.patch, aosp_diff/preliminary/frameworks/base/81_0081-Allow-filtering-of-services.bulletin.patch, aosp_diff/preliminary/frameworks/base/82_0082-Enforce-DevicePolicyManager-setUserControlDisabledPackages-i.bulletin.patch, aosp_diff/preliminary/frameworks/base/83_0083-Add-BubbleMetadata-detection-to-block-FSI.patch, aosp_diff/preliminary/frameworks/base/84_0084-Fix-issues-with-setRemotePlaybackInfo.patch, aosp_diff/preliminary/frameworks/base/85_0085--RESTRICT-AUTOMERGE-Fix-test-failure-caused-by-incorrect-st.bulletin.patch, aosp_diff/preliminary/packages/apps/Car/Settings/0001--automerge-Convert-argument-to-Intent-in-car-settings-accou.bulletin.patch, aosp_diff/preliminary/packages/apps/Car/Settings/0002-Convert-argument-to-Intent-in-car-settings-AddAccountActivit.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/0014-Convert-argument-to-intent-in-AddAccountSettings-.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/0015-Don-t-show-NLSes-with-excessively-long-component-names.bulletin.patch, aosp_diff/preliminary/packages/apps/Traceur/0001-Update-Traceur-to-check-admin-user-status.bulletin.patch, aosp_diff/preliminary/packages/apps/Traceur/0002-Add-DISALLOW_DEBUGGING_FEATURES-check.bulletin.patch, aosp_diff/preliminary/packages/apps/TvSettings/0001-Convert-argument-to-intent-in-addAccount-TvSettings-.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0029-Fix-OOB-read-in-btm_ble_periodic_av_sync_lost.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0030-Revert-Revert-Validate-buffer-length-in-sdpu_build_uuid_se.bulletin.patch, aosp_diff/preliminary/packages/modules/Wifi/0005--TOFU-Don-t-send-credentials-in-an-unauthenticated-TLS-tunn.bulletin.patch, aosp_diff/preliminary/packages/modules/Wifi/0006-Revert-TOFU-Don-t-send-credentials-in-an-unauthenticated-.bulletin.patch, aosp_diff/preliminary/packages/modules/Wifi/0007--TOFU-Implement-a-secure-TOFU-flow.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/0009-Call-Redirection-unbind-service-when-onBind-returns-null.bulletin.patch
=> ASB - Security Patch integration June 2023

aosp_diff/celadon_ivi/build/core/0001-remove-unknown-kernel-cmdline-buildvariant.patch
Tracked-On: OAM-108844
Change-Id: Ib087dbef846b5272112d0f9c478c29fec4bd971d
=> remove unknown kernel cmdline buildvariant

bsp_diff/cic_cloud/vendor/intel/external/intel-gpu/mesa/0007-WA-Add-type-GL_NONE-to-choose-mesa-format.patch
=> Update CHange-id to fix lunch error

aosp_diff/caas/system/sepolicy/0003-Move-mediatranscoding-type-to-public.patch
=> Fix the build error for buildbot

aosp_diff/celadon_ivi/packages/services/Car/0009-Revert-Force-stop-bootanimation-when-CarLauncher-UI-.patch
Reverted patch needs to be modified according to Android 12L and then submitted back reverting the old and this patch.
Tracked-On: OAM-110758
=> Reverting the patch to fix black screen issue.

aosp_diff/cic_cloud/frameworks/base/0002-Check-the-property-before-starting-some-services.patch
=> Enable meminfo, gfxinfo...etc service by default

bsp_diff/common/vendor/intel/external/project-celadon/nn-hal/0001-WA-Disabled-operations-causing-VTS-failures.patch
Regenerated patch for compatibility with nn-hal update: https://github.com/projectceladon/nn-hal/pull/27
Tracked-On: OAM-109729
=> Changes for compatibility with nn-hal update

bsp_diff/cic_cloud/vendor/intel/mediasdk_c2/0001-Changes-to-compile-codec2.0-in-Android-11.patch, bsp_diff/common/hardware/intel/onevpl-intel-gpu/0008-Fix-crash-seen-during-unloading-of-oneVPL-GPU-runtim.patch
=> Update C2 diff patches for latest C2 commit

aosp_diff/common/build/make/0002-Updating-Platform-Security-version.patch, aosp_diff/common/external/freetype/0001-DO-NOT-MERGE-Cherry-pick-two-upstream-changes.bulletin.patch, aosp_diff/common/frameworks/base/0174--RESTRICT-AUTOMERGE-Passpoint-Add-more-check-to-limit-the-c.bulletin.patch, aosp_diff/common/frameworks/base/0175-Ensure-that-only-SysUI-can-override-pending-intent-launch-fl.bulletin.patch, aosp_diff/common/frameworks/base/0176-Revert-Ensure-that-only-SysUI-can-override-pending-intent-l.bulletin.patch, aosp_diff/common/frameworks/base/0177-Add-a-limit-on-channel-group-creation.bulletin.patch, aosp_diff/common/frameworks/base/0178-Remove-Activity-if-it-enters-PiP-without-window.bulletin.patch, aosp_diff/common/frameworks/base/0179-Sanitize-VPN-label-to-prevent-HTML-injection.bulletin.patch, aosp_diff/common/frameworks/base/0180-Import-translations.-DO-NOT-MERGE-ANYWHERE.patch, aosp_diff/common/frameworks/base/0181-DO-NOT-MERGE-Add-size-check-on-PPS-policy.bulletin.patch, aosp_diff/common/frameworks/base/0182-DO-NOT-MERGE-Limit-the-ServiceFriendlyNames.bulletin.patch, aosp_diff/common/frameworks/base/0183-Only-allow-NEW_TASK-flag-when-adjusting-pending-intents.bulletin.patch, aosp_diff/common/frameworks/base/0184-DO-NOT-MERGE-Dismiss-keyguard-when-simpin-auth-d-and-.bulletin.patch, aosp_diff/common/frameworks/base/0185-DO-NOT-MERGE-Increase-notification-channel-limit-.bulletin.patch, aosp_diff/common/frameworks/base/0186-Verify-URI-permissions-for-EXTRA_REMOTE_INPUT_HISTORY_ITEMS-.bulletin.patch, aosp_diff/common/frameworks/base/0187-Truncate-ShortcutInfo-Id.bulletin.patch, aosp_diff/common/frameworks/base/0188-Visit-URIs-in-landscape-portrait-custom-remote-views-.bulletin.patch, aosp_diff/common/frameworks/opt/net/wifi/0003--RESTRICT-AUTOMERGE-Only-handle-saveToStore-from-the-WifiNe.bulletin.patch, aosp_diff/common/frameworks/opt/net/wifi/0004-DO-NOT-MERGE-Limit-the-number-of-Passpoint-per-App.patch, aosp_diff/common/system/bt/0028-Fix-gatt_end_operation-buffer-overflow.bulletin.patch, aosp_diff/common/system/nfc/0006-OOBW-in-rw_i93_send_to_upper.patch
=> ASB - Security Patch integration July 2023

aosp_diff/preliminary/bionic/0006-avx2-implementation-for-memmove-api.patch
Improves AnTuTu v9 "RAM Bandwidth" by 5%
Tracked-On: OAM-103726
=> AVX2 implementation for memmove

aosp_diff/celadon_ivi/packages/apps/Car/Settings/03_0003-Multi-passenger-feature-support.patch, aosp_diff/celadon_ivi/packages/services/Car/0003-Multi-Passenger-Feature-Support-in-IVI-AOSP.patch
Adding overlay mixins changes to support multi-passenger feature.
Tracked-On: OAM-109879
=> Multi-passenger feature support.

bsp_diff/cic_cloud/vendor/intel/external/project-celadon/minigbm/0006-Fix-coverity-issues-for-minigbm.patch
Tracked-On: OAM-106693
Change-Id: I750f76cfd3cd1ea203ee9a8d20107b6ee313b086
=> Fix coverity issues for minigbm.

aosp_diff/celadon_ivi/frameworks/av/media/libaudioprocessing/0002-AudioMixer-fix-multi-channel-track.patch
Fix audio mixer playback for mono source
Fix audio playback for mono audio source, when audio hal support multi channel output.
Tracked-On: OAM-111131
=> Fix audio mixer playback for mono source.

bsp_diff/cic_cloud/vendor/intel/mediasdk_c2/0004-Fixed-few-static-analysis-issues.patch
1. Time of check time of use (TOCTOU)
2. Uncaught exception
3. Calling usleep(1000U) is only useful for its return value, which is ignored
Tracked-On: OAM-110916
=> Fixed few static analysis issues

bsp_diff/common/vendor/intel/external/project-celadon/mediasdk-omx/0008-Fix-for-static-analysis-issues.patch
=> Fix for coverity scan issues on mediasdk-omx

bsp_diff/cic_cloud/vendor/intel/external/project-celadon/nn-hal/0001-Compatibility-changes-to-build-nn-hal-for-Android-R.patch, bsp_diff/cic_cloud/vendor/intel/external/project-celadon/nn-hal/0002-Disabled-operations-causing-CTS-VTS-crashes.patch
* Disable operation causing CTS/VTS crashed
* Added validation check for zero and invalid dimensions
* Set all supported operations default to false
* Adds load model for all execute specs
* Add checks for ouput recived from remote infer
* Return INVALID_ARGUMENT for failures in setting PoolInfos
Tracked-On: OAM-111360
=> Fix CTS not able to run to completion

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/aac/02_0002-Increase-patchParam-array-size-by-one-and-fix-out-of-bounce-.bulletin.patch, aosp_diff/preliminary/external/freetype/0002-Cherrypick-following-three-changes.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0167-Merge-Resolve-StatusHints-image-exploit-across-user-into-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0168-Verify-URI-permissions-in-MediaMetadata.patch, aosp_diff/preliminary/frameworks/base/99_0169-ActivityManagerService-Allow-openContentUri-from-vendor-sys.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0170-Do-not-load-drawable-for-wallet-card-if-the-card-image-icon-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0171-Ensure-policy-has-no-absurdly-long-strings.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0172-On-device-lockdown-always-show-the-keyguard.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0173-Preserve-flags-for-non-runtime-permissions-upon-package-upda.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0174-Check-URIs-in-notification-public-version.patch, aosp_diff/preliminary/frameworks/base/99_0175-Implement-visitUris-for-RemoteViews-ViewGroupActionAdd-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0176-Validate-ComponentName-for-MediaButtonBroadcastRecei.patch, aosp_diff/preliminary/frameworks/base/99_0177-Check-URIs-in-sized-remote-views-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0178-Fix-PrivacyChip-not-visible-issue.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0179-Visit-URIs-in-themed-remoteviews-icons-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0180-Merge-Use-Settings-System-getIntForUser-instead-of-getInt-t.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0181-Remove-unnecessary-padding-code.bulletin.patch, aosp_diff/preliminary/packages/apps/ManagedProvisioning/03_0003-Remove-factory-reset-logic-from-post-suw-syncauth.bulletin.patch, aosp_diff/preliminary/packages/modules/NeuralNetworks/0004-Fix-OOB-Read-in-setOperandValue.bulletin.patch, aosp_diff/preliminary/packages/modules/NeuralNetworks/0005-Fix-OOB-read-in-parseInputs-in-ShimPreparedModel-cpp.bulletin.patch, aosp_diff/preliminary/packages/modules/Permission/06_0006-RESTRICT-AUTOMERGE-Finish-ManagePermissionsActivity-if-devic.bulletin.patch, aosp_diff/preliminary/packages/providers/TelephonyProvider/0002-Update-file-permissions-using-canonical-path.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/11_0011-Resolve-StatusHints-image-exploit-across-user.-am-49.patch, aosp_diff/preliminary/system/ca-certificates/0001-Drop-TrustCor-certificates.bulletin.patch
ASB - Security Patch integration August 2023
Tracked-On: OAM-111372
=> ASB - Security Patch integration August 2023

bsp_diff/common/kernel/lts2020-yocto/0044-Add-module-parameter-for-virtio2d-3d-distinction.patch, bsp_diff/common/kernel/lts2020-yocto/0045-Fix-virtio2d-color-r-b-reversed-issue.patch
Also fix virtio2d r/b reversed issue.
Tracked-On: OAM-111154
=> Fix virtio2d cannot start issue on smr0 master

aosp_diff/celadon_ivi/packages/apps/Car/LocalMediaPlayer/0001-WA-Add-protection-on-LocalMedia-to-avoid-monkey-cras.patch
=> Add protection on LocalMedia to avoid monkey crash.

bsp_diff/celadon_ivi/vendor/intel/optee/optee_client/0001-Support-Android-integration-on-x86.patch
=> Support x86 for optee_client Android integration

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/25_0025-Fix-Segv-on-unknown-address-error-flagged-by-fuzzer-test-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0183--DO-NOT-MERGE-Update-quickshare-intent-rather-than-recreati.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0184-Ignore-virtual-presentation-windows-RESTRICT-AUTOMERGE.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0185-Update-AccountManagerService-checkKeyIntentParceledCorrectly.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0186-Forbid-granting-access-to-NLSes-with-too-long-component-name.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0187-Improve-user-handling-when-querying-for-resumable-me.patch, aosp_diff/preliminary/frameworks/native/18_0018-Allow-sensors-list-to-be-empty.bulletin.patch, aosp_diff/preliminary/packages/apps/Launcher3/02_0002-Fix-permission-issue-in-legacy-shortcut.bulletin.patch, aosp_diff/preliminary/packages/apps/Nfc/02_0002-Ensure-that-SecureNFC-setting-cannot-be-bypassed.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/32_0032-Don-t-hide-approved-NLSes-in-Settings.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/33_0033-DO-NOT-MERGE-Prevent-non-system-IME-from-becoming-device-ad.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/34_0034-Settings-don-t-try-to-allow-NLSes-with-too-long-component-n.bulletin.patch, aosp_diff/preliminary/packages/modules/NeuralNetworks/0006-Fix-out-of-Bounds-Read-in-convertSubgraphFromHAL-in-ShimConv.bulletin.patch, aosp_diff/preliminary/packages/providers/MediaProvider/06_0006-Remove-invalid-surrogates-during-bindSelection-am-b5aadde5f.bulletin.patch, aosp_diff/preliminary/packages/providers/MediaProvider/07_0007-Canonicalize-file-path-for-insertion-by-legacy-apps.bulletin.patch, aosp_diff/preliminary/packages/services/Telephony/0003-Fixed-leak-of-cross-user-data-in-multiple-settings-.bulletin.patch, aosp_diff/preliminary/system/bt/35_0035-Fix-an-integer-overflow-bug-in-avdt_msg_asmbl.bulletin.patch, aosp_diff/preliminary/system/bt/36_0036-Fix-integer-overflow-in-build_read_multi_rsp.bulletin.patch, aosp_diff/preliminary/system/bt/37_0037-Fix-potential-abort-in-btu_av_act-cc.bulletin.patch, aosp_diff/preliminary/system/bt/38_0038-Fix-UAF-in-gatt_cl-cc.bulletin.patch
ASB - Security Patch integration September 2023
Tracked-On: OAM-111936
=> ASB - Security Patch integration September 2023

aosp_diff/celadon_ivi/vendor/intel/optee/optee_apps/0001-Fix-issues-of-optee-keymaster.patch
- fix the initialization issue of resultParams
- make the build pass for optee keymaster
- disabled the gatekeeper build for currently
=> Fix issues of optee keymaster

aosp_diff/preliminary/system/core/0001-WA-remove-some-code-to-fix-a-reboot-bug.patch
Issue: DUT will reboot multiple times when boot for the first time
after the flashing.
Fix: Set the correct wipe status for data partition.
Tracked-On: OAM-112293
Signed-off-by: jizhenlo <zhenlong.z.ji@intel.com>
=> Fix a reboot issue

bsp_diff/common/device/intel/project-celadon/celadon_ivi/0001-mixins.spec-changed-for-12L-boot.patch
Update patchset to resolve patch conflict in celadon_ivi/mixins.spec
Tracked-On: OAM-112312
=> Fix patch conflict for docker option

bsp_diff/common/kernel/linux-intel-lts2021/0026-add-telemetry-for-pci-device-state.patch
=> add telemetry for pci device state

bsp_diff/celadon_ivi/kernel/LICENSE, bsp_diff/common/kernel/LICENSE
Added GPL v2 license file for kernel diff patches.
Tracked-On: OAM-112418
=> Add license file for kernel diff patches

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/libxml2/0001-malloc-fail-Fix-OOB-read-after-xmlRegGetCounter.bulletin.patch, aosp_diff/preliminary/external/webp/0001-update-to-v1-1-0-8-g50f60add.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0186-DO-NOT-MERGE-ActivityManager-killBackgroundProcesses-can-kill-c.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0187-Limit-the-number-of-supported-v1-and-v2-signers.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0188-Verify-URI-permissions-for-EXTRA_REMOTE_INPUT_HISTORY_ITEMS-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0189-Verify-URI-permissions-for-notification-shortcutIcon-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0190-Add-placeholder-when-media-control-title-is-blank.patch, aosp_diff/preliminary/frameworks/base/99_0191-Import-translations.-DO-NOT-MERGE-ANYWHERE.patch, aosp_diff/preliminary/frameworks/base/99_0192-DO-NOT-MERGE-Revert-Verify-URI-permissions-for-EXTRA_REMOTE_INP.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0193-Verify-URI-permissions-for-EXTRA_REMOTE_INPUT_HISTORY_ITEMS-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0194-Do-not-share-key-mappings-with-JNI-object.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0195--DO-NOT-MERGE-Verify-URI-Permissions-in-Autofill-RemoteViews.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0196-Fix-KCM-key-mapping-cloning.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0197-Disallow-loading-icon-from-content-URI-to-PipMenu.patch, aosp_diff/preliminary/frameworks/base/99_0198-Fixing-DatabaseUtils-to-detect-malformed-UTF-16-strings.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0200-RESTRICT-AUTOMERGE-SettingsProvider-exclude-secure_frp_mode-fr.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0201--RESTRICT-AUTOMERGE-Ignore-small-source-rect-hint.bulletin.patch, aosp_diff/preliminary/frameworks/opt/net/wifi/07_0007-DO-NOT-MERGE-Add-pre-share-key-check-for-wapi.bulletin.patch, aosp_diff/preliminary/frameworks/opt/net/wifi/08_0008-DO-NOT-MERGE-Update-password-check-for-WAPI.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/45_0045--RESTRICT-AUTOMERGE-Restrict-ApnEditor-settings.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/46_0046-RESTRICT-AUTOMERGE-Catch-exceptions-from-setLockCredential-.bulletin.patch, aosp_diff/preliminary/packages/providers/MediaProvider/09_0009-Fix-path-traversal-vulnerabilities-in-MediaProvider.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/12_0012-Fix-vulnerability-in-CallRedirectionService-.bulletin.patch, aosp_diff/preliminary/tools/apksig/0001-Limit-the-number-of-supported-v1-and-v2-signers.bulletin.patch
Test done: STS TCs Passed
Tracked-On: OAM-112564
=> ASB - Security Patch integration October 2023

bsp_diff/common/vendor/intel/hardware/interfaces/07_0001-fixing-DEBUG-variable-value-to-enable-disable-logs.patch
=> fixing DEBUG variable value to enable/disable logs

aosp_diff/preliminary/frameworks/av/media/codec2/0001-WA-Force-to-use-system-memory-for-TouTiao-APP.patch
BufferQueue/Pool doesn't work as expected in TouTiao case Once the issue is fixed, remove me.
Tracked-On: OAM-111768
=> [WA] Force to use system memory for TouTiao APP

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/22_0022-Fix-for-heap-buffer-overflow-issue-flagged-by-fuzzer-test-.bulletin.patch, aosp_diff/preliminary/frameworks/av/23_0023-Fix-heap-use-after-free-issue-flagged-by-fuzzer-test-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0202-enforce-stricter-rules-when-registering-phoneAccounts.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0204-Add-userId-check-before-loading-icon-in-Device-Contr.patch, aosp_diff/preliminary/frameworks/base/99_0205-DO-NOT-MERGE-Fix-BAL-via-notification-publicVersion.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0206--DO-NOT-MERGE-Check-caller-s-uid-in-backupAgentCreated-callback.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0207-Use-type-safe-API-of-readParcelableArray.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0208-RESTRICT-AUTOMERGE-Make-log-reader-thread-a-class-member.bulletin.patch, aosp_diff/preliminary/packages/modules/DnsResolver/0001-Fix-use-after-free-in-DNS64-discovery-thread.bulletin.patch, aosp_diff/preliminary/packages/providers/TelephonyProvider/03_0003-DO-NOT-MERGE-Block-access-to-sms-mms-db-from-work-profile-.bulletin.patch, aosp_diff/preliminary/packages/services/BuiltInPrintService/0001-Adjust-APIs-for-CUPS-2-3-3.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/13_0013-enforce-stricter-rules-when-registering-phoneAccounts.bulletin.patch, aosp_diff/preliminary/system/ca-certificates/0002-Remove-E-Tugra-certificates-.bulletin.patch
Test done: STS TCs Passed
Tracked-On: OAM-112869
=> ASB - Security Patch integration November 2023

aosp_diff/preliminary/bootable/recovery/03_0003-Modify-systemupdatersample-to-support-OTA-from-U-dis.patch, aosp_diff/preliminary/system/vold/0002-Remove-the-existence-check-of-mkfs.exfat-and-fsck.ex.patch
1. Modify systemupdatersample app to support OTA from U disk, Customers can do OTA from U disk through this app.
2. Support mounting U disk with exfat fs.
Tests done: 
1. OTA from U disk can be done by systemupdatersample app.
2. Create/copy/move/cat/echo operations work in the /storage/emulated/0 directory.
Tracked-On: OAM-113303
=> Support OTA from U disk in android normal mode

bsp_diff/common/kernel/linux-intel-lts2021/0030-add-scaling-support.patch, bsp_diff/common/kernel/linux-intel-lts2021/0031-suppport-configurable-queue-number.patch, bsp_diff/common/kernel/linux-intel-lts2021/0032-enable-vblank-for-crtc.patch
Add scaling and vblank feature to virtio gpu driver
Tracked-On: OAM-113127
=> add feature for virtio gpu driver

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/24_0024-httplive-fix-use-after-free.bulletin.patch, aosp_diff/preliminary/frameworks/av/25_0025--RESTRICT-AUTOMERGE-Update-uid-state-based-on-capability-field.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0209-On-device-lockdown-always-show-the-keyguard.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0210-Visit-Uris-added-by-WearableExtender.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0211-Fix-bypass-BAL-via-requestGeofence-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0212-Visit-Uris-related-to-Notification-style-extras.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0213-RESTRICT-AUTOMERGE-Drop-invalid-data-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0214-Validate-URI-based-shortcut-icon-at-creation-time-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0215-Require-permission-to-unlock-keyguard.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0216-Restrict-number-of-shortcuts-can-be-added-through-addDynamicShor.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0217-Use-readUniqueFileDescriptor-in-incidentd-service.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0218-Validate-userId-when-publishing-shortcuts.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0219-Revert-On-device-lockdown-always-show-the-keyguard-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0220-Updated-always-show-the-keyguard-on-device-lockdown.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0221-RESTRICT-AUTOMERGE-Check-URI-permissions-for-resumab.patch, aosp_diff/preliminary/packages/apps/Bluetooth/04_0004-Fix-UAF-in-CallbackEnv.bulletin.patch, aosp_diff/preliminary/packages/apps/Launcher3/03_0003-Fix-permission-bypass-in-legacy-shortcut.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/14_0014-Resolve-account-image-icon-profile-boundary-exploit-.bulletin.patch, aosp_diff/preliminary/system/bt/35_0035-Reject-access-to-secure-service-authenticated-from-a-temp-bondin.bulletin.patch, aosp_diff/preliminary/system/bt/36_0036-Reject-access-to-secure-services-authenticated-from-temp-bonding.bulletin.patch, aosp_diff/preliminary/system/bt/37_0037-Reorganize-the-code-for-checking-auth-requirement.bulletin.patch, aosp_diff/preliminary/system/bt/38_0038-Enforce-authentication-if-encryption-is-required.bulletin.patch, aosp_diff/preliminary/system/bt/39_0039-Reject-access-to-secure-service-authenticated-from-a-temp-bondi.bulletin.patch, aosp_diff/preliminary/system/bt/40_0040-Add-bounds-checks-in-btif_avrcp_audio_track-cc.bulletin.patch, aosp_diff/preliminary/system/bt/41_0041-Fix-timing-attack-in-BTM_BleVerifySignature.bulletin.patch, aosp_diff/preliminary/system/netd/0001-Fix-Heap-use-after-free-in-MDnsSdListener-Monitor-run.bulletin.patch
Test done: STS r21 TCs Passed
Tracked-On: OAM-113584
=> ASB - December 2023 Security Patches integration

bsp_diff/base_aaos/hardware/intel/kernelflinger/0001-REVERT-ME-Set-device-as-unlocked-state-by-default-on.patch
=> Fix conflict

aosp_diff/base_aaos/packages/apps/Car/Media/0002-Fixed-for-Media-crash-during-Monkey-Test-Run.patch, aosp_diff/base_aaos/packages/apps/Car/libs/0003-Fixed-for-Media-crash-during-Monkey-Test-Run.patch, aosp_diff/base_aaos/packages/services/Car/0019-Fixed-for-Crash-in-MD-Launcher-during-Monkey-Test.patch
Following crashes were observed
1) java.lang.RuntimeException: Unable to start activity ComponentInfo {com.android.car.multidisplay/com.android.car.multidisplay.launcher .LauncherActivity}
java.lang.NullPointerException Attempt to invoke virtual method 'java .lang.Object android.car.Car.getCarManager(java.lang.String)' on a null object reference
2) java.lang.RuntimeException: Unable to start activity ComponentInfo {com.android.car.media/com.android.car.media.MediaActivity} java.lang .NullPointerException: Attempt to invoke virtual method 'java.lang .Object android.car.Car.getCarManager(java.lang.String)' on a null object reference
3) java.lang.NullPointerException: Attempt to invoke virtual method 'void android.car.media.CarMediaManager.addMediaSourceListener(android …
=> Fixed for crashes during Monkey test run.

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/0025-Codec2BufferUtils-Use-cropped-dimensions-in-RGB-to-YUV-conversi.bulletin.patch, aosp_diff/preliminary/frameworks/av/0026-Fix-convertYUV420Planar16ToY410-overflow-issue-for-unsupported-c.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0157-DO-NOT-MERGE-Ensure-finish-lockscreen-when-usersetup.patch, aosp_diff/preliminary/frameworks/base/99_0158--SB-Privacy-Fetch-current-active-appops-on-startup-.bulletin.patch, aosp_diff/preliminary/packages/apps/Camera2/04_0004-Camera2-Do-not-pass-location-info-for-startActivity-case.bulletin.patch, aosp_diff/preliminary/packages/apps/Nfc/0002-Possible-deadlock-on-the-NfcService-object.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/0023-Make-sure-work-profile-app-cant-enable-notification-listener-ser.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/0024-Validate-ringtone-URIs-before-setting.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0049-Fix-some-OOB-errors-in-BTM-parsing.bulletin.patch, aosp_diff/preliminary/packages/modules/NeuralNetworks/0005-Fix-OOB-Read-in-convertSubgraphFromHAL.bulletin.patch
Test done: STS r22 TCs Passed
Tracked-On: OAM-114326
=> ASB-January 2024 Security Patches integration

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/32_0032-Codec2BufferUtils-Use-cropped-dimensions-in-RGB-to-YUV-conversi.bulletin.patch, aosp_diff/preliminary/frameworks/av/33_0033-Fix-convertYUV420Planar16ToY410-overflow-issue-for-unsupported-c.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0224-Add-null-check-for-media-metadata.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0225-Dismiss-keyguard-when-simpin-auth-d-and-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0226-DO-NOT-MERGE-Ensure-finish-lockscreen-when-usersetup-incomplete.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0227-Add-placeholder-when-media-control-title-is-blank.patch, aosp_diff/preliminary/frameworks/base/99_0228--SB-Privacy-Fetch-current-active-appops-on-startup-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0229-Fix-vulnerability-that-allowed-attackers-to-start-arbitary-activ.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0230-DO-NOT-MERGE-Fix-ActivityManager-killBackgroundProcesses-permis.bulletin.patch, aosp_diff/preliminary/packages/apps/Camera2/05_0005-Camera2-Do-not-pass-location-info-for-startActivity-case.bulletin.patch, aosp_diff/preliminary/packages/apps/Nfc/03_0003-Possible-deadlock-on-the-NfcService-object.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/37_0037-Validate-ringtone-URIs-before-setting.bulletin.patch, aosp_diff/preliminary/packages/modules/NeuralNetworks/0007-Fix-OOB-Read-in-convertSubgraphFromHAL.bulletin.patch, aosp_diff/preliminary/system/bt/49_0049--conflict-Merge-Fix-some-OOB-errors-in-BTM-parsing-into-rvc-d.bulletin.patch
Test done: STS r22 TCs Passed
Tracked-On: OAM-114311
=> ASB - January 2024 Security Patches integration

autopatch.sh
Test done : Boot check done
Tracked-On: OAM-114631
=> Fixed issue in base_aaos patch application

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/cts/0001-Change-open-jpeg-folder-name.bulletin.patch, aosp_diff/preliminary/frameworks/av/0027-Update-mtp-packet-buffer.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0159-DO-NOT-MERGE-Disallow-Wallpaper-service-to-launch-activity-from-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0160-DO-NOT-MERGE-Hide-Android-data-obb-sanbox-on-shared-storage.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0161-Unbind-TileService-onNullBinding.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0162-Restrict-activity-launch-when-caller-is-running-in-the-backgroun.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0163--RESTRICT-AUTOMERGE-Check-permission-of-Autofill-icon-URIs.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0164-Handle-screen-capture-disabled-state-for-multiple-users.bulletin.patch, aosp_diff/preliminary/frameworks/native/10_0010-File-size-seal-for-memory-mapped-region.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0050-Fix-an-OOB-bug-in-btif_to_bta_response-and-attp_build_value_cmd.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0051-Fix-an-OOB-write-bug-in-attp_build_read_by_type_value_cmd.bulletin.patch, aosp_diff/preliminary/packages/providers/DownloadProvider/0001-DO-NOT-MERGE-Consolidate-queryChildDocumentsXxx-implementatio.bulletin.patch, aosp_diff/preliminary/system/core/02_0002-Add-seal-if-ashmem-dev-is-backed-by-memfd.bulletin.patch
Test done: STS r223 TCs Passed
Tracked-On: OAM-115372
=> ASB-February 2024 Security Patches integration

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/libcups/0002-Upgrade-libcups-to-v2-3-3.bulletin.patch, aosp_diff/preliminary/frameworks/av/28_0028-Update-mtp-packet-buffer.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0225-DO-NOT-MERGE-Disallow-Wallpaper-service-to-launch-activity-from-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0226-DO-NOT-MERGE-Hide-Android-data-obb-sanbox-on-shared-storage.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0227-Unbind-TileService-onNullBinding.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0228-Restrict-activity-launch-when-caller-is-running-in-the-backgroun.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0229--RESTRICT-AUTOMERGE-Check-permission-of-Autofill-icon-URIs.bulletin.patch, aosp_diff/preliminary/packages/providers/DownloadProvider/03_0003-DO-NOT-MERGE-Consolidate-queryChildDocumentsXxx-implementatio.bulletin.patch, aosp_diff/preliminary/system/bt/43_0043-Fix-an-OOB-bug-in-btif_to_bta_response-and-attp_build_value_cmd.bulletin.patch, aosp_diff/preliminary/system/bt/44_0044-Fix-an-OOB-write-bug-in-attp_build_read_by_type_value_cmd.bulletin.patch, aosp_diff/preliminary/system/core/04_0004-Add-seal-if-ashmem-dev-is-backed-by-memfd.bulletin.patch
Test done: STS r23 TCs Passed
Tracked-On: OAM-115371
=> ASB - February 2024 Security Patches integration

aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/0004-Update-mtp-packet-buffer.bulletin.patch, aosp_diff/preliminary/frameworks/base/24_0024--Hide-Android-data-obb-sanbox-on-shared-storage.bulletin.patch, aosp_diff/preliminary/frameworks/base/25_0025-Unbind-TileService-onNullBinding.bulletin.patch, aosp_diff/preliminary/frameworks/base/27_0027-Enforce-permission-INJECT_EVENTS-for-injecting-to-input-filter-.bulletin.patch, aosp_diff/preliminary/frameworks/base/28_0028--RESTRICT-AUTOMERGE-Check-permission-of-Autofill-icon-URIs.bulletin.patch, aosp_diff/preliminary/frameworks/native/02_0002-File-size-seal-for-memory-mapped-region.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0003-Fix-an-OOB-bug-in-btif_to_bta_response-and-attp_build_value_cmd.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0004-Fix-an-OOB-write-bug-in-attp_build_read_by_type_value_cmd.bulletin.patch, aosp_diff/preliminary/packages/providers/DownloadProvider/0001-Consolidate-queryChildDocumentsXxx-implementations.bulletin.patch, aosp_diff/preliminary/system/core/03_0003-Add-seal-if-ashmem-dev-is-backed-by-memfd.bulletin.patch
Test done: STS r23 All TCs Passed except one
WIP on failed Test case.
android.security.cts.WallpaperManagerTest#testSetMaliciousStream
Tracked-On: OAM-115236
=> ASB - February 2024 Security Patch integration

bsp_diff/common/kernel/lts2022-chromium/0004-iwlwifi-Get-driver-and-firmware-version-vendor-comma.patch
Updating the iwlwifi patch to resolve conflicts.
Tracked-On: OAM-115437
=> Updating Wi-Fi patch

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/base_aaos/frameworks/av/37_0037-Validate-OMX-Params-for-VPx-encoders.bulletin.patch, aosp_diff/base_aaos/frameworks/av/38_0038-SoftVideoDecodeOMXComponent-validate-OMX-params-for-dynamic-HDR.bulletin.patch, aosp_diff/base_aaos/frameworks/av/39_0039-Fix-out-of-bounds-read-and-write-in-onQueueFilled-in-outQueue.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0249-Resolve-custom-printer-icon-boundary-exploit-.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0250--CDM-Validate-component-name-length-before-requesting-notificat.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0251-Validate-package-names-passed-to-the-installer-.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0252-Close-AccountManagerService-session-after-timeout-.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0253-Disallow-system-apps-to-be-installed-updated-as-instant-.bulletin.patch, aosp_diff/base_aaos/system/bt/53_0053-Fix-an-OOB-bug-in-smp_proc_sec_req.bulletin.patch, aosp_diff/base_aaos/system/bt/54_0054--conflict-Fix-an-OOB-write-bug-in-attp_build_value_cmd-am-ddca.bulletin.patch, aosp_diff/base_aaos/system/bt/55_0055-Revert-conflict-Fix-an-OOB-write-bug-in-attp_build_value_cmd-.bulletin.patch, aosp_diff/base_aaos/system/bt/56_0056-Reland-Fix-an-OOB-write-bug-in-attp_build_value_cmd.bulletin.patch, aosp_diff/base_aaos/system/bt/57_0057-Fix-a-security-bypass-issue-in-access_secure_service_from_temp_b.bulletin.patch
Test done: STS r24 TCs Passed
Tracked-On: OAM-115636
=> ASB - March 2024 Security Patches integration

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/0028-Validate-OMX-Params-for-VPx-encoders.bulletin.patch, aosp_diff/preliminary/frameworks/av/0029-SoftVideoDecodeOMXComponent-validate-OMX-params-for-dynamic-HDR.bulletin.patch, aosp_diff/preliminary/frameworks/av/0030-Fix-out-of-bounds-read-and-write-in-onQueueFilled-in-outQueue.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0165-Resolve-custom-printer-icon-boundary-exploit-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0166-Validate-component-name-length-before-requesting-not.patch, aosp_diff/preliminary/frameworks/base/99_0167-Validate-package-names-passed-to-the-installer-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0168-Disallow-system-apps-to-be-installed-updated-as-instant-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0169-Close-AccountManagerService-session-after-timeout-.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0052-Fix-an-OOB-bug-in-smp_proc_sec_req.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0053-Fix-an-OOB-write-bug-in-attp_build_value_cmd.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0054-Revert-Fix-an-OOB-write-bug-in-attp_build_value_cmd-.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0055-Reland-Fix-an-OOB-write-bug-in-attp_build_value_cmd.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0056-Fix-a-security-bypass-issue-in-access_secure_service_from_temp_b.bulletin.patch
Test done: STS r24 TCs Passed
Tracked-On: OAM-115633
=> ASB-March 2024 Security Patches integration

aosp_diff/preliminary/build/make/0001-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/0005-SoftVideoDecodeOMXComponent-validate-OMX-params-for-dynamic-HDR.bulletin.patch, aosp_diff/preliminary/frameworks/av/0006-Fix-out-of-bounds-read-and-write-in-onQueueFilled-in-outQueue.bulletin.patch, aosp_diff/preliminary/frameworks/base/29_0029-Always-sync-user-restriction-state-to-UserManager.bulletin.patch, aosp_diff/preliminary/frameworks/base/30_0030-Validate-package-names-passed-to-the-installer-.bulletin.patch, aosp_diff/preliminary/frameworks/base/31_0031-Disallow-system-apps-to-be-installed-updated-as-instant-.bulletin.patch, aosp_diff/preliminary/frameworks/base/32_0032-Close-AccountManagerService-session-after-timeout-.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0005-Fix-an-OOB-bug-in-smp_proc_sec_req.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0006-Fix-an-OOB-write-bug-in-attp_build_value_cmd.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0007-Revert-Fix-an-OOB-write-bug-in-attp_build_value_cmd-.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0008-Reland-Fix-an-OOB-write-bug-in-attp_build_value_cmd.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0009-Fix-a-security-bypass-issue-in-access_secure_service_from_temp_b.bulletin.patch, aosp_diff/preliminary/packages/modules/HealthFitness/0001-Exclude-exercise-routes-from-ExerciseSessionRecord-changelogs-.bulletin.patch
Test done: STS r24 All TCs Passed except one
WIP on failed Test case.
android.security.cts.WallpaperManagerTest#testSetMaliciousStream
Tracked-On: OAM-115659
=> ASB - March 2024 Security Patch integration

aosp_diff/base_aaos/frameworks/base/99_0254-Add-settings-for-display-HW-adjustment.patch, aosp_diff/base_aaos/packages/apps/Car/Settings/0006-Add-display-controlling-UI-on-settings.patch
Add UI on Settings and API on framework for display adjustment, including Saturation, Hue, Contrast, Luminance and White Balance.
Tracked-On: OAM-114024
=> Add display adjustment UI on settings and API on framework

.gitattributes, aosp_diff/base_aaos/external/chromium-webview/0001-Update-the-webview-apk.patch
Update the webview apk to latest from AOSP tree.
Test Done: Ran Monkey Test for webview module,
No issues seen
Tracked-On: OAM-114706
=> Update the webview apk

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/base_aaos/frameworks/base/99_0254-Revert-On-device-lockdown-always-show-the-keyguard-.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0255-Enforce-persisted-snoozed-notifications-limits.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0256-RESTRICT-AUTOMERGE-Added-limitations-for-attributions-to-handle-.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0257-Don-t-store-invalid-pkgs-when-migrating-filters.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0258-isUserInLockDown-can-be-true-when-there-are-other-strong-auth-re.bulletin.patch
Test done: STS r25 TCs Passed
Tracked-On: OAM-116788
=> ASB - April 2024 Security Patches integration

bsp_diff/base_aaos/kernel/linux-intel-lts2021/0035-f2fs-explicitly-null-terminate-the-xattr-list.patch, bsp_diff/base_aaos/kernel/linux-intel-lts2021/0036-binder-fix-use-after-free-in-shinkers-callback.patch, bsp_diff/base_aaos/kernel/linux-intel-lts2021/0037-f2fs-fix-to-avoid-dirent-corruption.patch, bsp_diff/base_aaos/kernel/linux-intel-lts2021/0038-block-add-check-that-partition-length-needs-to-be-aligned-with-blocksize.patch, bsp_diff/base_aaos/kernel/linux-intel-lts2021/0039-efivarfs-force-RO-when-remounting-if-SetVariable-is-not-supported.patch, bsp_diff/base_aaos/kernel/linux-intel-lts2021/0040-perf-Fix-perf_event_validate_size.patch, bsp_diff/base_aaos/kernel/linux-intel-lts2021/0041-bpf-Reject-variable-offset-alu-on-PTR_TO_FLOW_KEYS.patch, bsp_diff/base_aaos/kernel/linux-intel-lts2021/0042-bpf-Fix-re-attachment-branch-in-bpf_tracing_prog_attach.patch
=> Porting the patches to kernel new tag 5.15.148

aosp_diff/preliminary/art/0002-Auto-Fast-JNI-Optimization.patch, aosp_diff/preliminary/art/0003-Coverity-Fixes.patch, aosp_diff/preliminary/art/0004-Fixed-static-analysis-issue.patch, aosp_diff/preliminary/frameworks/base/04_0004-Enable-ART-AutoFastJni.patch
Port required art patches from Android-13
to Android-14.
- Enable ART Auto Fast JNI optimization
- Coverity Fixes - Fixed static analysis issue
Tracked-On: OAM-113063
=> Port required art patches to Android-14

host/kernel/lts2022-chromium/build_weekly.sh
Updating the host kernel script
Tracked-On: OAM-117159
=> Update Chromium commit hash in the host kernel build script for v6.1.75 rebase

host/kernel/lts2022-chromium/0001-Resolving-the-conflict-in-drivers.patch
This patch resolves the conflict present in video drivers for proper functionality.
Tracked-On: OAM-117158
=> Patch to resolve the conflict in drivers

aosp_diff/preliminary/build/make/0001-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/base/33_0033-Revert-On-device-lockdown-always-show-the-keyguard.patch, aosp_diff/preliminary/frameworks/base/34_0034-Updated-always-show-the-keyguard-on-device-lockdown.patch, aosp_diff/preliminary/frameworks/base/35_0035-RESTRICT-AUTOMERGE-Added-limitations-for-attribution.patch, aosp_diff/preliminary/frameworks/base/36_0036-Don-t-store-invalid-pkgs-when-migrating-filters.patch, aosp_diff/preliminary/frameworks/base/37_0037-isUserInLockDown-can-be-true-when-there-are-other-st.patch, aosp_diff/preliminary/frameworks/base/38_0038-Stop-marking-apps-as-privileged-if-they-are-not-sign.patch, aosp_diff/preliminary/packages/apps/Settings/0011--RESTRICT-AUTOMERGE-Restrict-WifiDialogActivity.bulletin.patch
Test done: STS r25 All TCs Passed except one
WIP on failed Test case.
android.security.cts.WallpaperManagerTest#testSetMaliciousStream
Tracked-On: OAM-117035
=> ASB - April 2024 Security Patch integration

bsp_diff/common/kernel/lts2022-chromium/0007-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch
Rebased for kernel v6.1.75
Tracked-On: OAM-116938
=> drm/i915: Sysfs interface to get GFX shmem usage

host/kernel/lts2022-chromium/build_weekly.sh
Updating the commit hash for utils in host kernel for v6.1.75 rebase
Tracked-On: OAM-117258
=> Update the utils commit hash in the host kernel build script

bsp_diff/common/kernel/lts2022-chromium/0007-Fix-compilation-issues-for-fuse-bpf.patch
=> Enable support for FUSE BPF

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/base/99_0170-Revert-On-device-lockdown-always-show-the-keyguard.patch, aosp_diff/preliminary/frameworks/base/99_0171-Updated-always-show-the-keyguard-on-device-lockdown.patch, aosp_diff/preliminary/frameworks/base/99_0172-Do-not-allow-setting-notification-access-across-users-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0173-RESTRICT-AUTOMERGE-Added-limitations-for-attributions-to-handle-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0174-Don-t-store-invalid-pkgs-when-migrating-filters.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0175-isUserInLockDown-can-be-true-when-there-are-other-st.patch, aosp_diff/preliminary/frameworks/base/99_0176-Stop-marking-apps-as-privileged-if-they-are-not-signed-properly-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0177-Enforce-persisted-snoozed-notifications-limits.patch, aosp_diff/preliminary/packages/apps/Settings/0025-Restrict-WifiDialogActivity.patch
Test done: STS r25 TCs Passed
Tracked-On: OAM-116786
=> ASB-April 2024 Security Patches integration

aosp_diff/base_aaos/frameworks/base/99_0261-Color-transform-fix.patch
Update color transform reboot setting to fix
previous performance regression issue
Test Done:Antutu test
Tracked-On: OAM-117740
=> Color transform fix

aosp_diff/preliminary/art/0005-Improve-linear-loop-optimization-overflow-checks.patch, aosp_diff/preliminary/art/0006-Improve-linear-induction-var-range-creation.patch, aosp_diff/preliminary/art/0007-Align-induction-var-range-checks-and-uses.patch
Test: art/test/testrunner/testrunner.py --host --64 --optimizing -b
Tracked-On: OAM-117262
=> Porting patches from AOSP

aosp_diff/base_aaos/packages/services/Car/0021-Fixed-for-Coverity-issue-in-Car-Service.patch
Captured concurrent data modification issue.
Synchronized data modification variable.
Tests: Build is successfull and device is booting fine.
Tracked-On: OAM-118066
=> Fixed for Coverity issue in Car Service.

aosp_diff/base_aaos/frameworks/base/99_0258-Fixed-for-crashe-during-Monkey-test-run.patch, aosp_diff/base_aaos/packages/apps/Car/Messenger/0001-Fixed-for-crash-during-Monkey-test-run.patch, aosp_diff/base_aaos/packages/apps/DeskClock/0003-Fixed-for-crash-during-Monkey-test-run.patch
=> Fixed for crash during Monkey test run.

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/base_aaos/external/sonivox/0001-fix-buffer-overrun-in-eas_wtengine.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0262--SettingsProvider-verify-ringtone-URI-before-setting.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0263-Truncate-user-data-to-a-limit-of-500-characters.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0264-RESTRICT-AUTOMERGE-Log-to-detect-usage-of-whitelistToken-when-se.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0265-Fix-security-vulnerability-that-creates-user-with-no-restriction.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0266-Prioritize-system-toasts.bulletin.patch, aosp_diff/base_aaos/packages/modules/Permission/07_0007-Do-not-grant-notification-access-for-work-apps-.bulletin.patch
Test done: STS r26 TCs Passed.
Tracked-On: OAM-117886
=> ASB-May 2024 Security Patches integration

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/sonivox/0001-fix-buffer-overrun-in-eas_wtengine.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0249--SettingsProvider-verify-ringtone-URI-before-setting.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0250-Truncate-user-data-to-a-limit-of-500-characters.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0251-RESTRICT-AUTOMERGE-Log-to-detect-usage-of-whitelistToken-when-se.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0252-Fix-security-vulnerability-that-creates-user-with-no-restriction.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0253-Prioritize-system-toasts.bulletin.patch, aosp_diff/preliminary/packages/modules/Permission/07_0007-Do-not-grant-notification-access-for-work-apps-.bulletin.patch
Test done: STS r26 TCs Passed
Tracked-On: OAM-117582
=> ASB - May 2024 Security Patches integration

bsp_diff/common/device/intel/mixins/0001-Enable-graphics.composer3-AIDL-HAL-service-in-Androi.patch
=> Resolve conflict diff patch for opencl sepolicy

aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/base/41_0041-Added-throttle-when-reporting-shortcut-usage.bulletin.patch, aosp_diff/preliminary/frameworks/base/42_0042-Verify-URI-permission-for-channel-sound-update-from-Notification.bulletin.patch, aosp_diff/preliminary/frameworks/base/43_0043-Check-for-NLS-bind-permission-when-rebinding-services.bulletin.patch, aosp_diff/preliminary/frameworks/base/44_0044-Hide-window-immediately-if-itself-doesn-t-run-hide-animation.bulletin.patch, aosp_diff/preliminary/frameworks/base/45_0045-Add-more-checkKeyIntent-checks-to-AccountManagerService-.bulletin.patch, aosp_diff/preliminary/frameworks/base/46_0046-Update-media_controls_lock_screen-setting-behavior.bulletin.patch, aosp_diff/preliminary/frameworks/base/47_0047-Resolve-message-conversation-image-Uris-with-the-cor.patch, aosp_diff/preliminary/frameworks/base/48_0048-CMD-Check-permissions-for-CDM-shell-commands.bulletin.patch, aosp_diff/preliminary/frameworks/base/49_0049-Fix-bug-in-screen-capture-and-lock-task-migrations.bulletin.patch, aosp_diff/preliminary/frameworks/base/50_0050--Bugfix-migrate-user-restrictions-to-DevicePolicyEngine.bulletin.patch, aosp_diff/preliminary/frameworks/base/51_0051-Check-hidden-API-exemptions.bulletin.patch, aosp_diff/preliminary/frameworks/base/52_0052--DO-NOT-MERGE-Autofill-Framework-Add-in-check-for-intent-filte.bulletin.patch, aosp_diff/preliminary/frameworks/base/53_0053-RESTRICT-AUTOMERGE-AccessibilityManagerService-remove-uninsta.bulletin.patch, aosp_diff/preliminary/packages/modules/HealthFitness/0003-Add-flag-to-prevent-non-system-apps-from-showing-overlay-on-HC-U.bulletin.patch, aosp_diff/preliminary/packages/modules/StatsD/0001--libstatssocket-Added-validation-for-adding-new-data-into-Stats.bulletin.patch, aosp_diff/preliminary/system/libfmq/0001-Use-the-values-of-the-ptrs-that-we-check.bulletin.patch
Test done: STS r25 All TCs Passed except one
WIP on failed Test case.
android.security.cts.WallpaperManagerTest#testSetMaliciousStream
Tracked-On: OAM-119025
=> ASB-June 2024 Security Patches integration

bsp_diff/base_aaos/device/intel/mixins/0001-adding-required-sensors-xml-files-for-automotive.patch
addition required sensors xml files for automotive
providing specific permission for automotive sensors.
Tracked-On: OAM-118145
=> mixin changes for cts aaos14 sensors

aosp_diff/aaos_iasw, bsp_diff/aaos_iasw, vendorsetup.sh
This reverts commit 0a2209698a02c60dd26db394b7017106271cb283.
Tracked-On: OAM-121246
=> Revert "New extended lunch target for base_aaos"

bsp_diff/base_aaos/device/intel/mixins/0002-adding-required-uncalibrated-sensors-xml-files-for-a.patch
enabling limited_axis uncalibrated features.
Tracked-On: OAM-118805
=> adding required uncalibrated sensors xml files for automotive

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/base_aaos/frameworks/base/99_0281-DO-NOT-MERGE-CDM-Fix-a-security-issue-that-allow-3p-apps-to-s.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0282-RESTRICT-AUTOMERGE-PM-Send-ACTION_PACKAGE_CHANGED-when-mimeGr.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0283-Fix-security-vulnerability-allowing-apps-to-start-from-backgroun.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0284-DO-NOT-MERGE-CDM-Fix-setSkipPrompt-on-Android-S.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0285-Verify-UID-of-incoming-Zygote-connections-.bulletin.patch, aosp_diff/base_aaos/packages/modules/StatsD/0003-statsd-Make-executor-thread-a-class-member-of-MultiConditionTr.bulletin.patch, aosp_diff/base_aaos/packages/providers/MediaProvider/09_0009-Prevent-insertion-in-other-users-storage-volumes.bulletin.patch, aosp_diff/base_aaos/system/bt/62_0062-Fix-an-authentication-bypass-bug-in-SMP.bulletin.patch
Test done: STS r28 TCs Passed.
Tracked-On: OAM-121435
=> ASB-July 2024 Security Patches integration

bsp_diff/base_aaos/hardware/intel/kernelflinger/0058-Fix-Out-of-bounds-access-and-32-bit-time_t.patch
=> Fix Out-of-bounds access and 32-bit time_t

bsp_diff/base_aaos/hardware/intel/kernelflinger/0056-Fix-Resource-leaks-and-Uninitialized-pointer-reads.patch, bsp_diff/base_aaos/hardware/intel/kernelflinger/0057-Fix-Resource-leaks-and-32-bit-time_t-usage.patch
=> Fix Resource leaks, 32-bit time_t usage and uninitialized pointer reads

aosp_diff/preliminary/frameworks/base/99_0200-Avoid-HIGH_ACCURACY-request-from-stationary-throttli.patch
Bug: 319054085
Test: atest StationThrottlingLocationProviderTest
Change-Id: I33e945b62c660db7e0ecce45ca6959213cd64bf4
Tracked-On: OAM-122224
=> Avoid HIGH_ACCURACY request from stationary throttling

host/qemu/0013-dm-virtio-gpu-Add-virtio-gpu-plane-format-modifier-s.patch
Need this patch as the minigbm patch 4752352 merged
Tracked-On: OAM-122625
=> Fix android as SRIOV boot issue

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/base_aaos/frameworks/av/41_0041-libmediatranscoding-handle-death-recipient-cookie-ownership-dif.bulletin.patch, aosp_diff/base_aaos/frameworks/av/42_0042-StagefrightRecoder-Disabling-B-frame-support.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0286-Fix-error-handling-for-non-dynamic-permissions.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0287-Fix-security-vulnerability-of-non-dynamic-permission-removal.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0288-RESTRICT-AUTOMERGE-Backport-preventing-BAL-bypass-via-bound-serv.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0289-Rate-limiting-PiP-aspect-ratio-change-request.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0290-Restrict-USB-poups-while-setup-is-in-progress.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0291-Add-the-protection-to-avoid-data-overflow-in-BinaryXmlSerializer.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0292-Hide-SAW-subwindows.bulletin.patch, aosp_diff/base_aaos/hardware/interfaces/14_0014-Keep-track-of-DeathMonitor-cookies.bulletin.patch, aosp_diff/base_aaos/system/bt/63_0063-Fix-heap-buffer-overflow-in-sdp_utils-cc.bulletin.patch
Test done: STS r29 TCs Passed
Tracked-On: OAM-122533
=> ASB-Aug 2024 Security Patches integration

aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch, aosp_diff/preliminary/frameworks/av/0007-libmediatranscoding-handle-death-recipient-cookie-ownership-dif.bulletin.patch, aosp_diff/preliminary/frameworks/av/0008-StagefrightRecoder-Disabling-B-frame-support.bulletin.patch, aosp_diff/preliminary/frameworks/base/59_0059-Fix-error-handling-for-non-dynamic-permissions.bulletin.patch, aosp_diff/preliminary/frameworks/base/60_0060-Security-fix-for-VPN-app-killable-via-lockscreen-.bulletin.patch, aosp_diff/preliminary/frameworks/base/61_0061-Rate-limiting-PiP-aspect-ratio-change-request.bulletin.patch, aosp_diff/preliminary/frameworks/base/62_0062-Restrict-USB-poups-while-setup-is-in-progress.bulletin.patch, aosp_diff/preliminary/frameworks/base/63_0063-Add-unit-test-to-test-data-overflow-when-using-BinaryXmlSerializ.bulletin.patch, aosp_diff/preliminary/frameworks/base/64_0064-Hide-SAW-subwindows.bulletin.patch, aosp_diff/preliminary/frameworks/base/65_0065-Ensure-device_owners2-xml-is-always-written-.bulletin.patch, aosp_diff/preliminary/frameworks/base/66_0066-Fix-READ-WRITE-operation-access-issues-on-Restricted-appOps-.bulletin.patch, aosp_diff/preliminary/frameworks/libs/modules-utils/0001-Add-the-protection-to-avoid-Integer-overflow-in-BinaryXmlSeriali.bulletin.patch, aosp_diff/preliminary/frameworks/native/04_0004-Fix-transaction-sanitization.bulletin.patch, aosp_diff/preliminary/hardware/interfaces/13_0013-Use-onUnlinked-in-health-HAL.bulletin.patch, aosp_diff/preliminary/hardware/interfaces/14_0014-Keep-track-of-DeathMonitor-cookies.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0011-Fix-heap-buffer-overflow-in-sdp_utils-cc.bulletin.patch, aosp_diff/preliminary/system/nfc/0001-Remove-the-use-of-the-death-recipient-cookie.bulletin.patch, aosp_diff/preliminary/system/security/0001-Create-and-use-a-death-recipient-cookie-object.bulletin.patch
Test done: STS r29 All TCs Passed
Tracked-On: OAM-122388
=> ASB-August 2024 Security Patches integration

aosp_diff/aaos_iasw/packages/providers/MediaProvider/0001-Reduce-POLL_INTERVAL_MS-to-50ms-to-optimize-cold-boo.patch
Reduce POLL_INTERVAL_MS to 50ms and increase POLL_COUNT to 100 to optimize cold boot.
Tracked-On: OAM-123666
=> Add patch reducing POLL_INTERVAL_MS to 50ms to optimize cold boot

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/base_aaos/frameworks/av/43_0043-omx-check-HDR10-info-param-size.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0293-DO-NOT-MERGE-Ignore-Sanitized-uri-scheme-by-removing.patch, aosp_diff/base_aaos/frameworks/base/99_0294-RESTRICT-AUTOMERGE-Delete-keystore-keys-from-Recover.patch, aosp_diff/base_aaos/packages/apps/Settings/38_0038-Limit-wifi-item-edit-content-s-max-length-to-500.bulletin.patch, aosp_diff/base_aaos/packages/apps/Settings/39_0039-Replace-getCallingActivity-with-getLaunchedFromPackage-.bulletin.patch, aosp_diff/base_aaos/packages/apps/Settings/40_0040-Ignore-fragment-attr-from-ext-authenticator-resource.bulletin.patch, aosp_diff/base_aaos/packages/apps/Settings/41_0041-RESTRICT-AUTOMERGE-Restrict-Settings-Homepage-prior-to-provision.bulletin.patch, aosp_diff/base_aaos/packages/services/Telecomm/15_0015-Unbind-CallScreeningService-when-timeout-reached-.bulletin.patch, aosp_diff/base_aaos/system/sepolicy/13_0013-RESTRICT-AUTOMERGE-Allow-system_server-to-call-IKeystoreMaintena.bulletin.patch
Test done: STS r30 TCs Passed.
Tracked-On: OAM-123594
=> ASB-SEP 2024 Security Patches integration

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/base_aaos/frameworks/av/42_0042-omx-check-HDR10-info-param-size.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0289-DO-NOT-MERGE-Ignore-Sanitized-uri-scheme-by-removing.patch, aosp_diff/base_aaos/frameworks/base/99_0290-RESTRICT-AUTOMERGE-Delete-keystore-keys-from-Recover.patch, aosp_diff/base_aaos/packages/apps/Settings/38_0038-Limit-wifi-item-edit-content-s-max-length-to-500.bulletin.patch, aosp_diff/base_aaos/packages/apps/Settings/39_0039-Replace-getCallingActivity-with-getLaunchedFromPackage-.bulletin.patch, aosp_diff/base_aaos/packages/apps/Settings/40_0040-Ignore-fragment-attr-from-ext-authenticator-resource.bulletin.patch, aosp_diff/base_aaos/packages/apps/Settings/41_0041-RESTRICT-AUTOMERGE-Restrict-Settings-Homepage-prior-to-provision.bulletin.patch, aosp_diff/base_aaos/packages/services/Telecomm/15_0015-Unbind-CallScreeningService-when-timeout-reached-.bulletin.patch, aosp_diff/base_aaos/system/sepolicy/13_0013-RESTRICT-AUTOMERGE-Allow-system_server-to-call-IKeystoreMaintena.bulletin.patch
Test done: STS r30 TCs Passed.
Tracked-On: OAM-123585
=> ASB-SEP 2024 Security Patches integration.

aosp_diff/base_aaos/external/thermal_daemon/0001-Coverity-fixes-for-Thermal-Daemon.patch
Fix static analysis issue for thermal daemon for IVI
Below issue will be solved with this change.
+-------------------------------+
|COPY_INSTEAD_OF_MOVE |
+-------------------------------+
Tracked-On: OAM-121348
Signed-off-by: Manvi Bajaj <manvi.bajaj@intel.com>
=> Coverity fixes for thermal-daemon

aosp_diff/base_aaos/external/thermal_daemon/0002-Fix-static-analysis-issues-for-thermal-daemon-for-IV.patch
Below issues will be solved with this change.
+-------------------------------+
|Unchecked return value from library |
|Argument cannot be negative |
|Waiting while holding a lock |
|Resource leak |
|Uninitialized scalar variable |
+-------------------------------+
Tracked-On: OAM-124640
=> Fix static analysis issues for thermal daemon for IVI

vendorsetup.sh
This patch will support CI builder to perform lunch without depending on the TARGET_RELEASE version of the underlying AOSP code. It will allow CI builder to provide lunch as target-variant and output will be target-release-variant sent to AOSP build system.
Tests Done: source and lunch target-variant
Tracked-On: OAM-124766
=> CI builder TARGET_RELEASE agnostic lunch support

bsp_diff/common/kernel/lts2022-chromium/0007-drm-i915-Sysfs-interface-to-get-GFX-shmem-usage.patch
Tests done:
- Android boot in CIV and BM
- adb reboot
- Wi-Fi connect/disconnect
- BT on/off/connect/disconnect
- Audio playback and recording
- Image capture
Tracked-On: OAM-124600
=> Update i915 sysfs memtrack patch

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/base_aaos/frameworks/base/99_0295-Fail-parseUri-if-end-is-missing.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0296-Update-AccountManagerService-checkKeyIntent-.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0297-Prevent-Sharing-when-FRP-enforcement-is-in-effect.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0298-RESTRICT-AUTOMERGE-Check-whether-installerPackageName-contains.bulletin.patch, aosp_diff/base_aaos/libcore/02_0002-Do-not-accept-zip-files-with-invalid-headers-.bulletin.patch, aosp_diff/base_aaos/packages/apps/Settings/42_0042-RESTRICT-AUTOMERGE-FRP-bypass-defense-in-App-battery-usage-page.bulletin.patch
Test done: STS r31 TCs Passed.
Tracked-On: OAM-125599
=> ASB-OCT 2024 Security Patches integration

bsp_diff/caas/device/intel/mixins/0003-Enable-wifi-RTT-and-NAN-features.patch
Update patch 0003-Enable-wifi-RTT-and-NAN-features.patch.
Tracked-On: OAM-125143
=> Update patch 0003-Enable-wifi-RTT-and-NAN-features.patch.

aosp_diff/preliminary/bionic/0003-Optimize-bionic-memory-functions-with-avx2-instructi.patch, aosp_diff/preliminary/bionic/0004-Optimize-bionic-string-functions-with-avx-implementa.patch, aosp_diff/preliminary/bionic/0005-avx2-implementation-for-memmove-api.patch
Port required bionic patches from Android-14
to Android-15.
- Optimize-bionic-string-functions-with-avx
- Optimize-bionic-memory-functions-with-avx2
- AVX2-implementation-for-memmove-api.patch
Test done: Build and boot is fine, Run the benchmarks suite.
Tracked-On: OAM-126872
=> Port required Utils bionic patches to Android-15

aosp_diff/preliminary/art/0001-Auto-Fast-JNI-Optimization.patch, aosp_diff/preliminary/art/0002-Coverity-Fixes.patch, aosp_diff/preliminary/art/0003-Fixed-static-analysis-issue.patch, aosp_diff/preliminary/frameworks/base/24_0024-Enable-ART-AutoFastJni.patch
Port required art patches from Android-14
to Android-15.
- Enable ART Auto Fast JNI optimization
- Coverity Fixes
- Fixed static analysis issue
Test done: Build and boot is fine, Run the benchmarks suite.
Tracked-On: OAM-126116
=> Port required art patches to Android-15

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/base_aaos/external/skia/0001-RESTRICT-AUTOMERGE-Avoid-potential-overflow-when-allocating-3D-.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0300--fix-Security-Report-Reveal-images-across-users-via-EditUserPh.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0301-Remove-authenticator-data-if-it-was-disabled-.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0302-Check-more-URIs-in-notifications.patch, aosp_diff/base_aaos/frameworks/base/99_0303-Set-no-data-transfer-on-function-switch-timeout-for-accessory-mo.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0304-Disallow-device-admin-package-and-protected-packages.patch, aosp_diff/base_aaos/frameworks/base/99_0305-RESTRICT-AUTOMERGE-Clear-app-provided-shortcut-icons.bulletin.patch, aosp_diff/base_aaos/packages/apps/Bluetooth/08_0008-Fix-permission-bypasses-to-multiple-methods.bulletin.patch, aosp_diff/base_aaos/packages/apps/Settings/43_0043-RESTRICT-AUTOMERGE-Stops-hiding-a11y-services-with-the-same-pack.bulletin.patch, aosp_diff/base_aaos/packages/apps/Settings/44_0044-startActivityForResult-with-new-Intent.bulletin.patch, aosp_diff/base_aaos/packages/apps/Settings/45_0045-Checks-cross-user-permission-before-handling-intent.bulletin.patch, aosp_diff/base_aaos/packages/modules/Permission/08_0008-RESTRICT-AUTOMERGE-Fix-to-restrict-admin-from-granting-permissio.bulletin.patch, aosp_diff/base_aaos/packages/modules/Wifi/0012-Fix-security-isseu-by-change-the-field-in-WifiConfig.bulletin.patch, aosp_diff/base_aaos/packages/providers/MediaProvider/10_0010-Prevent-apps-from-renaming-files-they-don-t-own.bulletin.patch
Test done: STS r32 TCs Passed.
Tracked-On: OAM-126588
=> ASB-NOV 2024 Security Patches integration

aosp_diff/preliminary/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/skia/0003-pdf-Bounds-check-in-skia_alloc_func.bulletin.patch, aosp_diff/preliminary/external/skia/0004-RESTRICT-AUTOMERGE-Check-for-size-overflow-before-allocating-Sk.bulletin.patch, aosp_diff/preliminary/external/skia/0005-Prevent-overflow-when-growing-an-SkRegion-s-RunArray.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0224-Block-clipboard-UI-when-device-is-locked.patch, aosp_diff/preliminary/frameworks/base/99_0225-Properly-handle-onNullBinding-in-appwidget-service-.bulletin.patch, aosp_diff/preliminary/packages/apps/Car/Launcher/0001-DO-NOT-MERGE-Stop-reading-component-name-from-call-extras.patch, aosp_diff/preliminary/packages/modules/Bluetooth/60_0060-Fix-OOB-write-in-build_read_multi_rsp-of-gatt_sr-cc.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/61_0061-Fix-GATT-Read-Multiple-Variable-Response-builder.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/62_0062-Encrypt-LE-link-immediately-on-reconnection.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/63_0063-Fix-OOB-writes-in-gatt_sr-cc.bulletin.patch
Test done: STS r33 TCs Passed.
Tracked-On: OAM-127559
=> ASB DEC 2024 Security Patches integration

aosp_diff/preliminary/build/make/0007-Configure-virtual_ab-compression.patch
Set vabc algo to lz4.
Enabled vabc compression threads.
Enabled vabc compression xor.
Tests done: Build-Flash-Verify
Tracked-on: OAM-125218
=> Configure virtual_ab compression

aosp_diff/caas/external/thermal_daemon/0001-Fix-static-analysis-issues-for-thermal-daemon-for-ca.patch
Below issues will be solved with this change.
+---------------------------------------+
|Unchecked return value from library |
|Argument cannot be negative           |
|Resource leak                                     |
+---------------------------------------+
Tracked-On: OAM-128504
=> Fix static analysis issues for thermal daemon for caas

aosp_diff/preliminary/build/make/04_0004-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/giflib/0001-Fix-potential-overflow-when-calculating-ImageSize.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0294-RingtoneManager-verify-default-ringtone-is-audio.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0295-SettingsProvider-verify-ringtone-URI-before-setting.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0296-RingtoneManager-allow-video-ringtone-URI.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0297-enforce-limits-for-VisualVoicemailSmsFilterSettings-properties.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0298-Fix-allowlist-token-issues.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0299-Update-checkKeyIntent.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0300-Always-show-all-approved-apps.bulletin.patch, aosp_diff/preliminary/frameworks/native/21_0021-binder-fix-FD-handling-in-continueWrite.bulletin.patch, aosp_diff/preliminary/frameworks/native/22_0022-libbinder-Parcel-grow-rejects-large-data-pos.bulletin.patch, aosp_diff/preliminary/frameworks/native/23_0023-libbinder-Parcel-validate-read-data-before-write.bulletin.patch, aosp_diff/preliminary/packages/apps/Bluetooth/06_0006-RESTRICT-AUTOMERGE-Disallow-unexpected-incoming-HID-connections-.bulletin.patch, aosp_diff/preliminary/packages/apps/DocumentsUI/0001-Prevent-clickjacking-attack-in-DocsUi-.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/46_0046-CDM-NLS-Check-if-the-NLS-service-has-an-intent-filter.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/47_0047-Disable-factory-reset-in-DSU-mode.bulletin.patch, aosp_diff/preliminary/packages/modules/Permission/09_0009-Fix-Dynamic-Permission-group-auto-grant-behaivor.bulletin.patch, aosp_diff/preliminary/packages/services/Telephony/0004-enforce-the-calling-package-is-the-default-dialer-for-VisualVoic.bulletin.patch, aosp_diff/preliminary/system/bt/63_0063-RESTRICT-AUTOMERGE-Disallow-unexpected-incoming-HID-.patch, aosp_diff/preliminary/system/bt/64_0064-Resolve-incomplete-fix-for-SMP-authentication-bypass.bulletin.patch
Test done: STS r34 All TCs Passed except
2 TCs failed due to Kernel LTS Update requird,
Test: KernelLts Test#testRequiredKernelLts_ENFORCING
KernelLts Test#testRequiredKernelLts_WARN
Update in upcoming ASB WIP.
Tracked-On: OAM-128659
=> ASB JAN 2025 Security Patches integration

aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/giflib/0001-Fix-potential-overflow-when-calculating-ImageSize.bulletin.patch, aosp_diff/preliminary/frameworks/base/82_0082-RingtoneManager-allow-video-ringtone-URI.patch, aosp_diff/preliminary/frameworks/base/83_0083-enforce-limits-for-VisualVoicemailSmsFilterSettings-properties.bulletin.patch, aosp_diff/preliminary/frameworks/base/84_0084-Fix-allowlist-token-issues.patch, aosp_diff/preliminary/frameworks/base/85_0085-Update-checkKeyIntent.bulletin.patch, aosp_diff/preliminary/frameworks/base/86_0086-Always-show-all-approved-apps.bulletin.patch, aosp_diff/preliminary/frameworks/base/86_0086-Pass-SafeActivityOptions-with-actual-caller-for-startActivityInT.bulletin.patch, aosp_diff/preliminary/frameworks/libs/net/0001-Handle-v4-mapped-v6-address-in-Struct-parsing.bulletin.patch, aosp_diff/preliminary/frameworks/libs/net/0002-Add-util-method-to-generate-IPv4-mapped-IPv6-address-from-IPv4-a.bulletin.patch, aosp_diff/preliminary/frameworks/native/08_0008-binder-fix-FD-handling-in-continueWrite.bulletin.patch, aosp_diff/preliminary/frameworks/native/09_0009-libbinder-Parcel-grow-rejects-large-data-pos.bulletin.patch, aosp_diff/preliminary/frameworks/native/10_0010-libbinder-Parcel-validate-read-data-before-write.bulletin.patch, aosp_diff/preliminary/packages/apps/DocumentsUI/0001-Prevent-clickjacking-attack-in-DocsUi-.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/21_0021--CDM-NLS-Check-if-the-NLS-service-has-an-intent-filter.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/22_0022-Disable-factory-reset-in-DSU-mode.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0018-RESTRICT-AUTOMERGE-Disallow-unexpected-incoming-HID-connections.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0019-Resolve-incomplete-fix-for-SMP-authentication-bypass.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0001-netd-bpf-implement-ingress-discard-based-on-dstip-ifindex-.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0002-Add-java-class-for-Ingress-discard-bpf-map-key-value.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0003-Add-methods-for-updating-ingressDiscardRule-bpf-map-to-BpfNetMap.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0004-Drop-packets-to-VPN-address-ingressing-via-non-VPN-interface.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0005-Skip-adding-ingress-discard-rule-to-legacy-VPN.bulletin.patch, aosp_diff/preliminary/packages/modules/Connectivity/0006-Skip-adding-ingress-discard-rule-to-OEM-VPN.bulletin.patch, aosp_diff/preliminary/packages/modules/Permission/0002-Fix-Dynamic-Permission-group-auto-grant-behaivor.bulletin.patch, aosp_diff/preliminary/packages/services/Telephony/04_0004-enforce-the-calling-package-is-the-default-dialer-for-VisualVoic.bulletin.patch
Test done: STS r34 TCs Passed 100% on MBL with ACRN
Bare metal scenario not tested, as blocked by the issue: OAM-129200
Tracked-On: OAM-129118
=> Asb u stable jan 2025

aosp_diff/caas/external/thermal_daemon/0002-Fix-static-analysis-issues-for-thermal-daemon.patch
and deprecate KBL support.
Below issues will be solved with this change.
+------------------------------+
|COPY_INSTEAD_OF_MOVE          |
|Waiting while holding a lock  |
|Resource leak                 |
|Uninitialized scalar variable |
+------------------------------+
KBL is not supported anymore, therefore deprecating.
Tracked-On: OAM-129647
=> Fix static analysis issues for thermal daemon

aosp_diff/base_aaos/build/make/0004-Update-security_patch_level-string.patch, aosp_diff/base_aaos/external/dng_sdk/0001-Catch-null-HuffmanTables-when-decoding-jpeg.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0319-Resolve-cross-account-user-icon-validation-.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0320-Check-account-type-returned-by-AbstractAccountAuthenticator-.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0321-RESTRICT-AUTOMERGE-PM-Fix-the-profile-issue-in-UninstallerActi.bulletin.patch, aosp_diff/base_aaos/frameworks/base/99_0322-DO-NOT-MERGE-Hide-Android-data-obb-sanbox-on-shared-.patch, aosp_diff/base_aaos/frameworks/base/99_0323-Restrict-access-to-directories.patch, aosp_diff/base_aaos/frameworks/native/24_0024-servicemanager-set-consistent-flags-for-self-reg.bulletin.patch, aosp_diff/base_aaos/packages/apps/Bluetooth/10_0010-backport-opp-validate-that-content-uri-belongs-to-current-user.bulletin.patch, aosp_diff/base_aaos/packages/apps/Bluetooth/11_0011-Reset-permissions-for-not-bonded-device.bulletin.patch, aosp_diff/base_aaos/packages/providers/DownloadProvider/0002-Ensure-ownership-validation-in-downloadprovider-insert-method.bulletin.patch, aosp_diff/base_aaos/packages/services/Telecomm/16_0016-Resolve-cross-account-user-icon-validation-.bulletin.patch, aosp_diff/base_aaos/system/bt/73_0073-Prevent-use-after-free-of-HID-reports.patch, aosp_diff/base_aaos/system/bt/74_0074-Use-encrypted-link-for-avdtp-and-avctp-channels.bulletin.patch
Integrating Google Android Security Bulletin Patches.
Test done: STS r36 All TCs Passed except
2 TCs failed due to
Bluetooth not working on executing below test issue-id: 130035
Test: android.security.cts.CVE_2022_20429.CVE_2022_20429#testPocCVE_2022_20429
Kernel LTS Update required issueid: 130660
Test:  android.security.sts.KernelLtsTest#testRequiredKernelLts_WARN
Tracked-On: OAM-130582
=> ASB MAR 2025 Security Patches integration

aosp_diff/preliminary/build/release/0001-Update-RELEASE_PLATFORM_SECURITY_PATCH-string.patch, aosp_diff/preliminary/external/dng_sdk/0002-Fail-fast-in-dng-sdk-if-an-invalid-tag-count-is-seen.bulletin.patch, aosp_diff/preliminary/external/skia/0001--bmp-Fix-swizzler-initialization.bulletin.patch, aosp_diff/preliminary/frameworks/base/0029-Remove-flag-fixAvatarCrossUserLeak.bulletin.patch, aosp_diff/preliminary/frameworks/base/0030-Verify-that-the-caller-has-permissions-for-the-icons-it-provided.bulletin.patch, aosp_diff/preliminary/frameworks/base/0031-Fix-Block-opening-settings-app-on-keyguard-without-u.patch, aosp_diff/preliminary/frameworks/base/0032-BaseBundle-fix-unparcel-error-logic.bulletin.patch, aosp_diff/preliminary/frameworks/base/0033-Parse-authority-to-separate-userId-and-non-user-parts-of-it.bulletin.patch, aosp_diff/preliminary/frameworks/base/0034-Check-cross-user-permissions-for-a-given-UID.patch, aosp_diff/preliminary/frameworks/base/0035-Remove-notification-content-from-icon-a11y.bulletin.patch, aosp_diff/preliminary/frameworks/base/0036-Add-permissions-check-to-isInSignificantPlace-.bulletin.patch, aosp_diff/preliminary/frameworks/base/0037-Check-underlying-intent-as-well-as-intent-selector.bulletin.patch, aosp_diff/preliminary/frameworks/base/0038-Do-not-allow-non-system-apps-to-provide-unverified-attributions.bulletin.patch, aosp_diff/preliminary/frameworks/base/0039-DO-NOT-MERGE-Update-ActivityRecordInputSink-using-the-pending-t.bulletin.patch, aosp_diff/preliminary/frameworks/base/0040-Disable-Developer-options-by-default-for-managed-profiles-.bulletin.patch, aosp_diff/preliminary/packages/apps/DocumentsUI/0002-Fix-for-SAF-loophole-in-the-lastAccessedStack-.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/0003-Check-the-permission-of-the-callingUid-instead-of-the-calling-pa.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/0004-Remove-incorrect-call-to-Window-addFlags-with-a-system-flag.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0007-Fix-type-confusion-in-avdt_msg-cc.bulletin.patch, aosp_diff/preliminary/packages/modules/IntentResolver/0001-Check-underlying-intent-as-well-as-intent-selector.bulletin.patch, aosp_diff/preliminary/packages/modules/Permission/0002-Role-re-evaluation-should-respect-ask-every-time-choice-by-user.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/0002-Unbind-CS-if-connection-is-not-created-within-15-sec.patch, aosp_diff/preliminary/packages/services/Telecomm/0003-Ensure-connection-is-unbound-on-call-redirection-timeout-.bulletin.patch, aosp_diff/preliminary/packages/services/Telecomm/0004-Ensure-ScheduledExecutor-is-not-shutdown-before-sche.patch, aosp_diff/preliminary/packages/services/Telephony/0004-Prevent-overlays-on-Telephony-settings-screen-.bulletin.patch
Integrating Google Android Security Bulletin Patches.
Test done: STS r37 TCs Passed
Tracked-On: OAM-131272
=> ASB APR 2025 Security Patches integration

aosp_diff/preliminary/build/make/0009-Update-security_patch_level-string.patch, aosp_diff/preliminary/external/freetype/0001-DO-NOT-MERGE-truetype-Clean-up-zeroing-and-local-variables-.bulletin.patch, aosp_diff/preliminary/frameworks/av/0010-CameraService-Watch-for-foreground-changes-from-AppOps.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0106-Hide-Android-data-obb-sanbox-on-shared-storage.patch, aosp_diff/preliminary/frameworks/base/99_0107-Don-t-allow-non-system-uids-to-use-android-as-calling-package-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0108-Avoid-app-pinning-requests-if-the-Task-is-already-locked.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0109-Get-calling-package-name-using-a-reliable-API.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0110-Add-a-list-of-Biometric-protected-packages.patch, aosp_diff/preliminary/frameworks/base/99_0111-Delay-appop-revocation-when-only-capability-is-lost.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0112-Allow-core-uids-to-register-receiver-as-android-.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0113-Remove-invalid-null-check-for-callingPackage.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0114-vims-better-handle-assistant-force-stop.bulletin.patch, aosp_diff/preliminary/frameworks/base/99_0115-Impose-a-threshold-on-the-number-of-attributed-op-entries-return.bulletin.patch, aosp_diff/preliminary/packages/apps/Settings/30_0030-Add-biometric-authentication-for-package-modificatio.patch, aosp_diff/preliminary/packages/apps/Settings/31_0031-CDM-Checks-NLS-component-name-instead-of-package-name.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0028-Fix-authentication-bypass-bug-in-SMP.bulletin.patch, aosp_diff/preliminary/packages/modules/Bluetooth/0029-Fix-OOB-read-in-bta_av_setconfig_rej.bulletin.patch, aosp_diff/preliminary/packages/modules/Permission/03_0003-RESTRICT-AUTOMERGE-Merge-multiple-requests-by-an-app-in-the-same.bulletin.patch, aosp_diff/preliminary/packages/modules/Permission/04_0004-RESTRICT-AUTOMERGE-Add-missing-preconditions-to-get-setDefaultAp.bulletin.patch, aosp_diff/preliminary/packages/modules/Wifi/03_0003-Add-size-check-for-IP-config.bulletin.patch
Integrating Google Android Security Bulletin Patches.
Test done: STS r38 TCs Passed
Tracked-On: OAM-132056
=> ASB MAY 2025 Security Patches integration
